### ISSUE TITLE
Failed to decode downloaded font: http://localhost:3000/fonts/app-fonts.woff

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#10]
Hi Rob, with the 'develop' branch this morning (Feb 4, 2106) I am getting these two errors:
Failed to decode downloaded font: http://localhost:3000/fonts/app-fonts.woff
OTS parsing error: invalid version tag

**Comment by DaleMcGrew** [comment]
This problem went away after I restarted gulp. Our new build environment doesn't automatically pick up changes.

**Comment by nf071590** [comment]
Dale, so no. The build watches changes to src/index.html, src/js/** (all
js?x files), and src/sass/**/*.scss... I do not think that index file will
update in build after changes... The build environment does automatically
pickup changes just not for some directories that do not change often but
this will change.

Best,

Nick

**Comment by minooo** [comment]
@nf071590 hello，I have the same problem, I don not know how to do with it;
[this is my problem](https://github.com/minooo/CSS-Modules-----React)
when you run `npm install` and `npm start`,open `localhost:5000`
you can see the problem like this 
![image](https://cloud.githubusercontent.com/assets/9410091/14010823/a260517c-f1d3-11e5-8bb3-6924ff9fd30a.png)

**Comment by pertrai1** [comment]
You should be running `gulp` and then that will start on localhost:3001
