### ISSUE TITLE
Change Address -> No Ballot -> Address in header doesn't update

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#100]
1. Visit the Ballot page
2. Enter a valid address "2208 Ebb Tide Rd, Virginia Beach, VA 23451"
3. You are taken to the Ballot and see all of your ballot items
4. Go to "My Ballot Location" and update the address to an address that doesn't return ballot items, like "Oakland, CA 94608"
5. You are redirected to http://localhost:3000/ballot/empty but the address in the header doesn't update (it should)
6. If you go back to the ballot, the address hasn't updated either
7. If you go to "My Ballot Location" the address hasn't updated
8. Go back to the ballot page and refresh -- you will see the address update to "Oakland, CA 94608"

I believe the cause of this is that we are relying on a "location" cookie, and instead we should be updating this value in the VoterStore and not use a cookie. We should avoid caching data in cookies that should live in a Store.

**Comment by lisamcho** [comment]
Resolved!
