### ISSUE TITLE
Add "Close search" x to search boxes

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1006]
### Please describe the issue (What happens? What do you expect?)
In the main search box we have added an "x" that clears the search text from the search box:
![screen shot 2017-08-06 at 9 13 54 am](https://user-images.githubusercontent.com/7756031/29005049-ffef5084-7a87-11e7-8950-65dfc7949d5d.png)

Please add this "x" to any other search box in We Vote. Some places:
- [ ] Your own voter guide, "Who You are Following"
- [ ] Network > All Friends: http://localhost:3000/friends
- [ ] Network > Organizations to Follow: http://localhost:3000/more/network
- [ ] Others?

**Comment by josh-southern** [comment]
I started working on this tonight. Going to work on abstracting the search bar with close and button options tomorrow. Is it ok to self assign?

**Comment by DaleMcGrew** [comment]
Thank you! Yes, please feel free to self assign. One request--I think we may want to avoid doing any refactoring on the main header search box right now, but abstracting for all of the other search boxes sounds great!

**Comment by josh-southern** [comment]
Dropped the new component into /more/network, but I'm unsure how to see the /friends search box. Do I need the backend to add friends and test that out?

**Comment by DaleMcGrew** [comment]
Hi @josh-southern, at this time adding friends is a little hard to test, so I think it is fine to consider this issue closed by putting it on the network page. I can migrate it to the harder-to-test pages. Thank you!

**Comment by DaleMcGrew** [comment]
Hi @josh-southern, I just got a chance to do some testing. This is mostly in great shape with one request. On all pages that use the new search box, could you please add the magnifying glass icon in the resting state (when the search box is empty) like you do on the scratchpad ( http://localhost:3000/testing/scratchpad )?

Pages where I don't see the magnifying glass:
http://localhost:3000/more/network
http://localhost:3000/opinions

**Comment by josh-southern** [comment]
Just flipped the flag. Should be showing on both pages now.

**Comment by DaleMcGrew** [comment]
Great work @josh-southern -- this issue is now complete.
