### ISSUE TITLE
Network buttons: add explanation text under each button

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1008]
### Please describe the issue (What happens? What do you expect?)
On the network page, we have either 2 or three buttons. We would like to add text under each button (in desktop view) like this:
<img width="791" alt="screen shot 2017-08-06 at 8 27 17 pm" src="https://user-images.githubusercontent.com/7756031/29011155-b482e0b2-7ae5-11e7-8e44-a6d1e805ebbb.png">
The component file is here: WebApp/src/js/routes/Network.jsx

**Find Voter Guides**
Signing into Twitter is the fastest way to find voter guides related to the issues you care about. When you sign into Twitter, We Vote will find the voter guides for everyone you are following.

**Choose Friends**
By signing into Facebook here, you can choose which friends you want to talk politics with, and avoid the trolls (or that guy from work who rambles on)! You control who is in your We Vote network.

**Invite Friends**
Send email invitations to your friends. Share your vision, and get your friends help on figuring out everything on your ballot.

Extra credit - we may need to offer a "more" link at the end of the text if it is taking up more than two vertical lines to display. (We have sample code for doing that.)

**Comment by n0f3** [comment]
i can work on this

**Comment by DaleMcGrew** [comment]
Thank you @n0f3 for implementing the first version of this!

**Comment by n0f3** [comment]
no problem! glad i could help 👍
