### ISSUE TITLE
Write brief descriptions of issues

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1012]
We have 90 issues (see here on the live site: https://wevote.us/more/network/issues ), and we would like to include a brief description for all 90. We need help writing these descriptions into this Google Doc:
https://docs.google.com/spreadsheets/d/1Eb9W8kK1wiBfl1jrThjkpizcTHEBjd5F1qIO7LJx_Wk/edit#gid=0

Thank you!

**Comment by n0f3** [comment]
what are the plans for integration in the frontend app?

**Comment by DaleMcGrew** [comment]
Hi @n0f3 given there are so few Issues in We Vote (~90), we just copy and paste the descriptions so they show up on this page: https://wevote.us/more/network/issues
We also are selecting photos for all of these issues.

**Comment by DaleMcGrew** [comment]
I am closing this issue given we are doing a restructure of We Vote issues. Thank you to everyone who has been helping!
