### ISSUE TITLE
Free voter guide tool

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1014]
Create simple HTML code that an organization can copy in order to place a We Vote “Free voter guide tool” widget on an existing website. We have implemented a first version of the “Free civic engagement tools” page, that currently includes widgets from Vote.org that is here: https://wevote.us/more/tools 
We want this new widget to be right above "Free voter registration tool from Vote.org"

Two steps:
- [ ] Step 1: Enter your Twitter handle, then click “Go” button
- [ ] Step 2: Leave the "Enter your Twitter handle" input in place, but now show the “Click to copy code” text area + button. I think we can use the same iframe code as in the other boxes, but update the iframe src to "https://WeVote.US/TWITTER_HANDLE_HERE?campaign=free-tools", with TWITTER_HANDLE_HERE being the handle they enter.
- [ ] Please provide example of this framed version working on another website.

Example voter guide: https://wevote.us/aclu

Files you will need to touch:
WebApp/src/js/routes/More/ToolsToShareOnOtherWebsites.jsx
WebApp/src/js/components/Widgets/CodeCopier.jsx
WebApp/src/sass/components/_more-tools.scss
WebApp/src/js/stores/VoterStore.js (for current Twitter information in voter object)

**Comment by josh-southern** [comment]
Hey, since I worked on the code copier I was thinking I'd work on this next.

**Comment by DaleMcGrew** [comment]
Hi @josh-southern, it turns out we need to develop a process for setting up new voter guides that needs to be built before we can implement this. I will slack you some ideas of other issues that we are ready to tackle.

**Comment by josh-southern** [comment]
Alright, I'll look at the others.

**Comment by DaleMcGrew** [comment]
This is going to require deeper work. We can reopen this after the November elections.
