### ISSUE TITLE
City, State ZIP is not enough info to retrieve full ballot

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#102]
Since City, State ZIP (what we get from Geocoding) is not enough info retrieve a ballot from the Google Civic API, @dalemcgrew will be creating the following system to make sure voters always get an actual ballot (if they are in an area where we are supporting), even before they provide their full address.

Functional sequence:
1. Voter visits wevote.me, geolocation works and returns "City, State ZIP" and this is stored in the database
2. We find the closest ballot to this location that we have stored (pre-stored during the "Retrieve ballots" Admin tool, using polling location addresses to query Google Civic ballot data)
3. Display that ballot to the voter with this message:
“We made our best guess at your location, and are showing a ballot for a nearby polling location. If you would like to find your actual ballot, please enter your full address.”

**Comment by lisamcho** [comment]
Yes, I think that is a better approach. Please feel free to remove my code with the EmptyBallot route.

**Comment by DaleMcGrew** [comment]
I think even when this feature (#102) is done, we will still need the EmptyBallot routine you created. There will be many areas of the country that won't have ballot data at any particular time which will need EmptyBallot. Issue #102 just makes sure we always deliver a ballot in regions we are supporting.

**Comment by DaleMcGrew** [comment]
There will be ongoing refinement to this, but this is now working.
