### ISSUE TITLE
Implement TextTruncate as custom component

### ISSUE THREAD

**Issue by edward-ly** [wevote/WebApp#1026]
### Please describe the issue (What happens? What do you expect?)

The TextTruncate component from the npm package "react-text-truncate" has some limitations:

1. The component only accepts a single string for its text input instead of raw HTML, limiting the formatting capabilities of the text we want to truncate (such as the description of each candidate in the ballot page).
2. ~~The component might not automatically re-render when the display resolution of the web page changes (e.g. switching from desktop mode to mobile mode, and vice versa), causing some text to be unnecessarily truncated (see: the top office name of each ballot item).~~

We want to implement our own version of TextTruncate that accepts HTML (as a component property value or as a child element) ~~and re-renders every time the browser resolution changes~~.

### Update

The issue with the ballot item office name not properly truncating has been resolved; it was likely caused by the surrounding block and floating elements in the page, so take care to note where this component is used.

**Comment by n0f3** [comment]
I've looked at this component while working on a different issue, I can take a look

**Comment by edward-ly** [comment]
Updated the issue now that the ballot item office name is properly truncating in the latest pull request. Now the only issue left to resolve is to modify the component arguments as mentioned previously.

**Comment by DaleMcGrew** [comment]
Closing for now, until we want to reopen.
