### ISSUE TITLE
Network buttons layout improvement

### ISSUE THREAD

**Issue by n0f3** [wevote/WebApp#1032]
### Please describe the issue (What happens? What do you expect?)
The layout for the network buttons is currently fairly static and doesn't utilize the negative space very well. I would love to improve on that and provide a more scalable and dynamic solution

### Steps to reproduce the problem (1, 2, 3...), including links
https://wevote.us/more/network/, take a look at the build your network section

**Comment by DaleMcGrew** [comment]
Thank you @n0f3 for these improvements! I found these bugs:
**Bug A) Network buttons break onto two lines in Desktop mode**
1) Refresh browser on http://localhost:3000/more/network (when you are not signed in) -- layout is fine.
2) Slowly reduce the width of the browser window and you will see this around 829px width -- all three buttons should remain on one horizontal line:
![screen shot 2017-08-22 at 6 13 17 am](https://user-images.githubusercontent.com/7756031/29567117-12ec9180-8701-11e7-9781-481184694174.png)

**Bug B) Descriptions go away in desktop**
3) Keep narrowing the window until the buttons go into mobile mode, then widen the window until they jump back to desktop mode. The descriptions go away:
![screen shot 2017-08-22 at 6 14 09 am](https://user-images.githubusercontent.com/7756031/29567203-4a1154ca-8701-11e7-9bc7-2666fbc0af54.png)

**Bug C) Network buttons should fit on one horizontal line in mobile mode (iPhone 5).**
Removing the current margins might be enough space. If that doesn't work we could take the text down in font size.
![screen shot 2017-08-22 at 6 16 30 am](https://user-images.githubusercontent.com/7756031/29567289-945f2f98-8701-11e7-81dd-05a75a060cbb.png)

**Comment by n0f3** [comment]
Sounds good, I'll make sure to fix them up!

**Comment by DaleMcGrew** [comment]
Hi @n0f3, are you available to come to Code for SF tonight? I'd love to get your changes checked in.

**Comment by n0f3** [comment]
@DaleMcGrew I've fixed the issues relative to spacing and style. The TextTruncate component is what's causing the bugs with the text going away and it's due to it detecting that the parent div's width is 0, but never updating itself. 

There is no way that I can see to easily detect changes in styles in the page and force and update to the component.

I think issues with TextTruncate not updating itself should be filed as a different bug, as it will affect other components that rely on display: none to hide/show elements depending on resolution

**Comment by DaleMcGrew** [comment]
Thank you @n0f3, your changes look great!

**Comment by n0f3** [comment]
@DaleMcGrew no problem! the text will likely still show the bug that you have reported and as I mentioned in my previous comment it has to deal with the texttruncate component. Let me know if you want me to look more into it, I believe that the best course of action would be to probably make a custom component that replicates its functionality and is able to update the text on rectangle width change.
