### ISSUE TITLE
Place cursor in input field when you edit address

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1036]
### Please describe the issue (What happens? What do you expect?)
When a voter goes to change their address, you need to click on the "Enter address where you are registered to vote" box before you can start typing.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to Ballot page
2. Click "Edit" next to the address field
3. A modal popup appears
We want the cursor to be in the input field so a person can start typing without having to click in the input field first

**Comment by edward-ly** [comment]
I found two possible solutions for this one. One would just be to add the `autofocus` attribute to the text `<input />`. Another would be to add `this.refs.autocomplete.focus();` inside the `componentDidMount` function (this is all in `src/js/components/AddressBox.jsx`, by the way). Let me know which implementation you prefer.

**Comment by DaleMcGrew** [comment]
If adding autofocus to the input works, that sounds simplest!

**Comment by edward-ly** [comment]
OK, I can include it in my next pull request (or if you want to add it in yourself, be my guest).

**Comment by DaleMcGrew** [comment]
Solved! Thank you @edward-ly.
