### ISSUE TITLE
"Follow Issues" Page Needs Images

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1059]
We have started introducing an image for each Issue. (Sample code to copy is in: WebApp/src/js/components/Issues/IssueFollowToggleSquare.jsx ) Please update these three pages to show images, and clean up the left-to-right positioning of the Issue names and descriptions:
http://localhost:3000/issues_to_follow
and
http://localhost:3000/issues_followed
and
http://localhost:3000/more/network/issues

To be upgraded:
<img width="955" alt="screen shot 2017-09-02 at 8 30 43 am" src="https://user-images.githubusercontent.com/7756031/29996771-8923f102-8fb9-11e7-96af-04bed3ee6abe.png">

**Comment by josh-southern** [comment]
Hey, dragging my feet on this a little bit, but I will be by Code for America tonight to finish it up.

**Comment by DaleMcGrew** [comment]
No problem Josh -- see you tonight!

**Comment by DaleMcGrew** [comment]
This is excellent Josh! I will create a new issue for the addition of the the "info" icon and overlay.
