### ISSUE TITLE
Candidate display on Ballot and Candidate page (Column changes)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#106]
On the ballot (/src/js/components/Ballot/CandidateItem.jsx) and candidate pages (/src/js/routes/Ballot/Candidate.jsx) the photo and candidate name info are both in a “col-xs-6”. Since the photo doesn’t need as much room as the candidate name, I was hoping to change the photo div to use “col-xs-4”, and the candidate name to use “col-xs-8”. When I tried this, I discovered some responsive code that doesn’t allow this simple change:
`@media all and (max-width: 695px) {
  .no-show {
    display: none; }
  .col-xs-8 {
    width: 100%; }
}`

**Comment by nf071590** [comment]
See here: http://getbootstrap.com/css/#grid <http://getbootstrap.com/css/#grid>

**Comment by DaleMcGrew** [comment]
What I am commenting on is a We Vote specific style change to "col-xs-8" that causes display problems.

**Comment by pertrai1** [comment]
@DaleMcGrew This was done because of the layout that did not work when going from desktop to mobile view with the layout that is being used. Will have to be researched more with how using Bootstrap can handle this.

**Comment by pertrai1** [comment]
@DaleMcGrew This has been fixed now with changing and using a custom `col-xs-8-container` so the regular Bootstrap `col-xs-8` works as it should.

**Comment by DaleMcGrew** [comment]
Thank you @pertrai1
