### ISSUE TITLE
Make "Following" and "Ignore" buttons work on "Opinions I'm Following" page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#108]
- [x] On the "Opinions I'm Following" page, all of the "Follow" buttons should instead say "Following". 
- [x] When you click "Following" it should remove the group from the "Opinions I'm Following" list
- [x] When you click "Ignore" it should remove the group from the "Opinions I'm Following" list and add it to the Ignore list

**Comment by lisamcho** [comment]
So you click "Following" and it means you unfollow an org? and the org disappears from the list (like the More Opinions view)? What is the "Ignore list"? Is that meant to be a separate route/page (next to Opinions I'm Following we would also have Opinions I'm Ignoring)?

**Comment by DaleMcGrew** [comment]
@lisamcho when you visit the "Opinions I'm Following" page, all of the buttons should say "Following" instead of "Follow". When you click the "Following" button, it should remove the org from that list, but will then be available again on the "More Opinions" page. We don't currently offer a way to view the orgs on your "Ignore" list, but we will add that in the future.

**Comment by DaleMcGrew** [comment]
Actually, when I look at the way Twitter does it, hovering over the "Following" button on the "Opinions I'm Following" page should show a red button that says "Unfollow". If you click it, I am fine with either: A) you stop following the org, and the org disappears from the page, or B) the button should revert back to "Follow", but the org doesn't disappear until you leave the page (that is, it is gone when you return to the page).

**Comment by lisamcho** [comment]
So the merged pull request should resolve this issue. I just tagged as VerifyFix. How does this new system work am I supposed to assign it to someone else to verify the fix and close the issue?

**Comment by DaleMcGrew** [comment]
Thanks Lisa, you can add the VerifyFix tag and then add a quick comment like "@dalemcgrew this is ready to test." with the name of the person who entered the issue. I think it is also fine for others (aside from the person who checked in the fix) to verify most issues.

**Comment by lisamcho** [comment]
Got it @DaleMcGrew this is ready to test!

**Comment by DaleMcGrew** [comment]
Verified!
