### ISSUE TITLE
Design: On Edit Address pages, improve the experience while you wait

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1088]
When a voter changes their address, there can be a 5-15 second wait. I think we should change this "Loading" page to inform the voter about what is coming next, so we don't lose them.

It could be as simple as changing the text to "Finding your ballot information now!" and then including a 10-9-8-7-6... countdown. Maybe adding some "Did you know?" text?

More ideas here: https://docs.google.com/document/d/1YPsRDZCjO-xxJXmOqFX5v0VNsK320LBBxTlxW3tSWRM/edit

This is related to Issue: https://github.com/wevote/WebApp/issues/1247

**Comment by MikeTarkington** [comment]
This is completed in my latest PR.  I can add "Did you know? ..." text but to me it seemed excessive and a countdown may serve merely emphasize to the user that they are waiting.

**Comment by DaleMcGrew** [comment]
This is working much better now!
