### ISSUE TITLE
CLA Agreement

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#109]
I just pushed some code to the NFL repo and was cool because you have to sign a CLA. There is a great app that has been created for GitHub. https://www.clahub.com/

- [x] Update current version of our CLA here to have the "We Vote USA" name: https://www.clahub.com/agreements/wevote/WebApp

**Comment by DaleMcGrew** [comment]
I think weaving this into our process would be great. Why is this labeled "invalid"? I changed to Version 1.1 but could be done anytime.

**Comment by DaleMcGrew** [comment]
Updated. Thanks @pertrai1!
