### ISSUE TITLE
Organization disappears too quickly from ballot intro modal after follow

### ISSUE THREAD

**Issue by edward-ly** [wevote/WebApp#1105]
When following an organization from the ballot intro modal, it quickly disappears from the list of organizations as the list refreshes after each follow. So after each follow or unfollow, we want to either:

a. delay the refresh by some number of seconds (using ReactCSSTransitionGroup), or
b. prevent the refresh from occurring at all (so it behaves like the list of issues).

The modal page in question is under `src/js/components/Ballot/BallotIntroFollowAdvisers.jsx`, while each square uses the component `src/js/components/Ballot/OrganizationFollowToggle.jsx`.
An example usage of ReactCSSTransitionGroup is in `src/js/components/Friends/FriendInvitationList.jsx`.

**Comment by DaleMcGrew** [comment]
Verified! Thank you @jainanisha90.
