### ISSUE TITLE
Modal for "Send message to Facebook friends" shrinks

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1131]
### Please describe the issue (What happens? What do you expect?)
On chrome, when I select a Facebook Friend and try to send a message to them, the modal shrinks until it is tiny and unusable. (Dale has a video he can send to you, showing this.)

1. Go to Network
2. Choose Friends
3. Choose one friend
4. Modify the message
5. Click Send

**Comment by josh-southern** [comment]
I found the source of the request loop, but I'm unsure if it affects other components.

In VoterStore.jsx I made this comment:

`           
            // FriendsInvitationList.jsx is choking on this because calling this
            // results in an infinite loop cycling between voterRetrieve and getFaceProfilePicture which
            // resolves to FACEBOOK_RECIEVED_PICTURE which then attempts to save using voterFacebookSignInPhoto
            // which in turn resolves to voterFacebookSignInSave which finally attempts to call
            // voterRetrieve again

            // url never seems to be satisfied in this case
            
            /*
            if (action.res.signed_in_facebook && (url === null || url === "")) {
              const userId = FacebookStore.userId;
              FacebookActions.getFacebookProfilePicture(userId);
            }
            */
`

**Comment by josh-southern** [comment]
This is in the 'voterRetrieve' case of the store.

**Comment by DaleMcGrew** [comment]
This issue still exists and prevents sending friend invitation via Facebook. It may be due to some style we have that affects the Facebook popup? It does seem strange that the styles aren't coming from the Facebook page that we wrap in the popup.
![screen shot 2017-10-28 at 7 58 28 am](https://user-images.githubusercontent.com/7756031/32135542-d9a50a30-bbb5-11e7-95f0-de6b7641f2d9.png)

**Comment by DaleMcGrew** [comment]
Strangely, this issue seemed to have solved itself.
