### ISSUE TITLE
Ballot Location Buttons: Add "x more" button in mobile mode

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1132]
### Please describe the issue (What happens? What do you expect?)
Currently we show 5-6 ballot location buttons in desktop. In mobile, we want to show 2 ballot location buttons and then a "x more" button that unfurls all of the other options. It would be ideal if these three buttons could fit on 1 line. This is what we currently show in mobile:
![img_4237](https://user-images.githubusercontent.com/7756031/31421953-7aeee83a-adff-11e7-9937-f567d013e109.jpeg)

The code that powers these buttons is here:
WebApp/src/js/components/Navigation/BallotLocationChoices.jsx

You can find an election with multiple ballot locations here:
https://wevote.us/ballot/arlington_virginia_november_2017

**Comment by josh-southern** [comment]
Got a ok version of this working. Not sure I completely like the structure right now, but will push next week sometime regardless of what state it's in.

**Comment by DaleMcGrew** [comment]
Thank you for letting me know Josh!

**Comment by DaleMcGrew** [comment]
Resolved! Thank you @josh-southern.
