### ISSUE TITLE
Welcome page style consolidation

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1135]
### Please describe the issue (What happens? What do you expect?)
Within this css file, the styles have been spread out. Without changing the look or behavior of the page, we need to consolidate the styles from the bottom half of the page up into the top half.
WebApp/src/sass/routes/_welcome.scss

Please make sure to be familiar with our styling guidelines:
https://github.com/wevote/WebApp/blob/develop/docs/working/STYLING.md

**Comment by n0f3** [comment]
Hi there, I can take this, is it just a matter of renaming classes and clean up scss?

**Comment by DaleMcGrew** [comment]
Great work @armendo! Verified.
