### ISSUE TITLE
Issues can be dragged left or right in BallotIntroModal

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1137]
### Please describe the issue (What happens? What do you expect?)
When you view the BallotIntroModal on your first visit to the Ballot, the issues screen, which can scroll up or down, can also be pulled slightly left or right, leaving it looking like this:
![img_4238](https://user-images.githubusercontent.com/7756031/31473733-38c1f69e-aeab-11e7-9cb6-27b82e347749.jpeg)

This should be fixed so it cannot be dragged left or right within the scrollable area.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to the Ballot.
2. Click on the "Issues" button

The code can be found here, by searching for "BallotIntroFollowIssuesModal":
WebApp/src/js/components/Navigation/HeaderGettingStartedBar.jsx

**Comment by josh-southern** [comment]
Having trouble reproducing this error. Tried Chrome and Safari on iPhone 6 simulator.

**Comment by DaleMcGrew** [comment]
Great work @josh-southern, this is fixed.
