### ISSUE TITLE
Build Your Network Buttons too narrow in mobile mode

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1144]
### Please describe the issue (What happens? What do you expect?)
In desktop, these buttons look correct:
![screen shot 2017-10-19 at 11 20 36 am](https://user-images.githubusercontent.com/7756031/31787135-9363b988-b4bf-11e7-8f05-2bc6a6b8fc14.png)

In mobile mode, they are very narrow. Something changed to break this.
![screen shot 2017-10-19 at 11 11 39 am](https://user-images.githubusercontent.com/7756031/31787153-ac9fbc3a-b4bf-11e7-9d12-3c1a237743ae.png)

jsx code here: WebApp/src/js/routes/Network.jsx
Relevant CSS file: WebApp/src/sass/components/_network.scss

**Comment by n0f3** [comment]
Fixed and PR ready :)
