### ISSUE TITLE
Ballot overlay remains after Modal opens, and shows on top of the modal

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1153]
### Please describe the issue (What happens? What do you expect?)
In mobile (iPhone Safari) on the Ballot page, I click on the position bar and see an overlay:
![screen shot 2017-10-28 at 8 05 05 am](https://user-images.githubusercontent.com/7756031/32135624-c02d0c82-bbb6-11e7-90aa-9d4288644eac.png)

I then click again and the modal opens. But the overlay remains and displays over the modal:
![screen shot 2017-10-28 at 8 06 52 am](https://user-images.githubusercontent.com/7756031/32135637-0339a2b0-bbb7-11e7-8455-4bdcc92bcf68.png)

What we want is to have the overlay go away on the second click (when the modal opens).

Note that in desktop the overlay displays on mouse rollover. When I click the position bar the overlay remains as long as my mouse is over the original overlay spot. When I move away from the overlay spot it goes away and stays away even if I go back.

The candidate modal is triggered in WebApp/src/js/components/Ballot/OfficeItemCompressed.jsx around line 140 (See "onClick={ this.props.link_to_ballot_item_page")

The OverlayTrigger is in this file WebApp/src/js/components/Widgets/ItemSupportOpposeCounts.jsx

**Comment by edward-ly** [comment]
This seems to be a cross-compatibility issue of some kind, as I tried reproducing the issue in Chrome and Firefox (both Linux and Windows), but with no success. I was, however, able to reproduce the issue in Microsoft Edge, so I'm not sure what's going on with Edge and Safari that's causing this issue.

**Comment by DaleMcGrew** [comment]
Verified!
