### ISSUE TITLE
Voter guide display: Reduce vertical screen real estate

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#116]
http://localhost:3000/more/opinions/followed is powered by "routes/More/OpinionsFollowed.jsx"
This loads: /src/js/components/VoterGuide/VoterGuideItem.jsx

- [x] Recapture vertical space, so we can get more Voter Guides displayed above the page fold. Each voter guide should fit into a 100px vertical space. Return to earlier design with 3 "columns". Column 1: image (on the left), Column 2: an area for Name and Twitter, Column 3: Follow and Ignore buttons
The display (by React) of each voter guide item in "GuideList" was refactored from this file, where the design was correct: /src/js/components/VoterGuide/VoterGuideItem.jsx
Wireframe showing vertically-compact display: https://projects.invisionapp.com/share/2R41VR3XW#/screens/89479670

These "More Opinions" pages:
http://localhost:3000/opinions is powered by /src/js/routes/Opinions.jsx
http://localhost:3000/opinions/wv02cand3 is powered by /src/js/routes/Ballot/OpinionsAboutItem.jsx
...load up /src/js/components/VoterGuide/GuideList.jsx
Which then loads /src/js/components/VoterGuide/Organization.jsx

- [x] Refactor these pages to use VoterGuide/VoterGuideItem.jsx (so Organization isn't separated in components/VoterGuide/GuideList.jsx)

**Comment by pertrai1** [comment]
@DaleMcGrew Can you add a wireframe reference to view please?

**Comment by DaleMcGrew** [comment]
@pertrai1 Description text updated with this link: https://projects.invisionapp.com/share/2R41VR3XW#/screens/89479670

**Comment by pertrai1** [comment]
@DaleMcGrew Let me know after reviewing this pull request if I have corrected the appropriate views :ok_hand:

**Comment by DaleMcGrew** [comment]
Hi Rob, thank you for your changes on the "Opinions I'm Following" page:
http://localhost:3000/more/opinions/followed (implemented in "/src/js/components/VoterGuide/VoterGuideItem.jsx") They are the right direction. Here are some comments on your changes:
- [ ] I would like to preserve the icon in mobile mode. It can be smaller in mobile mode, if necessary.
- [ ] To save horizontal space, I think we can take the size of the "Ignore" button down in both Desktop & Mobile. We could also stack Follow and Ignore vertically instead of making them left/right.
- [ ] There is some overlap of the organization name text over the icons.
- [ ] We probably don't need as much margins as we currently use

PS. I clarified the issue description above too.

**Comment by pertrai1** [comment]
@DaleMcGrew Perfect. I will work on these so we can get this completed.

**Comment by pertrai1** [comment]
@DaleMcGrew Is the opinions also needing to be changed? I am not able to get that view to show up and get errors in the console. Does that view show for you?

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 I am able to go to:
1. My Ballot Location and enter "Columbus, OH 43202"
2. See a live ballot on the ballot page: http://localhost:3000/ballot
3. Follow about 20 opinions on this page: http://localhost:3000/opinions
4. Then I see those opinions on: http://localhost:3000/more/opinions/followed
As of Mar 19th Noon PT, this page is broken and can't be reached: http://localhost:3000/opinions/wv02cand3 (needs work)

**Comment by pertrai1** [comment]
@DaleMcGrew Is this issue fixed or is the page still broken?

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 yes the check box items in the opening comment are all still active.

**Comment by DaleMcGrew** [comment]
Actually, this is the comment with the active check boxes: https://github.com/wevote/WebApp/issues/116#issuecomment-196004430

**Comment by pertrai1** [comment]
@DaleMcGrew great thank you

**Comment by pertrai1** [comment]
@DaleMcGrew Please verify fix

**Comment by DaleMcGrew** [comment]
@pertrai1 these changes look great. Thank you!
