### ISSUE TITLE
Add scroll bar to Issue and Organization Modals

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1168]
### Please describe the issue (What happens? What do you expect?)
In the Issues and Organization Modals, we would like a scroll bar to show up when in desktop mode. (Not necessary in mobile mode.) Voter testing showed that it wasn't obvious that this area could be scrolled through.

![screen shot 2017-11-08 at 7 24 54 am](https://user-images.githubusercontent.com/7756031/32557547-5800a12e-c457-11e7-8702-8725dd1357ee.png)

To get here:
1. Go to ballot
2. Click on Issues button:
![screen shot 2017-11-08 at 7 47 18 am](https://user-images.githubusercontent.com/7756031/32558235-264f216c-c459-11e7-96cf-d2f7304a9ea1.png)

**Comment by DaleMcGrew** [comment]
Great work @josh-southern! I love how it works now in the Issues modal. Could you please add the changes that you made to the Issues modal over to the Organization modal?

**Comment by josh-southern** [comment]
Hey fixed this bug, and applied it to the Organizations modal, but there's still quite a bit of extra space in the modals. I will likely tweak it more with breakpoints next week.

**Comment by DaleMcGrew** [comment]
Ok thank you @josh-southern! If you'd like your current code merged with develop could you please create a pull request? Or you can do that next week after your additional changes.

**Comment by DaleMcGrew** [comment]
Thank you @josh-southern!
