### ISSUE TITLE
Update WebApp Script: Problem with npm start

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#118]
Nick's comment: "There's already a server running on port 3003, don't think you killed the previous process."

-----------------------
(WebAppEnv)root@ip-172-31-18-20:/home/wevote/WebApp# npm start

> wevoteusa@0.2.0 start /home/wevote/WebApp
> gulp

[21:48:41] Using gulpfile /home/wevote/WebApp/Gulpfile.js
events.js:154
     throw er; // Unhandled 'error' event
     ^

Error: listen EADDRINUSE :::3003
   at Object.exports._errnoException (util.js:856:11)
   at exports._exceptionWithHostPort (util.js:879:20)
   at Server._listen2 (net.js:1236:14)
   at listen (net.js:1272:10)
   at Server.listen (net.js:1368:5)
   at EventEmitter.listen (/home/wevote/WebApp/node_modules/express/lib/application.js:617:24)
   at Object.<anonymous> (/home/wevote/WebApp/server.js:13:4)
   at Module._compile (module.js:413:34)
   at Object.Module._extensions..js (module.js:422:10)
   at Module.load (module.js:357:32)

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/home/NodeEnvironments/WebAppEnv/bin/node" "/home/NodeEnvironments/WebAppEnv/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! wevoteusa@0.2.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wevoteusa@0.2.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wevoteusa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls wevoteusa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wevote/WebApp/npm-debug.log

[1:51] 
——————————— here is npm-debug.log ---------------------

[1:52] 
0 info it worked if it ends with ok
1 verbose cli [ '/home/NodeEnvironments/WebAppEnv/bin/node',
1 verbose cli   '/home/NodeEnvironments/WebAppEnv/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wevoteusa@0.2.0~prestart: wevoteusa@0.2.0
6 silly lifecycle wevoteusa@0.2.0~prestart: no script for prestart, continuing
7 info lifecycle wevoteusa@0.2.0~start: wevoteusa@0.2.0
8 verbose lifecycle wevoteusa@0.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle wevoteusa@0.2.0~start: PATH: /home/NodeEnvironments/WebAppEnv/lib/node_modules/npm/bin/node-gyp-bin:/home/wevote/WebApp/node_modules/.bin:/home/NodeEnvironments/WebAppEnv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle wevoteusa@0.2.0~start: CWD: /home/wevote/WebApp
11 silly lifecycle wevoteusa@0.2.0~start: Args: [ '-c', 'gulp' ]
12 silly lifecycle wevoteusa@0.2.0~start: Returned: code: 1  signal: null
13 info lifecycle wevoteusa@0.2.0~start: Failed to exec start script
14 verbose stack Error: wevoteusa@0.2.0 start: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/NodeEnvironments/WebAppEnv/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/NodeEnvironments/WebAppEnv/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid wevoteusa@0.2.0
16 verbose cwd /home/wevote/WebApp
17 error Linux 3.13.0-74-generic
18 error argv "/home/NodeEnvironments/WebAppEnv/bin/node" "/home/NodeEnvironments/WebAppEnv/bin/npm" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error wevoteusa@0.2.0 start: `gulp`
22 error Exit status 1
23 error Failed at the wevoteusa@0.2.0 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wevoteusa package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get their info via:
23 error     npm owner ls wevoteusa
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

nf071590 [1:53 PM] 
There's already a server running on port 3003, don't think you killed the previous process.

[1:53] 
You should let me setup the front end build process..

**Comment by josephevans** [comment]
You can't just run "npm start" to start a new process -- you have to kill the previous process. All of this is  managed by the upstart service that makes sure the process is always running (and starts it on boot.)

We have a script /root/update_code that updates all the code from git and restarts the npm process. 

If you just want to restart the npm process, run "service wevote-www restart". 

Both of these commands need to be run as root.

**Comment by DaleMcGrew** [comment]
Thank you Joe.

**Comment by DaleMcGrew** [comment]
BTW, I updated /root/update_code from `git pull` to `git pull origin develop` since we haven't pushed the latest version from develop to master yet.

**Comment by josephevans** [comment]
Ok, thanks for taking care of that Dale!
