### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by feargswalsh92** [wevote/WebApp#1187]
### Please describe the issue (What happens? What do you expect?)
Favicon missing from site. 
### Steps to reproduce the problem (1, 2, 3...), including links

![image](https://user-images.githubusercontent.com/19194339/33159186-81f7a76a-cfc5-11e7-9558-5c9022b59097.png)

**Comment by feargswalsh92** [comment]
If someone could assign me to this I can take care of that

**Comment by DaleMcGrew** [comment]
Fixed!
