### ISSUE TITLE
Email Ballot: add rounded corners to the bottom of the white area

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1206]
### Please describe the issue (What happens? What do you expect?)
On these two pages, make sure the white content areas have rounded corners at the bottom, and the modal has the correct height (currently it is too tall):
WebApp/src/js/components/Ballot/EmailBallotModal.jsx and WebApp/src/js/components/Ballot/EmailBallotToFriendsModal.jsx

![email_ballot-rounded_edges_missing_at_bottom](https://user-images.githubusercontent.com/7756031/33791382-c95edd7c-dc3f-11e7-9833-f6e06d738510.png)

**Comment by chulinguy** [comment]
Resolved I believe.

**Comment by DaleMcGrew** [comment]
Resolved! Thank you @chulinguy.
