### ISSUE TITLE
ES6 Exports to Replace Module Exports

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#1227]
### Please describe the issue (What happens? What do you expect?)
I think it would be good to move from `module.exports` to es6 `exports`. Will allow for staying up to date with the specs.

**Comment by SailingSteve** [comment]
How would you do this for something like BallotStore.js and config.js?

**Comment by pertrai1** [comment]
Change to a constant named object and export the object

**Comment by chulinguy** [comment]
Just tried it and works OK locally.  
Browserify seems to transpile all js/jsx files in the src directory.

**Comment by DaleMcGrew** [comment]
@chulinguy is there anything else left to do on this issue? Thank you!

**Comment by chulinguy** [comment]
I mean, it's purely a code styling thing, but I updated them in the latest pull request.

**Comment by DaleMcGrew** [comment]
Resolved! Thank you @chulinguy.
