### ISSUE TITLE
"Add Friends by Email" fails despite valid email

### ISSUE THREAD

**Issue by robla** [wevote/WebApp#1231]
### Please describe the issue (What happens? What do you expect?)
Adding a friend using /friends/invitebyemail throws an empty email address error despite providing valid email.

### Steps to reproduce the problem (1, 2, 3...), including links
1.  Go to https://wevote.us/friends/invitebyemail
2.  Fill in an email address (and a first+last name)
3.  Click "Send >"
4.  Expected behavior: a celebration of a valid email  :-)
     Actual: An error: "Please enter at least one email address."

**Comment by chulinguy** [comment]
Hi robla, 

I believe I accidentally introduced this bug in one of my commits; I just created a pull request to fix this.  Thanks for letting me know! 

Chi

**Comment by DaleMcGrew** [comment]
This particular issue is now fixed.
