### ISSUE TITLE
Mobile "More" Menu: Make it disappear when you click the hamburger a second time

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#124]
1. View 'My Voter Guide' in mobile mode
2. Click the hamburger icon in the upper left of the screen
3. When you click outside of the menu, the menu should go away
- [x] Clicking the hamburger when the menu is open should close the menu
- [x] On an iPhone 6 on Safari, clicking outside the menu did not close it. (Please let me know if you need more details.)

**Comment by pertrai1** [comment]
@DaleMcGrew Take a look at this and test while drinking :coffee:

**Comment by DaleMcGrew** [comment]
I love it! Great work. One minor glitch, the menu doesn't close when you click the hamburger and should.
- [ ] Clicking the hamburger when the menu is open should close the menu

**Comment by pertrai1** [comment]
Ah yes, did not look at that case. Will make sure the icon is not caught behind the body listener

**Comment by DaleMcGrew** [comment]
@pertrai1 I just added one more issue I found on a mobile phone to the opening description.

**Comment by lisamcho** [comment]
I see a lot of issues around the burger menu. I came across this, wondering if it would be easier...
https://github.com/negomi/react-burger-menu

**Comment by pertrai1** [comment]
@lisamcho I love it. You can take this on if you have time or I can. whichever works best for you. Thanks for finding that.

**Comment by lisamcho** [comment]
Today and tomorrow before our v1.0 milestone are kinda busy for me. Punting back to you :)

**Comment by pertrai1** [comment]
Ok the last 3 days have been very busy for me with the first of 3 releases this year for our cloud product and on premise. I will work hard on getting this and others done tonight. @DaleMcGrew @lisamcho

**Comment by pertrai1** [comment]
@DaleMcGrew @lisamcho I am close to having this done but don't think it can be done in the next 8 hours as I am going to get some sleep. This plugin looks good, just have run out of time to make sure it is implemented correctly.

**Comment by DaleMcGrew** [comment]
@pertrai1 waiting on this to see if the design changes being discussed with @ixley will affect how this is implemented.

**Comment by pertrai1** [comment]
@DaleMcGrew please verify

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 this is very nice. Great work! One reproducible issue I am seeing is:
1. Click the hamburger
2. Choose a menu option and it takes you to the page
3. Click the hamburger again -- it doesn't respond. (this is the bug)
4. Click the hamburger again and it works.
