### ISSUE TITLE
Pre-load Issue Images so they are in browser cache

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1240]
### Please describe the issue (What happens? What do you expect?)
When people first see the Issues popup, there is a delay while the Issue images load, causing the page to jump around while they are loading, which looks messy.
- [ ] Make the squares have a fixed size (where the issue images will appear) even before the Issue images finish downloading
- [ ] Request the Issue images before they are actually needed, so we aren't waiting for the images to be retrieved from the server.

**Comment by chulinguy** [comment]
I do not fully understand how the "fixed square size" will help but my PR addressed the earlier image request fix.
