### ISSUE TITLE
Mobile: When thumbs up is toggled on, add "pop down" notification

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1241]
### Please describe the issue (What happens? What do you expect?)
Currently in mobile we show overlays when you click the thumbs up or thumbs down. We want to remove these overlays, and instead show a "pop down" notification (research needed to find the best package) with similar text that shows *after* the click. The behavior in desktop should not change.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to the ballot page https://WeVote.US/ballot on your mobile device
2. Click on one office until you see candidates
3. Click on the thumbs up, and you will see that the overlay shows. You have to click again to make the thumbs up select. This should be changed so that clicking on the thumbs up causes a "pop down" notification at the top of the screen, and no overlay next to the thumbs up.

WebApp/src/js/components/Widgets/ItemActionBar.jsx
We have "supportButtonPopoverTooltip" which should show in desktop. 
- [x] Don't show "supportButtonPopoverTooltip" (or "opposeButtonPopoverTooltip") in mobile.
- [ ] Add a new "pop down" notification (from the top of the screen) that shows in mobile, but not desktop

**Comment by uncleoptimus** [comment]
Would this toast library do the trick?
https://fkhadra.github.io/react-toastify/

(or something similar)

**Comment by DaleMcGrew** [comment]
@uncleoptimus, I love the package you found! https://fkhadra.github.io/react-toastify/ Thank you for doing the research.

**Comment by uncleoptimus** [comment]
Cool, looks like we can just use the Bootstrap responsive classes to hide the tooltips on mobile 👍 

Couple quik thoughts:

- Should I go ahead and bump up the Bootstrap version to the new official 4.0 release? Btwn v3.3 and official 4.0 there have been like three different naming conventions for the responsive classes (including differences btwn the version currently used on dev branch and the new release). Downside: may break things if other folks have been using stuff from 4.0-beta that has been altered
 
- `package.json`: seems we got some dev packages listed under "dependencies" and vice-versa. Can shift stuff around a bit there if desired

**Comment by uncleoptimus** [comment]
Cool @edward-ly @DaleMcGrew , should still I go ahead and pull down these latest changes and proceed with the toast feature (only on mobile)?

Also, do we already have a programmatic way to determine if the User is on mobile? Else, I added a lil util function based on:
https://stackoverflow.com/a/3540295

Reference screen w/ default styling:
![screenshot 2018-01-24 at 23 45 50 - edited](https://user-images.githubusercontent.com/9262383/35376806-8c1b0976-0161-11e8-9698-a97895170b4f.png)

**Comment by DaleMcGrew** [comment]
Hi @uncleoptimus, yes feel free to  grab the latest changes and add the toast functionality. We use the className “visible-xs”  to get HTML elements to only show up in mobile mode. Spans and Divs with hidden-xs only show up in desktop.

**Comment by uncleoptimus** [comment]
👍  
Any styling/theme preferences? I'll increase the font size of the toast message and vertically center the text.

Also, the toast messages are currently just:

- "Support added / removed!"
- "Opposition added / removed!"

depending on the button clicked.

**Comment by DaleMcGrew** [comment]
Thank you @uncleoptimus! I think default styling is fine for now, and after we can play with it on the live site I'll see about recruiting one of our designers to share their thoughts.

**Comment by DaleMcGrew** [comment]
Hello @uncleoptimus, your pull request looks good and I am ready to approve it. Currently you submitted your pull request against your own forked repository. Could you please submit it against https://github.com/wevote/WebApp?

**Comment by uncleoptimus** [comment]
Hahah!
I felt funny about that (have only worked in shared repos) but I was trying to follow the guide. 🤔 

Anyway, I'll create that PR pronto

**Comment by DaleMcGrew** [comment]
This is working great!
