### ISSUE TITLE
Do not show BallotStatusMessage a second time (election-by-election)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1242]
### Please describe the issue (What happens? What do you expect?)
When you first look at an election on your Ballot page we show a BallotStatusMessage that says something like "This election was held on Nov 7th, 2017. Some items below may not have been on your official ballot." If you close it, it will come back the next time you return to the Ballot. We would like this message to only show once per election, until the voter closes it, so that once you close it for one election, it won't show again. I think we should set a cookie that keeps track of the elections it has been closed for.

WebApp/src/js/components/Ballot/BallotStatusMessage.jsx

**Comment by chulinguy** [comment]
fixed this bug but apparently I can only have one PR from my fork so I just updated my last PR.

**Comment by DaleMcGrew** [comment]
Fixed!
