### ISSUE TITLE
Position popover opens to the right of where it should, including off-screen

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1263]
### Please describe the issue (What happens? What do you expect?)
On the ballot we have organizational icons that when clicked, open a popover with the position of the organization. The problem is that they open significantly to the right. We would like them to open directly beneath the organizational icon. They should not open outside of the viewport (they currently do on mobile devices).
![img_4480](https://user-images.githubusercontent.com/7756031/34919290-30967124-f916-11e7-9a2d-6fee61a5b89b.jpeg)

Desktop:
<img width="262" alt="screen shot 2018-01-14 at 10 19 24 am" src="https://user-images.githubusercontent.com/7756031/34919288-11a0bf7c-f916-11e7-864c-5e2c0fc1c869.png">

### Steps to reproduce the problem (1, 2, 3...), including links
These popovers open from here (search for "organizationPopover"):
WebApp/src/js/components/Widgets/ItemSupportOpposeRaccoon.jsx

and here (search for "organizationPopover"):
WebApp/src/js/components/Position/ItemTinyPositionBreakdownList.jsx

**Comment by ixley** [comment]
@DaleMcGrew The only thing I could determine is that the popover is positioning itself relative to the trigger element, it's just not properly centering *itself*. Notice that the overlay box always positions itself relative to the trigger, but it positions its left side where its center should be. You can see this is consistent if you alter the width of any of the trigger elements. I wasn't able to figure out anything helpful beyond that, but hopefully that context is useful.

<img width="341" alt="pasted_image_1_14_18__10_22_pm" src="https://user-images.githubusercontent.com/160662/34929603-a02441fc-f979-11e7-9e10-e3685165f6d7.png">

**Comment by DaleMcGrew** [comment]
Fixed!
