### ISSUE TITLE
Implement filter so we don't run afoul of iOS App Store rules

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1299]
### Please describe the issue (What happens? What do you expect?)
I just saw this article about another App being pulled from the app store because they didn't have good enough control over the content entered in their app. We need to design a way to filter public content, so we can comply with these rules. Quote from the article:
=================
Apple’s developer guidelines for iOS apps include a section on safety that proscribes “upsetting or offensive content”. A sub-section here, regarding user-generated content (which would apply to any messaging app with a public broadcast facility, as Telegram has), notes these types of apps “present particular challenges” — and must therefore contain:

1. A method for filtering objectionable material from being posted to the app
2. A mechanism to report offensive content and timely responses to concerns
3. The ability to block abusive users from the service
4. Published contact information so users can easily reach you

“Apps with user-generated content or services that end up being used primarily for pornographic content, objectification of real people (e.g. “hot-or-not” voting), making physical threats, or bullying do not belong on the App Store and may be removed without notice,” the iOS guidelines add.

**Comment by evan-gelfand** [comment]
Here's a spec for this, specifically focusing on 1+2, which are higher priority as discussed with @DaleMcGrew : https://docs.google.com/document/d/1SDtZn96kIbgSPmpjBPY3iTHBIixhwycusWoksI6AcBA/edit?usp=sharing

**Comment by DaleMcGrew** [comment]
Thank you @evan-gelfand, your designs accomplish the goal!
