### ISSUE TITLE
Desktop mode: Ballot items dropping below the More Menu

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#13]
In desktop mode, the ballot items often drop beneath the left-hand "More" menu.

<img width="448" alt="screen shot 2016-02-10 at 11 03 42 pm" src="https://cloud.githubusercontent.com/assets/7756031/12971004/95f7ca6e-d04a-11e5-827b-11c942c8602f.png">

**Comment by pertrai1** [comment]
@DaleMcGrew Yes there are some major UI additions that will be added to stabilize the front end in the next couple of days. Hopes are to have them done for review on Saturday.

**Comment by DaleMcGrew** [comment]
Closing Issue #17 solved this. Thank you!
