### ISSUE TITLE
Header Navigation: Submenu slide down anywhere on ballot

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#132]
Desktop & Mobile
- [x] When you are 1/2 way down the ballot page, and then scroll back up, make the “Add Friends” and “More Opinions” bar animate down into place (just after the “My Voter Guide” bar does currently. Right now this “Add Friends” and “More Opinions” bar doesn’t animate down unless you are near the top of the ballot

**Comment by pertrai1** [comment]
@lisamcho would you have any time this week to look into this at all? I can pair with you if you think you could take some time to investigate the level of effort in doing this.

**Comment by lisamcho** [comment]
@pertrai1 Sure, I can look into this Wednesday night. No idea what kind of effort is required.

**Comment by lisamcho** [comment]
I found a fix for this, low effort. Will submit a pull request shortly.

**Comment by lisamcho** [comment]
See pull request #207

**Comment by DaleMcGrew** [comment]
Verified.
