### ISSUE TITLE
If Ballot is empty tell voter to enter address

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#134]
1. Clear your address
2. Go to ballot page
3. If no address has been saved, you should be redirected to http://localhost:3000/settings/location
PS. This problem was originally fixed with Issue #68, but was reintroduced after location cookie was refactored away.

**Comment by lisamcho** [comment]
So initialize is always guessing a location based on IP address right now, so I'm not sure when this is supposed to occur. When you say clear your address, that is actually enter a blank value and hit save in the address box?

**Comment by lisamcho** [comment]
To be clear, I did not refactor away the location cookie. I think it still exists along with voter_id cookie. VoterStore in general probably needs refactoring, to be done as soon as backend CreateVoter api is fixed.

**Comment by DaleMcGrew** [comment]
Thanks Lisa. createVoter API is fixed as of about 4 hours ago. The geolocation doesn't always return an address, so in cases like that A) we will get a blank address, and B) if a voter deletes their address from "My Ballot Location" and saves.

**Comment by DaleMcGrew** [comment]
Verified
