### ISSUE TITLE
Place We Vote ballot on Wordpress site

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1350]
### Please describe the issue (What happens? What do you expect?)
We have created an Interactive Ballot Tool to make it easy for organizations to place a ballot in a frame on their website: https://quality.wevote.us/settings/tools

We need someone to set up a Wordpress blog (free version) and test out adding a We Vote ballot to that blog, followed by writing instructions in this section, specific to Wordpress: https://help.wevote.us/hc/en-us/sections/115000636773-Voter-Guide-Campaign-Tools (Dale can provide the sign in for help.WeVote.US.)

We also would love to see how the set up is different on a paid Wordpress blog (you can use blog.WeVote.US)

You can find an example of how organizations embed tools like this "Register to Vote" tool here: http://younginvincibles.org/issues/civic-engagement/

**Comment by DaleMcGrew** [comment]
Archived for later.

**Comment by jarodpeachey** [comment]
@DaleMcGrew I'm running into some issues getting the Interactive Ballot Tool on the Wordpress site. I looked into this article on Wordpress embeds, and it says that you have to have a site compatible with oEmbed: 

https://wordpress.org/support/article/embeds/#oembed

After that, you have to add your site to the whitelist in order for the embed to work: 

https://wordpress.org/support/article/embeds/#adding-support-for-an-oembed-enabled-site

**Comment by DaleMcGrew** [comment]
Thank you @jarodpeachey for this research. Do they support just using a simple iFrame?

**Comment by jarodpeachey** [comment]
@DaleMcGrew No, I don't think so. I used a custom HTML block and put in an iFrame that just went to https://google.com, but it did not display. The only iFrames that you can use on Wordpress are these in the whitelist, plus anything that you add to the whitelist:

https://wordpress.org/support/article/embeds/#okay-so-what-sites-can-i-embed-from

**Comment by DaleMcGrew** [comment]
At some point we will want to do this, but I think we can put this project on hold for now, given the level of effort required. I'll Archive for Later. Thank you again!
