### ISSUE TITLE
setState error with "More Opinions" and "Opinions I'm Following"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#136]
1. Go to https://wevote.me
2. Enter "Charlotte, NC 28205" as your address.
3. Go to your ballot. (You should see many presidential candidates.)
4. Click on "More Opinions" icon in top right.
5. "Follow" 4 or 5 orgs.
6. Go to "Opinions I'm Following" in the More menu
7. Click on the "More Opinions" icon and follow more orgs. I get this error in the console log:
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

**Comment by lisamcho** [comment]
@DaleMcGrew ready to test!

**Comment by DaleMcGrew** [comment]
Verified!
