### ISSUE TITLE
Login inactive on Candidate detail page

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#1362]
If you are not logged in, and up/down vote a candidate, when you try to login from the detail page, the anonymous icon does not bring up the pop-up.

![screen shot 2018-03-02 at 11 27 27 am](https://user-images.githubusercontent.com/6923653/36917874-df8e3b06-1e0c-11e8-8e1b-fe95cddb29f1.png)

This may be related to:  wevote/WeVoteCordova/issues/19  which comes from a WebApp side issue.

**Comment by DaleMcGrew** [comment]
Fixed on my local machine, not checked in yet.
