### ISSUE TITLE
Confusing merge accounts message

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#1371]
<img width="436" alt="screen shot 2018-03-03 at 12 01 06 pm" src="https://user-images.githubusercontent.com/6923653/36938723-b26ca7ba-1eda-11e8-8288-a94631a9825d.png">

This message makes sense only if you already throughly understand how the app works, and are forgiving about the sentence logic.  A year into it, and I am not completely sure when I read this message.

An alternative:

The changes that you made when not logged in, can be merged with those changes that existed the previous time you logged in.  

Press "Merge My Offline Changes" if you would like to merge your recent offline choices, with the choices that were saved when you previously logged in.   

Press "Abandon My Offline Changes" if you want to abandon the recent changes you made when not logged in.

+------------------------------+&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;+---------------------------------+ 
|&nbsp; &nbsp;&nbsp;Merge My Offline Changes&nbsp; &nbsp;&nbsp;|&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp; &nbsp;&nbsp;Abandon My Offline Changes&nbsp; &nbsp;&nbsp;|
+------------------------------+&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;+---------------------------------+

**Comment by DaleMcGrew** [comment]
Thank you Steve, these are some great suggestions. I'll get my head around it and make some changes.

**Comment by DaleMcGrew** [comment]
Fixed but not checked in yet.
