### ISSUE TITLE
JSCS has been deprecated

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#1405]
While exploring a irritating JSCS warning where in *.js files, JSCS doesn't like the space after $ajax in the following line, but es-lint insists on having one there, I stumbled upon the fact that the JSCS project has  been ended and has been merged merged with es-lint

```
export function $ajax (options) {
```

   https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2

As of today ESLint is at "v4.19.0 released 16 March 2018"

   https://eslint.org/

We are at:

```
    "eslint": "^3.13.1",
    "eslint-plugin-react": "^6.9.0",
    "jscs": "^3.0.7",
```

------
This would take a sensitive touch to change, we don't want to create a zillion more red indictors in our code.

**Comment by DaleMcGrew** [comment]
This will be an important upgrade. Given our current backlog, we will tackle this in 2019. I have labeled this "Archive for Later".
