### ISSUE TITLE
Prevent form submit temporarily, Create Your Voter Guide, Step 1

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1465]
### Please describe the issue (What happens? What do you expect?)
In Step 1 of "Create Your Voter Guide", we ask a voter to enter their Twitter handle:
https://wevote.us/voterguidegetstarted
In user testing we found that the voter enters their Twitter handle, and then hits return. The problem with this is that it doesn't give the page a chance to receive the response from the server with the Twitter data. I attempted a fix, and in fact changed the button to say "One Moment...", but I wasn't able to disable the form. Please disable the form until we have received a response from the server.
This is only a problem in desktop mode.

### Steps to reproduce the problem (1, 2, 3...), including links
The code for this is here:
WebApp/src/js/routes/VoterGuide/VoterGuideGetStarted.jsx

**Comment by chulinguy** [comment]
Can I take this one please?

**Comment by DaleMcGrew** [comment]
Its all yours!
