### ISSUE TITLE
Install Google Analytics Code in WebApp

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#147]
Please note that we will need to add the actual analytics code as an environment variable, as opposed to directly in the code. WeVote.me tracking code: UA-53643204-3
Please let @hdronamraju know when this is done.

This is the analytics code for https://wevote.me (click edit to see)
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53643204-3', 'auto');
  ga('send', 'pageview');

</script>`

This is the code for the c3 site to be created: (click edit to see code)
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75328949-1', 'auto');
  ga('send', 'pageview');

</script>`

**Comment by pertrai1** [comment]
@DaleMcGrew I am not sure what the c3 site is. We can set environment variables but would need to know the process for determining what variable state to use during deployment. Maybe the context of the c3 site will help more.

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 because We Vote will eventually allow political conversation, the network we grow to 10 Million members will need to be running on servers paid for by our 501(c)(4) (due to IRS rules about what a 501(c)(3) can and can't do in order to maintain nonprofit status). This is http://wevote.me.

As long as we don't offer those communication features under the network paid for by our (tax deductible) 501(c)(3), we can run a version of We Vote on a separate 501(c)(3) funded network (funded by tax deductible donations). One benefit of this is that we can apply for a $10,000 per month Google AdWords budget so we can drive voters to the 501(c)(3) version of the site and observe their behavior. This is the parallel site that Joe is almost done installing at http://WeVote.guide and http://api.wevoteeducation.org

**Comment by DaleMcGrew** [comment]
Verified.
