### ISSUE TITLE
Popover "x" isn't working for some popovers

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1485]
### Please describe the issue (What happens? What do you expect?)
These two popovers have a problem with the "x" not working:
![screen shot 2018-04-26 at 10 21 38 am](https://user-images.githubusercontent.com/7756031/39321392-bb6c558c-493b-11e8-8278-106ff6fc5b38.png)

![screen shot 2018-04-26 at 10 23 00 am](https://user-images.githubusercontent.com/7756031/39321420-d8c2b28e-493b-11e8-9e5e-50d54b4e0f57.png)

**Comment by DaleMcGrew** [comment]
Hello @ndrewr, do you think you would be able to fix this before the end of this week? (I hope you had a good weekend!)

**Comment by ndrewr** [comment]
Sure thing. 👍 
Got caught up trying to trace `ref` values over a couple sessions. I think the trigger component is not properly referenced.
https://reactjs.org/docs/refs-and-the-dom.html#callback-refs

But the truth is a fix in this situation is probably as simple as invoking another click on the label to close the popover. I forget that sometimes its more important to get something working to satisfaction so you can move on.

**Comment by DaleMcGrew** [comment]
Fixed!
