### ISSUE TITLE
React warning messages

### ISSUE THREAD

**Issue by chulinguy** [wevote/WebApp#1490]
### Please describe the issue (What happens? What do you expect?)
-React warning messages
![setstate warning](https://user-images.githubusercontent.com/25993366/39417574-13ebb48e-4c0a-11e8-9b60-8c004e104492.JPG)

### Steps to reproduce the problem (1, 2, 3...), including links
1) Sign in with Twitter handle
2) You should be redirected to a Twitter API page that asks you "Authorize We Vote Social Voter Guide to use your account?", click "Authorize App"
3) You'll be redirected back to WeVote with a "you've signed in with Twitter message", at which point the warning messages appear

**Comment by DaleMcGrew** [comment]
Archived for later.
