### ISSUE TITLE
Fix vertical alignment for organization positions list on ballot page

### ISSUE THREAD

**Issue by edward-ly** [wevote/WebApp#1500]
When viewing the ballot page on mobile, the list of organizations for each candidate is misaligned vertically in relation to the surrounding scroll icons.

![screenshot from 2018-05-03 16-50-42](https://user-images.githubusercontent.com/11434331/39607858-65b16bfc-4ef2-11e8-98d6-cdeff71f6834.png)

**Comment by DaleMcGrew** [comment]
Hello @edward-ly, does this require further work?

**Comment by DaleMcGrew** [comment]
Verified!
