### ISSUE TITLE
itemActionBar - yes_vote_description formatting

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1507]
### Please describe the issue (What happens? What do you expect?)
When a voter is looking at a measure that has text describing what a "Yes vote" and a "No vote" mean, the text is not formatted yet:
![screen shot 2018-05-10 at 3 35 13 pm](https://user-images.githubusercontent.com/7756031/39897594-ca115d30-5467-11e8-8c0d-d50d3c031616.png)

### Steps to reproduce the problem (1, 2, 3...), including links
The code for this is here:
WebApp/src/js/components/Widgets/ItemActionBar.jsx
Search for "yesVoteDescription"

**Comment by josh-southern** [comment]
@DaleMcGrew Hey I've unassigned myself because I've been busy with work and I don't know how soon I can contribute again, so I want to leave this up for someone else to grab if they want to tackle it. Have a good hacking session tonight!

**Comment by DaleMcGrew** [comment]
Looks great @edward-ly, thank you!
