### ISSUE TITLE
Upgrade how we import @import 'dist/css/bootstrap-grid';

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1516]
### Please describe the issue (What happens? What do you expect?)
We are getting this error when we build (npm start):

DEPRECATION WARNING on line 7, column 8 of /home/wevote/WebApp/src/sass/bootstrap.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

**Comment by agheith** [comment]
This behavior currently violates the language specification. Importing a `.css` file from node-sass makes code non-portable. For the time being, it's recommended to stop importing `.css` files until the next release of node-sass@4.10, which is going to target some edge cases around import and custom importer. [https://github.com/sass/node-sass/issues/2362](url)

**Comment by DaleMcGrew** [comment]
Archived for later.
