### ISSUE TITLE
Rapid clicks on Support/Oppose links excessively increment counts

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#153]
By rapidly clicking on support and oppose buttons, the counts can be moved by more than the intended single toggle. Bug seems to depend on the delay that that the clicks are registered.

Occurs on:
- both Ballot and Candidate pages. 
- Mac, latest versions of Chrome, Safari, Firefox, and iOS versions of Safari and Chrome

*Will try to attach a screen capture when I get a chance

**Comment by DaleMcGrew** [comment]
Thank you @ixley! It would be helpful to know: Browser you were using, whether in desktop or mobile mode, and whether you were on the ballot summary page or Candidate page.

**Comment by lisamcho** [comment]
Just submitted a pull request to fix this.

**Comment by DaleMcGrew** [comment]
@ixley would you be willing to verify this fix and close it? Code is live on https://WeVote.me

**Comment by pertrai1** [comment]
@lisamcho Can you reference that pull request here so we will have a history of the changes with this issue?

**Comment by lisamcho** [comment]
Sure, its' #158

**Comment by ixley** [comment]
I only verified on mobile but it looms good to me.

**Comment by DaleMcGrew** [comment]
Thank you Jeff!
