### ISSUE TITLE
Reset anchor tag in ballot URL when you open office/measure after jumping to anchor tag

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1537]
### Please describe the issue (What happens? What do you expect?)
Under discussion.

**Comment by DaleMcGrew** [comment]
Hi @jingyiwang1209, I am loving how this is working. Thank you! I found one bug: If you support/oppose a Proposition (ex/ "California Proposition 68: California Parks, Environment, and Water Bond") it jumps back to the last office anchor tag.

**Comment by jingyiwang1209** [comment]
Dale, thanks for pointing this out. I just fixed it. The reason was California Proposition 68 and other offices whose type are "MESURE" do not call the function that I updated last time.

**Comment by DaleMcGrew** [comment]
Resolved.
