### ISSUE TITLE
On Candidate detail pages, add a link to the Office page with all of the candidates

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1544]
### Please describe the issue (What happens? What do you expect?)
Example candidate page: https://wevote.us/candidate/wv02cand30682

"I can't figure out how to view all the candidates on position I already decided about.  For example, I had clicked that I support Barbara Lee, but I actually want to go back and see who else is on the ballot, and maybe support someone else (at least in the primary, I don't think there are any other Dems running against her, but now I'm thinking I might like to vote for someone to the left of her to help them be the 2nd candidate on the Nov. ballot.)

Anyways, in "Your Positions" under my "California Primary Elections" voter guide, I see "Barbara Lee".  Clicking on her opens her candidate page (https://wevote.us/candidate/wv02cand30682), and it lists that she's a candidate of " U.S. House California District 13", but that's not clickable.

Similarly, in my ballot, under "Items Decided", there's the "U.S. House California District 13 " line, with two links seemingly separate links to "View Candidate" and "Show More", but both of those open the exact same thing: more about Barbara Lee (opinions about her, related issues, etc.).   There's no link to "view all candidates" like there is under the positions in the "Remaining Decisions" tab of my ballot.

**Comment by chulinguy** [comment]
Can I take this issue?

**Comment by DaleMcGrew** [comment]
Sure! There is some complexity given we have "Back to" variables to include if they came in for the candidate. See:
WebApp/src/js/Root.jsx, around line 97:
      <Route path="/office/:office_we_vote_id/b/:back_to_variable/" component={Office} />
      <Route path="/office/:office_we_vote_id/:back_to_variable/:organization_we_vote_id" component={OrganizationVoterGuideOffice} />
      <Route path="/office/:office_we_vote_id/:organization_we_vote_id" component={OrganizationVoterGuideOffice} />
      <Route path="/office/:office_we_vote_id" component={Office} />

**Comment by DaleMcGrew** [comment]
This works great, thank you! Verified.
