### ISSUE TITLE
Create Your Voter Guide, stuck at step 4

### ISSUE THREAD

**Issue by chulinguy** [wevote/WebApp#1551]
### Please describe the issue (What happens? What do you expect?)
There seems to be a particular flow that makes the app stuck during creating a voter guide.
I got stuck at the step 4, as clicking on the 

### Steps to reproduce the problem (1, 2, 3...), including links
1. Clear cookies
2.  Try to sign in as a Twitter user
3.  Click "authorize app"
4.  Try to create a voter guide; the app will jump to step 3 as it already has your twitter data
5.  Update the inputs to other values in step 3 and click "next"
6.  At step 4, the app presents you with at least one election option, try clicking on one election
7.  The app is stuck at step 4

**Comment by DaleMcGrew** [comment]
We will tackle this in 2019.
