### ISSUE TITLE
Get API server to use voter_device_id from WebApp

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#16]
We need to pass the voter_device_id from a cookie in the voter's browser, over the wire to the API server. The API server won't have access to the voter_device_id cookie from the WebApp running in the browser. If we pass voter_device_id as a GET variable, routers that pass along the URL will show the voter_device_id, which needs to remain secret. Do we need to convert all API calls to POST, so the voter_device_id remains secret?

**Comment by nf071590** [comment]
No we can send it with the cookies. That is how we send all the requests so
far... They send the csrf Middleware token along with some other cookies to
the server on every request.

**Comment by DaleMcGrew** [comment]
Hi Nick, if you remove your "voter_device_id" cookie (this cookie is created every time you visit "https://api.wevoteusa.org"), and then try to use the WebApp, you get a cross-domain error. When we were all working on localhost, we didn't see this error. I think this is caused because api.wevoteusa.org doesn't have access to the locahost cookie that the WebApp sets. I don't think we want to set a voter_device_id cookie on the api server -- we want to pass that from the browser where the WebApp is running.

**Comment by DaleMcGrew** [comment]
I have been researching this and testing some changes to no avail. Can I get someone's help with debugging this (I'm open to pair programming)? It is hard to tell if we aren't sending the right headers from WebApp, or if the API server has CORS set up correctly so we can see incoming cookies from other domains.

Notes:
* API SERVER COOKIE ONLY: Currently, if you have a voter_device_id cookie set up on both localhost and the API server, a WebApp call (to an API Endpoint 'voterAddressRetrieve' for example) will *only* pay attention to the API server 'voter_device_id' cookie.
* COOKIE NAME COLLISION: As of 2013, the DJANGO CORS implementation didn't provide a way to distinguish between identically named cookies. So if WebApp passed voter_device_id, there wasn't a way to tell it apart from a voter_device_id cookie created on the API Server. To deal with this, I am migrating the API server cookie to the name 'voter_api_device_id'.
* POSTs to API server: currently (I believe -- I'm having a hard time confirming) we are getting a complaint about cross domain posts when we try to POST to an API server endpoint from WebApp on localhost.

Here are the best articles I'm finding:
https://github.com/ottoyiu/django-cors-headers
http://www.html5rocks.com/en/tutorials/cors/

**Comment by pertrai1** [comment]
@DaleMcGrew @nf071590 Maybe just setup JSONP to handle the issue with a callback that will take care of the security issue and then handle the request/response -  https://www.wikiwand.com/en/JSONP

**Comment by DaleMcGrew** [comment]
Thanks Rob, Nick and I are working on this right now. We are switching things to pass the voter_device_id as a GET variable.

**Comment by DaleMcGrew** [comment]
@nf071590 @DaleMcGrew pair programmed and decided to just pass the voter_device_id as a GET variable. Live server is up to date now, and as soon as we have updated all of the WebApp endpoints to pass voter_device_id as a GET variable, we will be able to close this.

**Comment by DaleMcGrew** [comment]
This issue is now resolved.
