### ISSUE TITLE
Eliminate some Twitter OAuth callbacks, so that we have room for localhost

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#1607]
Twitter only allows 10 callbacks, and we have used all 10, some might not be needed, but we need to free up room for localhost if we want to be able to debug twitter login with Python on our Macs.

Twitter advises having a single callback with url, with a parameter that selects the action...
so
    https://api.wevoteusa.org/complete/twitter/
would become
    https://api.wevoteusa.org/twitterCallback&action=complete
and
    https://api.wevoteusa.org/login/twitter/
would become
    https://api.wevoteusa.org/twitterCallback&action=login

Then you would only need 1 callback URL for multiple actions

--------- Our 10 callbacks as they exist today --  https://apps.twitter.com/app/9433049/settings
**Callback URLs**
_Where should we return after successfully authenticating? OAuth 1.0a applications must explicitly specify their oauth_callback URL(s) here, as well as include the one of the URLs below in the request token step. To restrict your application from using callbacks, leave this field blank._

https://api.wevoteusa.org:443/auth/complete/twitter/

https://api.wevoteusa.org/complete/twitter/

https://api.wevoteusa.org/login/twitter/

https://api.wevoteusa.org/auth/complete/twitter/

https://wevote.us/twitter_sign_in/

https://api.wevoteusa.org:443/login/twitter/

https://api.wevoteusa.org:443/complete/twitter/

https://wevote.us/twitter_sign_in

https://api.wevoteusa.org/apis/v1/twitterSignInRequestAccessToken/

https://api.wevoteusa.org/apis/v1/twitterSignInRequestVoterInfo/

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve I am going to combine "twitterSignInRequestAccessToken" and "twitterSignInRequestVoterInfo" to make room for "https://localhost:3000/twitter_sign_in". 

Question: Are we using Twitter Kit for Cordova? "If you use Twitter Kit for iOS or Android, you will have to use the following callback URLs:"
- Android - twittersdk://
- iOS - twitterkit-CONSUMERKEY://

https://developer.twitter.com/en/docs/basics/apps/guides/callback-urls.html

If we aren't using Twitter Kit, do we need any other URL's for mobile sign in?
PS. I am going to set up another Twitter app that we can use for local WeVoteServer testing and development.

**Comment by DaleMcGrew** [comment]
I am able to sign in locally and on the live API server with the current (updated) Callback URL's.
