### ISSUE TITLE
Issues don't appear on Issues Following page without refresh

### ISSUE THREAD

**Issue by aschneit** [wevote/WebApp#1611]
### Please describe the issue (What happens? What do you expect?)
After selecting issues and going to the issues following page, no issues appear until the page is refreshed.

### Steps to reproduce the problem (1, 2, 3...), including links
Select issues
Go to https://wevote.us/issues_followed
No issues appear
Refresh the page
Issues appear

**Comment by DaleMcGrew** [comment]
Verified!
