### ISSUE TITLE
Use HTML5 local storage to store your ballot card, if no internet in the voting booth

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#1615]
HTML 5 local storage would solve the problem for both Cordova and the WebApp in mobile devices.
Add an opt out option, for those who are worried about security/privacy.
Store the voter's currently selected election, with 
* The election title
* The election date
* Each Office, Measure, & Proposition
* and your choice for each, or "undecided"

Upon detecting AJAX timeouts, change to the static ballot card page.
Display it as rows of text, with minimal styling.

Add a button to "Try online access" which would navigate to the ballot page.

**Comment by DaleMcGrew** [comment]
This will be a very important upgrade. Given our current backlog, we will tackle this in 2019. I have labeled this "Archive for Later".
