### ISSUE TITLE
Add "beta" to header under We Vote logo (Desktop)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1625]
### Please describe the issue (What happens? What do you expect?)
When viewing the website in desktop mode (not needed in mobile), add the word "beta" (as HTML) to the lower right of the logo (aligned vertically with "Ballot") so we don't have to add any more width.
![screen shot 2018-07-31 at 9 57 52 am](https://user-images.githubusercontent.com/7756031/43474707-76b16140-94a8-11e8-9141-b120eeb11315.png)

Alternately, it could be to the right of the We Vote logo. If this route is necessary, please make sure the layout and spacing remains as it is otherwise. Please test thoroughly.

**Comment by DaleMcGrew** [comment]
No longer needed.

**Comment by DaleMcGrew** [comment]
Hello @gj262, would you like to work on this issue?

**Comment by gj262** [comment]
yeah, I can take a look.

**Comment by gj262** [comment]
Here is how it could look below the logo:

![screen shot 2018-10-24 at 3 13 24 pm](https://user-images.githubusercontent.com/6854428/47464978-dfd74880-d79f-11e8-97fe-65c0c36ed631.png)

I think it is slightly nicer offset:

![screen shot 2018-10-24 at 3 15 51 pm](https://user-images.githubusercontent.com/6854428/47465013-fb425380-d79f-11e8-99af-1dc51c2a145a.png)

It can be lowercase or capitalized or a different color etc.

**Comment by DaleMcGrew** [comment]
Hello @gj262, I think you are right -- I think the offset version looks better. I suspect all lower case will look best. Could you also add the "beta" to the mobile version, where it is just our "W" icon? I'd be interested to see how that looked.

**Comment by gj262** [comment]
I'm not lovin all lowercase in mobile due to the proximity of "Ballot" & "Network"

![screen shot 2018-10-24 at 3 59 17 pm](https://user-images.githubusercontent.com/6854428/47466399-e4066480-d7a5-11e8-95a4-b2cb8f5e8ca7.png)

![screen shot 2018-10-24 at 3 57 18 pm](https://user-images.githubusercontent.com/6854428/47466338-abff2180-d7a5-11e8-93ea-8768a11551be.png)

**Comment by DaleMcGrew** [comment]
I’m cool with “Beta”!  It looks great.
