### ISSUE TITLE
Unable to close Ballot modal after entering address 

### ISSUE THREAD

**Issue by jappareti** [wevote/WebApp#1670]
The ballot issue box won't close after you save your address.

<img width="979" alt="screenshot 2018-09-05 19 51 46" src="https://user-images.githubusercontent.com/1170323/45132265-22d45280-b145-11e8-8f87-457e15d88078.png">

### Steps to reproduce:

1. Click on "Issues" which brings up the modal https://www.wevote.us/ballot
2. Select your issues, until you get to the address
3. Enter an address and click Save

A loading indicator shows up, but doesn't go away. You also can't close the ballot modal by clicking the close button or outside of the modal popup.

**Comment by DaleMcGrew** [comment]
Thank you @jappareti for fixing this!
