### ISSUE TITLE
Replace broken image links?

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#168]
For opinions there seems to be a lot of dead links. Is there a placeholder image that we should display instead?

**Comment by DaleMcGrew** [comment]
Thank you Lisa, yes we need to investigate why those links are dead on the data side. That said, is there a way to detect in WebApp if an image link is broken, and replace it with our "default org" image?

Rob @pertrai1 will know for sure, but I think this is the style with the default org icon:
icon-icon-org-placeholder
<i className="icon-lg icon-main icon-icon-org-placeholder-6-2 icon-light"/>

**Comment by lisamcho** [comment]
@DaleMcGrew so if I'm the one who originally filed the bug should I just tag someone else like you to verify the fix and close the issue?

**Comment by DaleMcGrew** [comment]
Verified!
