### ISSUE TITLE
On Candidate page: Give more space and spacing for Candidate bio

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1682]
When on the candidate page, show more lines of descriptive text, make the text larger, and give it more line padding.
<img width="669" alt="screen shot 2018-09-17 at 3 08 07 pm" src="https://user-images.githubusercontent.com/7756031/45653134-bc77fa00-ba8b-11e8-8d57-12b04c92b7ec.png">

**Comment by josh-southern** [comment]
Going to take this one. Will try and get it done tonight.

**Comment by fulin426** [comment]
submitted as PR #1846 
![screen shot 2019-01-07 at 11 37 16 pm](https://user-images.githubusercontent.com/35435397/50816365-351df300-12d5-11e9-8561-b294d600baf1.png)

**Comment by DaleMcGrew** [comment]
Thank  you Fu-Lin!
