### ISSUE TITLE
Glitch with "Related Issues" list popover position

### ISSUE THREAD

**Issue by edward-ly** [wevote/WebApp#1691]
### Please describe the issue (What happens? What do you expect?)

When viewing the list of related issues on a candidate's page, the popovers that appear after clicking on an item can show up at a seemingly random position (far) above their respective issue.

![screenshot 2018-09-20 22 48 07](https://user-images.githubusercontent.com/11434331/45863060-54deda80-bd29-11e8-8e80-543191bdfdd4.png)
![screenshot 2018-09-20 23 04 05](https://user-images.githubusercontent.com/11434331/45863125-9c656680-bd29-11e8-90e5-44e27fabe068.png)

Please fix the positions of each popover to be consistent with other popovers in the app (such as the one above the "Related Issues" label).

### Steps to reproduce the problem (1, 2, 3...), including links

1. Go to a candidate's page with a list of related issues (such as [Xavier Becerra](http://localhost:3000/candidate/wv02cand40273/b/btdb/)).
2. Scroll down to the bottom of the page to see said list, and click on several of the issues in the list. Note the position of the popover that appears for each issue.

The component in question:
src/js/components/Issues/IssueTinyDisplay.jsx

**Comment by DaleMcGrew** [comment]
Replaced with updated issue component.
