### ISSUE TITLE
NPM package updates needed to remove vulnerabilities

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1693]
### Please describe the issue (What happens? What do you expect?)
![screen shot 2018-09-27 at 12 27 07 pm](https://user-images.githubusercontent.com/7756031/46169878-209b7a80-c251-11e8-98e9-07a0d77c2aea.png)

Note that some the packages that we do not want to update before the 2018 election (due to the level of upgrade and testing needed) include:
 - react
 - react-dom

**Comment by SailingSteve** [comment]
Some of these addressed in https://github.com/wevote/WebApp/pull/1815

**Comment by SailingSteve** [comment]
Steves-MacBook-Pro-32GB-Oct-3171:WebApp stevepodell$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install --save-dev browserify@16.2.3  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ cached-path-relative                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ browserify [dev]                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ browserify > cached-path-relative                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/739                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ cached-path-relative                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ browserify [dev]                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ browserify > module-deps > cached-path-relative              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/739                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update browserify --depth 2  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ cached-path-relative                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ watchify [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ watchify > browserify > cached-path-relative                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/739                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ cached-path-relative                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ watchify [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ watchify > browserify > module-deps > cached-path-relative   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/739                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
│               │ >                                                            │
│               │ 96a850888a05783af6da17cfc4c90ba98bd49c29164eede2ad4d87e9afa… │
│               │ > babel-core > minimatch                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
│               │ >                                                            │
│               │ 96a850888a05783af6da17cfc4c90ba98bd49c29164eede2ad4d87e9afa… │
│               │ > recursive-readdir > minimatch                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jscs [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jscs > jscs-jsdoc > jsdoctypeparser > lodash                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jscs [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jscs > lodash                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jscs [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jscs > xmlbuilder > lodash                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
│               │ [dev]                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
│               │ >                                                            │
│               │ 96a850888a05783af6da17cfc4c90ba98bd49c29164eede2ad4d87e9afa… │
│               │ > babel-core > babel-plugin-proto-to-assign > lodash         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
│               │ [dev]                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 006915fd477ff8669f398052c5e8901744f1e6dddba019c8a2adfeb3df7… │
│               │ >                                                            │
│               │ 96a850888a05783af6da17cfc4c90ba98bd49c29164eede2ad4d87e9afa… │
│               │ > babel-core > lodash                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 11 vulnerabilities (5 low, 6 high) in 29158 scanned packages
  run `npm audit fix` to fix 2 of them.
  2 vulnerabilities require semver-major dependency updates.
  7 vulnerabilities require manual review. See the full report for details.
Steves-MacBook-Pro-32GB-Oct-3171:WebApp stevepodell$

**Comment by SailingSteve** [comment]
Steves-MacBook-Pro-32GB-Oct-3171:WebApp stevepodell$ npm audit | grep Path
│ Path          │ browserify > cached-path-relative                            │
│ Path          │ browserify > module-deps > cached-path-relative              │
│ Path          │ watchify > browserify > cached-path-relative                 │
│ Path          │ watchify > browserify > module-deps > cached-path-relative   │
│ Path          │ 9df9a6b7f5f09310f57bc758784b88829198e627b5edbc535828dcbbd38… │
│ Path          │ 9df9a6b7f5f09310f57bc758784b88829198e627b5edbc535828dcbbd38… │
│ Path          │ jscs > jscs-jsdoc > jsdoctypeparser > lodash                 │
│ Path          │ jscs > lodash                                                │
│ Path          │ jscs > xmlbuilder > lodash                                   │
│ Path          │ 9df9a6b7f5f09310f57bc758784b88829198e627b5edbc535828dcbbd38… 
  >babel-core > babel-plugin-proto-to-assign > lodash
│ Path          │ 9df9a6b7f5f09310f57bc758784b88829198e627b5edbc535828dcbbd38… │
 > babel-core > lodash
Steves-MacBook-Pro-32GB-Oct-3171:WebApp stevepodell$

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, running ```npm audit fix``` will solve 2 of these vulnerabilities.

**Comment by SailingSteve** [comment]
Steves-MacBook-Pro-32GB-Oct-3171:WebApp stevepodell$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 28034 scanned packages
Steves-MacBook-Pro-32GB-Oct-3171:WebApp stevepodell$

**Comment by SailingSteve** [comment]
Had to back out some earlier changes, to get "npm start" to complete babelify.  Will get back to this.
