### ISSUE TITLE
Google Search: Garbage text under description

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1694]
### Please describe the issue (What happens? What do you expect?)
Please implement a fix so that the garbage text under We Vote when you search with Google shows the description of We Vote. I believe this text should be coming from this file:
WebApp/src/index.html

<img width="821" alt="wevote-descriptiongarbagetext" src="https://user-images.githubusercontent.com/7756031/46170027-8425a800-c251-11e8-9fce-9bbcc9b65dc2.png">

**Comment by josh-southern** [comment]
Should this issue be closed?

**Comment by DaleMcGrew** [comment]
Hi @josh-southern we approved the pull request, but because of our update to React 16 we haven't been able to update the live site to verify that it is working. I'm marking it Verify Fix.

**Comment by DaleMcGrew** [comment]
Site updated with a fix Friday morning 10/26, Google not updated yet by Saturday morning 10/27.

**Comment by DaleMcGrew** [comment]
Verified!
