### ISSUE TITLE
Embed We Vote in frame: Display fixes needed

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1695]
### Please describe the issue (What happens? What do you expect?)
We Vote can be used by partners who want to embed an interactive ballot on their website. We show this on a sample page example here:
http://localhost:3000/more/myballot
WebApp/src/js/routes/More/WeVoteBallotEmbed.jsx

Currently, the iframe area has these issues:
 - [ ] Display area for the ballot much too small
 - [ ] Make sure that you can scroll up and down the ballot
 - [ ] Verify that the Issues modal still shows up in the top of the frame
 - [ ] Please test thoroughly for other issues

![screen shot 2018-09-27 at 1 17 55 pm](https://user-images.githubusercontent.com/7756031/46172217-cce05f80-c257-11e8-87a1-4cf319b93ecf.png)

We also provide sample code for putting We Vote on another site:
https://wevote.us/more/tools
Under "Interactive Ballot Tool", click "Show Code":
 - [ ] Please test this sample code on your local machine
 - [ ] In particular, please make sure that you can scroll up and down the ballot
 - [ ] Verify that the Issues modal still shows up in the top of the frame
Please see: WebApp/src/js/routes/More/ToolsToShareOnOtherWebsites.jsx

Once the "http://localhost:3000/more/myballot" page is working, please update the link "Click to view full size" (on "http://localhost:3000/more/tools") under "Interactive Ballot Tool" with a link that opens in a new tab like "Click to view example" under "Voter Guide Tool".

**Comment by DaleMcGrew** [comment]
Hi @lazorfuzz, when we are back from break, I would love to review this together, via screen share.

**Comment by lazorfuzz** [comment]
Hi @DaleMcGrew that sounds good. I tested for everything on the check list, the scrolling, modal position, etc. seem to work fine for me. The only issue I noticed was interactive ballot embed code not showing the iframe at full size, which I fixed in that last PR. Please let me know if I missed anything, thanks!

**Comment by DaleMcGrew** [comment]
Closed until this can be more thoroughly tested.
