### ISSUE TITLE
Detached google address list on WebApp in mobile browsers

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#1697]
1) Start up WebApp in Safari on an iPhone
2) Click "Issues" on the secondary bar
3) On the "verify your address" pane, if there is no address, enter one.
4) Press the X in the upper right corner, and you get a detached list with "powered by Google"

Other strange visual glitches happen, and exceptions are thrown in what looks like in Google code.
Same things happen in Cordova.

**Comment by SailingSteve** [comment]
![img_4062](https://user-images.githubusercontent.com/6923653/46175907-644ab000-c262-11e8-865b-b8c014e26b38.PNG)
![img_4065](https://user-images.githubusercontent.com/6923653/46175908-644ab000-c262-11e8-9fa0-56a6979817a8.PNG)
![img_4063](https://user-images.githubusercontent.com/6923653/46175909-644ab000-c262-11e8-8836-a6e070bdb03c.PNG)
![img_4064](https://user-images.githubusercontent.com/6923653/46175910-644ab000-c262-11e8-8809-538a03f4f0f2.PNG)

**Comment by DaleMcGrew** [comment]
We are removing the "verify your address" from this modal, so I am closing this bug.
