### ISSUE TITLE
Multiple issues with More Menu component

### ISSUE THREAD

**Issue by nf071590** [wevote/WebApp#17]
In desktop mode, the more menu pushes all the other components to the bottom.

Also, when in mobile view; More Menu hamburger icon displays more menu but clicking it again does not close the menu. There is no way to close the more menu when in mobile view.

**Comment by DaleMcGrew** [comment]
When the hamburger icon is clicked in mobile mode, please display a slide out more menu (populated from the "src/js/components/MoreMenu" component) that only fills ~250px of the left side of the screen. When you click anywhere to the right of the slide-out (or if you click the hamburger icon again), the more menu should slide off the screen.

**Comment by pertrai1** [comment]
@nf071590 @DaleMcGrew - I created a pull request that should be handling this issue now. Dale, your comment about the hamburger should be a different issue created.

**Comment by pertrai1** [comment]
merged #20
