### ISSUE TITLE
"What I Support" page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#170]
- [ ] Add version of /src/js/routes/Ballot/Ballot.jsx page that only shows offices + candidate and measures where a voter has expressed support

**Comment by DaleMcGrew** [comment]
This API endpoint, which returns what a voter supports or opposes by ballot_item_we_vote_id, is on the live server now:
https://api.wevoteusa.org/apis/v1/docs/voterAllPositionsRetrieve/

**Comment by lisamcho** [comment]
Implemented in #185

**Comment by DaleMcGrew** [comment]
Verified! Works like a charm. Great work!
