### ISSUE TITLE
Email Sign In: Make input box wider on desktop

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1708]
Leave more room for someone's email address on the email settings page. (for example, the email in this screenshot is "Dale.McGrew@WeVote.US" and it is getting cut off.)

![screen shot 2018-10-06 at 4 06 02 am](https://user-images.githubusercontent.com/7756031/46570698-3417a700-c91d-11e8-8909-75f543858275.png)

**Comment by indefinitelee** [comment]
how do you feel about using inline styles to accomplish this? or do you have another preferred method?

**Comment by DaleMcGrew** [comment]
Hello @indefinitelee, ideally you could add a specific style to WebApp/src/sass/components/_settings.scss and apply it to this input box.  For styles, we are big fans of BEM Naming:
http://getbem.com/naming/
https://css-tricks.com/bem-101/
https://css-tricks.com/snippets/sass/bem-mixins/

Thank you!

**Comment by DaleMcGrew** [comment]
Hi @josh-southern thank you for working on this last night. I don't think your changes made it into your pull request.

**Comment by DaleMcGrew** [comment]
Please make sure to test your solution on mobile. Thank you!

**Comment by DaleMcGrew** [comment]
Great work @josh-southern.
