### ISSUE TITLE
Move "Edit Address" Save Button to be Inline with Input Box

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1709]
Please move the "Save" button to be inline with the "Edit Address" input box.

![screen shot 2018-10-06 at 4 08 22 am](https://user-images.githubusercontent.com/7756031/46570714-abe5d180-c91d-11e8-89f5-5c54e5741437.png)

![screen shot 2018-10-06 at 4 07 58 am](https://user-images.githubusercontent.com/7756031/46570715-aee0c200-c91d-11e8-976c-40cde553341b.png)

**Comment by DaleMcGrew** [comment]
Hi Josh, since there isn't room to put the "Save" button on the same line in mobile, perhaps move it to the far right, with the cancel link to the left of it?
![screen shot 2018-10-18 at 1 47 40 pm](https://user-images.githubusercontent.com/7756031/47183320-93da5e80-d2dc-11e8-875b-52c9261c2ae8.png)

**Comment by josh-southern** [comment]
I'll try and get that in on Saturday.

**Comment by josh-southern** [comment]
Should be fixed now! Tell me if there needs to be more changes.

**Comment by DaleMcGrew** [comment]
Hi @josh-southern, since your prior pull request was approved, could you please submit a new pull request with your changes? Did you get a chance to also work on https://github.com/wevote/WebApp/issues/1708 ? Many thanks.

**Comment by josh-southern** [comment]
https://github.com/wevote/WebApp/issues/1708 Should be fixed already. I'll open a new PR.

**Comment by DaleMcGrew** [comment]
Thank you @josh-southern!
