### ISSUE TITLE
Issue with Facebook login when signing up for the first time

### ISSUE THREAD

**Issue by ericboucher** [wevote/WebApp#1717]
### Please describe the issue (What happens? What do you expect?)
Using Facebook to login does not work. Nothing happens when clicking on the button.

<img width="944" alt="screen shot 2018-10-12 at 1 34 11 pm" src="https://user-images.githubusercontent.com/16843267/46892840-a7408200-ce23-11e8-8308-4fded7f975ab.png">

### Steps to reproduce the problem (1, 2, 3...), including links
If you have never logged in using Facebook. Go to the Sign In page and try to use Facebook to login.

**Comment by DaleMcGrew** [comment]
Verified!

**Comment by ericboucher** [comment]
Nice! What was the issue?

Eric Boucher

**Comment by DaleMcGrew** [comment]
https://github.com/wevote/WeVoteServer/pull/980 We will need to do more extensive sign in testing with new voters going forward.
