### ISSUE TITLE
React 16 Upgrade: Please remove line breaks after election name

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1734]
### Please describe the issue (What happens? What do you expect?)
![screen shot 2018-10-18 at 2 18 09 pm](https://user-images.githubusercontent.com/7756031/47184870-b40c1c80-d2e0-11e8-9c34-68708fc8c52c.png)

**Comment by gj262** [comment]
@DaleMcGrew, I can take a look unless someone has done it already?

**Comment by DaleMcGrew** [comment]
Yes, that would be great. Thank you!
