### ISSUE TITLE
Sign In Buttons: Upgrade styling to Bootstrap 4

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1758]
### Please describe the issue (What happens? What do you expect?)
On this page: http://localhost:3000/settings/account
![screen shot 2018-10-24 at 2 34 37 pm](https://user-images.githubusercontent.com/7756031/47463088-114d1580-d79a-11e8-9e79-1616ab3ccc6f.png)

On this page: http://localhost:3000/more/network
![screen shot 2018-10-24 at 2 59 45 pm](https://user-images.githubusercontent.com/7756031/47464236-78b89480-d79d-11e8-882a-eb800335744d.png)

Also, when you have signed in with Facebook, the orange "Signed in with Email" button doesn't show the envelope icon that it should under "Currently Signed In".
<img width="483" alt="screen shot 2018-12-26 at 10 27 42 am" src="https://user-images.githubusercontent.com/7756031/50453926-17c24f80-08f9-11e9-8251-ce482e82289e.png">

**Comment by paliopolis** [comment]
Sarvesh - Assigned to me :)

**Comment by sarveshbhardwaj** [comment]
sarvesh - assigned to Sarvesh.

**Comment by ltsinh** [comment]
> ### Please describe the issue (What happens? What do you expect?)
> On this page: http://localhost:3000/settings/account
> ![screen shot 2018-10-24 at 2 34 37 pm](https://user-images.githubusercontent.com/7756031/47463088-114d1580-d79a-11e8-9e79-1616ab3ccc6f.png)
> 
> On this page: http://localhost:3000/more/network
> ![screen shot 2018-10-24 at 2 59 45 pm](https://user-images.githubusercontent.com/7756031/47464236-78b89480-d79d-11e8-882a-eb800335744d.png)
> 
> Also, when you have signed in with Facebook, the orange "Signed in with Email" button doesn't show the envelope icon that it should under "Currently Signed In".
> <img alt="screen shot 2018-12-26 at 10 27 42 am" width="483" src="https://user-images.githubusercontent.com/7756031/50453926-17c24f80-08f9-11e9-8251-ce482e82289e.png">

**Comment by ltsinh** [comment]
On this page: http://localhost:3000/more/network

I never successful stay in the production site because the login links take me to the live website.

**Comment by ltsinh** [comment]
Also, when you have signed in with Facebook, the orange "Signed in with Email" button doesn't show the envelope icon that it should under "Currently Signed In".

<img width="1141" alt="screen shot 2019-01-03 at 9 13 48 pm" src="https://user-images.githubusercontent.com/31012764/50671300-07683f80-0f9f-11e9-8bcb-0537a5faa5c5.png">
This is working fine now, I simply replaced it with a font awesome envelope image. Please see attached images.
<img width="1141" alt="screen shot 2019-01-03 at 9 13 48 pm" src="https://user-images.githubusercontent.com/31012764/50671348-58783380-0f9f-11e9-8692-7043873e88d7.png">
<img width="615" alt="screen shot 2019-01-03 at 9 33 48 pm" src="https://user-images.githubusercontent.com/31012764/50671349-58783380-0f9f-11e9-83c6-167a823f2ed6.png">

**Comment by DaleMcGrew** [comment]
Thank you @ltsinh! Could you please make the envelope white (instead of black) and slightly larger? Also, the Facebook icon seems to be vertically too high (by a few pixels).

**Comment by ltsinh** [comment]
<img width="1141" alt="screen shot 2019-01-04 at 12 39 50 pm" src="https://user-images.githubusercontent.com/31012764/50702156-16da9d80-101e-11e9-83e4-9d37b4ff9a30.png">
Here is how the 3 icons look together. I think twitter looks busy now?

**Comment by ltsinh** [comment]
@DaleMcGrew 
<img width="935" alt="screen shot 2019-01-04 at 1 50 23 pm" src="https://user-images.githubusercontent.com/31012764/50705138-d849e080-1027-11e9-8f67-4ade4b67ab4f.png">
<img width="337" alt="screen shot 2019-01-04 at 1 50 16 pm" src="https://user-images.githubusercontent.com/31012764/50705139-d849e080-1027-11e9-9eb6-48137b2c71e4.png">

I think the icon images look better now. I have them fixed in the branches, but I will do research on best practices for future icon issue in terms of how to build out future use of icon sizing.

**Comment by lazorfuzz** [comment]
@ltsinh I think we just worked on the same thing 😅PR https://github.com/wevote/WebApp/pull/1849

**Comment by DaleMcGrew** [comment]
Fixed!
