### ISSUE TITLE
Welcome page style problems (broken during Bootstrap 4 upgrade)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1759]
### Please describe the issue (What happens? What do you expect?)
We just upgraded to React 16/Bootstrap 4. Somehow during the upgrade, images that were in two columns (in desktop mode) have been reduced to one column. I would recommend looking at the history of the WebApp/src/js/routes/Welcome.jsx file to see what changed. Please test thoroughly in mobile mode, tablet and desktop.

### Steps to reproduce the problem (1, 2, 3...), including links
http://localhost:3000/welcome

NEW (BROKEN)
![screen shot 2018-10-24 at 2 36 18 pm](https://user-images.githubusercontent.com/7756031/47463253-8b7d9a00-d79a-11e8-9aaa-2f5cb7a6a168.png)

![screen shot 2018-10-24 at 2 36 28 pm](https://user-images.githubusercontent.com/7756031/47463269-9afce300-d79a-11e8-95e5-7635fcc5a7a4.png)

OLD (CORRECT)
![fireshot capture 024 - welcome to we vote - https___wevote us_welcome](https://user-images.githubusercontent.com/7756031/47463307-b0720d00-d79a-11e8-9046-e943a93c0dea.png)

**Comment by fulin426** [comment]
Hello, 

Is this one still open? I'd like to give it a try

**Comment by DaleMcGrew** [comment]
Hello @fulin426 this is still being worked on by another engineer. Thank you for checking though!

**Comment by fulin426** [comment]
@DaleMcGrew Thanks for letting me know!
