### ISSUE TITLE
Samsung Galaxy (Android), Navigator slides up - turn off autofocus

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#176]
1. Using a Samsung Galaxy, running Android, go to "More Opinions" page.
2. Tap the entry box so you can enter an organization's name to search for.
3. The Navigator buttons (Ballot, Requests, Connect, Activity) slide up above the keyboard. This restricts the voter's ability to see very much of the rest of the screen.

Please prevent the Navigator from appearing when the keyboard is shown on the screen.

**Comment by pertrai1** [comment]
@DaleMcGrew That is something I will look into tomorrow but do know that this is a feature of bootstrap that I don't know can be eliminated. If it can be, I am sure there are examples of how it is done out there for reference.

**Comment by pertrai1** [comment]
@DaleMcGrew I am not sure we can say this is a bug just yet because I looked at this on my Samsung Note Edge and it worked just fine and was able to see the search box just fine. We might be best off having a self contained so to speak lab where the app is tested. I say this because when I worked on a Veteran Affair project, we had to test on over 65 different devices that they supported. 

More discussion needed.

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 yes testing across multiple devices will be no small undertaking. We can discuss next week. 

When I user-tested this on the Samsung Galaxy, you could see and type into the search box, but the Navigator buttons prevented you from seeing the search results. The keyboard had to be hidden before you could see the results.

**Comment by pertrai1** [comment]
Options
* When there is a tap on the input elements, we will find the footer
* We will find the class `fixed`
* Remove the class `fixed`
* On blur we will add `fixed` back into the footer class

**Comment by pertrai1** [comment]
Relates to #201

**Comment by DaleMcGrew** [comment]
We will need to find someone with a Samsung Galaxy to verify this.

**Comment by DaleMcGrew** [comment]
I saw this same problem in a demo this last week (Android phone -- sorry I didn't get the make/model), where the keyboard pushed the Ballot-Requests-Connect-Activity navigator above the keyboard. I think we should turn off the search box auto-focus when in mobile mode.
Having auto-focus in desktop mode is still good.

**Comment by pertrai1** [comment]
@DaleMcGrew yes we can handle turning off the `autofocus` and push an event to it when we want it to have one. I will look more into the docs of Bootstrap to find out if there are already resolved problems with a fixed footer being an issue on mobile devices.

**Comment by pertrai1** [comment]
Add meta tag to prevent zooming

**Comment by DaleMcGrew** [comment]
We are going to turn off auto-focus for now to solve this.

**Comment by lisamcho** [comment]
Close this out?
