### ISSUE TITLE
Header logo problem between 575px and 768px

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1764]
### Please describe the issue (What happens? What do you expect?)
The logo jumps to a strange (very small) size, and should remain the same as in the larger "Desktop" view.
![screen shot 2018-10-25 at 9 39 09 am](https://user-images.githubusercontent.com/7756031/47516243-dc909b00-d839-11e8-843c-20d6d6a91d75.png)

**Comment by gj262** [comment]
I will have this fixed as part of my work on #1625.

**Comment by DaleMcGrew** [comment]
Thank you @gj262!

**Comment by DaleMcGrew** [comment]
Resolved! Thank you @gj262.
