### ISSUE TITLE
TransitionGroup animations are not fully implemented

### ISSUE THREAD

**Issue by gj262** [wevote/WebApp#1767]
A number of list displays use TransitionGroup/CSSTransition in what looks to be an attempt to add some kind of fade animation to items as they are added to/removed from the list.

However the code is missing the appropriate CSS to make the animation happen (i.e. .fade-enter/exit*) and the keys on the CSSTransitions should use a unique id related to the item if one wants to animate on exit. 

I found this confusing so opening this issue in case anyone else runs into it. However as it stands the code will render these lists just fine (though there could be a performance hit as TransitionGroup & CSSTransition do their work).

**Comment by DaleMcGrew** [comment]
Resolved.
