### ISSUE TITLE
More Opinions, showing only opinions about candidate

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#177]
Hi @lisamcho, I wasn't able to reproduce this (originally entered as a comment in Issue #8). Did I get the sequence correct?
1. Go to the Candidate page for a candidate.
2. Click on "More Opinions" or "Find More Opinions"
3. Click on "Opinions I'm following" in left navigation (or mobile drop down), 
4. Click on "More Opinions"
It shows the opinions for the candidate still rather than all the opinions to follow.

**Comment by lisamcho** [comment]
Yes I am able to reproduce it.

**Comment by lisamcho** [comment]
Should be fixed with #190

**Comment by DaleMcGrew** [comment]
Verified.
