### ISSUE TITLE
Right Side Bar 'Summary of ballot' not updating when changed address to diff state

### ISSUE THREAD

**Issue by DemiRonin** [wevote/WebApp#1787]
### Please describe the issue (What happens? What do you expect?)

1. Was at the site, not signed in.  Normally I see a California ballot. 
2. Changed my address to Wisconsin.  No Street, entered.   
3. When it update the race.  The right side bar still showed California Ballot Items.  
4. When I hit refresh however, it did update the right bar/menu.  

![screencapture-wevote-us-ballot-2018-11-02-11_09_12](https://user-images.githubusercontent.com/36363414/47933205-22301200-de91-11e8-9bd8-e650431e549c.png)

Bug fix notes: 
I think this has to do with ShouldComponentUpdate not letting the Summary of Ballot Items re-render.

**Comment by fulin426** [comment]
Is anyone working on this one? I'd like to take a crack at it this weekend.

**Comment by DaleMcGrew** [comment]
Hello Fu Lin, you are welcome to take this issue. Thank you! Note: I think this has to do with ShouldComponentUpdate not letting the Summary of Ballot Items re-render.

**Comment by fulin426** [comment]
Thanks, I'll take a look into shouldComponentUpdate lifecycle method as a starting point

**Comment by DaleMcGrew** [comment]
Hello Fu Lin, yes you can change that over to use the ballot in the state variable. I think this will be fine from a resource perspective. Thank you!
