### ISSUE TITLE
More Opinions page links cover the following/unfollowing buttons

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#179]
@DaleMcGrew sorry your last pull request changes didn't look that complicated so I read the code and merged without running it. Now I see that when you click on the More Opinions page and click Follow or Ignore, you are taken to the organization page because the link is covering those buttons.

**Comment by DaleMcGrew** [comment]
No worries, I'll fix that in a new pull request. Good catch.

**Comment by lisamcho** [comment]
Verified!
