### ISSUE TITLE
Preload "More Opinions" & "Opinions I'm Following"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#18]
Currently when you go to the "More Opinions" or "Opinions I'm Following" pages, it takes 3-4 seconds to load the opinions. I would like to call VoterGuideStore.initialize and load this data from the API server right after the ballot is loaded, so the voter doesn't perceive a loading delay.

**Comment by pertrai1** [comment]
@lisamcho Can you take a look at this?

**Comment by lisamcho** [comment]
I think the main reason that this is slow is that there is a loop of callbacks which initiates a separate API call for each item in a list, and it waits for the last API call to finish before displaying data. My 2 cents -- Don't we also want to enable directly navigating to root/more_opinions? May be better idea to load the list, display whatever data is available immediately, then have the other API calls initiated and detected separately via actions.?

**Comment by pertrai1** [comment]
@DaleMcGrew I think that @lisamcho is right in that we can throttle the calls so the first can be returned immediately while the others will be requested responses based on actions if I am not mistaken?

**Comment by DaleMcGrew** [comment]
We can address this after hitting the Version 1 MVP.

**Comment by DaleMcGrew** [comment]
Verified!
