### ISSUE TITLE
Retrieve all positions counts at once for faster speed - positionsCountForAllBallotItemsDocs

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#183]
We have a new API endpoint that retrieves the number of friends & orgs you follow that support/oppose a ballot item: https://api.wevoteusa.org/apis/v1/docs/positionsCountForAllBallotItemsDocs/

Replace the initial retrieval of all support/oppose counts with this new routine that retrieves all values in one single query.

**Comment by lisamcho** [comment]
Should be resolved with #184

**Comment by DaleMcGrew** [comment]
Wow load times are so much faster! Verified.
