### ISSUE TITLE
Switch "Select Issues" modal to use the new icons (instead of the photos)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1855]
Instead of showing photos, we want to show the new SVG icons.
![screen shot 2019-01-12 at 9 26 39 am](https://user-images.githubusercontent.com/7756031/51076357-486ded00-164c-11e9-97ca-ca2ac4b23215.png)

You can display the Issue icons like this:
``` <ReactSVG src={cordovaDot(`/img/global/svg-icons/issues/${oneIssue.issue_icon_local_path}.svg`)} svgStyle={{ fill: "#4B4B4B", padding: "1px" }}   />```

**Comment by DaleMcGrew** [comment]
Thank you @lazorfuzz, using the icons is an improvement. Could you please make the following upgrade?
- [ ] For the issues selector, please make the gray backdrop behind the text fill the entire square.
- [ ] For the second slider page of this modal, please try making the gray backdrop behind the text fill the whole square too. I think that will look better.
- [ ] Please try center aligning the text to see if it looks better than left aligning
- [ ] I'm thinking the icons will look better if they are 1/2 the current size and positioned in the top 2/3rds of the Issue square, so that for most Issue squares the icon will ride above the text. You will need to play with this to see what looks best.
- [ ] Please test in both desktop and mobile

**Comment by lazorfuzz** [comment]
Will do!

**Comment by DaleMcGrew** [comment]
Excellent work @lazorfuzz!
