### ISSUE TITLE
Fix eslint warnings for js/routes/TwitterHandleLanding.jsx

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1863]
Camel case updates:
WebApp/src/js/routes/TwitterHandleLanding.jsx

Fix the warnings that you get when you run `npm test`.

/Users/dalemcgrew/PythonProjects/PersonalGitForks/WebApp/src/js/routes/TwitterHandleLanding.jsx
   56:3   warning  _onTwitterStoreChange should be placed after getIncomingActiveRoute         react/sort-comp
   58:11  warning  Identifier 'twitter_followers_count' is not in camel case                   camelcase
   60:7   warning  Identifier 'kind_of_owner' is not in camel case                             camelcase
   60:22  warning  Identifier 'owner_we_vote_id' is not in camel case                          camelcase
   60:40  warning  Identifier 'twitter_handle' is not in camel case                            camelcase
   60:56  warning  Identifier 'twitter_description' is not in camel case                       camelcase
   60:78  warning  Identifier 'twitter_name' is not in camel case                              camelcase
   61:7   warning  Identifier 'twitter_photo_url' is not in camel case                         camelcase
   61:26  warning  Identifier 'twitter_user_website' is not in camel case                      camelcase
   64:16  warning  Identifier 'twitter_followers_count' is not in camel case                   camelcase
   65:7   warning  Identifier 'twitter_followers_count' is not in camel case                   camelcase
   86:33  warning  Expected 'this' to be used by class method 'organizationCreateFromTwitter'  class-methods-use-this
   86:34  warning  Identifier 'new_twitter_handle' is not in camel case                        camelcase
   92:11  warning  Identifier 'incoming_active_route' is not in camel case                     camelcase
   94:12  warning  Identifier 'incoming_active_route' is not in camel case                     camelcase
  106:14  warning  Identifier 'kind_of_owner' is not in camel case                             camelcase
  106:29  warning  Identifier 'owner_we_vote_id' is not in camel case                          camelcase
  106:47  warning  Identifier 'twitter_handle' is not in camel case                            camelcase
  108:11  warning  Identifier 'signed_in_twitter' is not in camel case                         camelcase
  109:9   warning  Identifier 'signed_in_with_this_twitter_account' is not in camel case       camelcase
  110:9   warning  Identifier 'looking_at_positions_for_friends_only' is not in camel case     camelcase
  111:9   warning  Identifier 'signed_in_twitter' is not in camel case                         camelcase
  112:13  warning  Identifier 'twitter_handle_being_viewed' is not in camel case               camelcase
  112:43  warning  Identifier 'twitter_handle' is not in camel case                            camelcase
  114:7   warning  Identifier 'signed_in_with_this_twitter_account' is not in camel case       camelcase
  114:75  warning  Identifier 'twitter_handle_being_viewed' is not in camel case               camelcase
  117:7   warning  Identifier 'looking_at_positions_for_friends_only' is not in camel case     camelcase
  122:11  warning  Identifier 'is_neither_organization_nor_politician' is not in camel case    camelcase
  122:52  warning  Identifier 'kind_of_owner' is not in camel case                             camelcase
  122:88  warning  Identifier 'kind_of_owner' is not in camel case                             camelcase
  123:9   warning  Identifier 'signed_in_with_this_twitter_account' is not in camel case       camelcase
  123:48  warning  Identifier 'is_neither_organization_nor_politician' is not in camel case    camelcase
  138:48  warning  Identifier 'owner_we_vote_id' is not in camel case                          camelcase
  141:51  warning  Identifier 'owner_we_vote_id' is not in camel case                          camelcase
  142:11  warning  Identifier 'looking_at_positions_for_friends_only' is not in camel case     camelcase

**Comment by fulin426** [comment]
Dale,

Should I focus on the camel case updates only? Or should try to eliminate
some of these types of warnings as well?
56:3 warning _onTwitterStoreChange should be placed after
getIncomingActiveRoute react/sort-comp
86:33 warning Expected 'this' to be used by class method
'organizationCreateFromTwitter' class-methods-use-this

So far I've fixed all the camel case warnings

**Comment by DaleMcGrew** [comment]
Hello @fulin426, for now let's focus on the Camel case warnings. Make sure to run `npm test` to verify your changes before creating your pull request. Thank you!

**Comment by DaleMcGrew** [comment]
Thank you @fulin426!
