### ISSUE TITLE
Reduce downtime caused by /root/update_code

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#187]
When I run `/root/update_code` the site currently goes down for about 30-45 seconds. I'm wondering if we can reduce this down time. @nf071590 @pertrai1 @josephevans 

Would it be possible to run `npm install` while the wevote-www service is still running? Ideally we could leave the service running while the install is happening, and then run `service wevote-www stop` followed immediately by `service wevote-www start`.

Here is the whole script:
#!/bin/sh
service wevote-www stop
cd /home/wevote/WebApp
git stash
git pull origin develop
git stash pop
cd /home/NodeEnvironments/WebAppEnv/
. bin/activate
cd /home/wevote/WebApp
npm install
service wevote-www start

**Comment by pertrai1** [comment]
@DaleMcGrew @josephevans depending on the pipeline it would make more sense to have CI run the npm install and then take the workspace created and the `wevote-www-` service would not take long. It is the `npm install` that is taking this so long. If we need a more advanced CI we can move from Travis CI and have a Jenkins server?

**Comment by nf071590** [comment]
We can have a server process that runs and a build process that runs. The server process would never have to go down technically.

**Comment by josephevans** [comment]
I changed the update_code script so that we just restart the npm process after pulling new code and running "npm install" -- this reduced the downtime to only about 15 seconds (from 30-45.)
