### ISSUE TITLE
Add "at state" to left navigation item that you are on

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#188]
1. Go to Ballot in either desktop or mobile mode.
2. Choose an option like "What I Support"
3. The "What I Support" navigation item should have an "at state" showing that you are on that page

**Comment by DaleMcGrew** [comment]
Looks great in desktop mode. Same change needed in mobile drop-down menu.

**Comment by lisamcho** [comment]
Are you talking about the hamburger dropdown? It makes sense for the left-menu but I've never seen at states in any dropdown menu.

**Comment by pertrai1** [comment]
:+1: on this work done @lisamcho

**Comment by DaleMcGrew** [comment]
We can close this and take it up with design team.
