### ISSUE TITLE
Fix ESlint warnings in routes/OpinionsFollowed.jsx

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1896]
This issue is for Urosh.

Update the code to remove most warnings for this file (when you run `npm test`):
WebApp/src/js/routes/OpinionsFollowed.jsx

Do not worry about these:
Expected 'this' to be used by class method 'getCurrentRoute' 
Anchor used as a button

**Comment by uroshima** [comment]
Done!

**Comment by DaleMcGrew** [comment]
Thank you @uroshima!
