### ISSUE TITLE
Identify components that are not ultimately included in a route

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1897]
We keep stumbling upon files that aren't in use. Please go through all of the files in these folders:
WebApp/src/js/components/VoterGuide/
WebApp/src/js/components/Widgets/
...and list in the comments of this Issue any that are not ultimately called from a route. (There will be components that are used by other components that when you follow the includes back to the route, are used.)

**Comment by fulin426** [comment]
The following components are not called from a route or have been turned off. They are some corresponding comments in the files. 
WebApp/src/js/components/VoterGuide/
PledgeToVoteButton
PledgeToVoteStatusBar
VoterGuideItem

All the Widgets components are being called by at least one other component. 
http://webapp/src/js/components/Widgets/

**Comment by DaleMcGrew** [comment]
Thank you Fu-Lin, this is very helpful!
