### ISSUE TITLE
Add organization logo and follow/ignore changes to "Opinions I'm Following" in Mobile mode

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#193]
Replicate the work done on "More Opinions I can Follow" on the "Opinions I'm Following" page in mobile mode.
- [x] Include the organization's logo, but smaller
- [x] Stack the Follow and Ignore buttons

**Comment by pertrai1** [comment]
@DaleMcGrew Please verify fix

**Comment by DaleMcGrew** [comment]
Verified.
