### ISSUE TITLE
Change address or election: Needs gray background

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1932]
### Please describe the issue (What happens? What do you expect?)
When a voter clicks the "change address or election" link on the ballot page, a modal opens. The screen behind it should gray out (like it does with you click the "Issues" button on the ballot page, to open the Issue modal).

Also, when the modal opens, all of the Ballot page content center aligns, and it shouldn't.

**Comment by jarodpeachey** [comment]
Where does this code live?  I could try taking a look at it tomorrow.
