### ISSUE TITLE
On "Choice Remaining" view, do not remove the "office" being viewed until you return to page 

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#194]
- [x] On "Choice Remaining" view, do not remove the "office" being viewed until you navigate away and return to page. The experience of the item disappearing is jarring.
- [ ] We can leave the behavior as is on the "What I support" page, where the item disappears immediately

**Comment by lisamcho** [comment]
Sorry I didn't see the note above, so I submitted a pull request to change them both to not disappearing. Did you mean that we SHOULD leave the behavior as is on "What I support"? Or that we could do either? I'd be for making them consistent.

**Comment by DaleMcGrew** [comment]
Verified!
