### ISSUE TITLE
New Header Style Refinements

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1942]
### Please describe the issue (What happens? What do you expect?)
Hi Leon, the new header looks amazing! Great work. I have a some style tweaks:

- [x] Mobile: When on the ballot, the top most header bar should not have a shadow--instead the shadow should be under the Federal, State, etc. chips. (like it shows after the top bar slides out of view.)

Current:
![screen shot 2019-02-15 at 6 03 04 pm](https://user-images.githubusercontent.com/7756031/52892916-0c96dd80-314c-11e9-92f2-1f799e892b14.png)

Desired:
![screen shot 2019-02-15 at 6 05 02 pm](https://user-images.githubusercontent.com/7756031/52892940-4536b700-314c-11e9-8995-6eb0d5fea309.png)

- [x] Please try to tighten up the vertical space as much as possible (check out iPhone 5), including reducing the space between the words "All, Choices and Decided" and the "at state" indicator under the word. (Especially in desktop)
- [x] Reduce the horizontal space between the chips, and even some of the spacing within the chips if possible. We were really hoping to get the start of the "local" chip to show on the iPhone 5e prior to scrolling.

![screen shot 2019-02-15 at 6 14 14 pm](https://user-images.githubusercontent.com/7756031/52893082-909d9500-314d-11e9-8848-dbb6a00cb7d4.png)

- [x] Please make the number bubbles to the right of Federal, State, Measure, etc. gray (as well as the radio button circle if possible) when the chip is not selected.
- [x] Update the Sign in button in the header to be a button with a border
- [x] Please make the "pin" button next to "Sign In" open up the "change your address or election" modal
- [x] Desktop: There is extra space above and below the chips when viewed in Desktop
![screen shot 2019-02-18 at 1 28 45 pm](https://user-images.githubusercontent.com/7756031/52977288-954a8f00-3381-11e9-99aa-34acf75ae034.png)
- [x] Desktop: Please remove the shadow on the ballot page under the top-most navigation bar that contains the We Vote logo (when on the Ballot page) -- just like you did in mobile
- [x] Desktop: Please add the words "Address & Elections" to the top navigation when in Desktop
![screen shot 2019-02-18 at 1 33 11 pm](https://user-images.githubusercontent.com/7756031/52977364-d3e04980-3381-11e9-9e2f-935f6f6eade4.png)
- [x] For the "Address & Elections" button to the left of the Sign in button, Ahmed would also like to use a standard pin drop icon instead of the one you have that includes a pencil icon

**Comment by DaleMcGrew** [comment]
The mobile changes you made look excellent @lazorfuzz, thank you! There is still some spacing refinement to do in desktop. Also I added two more tweaks to the description of this issue (relating to the sign in button and the location pin) since they are related.

**Comment by DaleMcGrew** [comment]
Hi @lazorfuzz I reviewed the latest header with Ahmed and we added some updated comments to this issue relating to desktop. Thank you!

**Comment by lazorfuzz** [comment]
@DaleMcGrew I'm not seeing the extra space above and below the chips in desktop:

![image](https://user-images.githubusercontent.com/13378467/52979676-9aacd700-338b-11e9-8f5e-1aa3c131c90b.png)

Any ideas on how to reproduce it?

**Comment by lazorfuzz** [comment]
Just added the other changes

![image](https://user-images.githubusercontent.com/13378467/52980673-1ad53b80-3390-11e9-9611-d4531fa6c014.png)

**Comment by lazorfuzz** [comment]
I personally really like the way YouTube does it, (flat sign in button and icon buttons):

![image](https://user-images.githubusercontent.com/13378467/52980772-a8b12680-3390-11e9-948b-0d4c94817134.png)

**Comment by DaleMcGrew** [comment]
Thank you Leon for the changes. I will talk with @AhmedElgamal01 about the style of the Address & Elections and Sign in Buttons.

I've been trying to see if I can get the spaces above and below the chips to go away (so I can see what you are seeing). I still see these spaces above Federal, State, Measure on Chrome and Safari in Desktop mode, but only when I do *not* use the device emulator (the problem goes away with I view it in Chrome as iPhone, iPad or Responsive mode). I wonder if there is a package that you have installed on your machine that needs to be included in package.json? (I have run `npm install` with the latest package.json.)

Problem exists:
<img width="987" alt="screen shot 2019-02-18 at 4 26 43 pm" src="https://user-images.githubusercontent.com/7756031/52982379-a0f67f80-339a-11e9-881f-1a88e06e7bdf.png">

Problem does not exist:
<img width="1183" alt="screen shot 2019-02-18 at 4 32 07 pm" src="https://user-images.githubusercontent.com/7756031/52982405-c1263e80-339a-11e9-96b9-377769315b45.png">

**Comment by lazorfuzz** [comment]
@DaleMcGrew that's so weird. I use Yarn so anything I `yarn add` should be automatically added to package.json without a `--save`.

**Comment by DaleMcGrew** [comment]
Spacing issues solved!
