### ISSUE TITLE
When signed in, Settings and Address icon disappear from header

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1995]
In the header, when you sign in, the Settings and Address icons disappear, and they should remain.

Not signed in on ballot page:
<img width="233" alt="Screen Shot 2019-03-09 at 10 53 14 AM" src="https://user-images.githubusercontent.com/7756031/54075913-958bcb00-4259-11e9-8bdd-189401c28fdf.png">

Signed in on ballot page:
<img width="129" alt="Screen Shot 2019-03-09 at 10 55 46 AM" src="https://user-images.githubusercontent.com/7756031/54075943-edc2cd00-4259-11e9-9861-0a0b2ccb6412.png">

**Comment by flurmbo** [comment]
@DaleMcGrew I've got something that works on the ballot page, should I try factoring it out into a separate component and add it to the "Back to X" components?

**Comment by DaleMcGrew** [comment]
Hi @flurmbo, I don't think we need the Settings and Address icons on the "Back to" pages.

**Comment by flurmbo** [comment]
@DaleMcGrew I PRed my changes, let me know what you think

**Comment by DaleMcGrew** [comment]
Thank you @flurmbo!
