### ISSUE TITLE
Ability for voter to save address

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2]
When you come to We Vote, check to see if there is an address saved from voterAddressRetrieve API:
https://api.wevoteusa.org/apis/v1/docs/voterAddressRetrieve/

If there isn't an address already saved, retrieve the "best guess" address from: https://api.wevoteusa.org/apis/v1/docs/voterLocationRetrieveFromIP/
...and then save the address found "voterLocationRetrieveFromIP" with:
https://api.wevoteusa.org/apis/v1/docs/voterAddressSave/

At any time, allow voter to type in a new address and save here:
https://api.wevoteusa.org/apis/v1/docs/voterAddressSave/

Note that whenever we call "voterAddressSave" we automatically (on the API server, behind the scenes) retrieve a ballot from the Google Civic API, so the WebApp needs to refresh the ballot data with:
https://api.wevoteusa.org/apis/v1/docs/voterBallotItemsRetrieve/

**Comment by nf071590** [comment]
I reassigned this to me... I will begin work today...

**Comment by DaleMcGrew** [comment]
Hi Nick, I don't think its a good idea to store the voter's address (or the voter_id) in a cookie, but should instead use the VoterStore (in memory) as the single source for the location to display. I have seen scenarios over the years where data stored "temporarily" in cookies can quickly get out of sync with the live data, and this creates debugging nightmares.

**Comment by DaleMcGrew** [comment]
I do believe we have a working first version of voter address save. As we need changes to address saving, we can enter new issues.
