### ISSUE TITLE
Incapsulate styles within JSX

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#200]

**Comment by ixley** [comment]
@pertrai1 This caught my attention and I was curious to get a better sense of what it implies. 

Can you point me to any (straightforward) articles that outline strong cases for style encapsulation? As someone who is familiar with the downsides of CSS's default global scope, but still just wrapping my head around the principles and conventions of React, the idea of widespread (as opposed to selective) inlining of styles in JSX still makes me squirm a little. I'm interested in better understanding what this issue actually refers to (the actual scope and intention of encapsulation), though, along with your thinking.

**Comment by pertrai1** [comment]
@ixley Take a look at this to get both sides of the coin and some references to more material:

https://css-tricks.com/the-debate-around-do-we-even-need-css-anymore/

**Comment by nf071590** [comment]
@pertrai1 this is a really interesting read, and then to read the comments...

I like the idea of creating dynamic style modules but what about media queries?

**Comment by pertrai1** [comment]
@nf071590 Right now this is the best option out there: http://stack.formidable.com/radium/

CC: @ixley

**Comment by ixley** [comment]
@pertrai1 Hah - I actually did read the CSS Tricks post but found myself more familiar with, and aligned with the arguments against. I'll take a look at Radium. I *do* see the appeal of some sort of hybridized approach, especially to take advantage of stateful modules, but am wary of js polyfills for browser supported functions like browser state styles and media queries, or calls to *completely* inline all styles.

**Comment by pertrai1** [comment]
@ixley I don't know if we need to focus on it much as we will soon be making use of the abilities that CSS will offer for encapsulation now that everyone is slowly getting familiar with the shadow DOM and how to get past the first layer of the DOM that allows for a certain fragment to have its own `:root`

**Comment by ixley** [comment]
@pertrai1 thanks. And just to reiterate, this is something I am still working to better understand, so my stance still reflects a limited familiarity.

**Comment by pertrai1** [comment]
@ixley you are welcome. Anything you need to get familiar with, let me know, and I might be able to help out.

**Comment by ixley** [comment]
@pertrai1 @nf071590 What are your thoughts on Radium vs (React) CSS Modules? I don’t have anyway great sense of what key differences these approaches have, but the thinking and reasoning behind the CSS Modules project particularly appeals to me.

http://glenmaddern.com/articles/css-modules

**Comment by pertrai1** [comment]
Closing as this is off topic and can be opened as new issue in the future if it comes to light.
