### ISSUE TITLE
Change Style of "Back to" buttons

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2005]
### Please describe the issue (What happens? What do you expect?)
This is the current style of the "Back to" button:
<img width="224" alt="Screen Shot 2019-03-14 at 3 27 44 PM" src="https://user-images.githubusercontent.com/7756031/54395844-328da000-466e-11e9-8e72-9e9f1cd2adda.png">

We want to upgrade the style to look like this:
<img width="200" alt="Screen Shot 2019-03-14 at 3 32 33 PM" src="https://user-images.githubusercontent.com/7756031/54395927-784a6880-466e-11e9-89b3-3325128338a2.png">

These buttons live in the "HeaderBackTo..." files like this one:
WebApp/src/js/components/Navigation/HeaderBackToBallot.jsx

**Comment by flurmbo** [comment]
Quick question about this @DaleMcGrew, do you think I should use the [arrow_back_ios](https://material.io/tools/icons/?search=arrow_back_ios&icon=arrow_back_ios&style=baseline) material icon for this? According to the [material design website](https://material.io/design/navigation/understanding-navigation.html) it seems like for android apps and web apps [this style of arrow](https://material.io/tools/icons/?search=arrow_back&icon=arrow_back&style=baseline) is preferred. Not sure how important this is but I figured it's worth mentioning

**Comment by DaleMcGrew** [comment]
Thank you for digging into this @flurmbo. Why don't we use the suggested "arrow_back" icon version as the default, but could you include the "arrow_back_ios" icon in that component with an if-statement for "if iOS", so we can easily use the iOS arrow on the Mac and iOS? (We can figure out how to detect that the voter is on Mac or iOS in the near future.)

**Comment by flurmbo** [comment]
Hey @DaleMcGrew, it looks like I'm going to need to override some Material UI styles. Do you know what is our preferred method to do that? I have been able to do it with the class property as described [here](https://material-ui.com/customization/overrides/#overriding-with-classes), but I've notcied that sometimes overrides are done in WebApp with "!important."

**Comment by DaleMcGrew** [comment]
Hi @flurmbo this new "back to" look is awesome! Thank you for implementing. Great work. Verified.
