### ISSUE TITLE
When on Voter Guide, "Ballot" at-state should not be selected on Desktop version

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2015]
The tab to display is in WebApp/src/js/components/Navigation/HeaderBar.jsx, and I believe is set on line ~217 with: value={this.getSelectedTab()}

This might be related to shouldComponentUpdate not firing when it needs to, so I would recommend doing initial testing with shouldComponentUpdate always returning True.

![Screen Shot 2019-03-19 at 4 09 18 PM](https://user-images.githubusercontent.com/7756031/54647895-824edb80-4a61-11e9-8a4b-e4ea489220db.png)

**Comment by jarodpeachey** [comment]
What jsx file would this be in?

**Comment by DaleMcGrew** [comment]
Hello @jarodpeachey, I have updated the description of this issue with some more notes.

**Comment by DaleMcGrew** [comment]
Great work @jarodpeachey. This is now verified.
