### ISSUE TITLE
Homepage button has default styling

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2029]
### Homepage Button has Default Styling
The get started button on the homepage still has default styling.  Didn't know if it's supposed to or not.  I've attached a screenshot below.

![ButtonCapture](https://user-images.githubusercontent.com/46693952/55173508-37645080-5152-11e9-8940-a350f835c3c0.PNG)

**Comment by DaleMcGrew** [comment]
Thank you Jarod for catching this. We are completely replacing this welcome page, so we don't need to make any updates to the current version.
