### ISSUE TITLE
Measure Detail Page - BallotItemSupportOpposeComment component doesn't show up on scroll up

### ISSUE THREAD

**Issue by lazorfuzz** [wevote/WebApp#2034]
### Please describe the issue (What happens? What do you expect?)

The support/oppose/comment component should reappear on the Measure page when the measure sticky header disappears.  In React dev tools, the component appears to be rendered, but the component doesn't show up in the DOM. The logic to appear/disappear the component is in MeasureItem.jsx.

### Steps to reproduce the problem (1, 2, 3...), including links
Test link:
https://localhost:3000/measure/wv02meas604/b/btdb/

1. Scroll down, until measure sticky header appears.
2. Scroll back up until the sticky header disappears.

**Comment by DaleMcGrew** [comment]
Verified.
