### ISSUE TITLE
Organization Links on "Opinions I'm Following" Incorrect

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#205]
1. Go to https://wevote.me and Follow one or more organizations
2. Go to "Opinions I'm Following" (https://wevote.me/more/opinions/followed) and click on the Organization name or image.
Bug: You should be taken to an organization landing page, and instead you are taken back to the ballot

**Comment by lisamcho** [comment]
Should be fixed with #209

**Comment by DaleMcGrew** [comment]
Verified.
