### ISSUE TITLE
How it Works (For Voters)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2053]
### Please describe the issue (What happens? What do you expect?)
We have new designs for a "How It Works" page. There will be a total of three of these pages, so this first one is "For Voters".

Text for the numbered items across the top (#4 is different than the image below):
1: Choose
2: Follow
3: Review
4: Decide
5: Friends

Desktop, step 1:
<img width="956" alt="Screen Shot 2019-04-11 at 1 56 55 PM" src="https://user-images.githubusercontent.com/7756031/55992736-175c8300-5c62-11e9-87d2-d560002f8d87.png">

Mobile, step 1:
<img width="303" alt="Screen Shot 2019-04-11 at 2 14 45 PM" src="https://user-images.githubusercontent.com/7756031/55993540-3825d800-5c64-11e9-91e1-c415645f9381.png">

All of the animated gifs have been checked into WebApp, and links to them are below.

And this is the text description to use:
1) Choose your interests
Follow topics that interest you. We will suggest endorsements based on your interests.
(animated gif of choosing two out of three value (choose “follow”))
WebApp/src/img/global/intro-story/FollowValues-20190401.gif

2) Follow organizations and people you trust
As you follow trusted organizations and people you know, their recommendations are added to your ballot.
(animated gif of following organization)
WebApp/src/img/global/intro-story/FollowOrganizations-20190401.gif

3) See who endorsed each choice on your ballot
Learn from the people you trust.
(animated gif showing a click on a score, and the popover showing the list of endorsing organizations and your friends. Then click on “show more” and have it show written endorsements.)
WebApp/src/img/global/intro-story/CandidateScore-20190401.gif

4) Fill the whole thing out in under six minutes
We Vote is fast, mobile, and helps you decide on the go.
(animated gif showing choosing candidates)
WebApp/src/img/global/intro-story/Decide-20190401.gif

5) Share with friends who could use a guide
Are your family and friends feeling lost when it’s time to vote? Be their hero.
(animated gif showing the ballot with their opinions, then the share my opinions)
WebApp/src/img/global/intro-story/ShareWithFriends-20190401.gif

**Comment by DaleMcGrew** [comment]
Amazing work @lazorfuzz! Would you be able to make the numbered "step" chips jump to the related step when clicked on, in both mobile and desktop?
![Screen Shot 2019-04-19 at 12 18 07 PM](https://user-images.githubusercontent.com/7756031/56440099-421b8c80-629d-11e9-839f-0133f61e5a92.png)

![Screen Shot 2019-04-19 at 12 18 19 PM](https://user-images.githubusercontent.com/7756031/56440105-46e04080-629d-11e9-972e-86405831d811.png)

**Comment by lazorfuzz** [comment]
@DaleMcGrew Sure, I can make them clickable. The step chips are responsive though, and are returned twice in the HowItWorks component. Should I label them with some other attribute?

**Comment by DaleMcGrew** [comment]
Thank you @lazorfuzz you can give the mobile chips one id name and the desktop chips another (but similar) id name.

**Comment by DaleMcGrew** [comment]
Verified!
