### ISSUE TITLE
Ballot Search Box: When it's the only icon, default to opening the text box

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2058]
Currently for elections that only have one category of "Federal", "State", "Measure" or "Local", we *only* display the search box like this:
<img width="196" alt="Screen Shot 2019-04-14 at 10 28 24 AM" src="https://user-images.githubusercontent.com/7756031/56096937-16fefa80-5ea3-11e9-82a9-b0e96e582531.png">

For elections like this, please adjust the vertical spacing so it looks like it does when there are "Federal", "State", etc. categories, and cause the text box to stay open, like this:
<img width="214" alt="Screen Shot 2019-04-14 at 10 51 53 AM" src="https://user-images.githubusercontent.com/7756031/56096969-5b8a9600-5ea3-11e9-91b5-b1e5d7f24651.png">

Please make sure to test thoroughly.

**Comment by DaleMcGrew** [comment]
Hi @flurmbo while you are working on this, could you also please remove this line between the election name and the search chip when the "All Items" tabs are turned off?
![Screen Shot 2019-04-25 at 9 06 49 AM](https://user-images.githubusercontent.com/7756031/56750946-b345be80-6739-11e9-98fb-78e824c09c19.png)

**Comment by flurmbo** [comment]
It looks like that line is shown on a separate line on smaller screens. On my desktop browser, it is shown on the same line as "US 2020 Presidential Primary Election" with a dash between them. When all items is turned off, do you want the date removed only for mobile/smaller screens or altogether?

**Comment by DaleMcGrew** [comment]
Hi @flurmbo I should have said "the thin horizontal line between the election name + date, and the search box". There isn't a need to adjust the date -- I am only talking about the thin horizontal line.

**Comment by flurmbo** [comment]
Got it!

**Comment by flurmbo** [comment]
@DaleMcGrew, quick question about this issue. In this situation, do you think anything should be done with the "X" symbol on the right of the search bar?

**Comment by DaleMcGrew** [comment]
Hi @flurmbo the "X" should remain and clear the contents of the search box, but would not shrink the search box.

**Comment by DaleMcGrew** [comment]
Thank you @flurmbo. The functionality of this new feature is great. There is a visual display glitch (an extra horizontal line) in mobile and tablet mode underneath the search box, when open or closed:
![Screen Shot 2019-05-07 at 9 08 31 AM](https://user-images.githubusercontent.com/7756031/57315190-f3952d00-70a7-11e9-973f-0c7ee2b8b550.png)

**Comment by flurmbo** [comment]
@DaleMcGrew, are you talking about the grey line that appears and fades away after toggling the search box in mobile, like in the attached gif? It looks a little different than what I see in your image, which I cannot reproduce

![Peek 2019-05-14 17-54](https://user-images.githubusercontent.com/35127144/57737460-68043900-7671-11e9-9b86-601251cd197b.gif)

**Comment by jarodpeachey** [comment]
On my side of things, when we hit the mobile mode (when the header nav goes away and the footer nav appears) this gray disabled scrollbar appears.  Might be something with the scrollX being set to scroll or auto on mobile mode.

![WeVoteIssueScrollbar](https://user-images.githubusercontent.com/46693952/57737821-0648cc80-767b-11e9-9852-4d99fa8ae3f9.gif)

**Comment by flurmbo** [comment]
@jarodpeachey thanks I'm able to see those scroll bars pop in now

**Comment by DaleMcGrew** [comment]
Thank you for tackling this Issue @flurmbo! I moved the remaining Mac bug into a new issue.
