### ISSUE TITLE
Create new "Follow/Ignore" button interface

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2062]
We offer the ability to follow voter guides (organizations or public figures), or ignore them.

Currently in WebApp/src/js/components/VoterGuide/GuideList.jsx (around line 199) we combine the component WebApp/src/js/components/Widgets/FollowToggle.jsx with a ```<button``` for "Ignore". Please update the FollowToggle component to include Ignore, and upgrade to a Material component.

These are the new designs. Initial state when you can Follow Organization:
<img width="486" alt="ToFollow" src="https://user-images.githubusercontent.com/7756031/56149688-f649aa00-5f61-11e9-8118-a83d485c8127.png">

What the "Follow" dropdown looks like:
<img width="452" alt="ToFollow-WithDropdown" src="https://user-images.githubusercontent.com/7756031/56149697-fa75c780-5f61-11e9-8444-0cc60e85bb84.png">

Once you are following an organization:
<img width="448" alt="Following" src="https://user-images.githubusercontent.com/7756031/56149709-fea1e500-5f61-11e9-9be8-bfd4b7698435.png">

When you are following an organization and the dropdown is open:
<img width="480" alt="Following-WithDropdown" src="https://user-images.githubusercontent.com/7756031/56149718-02ce0280-5f62-11e9-99bf-f75935de946c.png">

**Comment by DaleMcGrew** [comment]
Hi @lazorfuzz we wanted to get your advice (myself and @jarodpeachey ). Would it make sense to start with this component and try to customize? https://material-ui.com/demos/menus/

**Comment by lazorfuzz** [comment]
Yes, that would make the most sense. Just use style overrides!

**Comment by DaleMcGrew** [comment]
Awesome work @jarodpeachey!
