### ISSUE TITLE
Update Value Cards on Values Listing Page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2071]
### Please describe the issue (What happens? What do you expect?)
Please update the cards on https://quality.wevote.us/values/list to use Value/Issue cards in two columns:
![Screen Shot 2019-04-17 at 3 29 07 PM](https://user-images.githubusercontent.com/7756031/56325081-c0552300-6125-11e9-9852-b38384bc2452.png)

To finish this issue, you do not need to add the line that shows who else is following the Value/Issue, or update the Follow/Following button.

**Comment by jarodpeachey** [comment]
Does this issue take priority over issue #2037 as far as the design and layout goes?  Should the other issue be ignored, or would that be an entire separate component that we'll get to later, like `IssueCardCondensed.jsx`?

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey both issues *could* be solved with the same IssueCard component, but it might be easier to implement two components -- `IssueCard` for this page, and `IssueCardCompressed` for issue #2037. Feel free to tackle issue #2037 and issue #2071 in any order you would like -- both need to be implemented.

**Comment by jarodpeachey** [comment]
Ok.  And does the values list use the compressed, and the values page the standard from above, or the other way around?  I'm thinking you want /values/list page to look like this 
![image](https://user-images.githubusercontent.com/46693952/56780857-e6766500-67ae-11e9-87f7-4b73119b66c9.png)
and the /values page to look like this (with the new toggle button)
![image](https://user-images.githubusercontent.com/46693952/56780881-f9893500-67ae-11e9-8227-d2b321d8aa20.png)

**Comment by jarodpeachey** [comment]
Also, for this issue, is the green button going to be changed to look as on the designs above with the dropdown when you're following it?

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, correct, the green Follow button powered by IssueFollowToggleButton will need to be upgraded to this new design.

I was thinking that IssueCardCompressed could be created for the ValuesToFollowPreview component which is shown on https://quality.wevote.us/values and called by WebApp/src/js/routes/Values.jsx
![image](https://user-images.githubusercontent.com/46693952/56780881-f9893500-67ae-11e9-8227-d2b321d8aa20.png)

Please pay attention to the mobile version of /values:
![Screen Shot 2019-03-29 at 11 51 45 AM](https://user-images.githubusercontent.com/7756031/55255991-38ac8080-5219-11e9-9cee-d4752c2d8519.png)

IssueCard could be altered to be used for the full listing page https://quality.wevote.us/values/list powered by WebApp/src/js/routes/Values/ValuesList.jsx
![image](https://user-images.githubusercontent.com/46693952/56780857-e6766500-67ae-11e9-87f7-4b73119b66c9.png)

**Comment by DaleMcGrew** [comment]
Verified.
