### ISSUE TITLE
Reconsider at state

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#208]
Now that we have an "at state" on the submenu in Desktop mode, it creates a bad UX when coupled with the redirects. I.e. When you click on the "Opinions I"m following" and you aren't following any, then you're redirected automatically to All Opinions page (which isn't a submenu item). Hence you expect the submenu item to turn blue but it doesn't. It's kinda jarring.

We need to reconsider how to do this. UX issue.

**Comment by DaleMcGrew** [comment]
We have changed the interface to solve this issue.
