### ISSUE TITLE
Convert "More" page to slide-out menu

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#21]
When the hamburger icon is clicked in mobile mode, please display a slide out more menu (populated from the "src/js/components/MoreMenu" component) that only fills ~250px of the left side of the screen. When you click anywhere to the right of the slide-out (or if you click the hamburger icon again), the more menu should slide off the screen.

**Comment by pertrai1** [comment]
@DaleMcGrew Can this be closed?

**Comment by DaleMcGrew** [comment]
Yes!
