### ISSUE TITLE
Make Follow / Following button on Organization Voter Guide page work

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#210]
1. Go to https://wevote.me/voterguide/wv02org1310
2. Button to the right of organization name is permanently on "Following"
Button state should be based on the person viewing. Should also be a functioning button that can be toggled.
NOTE: We do not want to include an "Ignore" button on this page.

**Comment by lisamcho** [comment]
Please verify. Resolved with #218

**Comment by DaleMcGrew** [comment]
Hi Lisa, I am testing it and will be able to verify later tonight. I also did some work today I'm looking forward to checking in.

**Comment by DaleMcGrew** [comment]
Hi Lisa, I am hoping you can get the "Following" button to show as red and show the word "Unfollow" when you roll over it and the button is in the "Following" state. Rob got this working in /src/js/components/FollowOrIgnore.jsx (although I took that component out of /src/js/components/VoterGuide/VoterGuideItem.jsx -- you can add it back in there to see it in action.)

**Comment by lisamcho** [comment]
Done with #221

**Comment by DaleMcGrew** [comment]
Verified. Thank you!
