### ISSUE TITLE
Twitter Button Padding Error

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2114]
### Please describe the issue (What happens? What do you expect?)
The padding for the Twitter icon on the values page twitter button is off by a few pixels.

![TwitterBTNIssue](https://user-images.githubusercontent.com/46693952/57005946-481d4180-6baa-11e9-96e0-5742c2ea1403.PNG)

**Comment by DaleMcGrew** [comment]
Verified.
