### ISSUE TITLE
Footer: "Contact Sales" button has outline cover button text

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2148]
When you resize the browser width when looking at a Welcome page, there are some widths when the "Get Started" and "Contact Sales" buttons in the footer have the outer border overlapping the button text:
<img width="129" alt="Screen Shot 2019-05-11 at 6 04 45 PM" src="https://user-images.githubusercontent.com/7756031/57576576-866ef800-7417-11e9-9125-af1939bc9835.png">

**Comment by jarodpeachey** [comment]
I'll tackle this.  There's also an issue that the contact sales button does not go to the page unless you click the text.  Something with the "Get Started" button being a link, but the "Contact Sales" button only containing a link.  I'll take a look at this tomorrow.

**Comment by DaleMcGrew** [comment]
Verified!
