### ISSUE TITLE
More Opinions and More Opinions About Candidate Inconsistent

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#216]
When you click "Follow/Unfollow" from Opinions page, the items disappear off the page immediately with a CSS transition. When you are on the candidate-specific Opinions page, the items stay on the page (and the buttons stay the same) even though the Follow/Ignore is actually saved to the backend. These should be consistent. We've discussed both ways of doing this, but it should really be consistent whatever we choose.

**Comment by DaleMcGrew** [comment]
Thank you for pointing out this inconsistency @lisamcho. The items should disappear off the page immediately. So the "More Opinions" page is correct, and the "More Opinions About Candidate" needs to be updated.

**Comment by lisamcho** [comment]
See #221

**Comment by DaleMcGrew** [comment]
Verified. Great work.
