### ISSUE TITLE
Our Network Logos too tall in mobile

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2161]
https://quality.wevote.us/welcome
WebApp/src/js/routes/WelcomeForVoters.jsx
In the "Our Network" section of all three Welcome pages, some of the logos are too tall when viewed in mobile:
![Screen Shot 2019-05-15 at 1 29 34 PM](https://user-images.githubusercontent.com/7756031/57807303-c125a880-7715-11e9-85d7-4ab0e9c3cf51.png)

Ideally we would show two logos side-by-side in mobile, and have them be the correct height.

**Comment by flurmbo** [comment]
A possibly related issue is the way the network logos render in Firefox (tiny and smushed):

![Screenshot from 2019-05-18 01-27-07](https://user-images.githubusercontent.com/35127144/57965611-28a54900-790c-11e9-8a17-8dd1b8d8d197.png)

**Comment by DaleMcGrew** [comment]
Thank you for fixing this @flurmbo! Verified.
