### ISSUE TITLE
Update margins on Our Team Cards

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2165]
### Please describe the issue (What happens? What do you expect?)
On hover for the desktop and mobile modes, the name of the team member is too close to the image, and too far from the subtitle.

The fix should be somewhere around line 174 in the TeamMemberDisplayForList.jsx file.

![AboutCardMobile](https://user-images.githubusercontent.com/46693952/57862315-2a64f480-77c6-11e9-83fd-4d7610f45085.PNG)
![AboutCardDesktop](https://user-images.githubusercontent.com/46693952/57862316-2a64f480-77c6-11e9-9e38-f044f8bfb7af.PNG)

**Comment by DaleMcGrew** [comment]
Thank you @jarodpeachey -- I made some updates yesterday that should fix this problem. Could you please verify?

**Comment by jarodpeachey** [comment]
@DaleMcGrew Looks good! 👍
