### ISSUE TITLE
Keep OrganizationPopoverCard open

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2191]
In WebApp/src/js/components/Ballot/PositionItem.jsx we have an OverlayTrigger that opens a Popover that shows OrganizationPopoverCard. Right now when you move your mouse down into the OrganizationPopoverCard, you are moving your cursor away from the OverlayTrigger, so the Popover closes. We want to keep the popover open as long as the mouse is over either the OverlayTrigger or the OrganizationPopoverCard.

**Comment by flurmbo** [comment]
Hi @DaleMcGrew, it looks like the functionality we want here is not supported out of the box in React Bootstrap. However it looks like someone more clever than me has worked out a custom solution in [this public gist](https://gist.github.com/lou/571b7c0e7797860d6c555a9fdc0496f9). Are you okay with me using their code and adapting it for our purposes here?

**Comment by DaleMcGrew** [comment]
Hi @flurmbo that should be fine!

**Comment by DaleMcGrew** [comment]
Great work @flurmbo -- this is now verified.
