### ISSUE TITLE
Remove scrollbar underneath CandidateItem on mobile

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2199]
### Please describe the issue (What happens? What do you expect?)
There is an unwanted (I assume) scrollbar under the candidate item on the candidate page on mobile.

![WeVote CandidateItem Scrollbar](https://user-images.githubusercontent.com/46693952/58193598-5fbf8580-7c91-11e9-83f9-0184a75e67b8.PNG)

**Comment by DaleMcGrew** [comment]
Verified.
