### ISSUE TITLE
Header navigation transitions at different width than More Menu (hamburger and major icons)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#22]
The responsive switching between mobile and desktop, turns on the More menu (on the left) at a different page-width than when the header/footer navigation changes.

**Comment by pertrai1** [comment]
@DaleMcGrew Please take a screenshot so I can see this. I am not able to reproduce without the steps.

**Comment by DaleMcGrew** [comment]
1. View the ballot in desktop mode.
2. Slowly narrow the width of the browser.
3. At right around 680px wide, the left navigation "More" menu goes away, but the header navigation doesn't switch down to the footer navigation until you narrow the browser about 5-10 more pixels.
![screen shot 2016-02-13 at 5 56 29 am](https://cloud.githubusercontent.com/assets/7756031/13028000/ac23bf5a-d216-11e5-8150-8adde4765f41.png)

**Comment by pertrai1** [comment]
@DaleMcGrew I do see this very small difference. With all else that needs to go into Version 1, can this be pushed to after since it will be rare that someone will encounter this.

**Comment by DaleMcGrew** [comment]
Yes, that's fine! I created a new milestone for issues we want to push off.

**Comment by pertrai1** [comment]
@DaleMcGrew perfect. Working on the bigger UI issues will be the main focus for these next few weeks.

**Comment by DaleMcGrew** [comment]
You nailed it Rob. Thank you.
