### ISSUE TITLE
Donation buttons not working on refresh. 

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2217]
The donation buttons work fine once navigated to the actual page but once you get there and refresh the page the buttons don't work anymore.

http://localhost:3000/more/donate

<img width="906" alt="Screenshot 2019-05-24 at 12 37 23" src="https://user-images.githubusercontent.com/36188818/58352556-c1622a00-7e20-11e9-85d3-6187ba1f5bef.png">

**Comment by SailingSteve** [comment]
There are lots of other issues that have been introduced into this page.  I'm working on them.

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, I am testing this latest version. If I load We Vote (on the welcome page for instance) and then navigate to the page using the footer link, I can open this popover by clicking on a button:
![Screen Shot 2019-06-13 at 10 29 39 AM](https://user-images.githubusercontent.com/7756031/59454092-31335700-8dc6-11e9-8503-2105fe918fca.png)

If I start directly on the https://localhost:3000/more/donate page (or refresh on this page) the popover doesn't open, and I see errors like this in the console log:
StripeCheckout is NOT defined: undefined
DonationForm cannot open

**Comment by SailingSteve** [comment]
Donations are massively messed up.  
The problem this issue mentions is a minor timing problem, that will be fixed with an extra line in Application.jsx
The results table is a mess, partially due to untested refactors.  
There is probably a few days of work here, to get this back in shape.
