### ISSUE TITLE
Organization Follow Toggle Not Full Width

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2259]
### Please describe the issue (What happens? What do you expect?)
On the organization page, when you're following that organization, the button is full width. However, if you're not following, the button is not full width.
![Capture](https://user-images.githubusercontent.com/46693952/59115632-af4fb380-8917-11e9-8f39-871965e02738.PNG)
![Capture2](https://user-images.githubusercontent.com/46693952/59115636-b080e080-8917-11e9-98ac-a068d549a1fd.PNG)

**Comment by jarodpeachey** [comment]
I'll take this issue, because the entire component has issues. For example, the drop down menu still is hidden behind the edge of the card in most places, and the horizontal separator line is still out of whack.  I'll see what I can do to fix this.

**Comment by DaleMcGrew** [comment]
Works great!
