### ISSUE TITLE
Create very fast initial page load

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#226]
On mobile device, away from wifi, the initial page load can take 5-7 seconds. I'd like to get an initial page load of 1 second (splash screen is ok)

**Comment by pertrai1** [comment]
Lazy load what the user will not interact with and prioritize what needs to be seen right away for user

**Comment by pertrai1** [comment]
Here is a look at the possible reason for the slow load time. We will have to break apart the `bundle.js` into a couple file.

![screenshot 2016-04-23 11 40 58](https://cloud.githubusercontent.com/assets/442374/14762456/a14b0bba-0948-11e6-8bf3-4d9ebaa402b3.png)

It might be hard to see the popup, but the `bundle.js` is taking 4.6 seconds to completely download.

**Comment by lisamcho** [comment]
There's a lot of files that currently aren't being used in the repo. It would make bundle.js smaller if we removed everything for example in the components/Guides folder. (keep the files in a separate branch somewhere?)

**Comment by pertrai1** [comment]
@lisamcho yes I agree. I also think we might want to go with the standard of having a vendor type file and an application file.

**Comment by DaleMcGrew** [comment]
@lisamcho @pertrai1 @nf071590 I will move the (currently) unused files into a separate branch today. I am thinking that we could break the application into these "single page" sections to reduce the size of the first bundle.js file that downloads:
1) A loading screen - should be split second load before initial display. I think a loading screen buys us maybe 3 seconds before voter will start perceiving We Vote as slow.
2) App "Page" 1: The ballot (most of the functionality we have working today) - can we get this down to 1 MB or less? (This is the current bundle.js download)
3) App "Page" 2: Add friends, Respond to friend requests
4) App "Page" 3: Voter guide creation
5) App "Page" 4: Activity Feed

**Comment by nf071590** [comment]
Is bundle.js being minified?

**Comment by nf071590** [comment]
does our server support compression?

**Comment by nf071590** [comment]
@pertrai1, lazy loading is a good thought.

First lets try compression methods to see what load times get down to. 

Then we can maximizing our react-router from the advanced usage guides.

[Dynamic Routing](https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md)
[Minimizing Bundle Size](https://github.com/reactjs/react-router/blob/master/docs/guides/MinimizingBundleSize.md)

**Comment by DaleMcGrew** [comment]
@josephevans Does our WebApp server support compression? (Question from @nf071590)

**Comment by josephevans** [comment]
I just enabled gzip compression on the wevote.guide site. You should be able to compare it to wevote.me (without compression.)

**Comment by DaleMcGrew** [comment]
I have updated both https://wevote.me and https://wevote.guide with the latest code so we can test the difference.

**Comment by pertrai1** [comment]
@DaleMcGrew Little over 2 second difference between wevote.guide and wevote.me when it comes to the download time of `bundle.js`

**Comment by lisamcho** [comment]
What if we just started index.html with a static loading page image or a gif (not javascript)? That way we'd immediately see something without having to split a separate loading.js file out of bundle.js. (once all the javascript files are loaded then the document ready function would just render the app and replace the loading div.). Hopefully the uglification and getting rid of extraneous files in the components folder will get us the rest of the way for speed.

**Comment by DaleMcGrew** [comment]
Exactly @lisamcho. I think starting with a simple index.html page that loads in a split second is a good starting point. Does anyone know how to set that up?
@josephevans it sounds like gzip compression on https://wevote.me will make a difference.

**Comment by nf071590** [comment]
load time was cut in half for me using wevote.guide

![wevote loadtime](https://cloud.githubusercontent.com/assets/7058732/14808601/9f75bc64-0b54-11e6-9938-9b58422a1d1b.png)

**Comment by nf071590** [comment]
Lazy loading routes (what @pertrai1 suggested) is the solution that takes it further; Load ballot route quickly, then load the other routes when user needs them. Making a fake page is more work than what it's worth; We're not delivering content any faster and making our app size larger.

**Comment by nf071590** [comment]
@DaleMcGrew, also try changing vendor libraries to CDN

**Comment by pertrai1** [comment]
@DaleMcGrew @nf071590 we should not need to use a CDN as we will have our own using Amazon S3.

**Comment by lisamcho** [comment]
I agree with @nf071590 We should use CDN for stuff user probably already has cached, like jQuery, it will be faster.

**Comment by pertrai1** [comment]
But that is what Amazon S3 is and we are going to use that for all static assets of web app

**Comment by josephevans** [comment]
Please let me know what other assets should be added to the static.wevote.* sites. They are AWS S3 buckets.

**Comment by DaleMcGrew** [comment]
I believe we have moved all related speed issues into different Issues. If someone else agrees, we can close this issue.

**Comment by lisamcho** [comment]
#248 added loading screen.

**Comment by lisamcho** [comment]
Closing out
