### ISSUE TITLE
ItemPositionStatementActionBar: Stack "Friends only" and "Public" options in mobile

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2262]
Stack the "Friends only" and "Public" options in mobile:
<img width="652" alt="screen shot 2019-02-22 at 12 13 47 pm" src="https://user-images.githubusercontent.com/7756031/53268586-6000b280-369b-11e9-931f-35663264f8ff.png">

Currently they make the interface too wide when shown left-to-right:
![Screen Shot 2019-06-09 at 5 32 18 PM](https://user-images.githubusercontent.com/7756031/59166262-98a68980-8adc-11e9-9c82-a598a47b68ba.png)

**Comment by jarodpeachey** [comment]
My bad, I missed this. I'll grab this issue.

**Comment by jarodpeachey** [comment]
Hey @DaleMcGrew ! I'm working on this now and found another way we can fit this on the mobile screen. I've made the buttons smaller and took away the button text on mobile (The toggle still isn't stacked, but I'm still working on this.) Does this method look okay?

**Comment by DaleMcGrew** [comment]
Verified. Thank you @jarodpeachey!
