### ISSUE TITLE
ItemPositionStatementActionBar: Change background color when saved

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2263]
Input box color when a comment saved:
<img width="949" alt="screen shot 2019-02-22 at 12 18 07 pm" src="https://user-images.githubusercontent.com/7756031/53268806-f0d78e00-369b-11e9-90ac-74efbf29b7ca.png">

Input box color when adding or editing comment:
<img width="946" alt="screen shot 2019-02-22 at 12 17 32 pm" src="https://user-images.githubusercontent.com/7756031/53268777-ddc4be00-369b-11e9-9d89-a3780429a9c8.png">

**Comment by jarodpeachey** [comment]
I'll take this one as well

**Comment by DaleMcGrew** [comment]
Great work @jarodpeachey! Resolved.
