### ISSUE TITLE
ItemPositionStatementActionBar: Must click "Save" twice to actually save

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2264]
When you are editing your comment about a candidate:
![Screen Shot 2019-06-09 at 5 36 41 PM](https://user-images.githubusercontent.com/7756031/59167202-e6bf8b00-8ae4-11e9-89fe-f3424a968dde.png)

When you click "Save" the first time, it shrinks the box:
![Screen Shot 2019-06-09 at 5 36 52 PM](https://user-images.githubusercontent.com/7756031/59167209-f0e18980-8ae4-11e9-9968-44c0ecf61a60.png)

...but doesn't actually save until you click it a second time:
![Screen Shot 2019-06-09 at 5 37 06 PM](https://user-images.githubusercontent.com/7756031/59167210-f7700100-8ae4-11e9-8d96-a985a21e992f.png)

For some reason, the `onSubmit={this.savePositionStatement.bind(this)}` around line 284 in WebApp/src/js/components/Widgets/ItemPositionStatementActionBar.jsx doesn't fire on the first click of the Save button.

**Comment by jarodpeachey** [comment]
Ahh, I see. The onBlur event that decides the height of the input is firing BEFORE the onClick event, so the button doesn't actually get clicked. I'll see what I can do.

**Comment by DaleMcGrew** [comment]
Works very well. Resolved.
