### ISSUE TITLE
Vote page: Election name doesn't show in browser

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2270]
When you go tot he Vote page, the Election name/date doesn't show.
1. Start signed out
2. On the ballot page, make sure an election is chosen
3. Go to the vote page
4. The election name and date is not being shown because the subheader doesn't go down far enough on the page

<img width="322" alt="Screen Shot 2019-06-10 at 12 04 46 PM" src="https://user-images.githubusercontent.com/7756031/59219951-8843ec80-8b78-11e9-8277-df444e89cd60.png">

This is what it should look like (note the logo is missing from this graphic, and it *should* be included)
<img width="630" alt="Screen Shot 2019-06-10 at 12 18 57 PM" src="https://user-images.githubusercontent.com/7756031/59220554-22f0fb00-8b7a-11e9-9e81-6a4a71664596.png">

**Comment by SailingSteve** [comment]
This is a WebApp style issue, the changes I made for Cordova should not have any effect on this.  (When debugging this problem I could see that the Cordova specific  styles were not included).  Once this is fixed for the webapp, it will probably break the layout in cordova.

<img width="1135" alt="Screen Shot 2019-06-11 at 9 06 45 PM" src="https://user-images.githubusercontent.com/6923653/59322825-e7932100-8c8c-11e9-81b9-d2782057af4f.png">

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve, would you like me to ask another teammate to take a look at this?

**Comment by jarodpeachey** [comment]
@DaleMcGrew I can take this as soon as I finish the Issue Popover issue 👍

**Comment by DaleMcGrew** [comment]
Hello @jarodpeachey, thank you for working on this! I notice that in both mobile and desktop, when you scroll up, the header slides up and obscures the election name.

- [ ] Could you turn off the "sliding up" behavior in the Vote section?
- [ ] Could you reduce the space (in mobile and desktop) beneath the header and the start of the content beneath it? There will need to be dynamic spacing based on whether there are selected candidates to view (or not) in the Vote section (which turns on or off the search box), and Steve has implemented dynamic spacing based for the Ballot section based on "Are there multiple region categories? (Federal, State, Measure -- or are all ballot items under Federal)" Make sure to change elections to test, and choose some candidates / measures for one election, and no choices for another election (so you can see the "no chosen items" empty-state view). Please also test between mobile and desktop.

Mobile:
![Screen Shot 2019-06-19 at 6 55 24 AM](https://user-images.githubusercontent.com/7756031/59771953-afc54400-925f-11e9-8b7e-746592932dc3.png)

Desktop:
![Screen Shot 2019-06-19 at 6 55 47 AM](https://user-images.githubusercontent.com/7756031/59771956-b3f16180-925f-11e9-8abb-0c2f7158fa99.png)

**Comment by DaleMcGrew** [comment]
Verified!
