### ISSUE TITLE
Cordova: pop-down header cuts off candidate photo, iPhone 8

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2278]
![Canidate-photo-cutoff](https://user-images.githubusercontent.com/7756031/59247709-16e65700-8bd5-11e9-976f-99a7098f5ae8.jpeg)

**Comment by SailingSteve** [comment]
![Simulator Screen Shot - iPhone 8 - 2019-06-11 at 20 10 33](https://user-images.githubusercontent.com/6923653/59320930-10afb380-8c85-11e9-9624-419af0193473.png)

**Comment by SailingSteve** [comment]
Does not reproduce in the simulator.  Retest with the latest from TestFlight?

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve the problem happens when you are scrolled down the page, and you are looking at the popdown header -- as opposed to the top of the page when you first arrive on the Candidate page. (I am seeing the problem in the latest TestFlight version on my phone.)
