### ISSUE TITLE
Improve Print view of Vote section

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2280]
When a voter chooses print from their desktop machine, make sure the output sent to their printer is reasonable.

**Comment by LohitG** [comment]
Most major problems have been resolved. I delegated a small part that I did not know how to do to Leon in a separate issue.

**Comment by ffrancetic** [comment]
Should this be a concern?

<img width="546" alt="Screenshot 2019-06-28 at 10 22 22" src="https://user-images.githubusercontent.com/36188818/60359741-c6217d00-998e-11e9-9145-108835d99791.png">

 The "+1"s do not have a border. I realized that this happens on Chrome.

**Comment by LohitG** [comment]
I will send in a fix for that. This is interesting because I thought a border showed up previously.

**Comment by DaleMcGrew** [comment]
This issue is resolved. Thank you @LohitG.
