### ISSUE TITLE
After viewing an organization and clicking on a candidate, the candidate page is not the same

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2282]
### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to the values page
2. Click on a public figure
3. Click on a candidate from that page
4. Scroll down

You'll notice that the sticky header does not work. The PositionItems are also showing up twice, one with the old design and one with the new.

**Comment by DaleMcGrew** [comment]
Thank you for pointing this out @jarodpeachey. We will be changing the design of how we look at candidates under voter guides (organizational endorsements), so we will be able to fix this issue when we get to that.
