### ISSUE TITLE
Move the Follow button down into comment box

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2285]
Whether there is a comment or not, please move the "Follow" button down into the shaded box where comments go so we don't have so much empty vertical space:

![IMG_6059](https://user-images.githubusercontent.com/7756031/59310466-50fa3c00-8c5b-11e9-85a9-54afaca282ac.jpeg)

**Comment by jarodpeachey** [comment]
@DaleMcGrew Did you just fix this in your latest pull request?

**Comment by DaleMcGrew** [comment]
No, I did not. I am just about (in the next 5 minutes) to commit some changes to the code around this, fyi.

**Comment by jarodpeachey** [comment]
The reason there's so much empty space is because the issues are not there yet. Should I go ahead and make this change, but eventually change it back when the issues are displayed? The issues would be right below the image, and then there would be less vertical blank space.

**Comment by DaleMcGrew** [comment]
Great question @jarodpeachey. We have swapped the Follow and the "+1", but aside from that I think this layout still is a good target to shoot for with the "Follow" within the darker background area where the comment lives (when there is a comment), and the Issues right underneath the organization name:
<img width="603" alt="Screen Shot 2019-06-14 at 8 37 33 AM" src="https://user-images.githubusercontent.com/7756031/59520903-db22ea00-8e7f-11e9-999b-3d79c6a4b73b.png">

I will try to create a parallel `IssuesByBallotItemDisplayList` component for organizations called `IssuesByOrganizationDisplayList` today or over the weekend so we can fill in that endorsement card.

**Comment by DaleMcGrew** [comment]
Verified! Also, I implemented and checked in `IssuesByOrganizationDispayList` this weekend.
