### ISSUE TITLE
Ballot Header overhang tweaks needed (Browser vs. Cordova)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2286]
I did this testing on an iPhone 8, but I've observed this problem on other iPhones (in Browserstack). On the ballot page, there is too much "overhang" space for the browser:

![FullSizeRender-1](https://user-images.githubusercontent.com/7756031/59310656-f01f3380-8c5b-11e9-876f-8267817c6bf2.jpeg)

...and not enough "overhang" space in Cordova:

![FullSizeRender-2](https://user-images.githubusercontent.com/7756031/59310650-ea295280-8c5b-11e9-8ca8-2af3f7de29f8.jpeg)

Please add a little more spacing above the election name in Cordova (so it is more similar to the browser version).

**Comment by SailingSteve** [comment]
Vertical real estate is precious in mobile.  This overhang is consistent with other devices in cordova.

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, I'm referring to the vertical gap we designed between the shadow underneath the search box, and the card containing "Democratic Presidential Primary". The design has the top of the "Democratic Presidential Primary" card visible under the shadow (the browser version still shows too much space, but allows you to see the top of the card.)

**Comment by DaleMcGrew** [comment]
Resolved!
