### ISSUE TITLE
When at 575px, the screen shows two different breakpoints

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2288]
### Please describe the issue (What happens? What do you expect?)
When the screen size is 575px, both the mobile and desktop versions of everything show up. This is something to do with the media querys.

**Below, the ballot text shows up twice, the PositionItem shows up twice and other errors**
![Capture5](https://user-images.githubusercontent.com/46693952/59315022-e3afd080-8c85-11e9-9fd0-89edaa6a83ec.PNG)

**Comment by ffrancetic** [comment]
Cannot be reproduced on a Mac for some reason. Made multiple attempts.

**Comment by DaleMcGrew** [comment]
Resolved.
