### ISSUE TITLE
Allow voter to sign in (Facebook) and sign out

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#229]
- [x] Get our Facebook sign in working (and debugged) again.
- [x] Finish building our "Sign Out" feature to delete the voter_device_id and create a new one.
- [x] Turn off the "Disconnect from Facebook" interface from Account settings page

**Comment by lisamcho** [comment]
@DaleMcGrew before we re-implement this, I was thinking that I've never heard of this approach for login (i.e. swapping out a voter_device_id in the cookies). Most apps use a standard auth library because few developers are security experts. Are you positive that it doesn't have security vulnerabilities?

**Comment by DaleMcGrew** [comment]
Hi @lisamcho, having worked as a software engineer for 8 years, I have been through over 20 hours of in-person and video courses on user security, ranging from OWASP to phishing to social engineering. Our security model is solid. We are actually using a standard auth library within Django/Python, as well as our Facebook auth within WebApp. Also, our entire network is https so data passed between the browser and server is encrypted.

**Comment by DaleMcGrew** [comment]
If you would like to have a call as well, I can share what I think are the most likely areas we would be attacked, and how our approach protects against those attacks. 

We can also ask for an audit from people with even more experience with security than I have.  It will be very important that we protect voter data!

**Comment by lisamcho** [comment]
I think that your security experience is impressive. The implementation sounds solid to me, but audit with people who focus specifically 24/7 in security would be a good idea if we are doing anything custom at all. Then again, maybe we aren't doing anything custom....

On question I had (for example)....on logout we just delete the cookie and generate a new voter? I think we've also discussed having the webapp tell the server to delete or swap out its voter_device_id for the user account when the user logs out? (in case someone steals the cookie). Is that also necessary and what endpoint would it be?

**Comment by DaleMcGrew** [comment]
We should tell the server to delete the voter_device_id from the database, and then delete the cookie from the browser.  I will create an API endpoint called voterSignOut today that deletes voter_device_id from the database.

**Comment by DaleMcGrew** [comment]
@lisamcho The new API endpoint voterSignOut is now ready: https://api.wevoteusa.org/apis/v1/docs/voterSignOut/

**Comment by lisamcho** [comment]
#234

**Comment by DaleMcGrew** [comment]
Works really well! Great work.
