### ISSUE TITLE
Issue popover: X positioning wrong, and popover centering instead of being at bottom

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2294]
When you click an Issue under a candidate:
<img width="303" alt="Screen Shot 2019-06-12 at 7 25 42 PM" src="https://user-images.githubusercontent.com/7756031/59399274-4b2e5480-8d48-11e9-85e9-51432cdec538.png">

The popover opens with two problems:
<img width="309" alt="Screen Shot 2019-06-12 at 7 25 33 PM" src="https://user-images.githubusercontent.com/7756031/59399293-55505300-8d48-11e9-9891-6852cc22b136.png">

- [ ] 1: The x to close the popover should be right aligned
- [ ] 2: The popover should open under the Issue, instead of opening centered over the issue

**Comment by jarodpeachey** [comment]
@DaleMcGrew Should this be a hover popover as well, sort of like the OrganizationPopoverCard? I can use the sticky popover component, that way all the popovers have a consistent look and feel.

**Comment by DaleMcGrew** [comment]
Yes @jarodpeachey, that sounds great to use the same kind of popover as we are for OrganizationPopoverCard. In this case we want to open it with a click, and include an "x" to close it with another click. I am also fine with the popover closing when you move your mouse away from it. Please make sure to test extensively in mobile, since the OrganizationPopoverCard isn't used in mobile, so this code may have some different reactions when viewed in a mobile context.

**Comment by DaleMcGrew** [comment]
@jarodpeachey your solution works beautifully. Great work!
