### ISSUE TITLE
React warning: `props.history` and `context.history` are deprecated

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#230]
bundle.js:54006 Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://tiny.cc/router-contextchanges

**Comment by pertrai1** [comment]
Now it is recommended to use higher order components for the router: [React Updates](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md)

**Comment by alexd3d** [comment]
Hi guys! Link "React Updates" in warnings leads me to 404 broken GitHub page, why is that?

**Comment by DaleMcGrew** [comment]
Hi @alexd3d, this is a very old issue -- it looks like React Training has moved several of their old pages.
