### ISSUE TITLE
The Polling Location Modal: Contents too wide

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2301]
### Please describe the issue (What happens? What do you expect?)
The Polling Location Modal needs to be styled properly

http://localhost:3000/polling-place-locator
<img width="753" alt="Screenshot 2019-06-13 at 13 29 38" src="https://user-images.githubusercontent.com/36188818/59465417-b6773580-8ddf-11e9-93ea-f2ad1687c9e6.png">

### Steps to reproduce the problem (1, 2, 3...), including links
See the source for this widget here: https://tool.votinginfoproject.org/cms/index.html

1. Go to Vote section
2. Click on "Polling Location" button
- [ ] In desktop, there is too much padding around the iFrame that contains the polling location widget
- [ ] In desktop, please make the modal that the Polling Location widget is in much wider (to say 80% of the page?) so that there is more room for the widget
- [ ] In mobile, the frame styling wrapping the polling location widget is too wide, causing us to not be able to see the entire Polling location widget
![IMG_6063](https://user-images.githubusercontent.com/7756031/59517708-fccca300-8e78-11e9-942d-381a16c16cc3.jpeg)

**Comment by DaleMcGrew** [comment]
I still see this problem on an iPhone 6 in a browser (Safari). I think it is a problem with the interaction between the iFrame and the mobile phone. The Polling location widget looks fine in iPhone 5/SE screensize on my Mac in emulation mode, but only shows the left-most half of the widget (as shown above) when viewed from any browser on a phone.

**Comment by DaleMcGrew** [comment]
We have removed this feature from the product.
