### ISSUE TITLE
Update Bootstrap Button with Twitter icon

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2305]
I couldn't figure out how to add a white Twitter bird icon to this Bootstrap social button. It should be easy, but I ran out of time. 
Code is here: WebApp/src/js/components/Widgets/ThisIsMeAction.jsx
![Screen Shot 2019-06-14 at 8 00 38 AM](https://user-images.githubusercontent.com/7756031/59518632-db6cb680-8e7a-11e9-8fdb-d774ccdecc2a.png)

**Comment by jarodpeachey** [comment]
@DaleMcGrew I can take this. I do have one comment though. Currently, the Add Endorsements button, as well as this Claim button, are using the bootstrap social buttons. This leads to the buttons having the blue outline when clicked, and they don't have the ripple. Should I fix all of these and use the technique I used for the Follow/Toggle  component, which is to use a Material UI button with the bootstrap-social buttons. This way, the buttons can fit in more with the other buttons in the site?

**Comment by DaleMcGrew** [comment]
Yes please @jarodpeachey, that would be awesome!

**Comment by DaleMcGrew** [comment]
Great work!
