### ISSUE TITLE
Selenium/Appium: We need way to scroll down (or up) "X" pixels, or scroll to an element

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2309]
We need way to scroll down (or up) "X" pixels, or scroll to an element.

**Comment by flurmbo** [comment]
@DaleMcGrew does [this](https://webdriver.io/docs/api/element/scrollIntoView.html) look like what you're looking for? If so, let me know where in the test script we need this functionality and I can add it in

**Comment by DaleMcGrew** [comment]
That looks exactly right @flurmbo. Feel free to add it anywhere in the test script as an example.
