### ISSUE TITLE
Redundant Show More Link on Candidate Card

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2328]
On the party candidate list, the candidate item shows the "Show More" link, which takes you to the candidate page. However, since the entire card is clickable, this seems to be unneeded. @DaleMcGrew should this be removed since we don't use it?

![SnipForIssue](https://user-images.githubusercontent.com/46693952/59706505-97f1af80-91ce-11e9-9aed-f472d7c3b25c.PNG)

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey thank you for sharing this. We are creating a design language and want to include the "Show more" link here so that people who are zipping through the site can have a regular interface element to click on.
