### ISSUE TITLE
Two voter_device_id cookies created

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#233]
1. Visit ballot. Look in your cookies to make sure you have a voter_device_id
2. Navigate to the Save Address page.
3. Refresh the page, and it creates a second voter_device_id for the path "/settings"

App should only have one voter_device_id

**Comment by DaleMcGrew** [comment]
Note that if verifying this fix on localhost in chrome, it will appear to still be broken:
http://stackoverflow.com/questions/335244/why-does-chrome-ignore-local-jquery-cookies/347997#347997
I verified that this works if we don't use "localhost", here for example: http://127.0.0.1:3000/more/opinions/followed

**Comment by pertrai1** [comment]
@DaleMcGrew your change does the trick for this. closing based on #236
