### ISSUE TITLE
The follow and ignore button on My Values page is broken

### ISSUE THREAD

**Issue by LohitG** [wevote/WebApp#2344]
If you hit ignore, and then hit follow, it seems to stack the ignore and the follow. So when you unfollow, it automatically sets to ignore. The symbols are also stacked vertically.
<img width="1280" alt="Screen Shot 2019-06-19 at 13 41 37" src="https://user-images.githubusercontent.com/23069689/59798906-0fd7dc80-9298-11e9-8fb9-b25e3e2bc5d2.png">
There is also no way to undo an ignore without hitting follow, which then creates this issue.

**Comment by jarodpeachey** [comment]
I just tested this on the quality.wevote.us site, and it seems that the icons are stacked only for a small moment. Could your internet be slow? Either that, or the quality.wevote.us site does not have that bug yet. @DaleMcGrew when was the last time you updated it?

**Comment by LohitG** [comment]
Yeah now it disappears after a small instant. That's weird...

**Comment by jarodpeachey** [comment]
I would just close this issue, it's just because of a re-render with React. This isn't the first time i've thought something was a bug, but it was just loading slow at the moment.

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, yesterday afternoon @LohitG and myself did more debugging, and we found that because of an API server bug, it was possible to get the WebApp into a weird display state. We fixed the display state, and I have updated the broken API. @LohitG could you please verify this is fixed? (The latest code is up on the Quality site.)

**Comment by LohitG** [comment]
Awesome! I’ll take a look at it as soon as possible.

**Comment by LohitG** [comment]
It looks good. Sometimes it takes a bit for the sign to disappear but that's probably a re-render issue.
