### ISSUE TITLE
Frontend server and gulp process need process management so that when they crash, they restart

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#235]
Frontend server and gulp process need process management so that when they crash, they restart.

To address the problem, I’ve added new `npm run prod` scripts and left `npm run prod` in place so it doesn’t break anything. If processes crash, they are restarted by forever.js. Output for the processes are logged to 4 separate files: server.log, server.err.log, gulp.log, & gulp.err.log. I will push the code to a new branch where it can be tested and then merged into develop or master by another developer.

##Valuable Gains - Zero Downtime, Logging... and a New Workflow?
When the front-end server crashes without forever.js, wevote.me is down until someone can start it. Also, forever.js allows better log output for info & errors that can give us insight to what went wrong and how we’re performing.

###A New Workflow?
Not necessaryily due to forever.js management, but you may notice a workflow that will allow us to continuously integrate our application repo with AWS; Giving the front-end server effectively zero downtime. 

Take a look at the following (simplified) workflow example:

1. Developer does a pull request for the WeVote/WebApp origin/develop branch.
2. Code passes tests and reviewer merges code into develop branch
3. (when applicable) The new code will be merged into Master Branch
4. Remote WeVote/WebApp repository file watcher picks up master branch changes and pulls/pushes code to remote directory on AWS server.
5. Remote (AWS) Gulp daemon (listening for changes to the filesystem) “hears” (or sees) that the files in our remote `src/` directory have changed.
6. Remote (AWS) Gulp rebuilds the project and moves the files into the remote ‘build/‘ directory.

… And obviously,
7. Next time a client loads the page it is the brand new updated code

You’ll notice no processes ever end or restart and the application is continuously integrated when new code is pushed.

##New Commands
There are four new commands:
```
$ npm run prod:start
$ npm run prod:kill
$ npm run prod:restart
$ npm run prod:clean

#`npm run prod` still exists but is considered deprecated

```

##Documentation
`npm run prod:start` - starts both processes: *server* and *gulp* build process as daemon processes that run infinitely. 

`npm run prod:kill` - stops both daemon processes

`npm run prod:restart` - stops and then starts both daemon processes

`npm run prod:clean` - empties the log files

Although you shouldn’t need to use Forever.js directly, I’d recommend doing a Google search for forever.js or searching npmjs.com <http://npmjs.com/> for forever.js for more information on forever.js process management and how it works.

Thanks for your time,

Nick

**Comment by pertrai1** [comment]
The workflow will have to take into consideration the different servers that could be running. Most of these files will be picked up by S3, so wherever the daemon is running, there will have to be a maestro that knows where resources will have to go.

**Comment by josephevans** [comment]
We are already using upstart to manage the npm process for the websites. This monitors the PID of the node server and automatically restarts it if it dies. Are we actually having problems with it crashing and not coming back up?

**Comment by josephevans** [comment]
I tried changing the upstart config file to use "npm run prod:start" for starting the production server - it doesn't appear to work. 

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/home/NodeEnvironments/WebAppEnv/bin/node" "/home/NodeEnvironments/WebAppEnv/bin/npm" "run" "prod:start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12

npm ERR! missing script: prod:start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wevote/WebApp/npm-debug.log

**Comment by nf071590** [comment]
I don't think anyone updated the npm script and dependencies yet.

**Comment by DaleMcGrew** [comment]
Per a discussion May 7th, 2016, we will be serving index.html via ngnx instead of node express.
