### ISSUE TITLE
Cordova: Images of candidates not displaying on the Vote tab (Android and iOS)

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2354]
### Please describe the issue (What happens? What do you expect?)

Images of candidates not displaying on the Vote tab after choosing them. (Android and iOS) 

### Steps to reproduce the problem (1, 2, 3...), including links

<img width="286" alt="Screenshot 2019-06-20 at 11 39 27" src="https://user-images.githubusercontent.com/36188818/59873104-22ade800-9350-11e9-9a9b-67c63b7e9f39.png">

**Comment by SailingSteve** [comment]
<img width="508" alt="Screen Shot 2019-06-20 at 5 17 18 PM" src="https://user-images.githubusercontent.com/6923653/59889065-666c1600-937f-11e9-8840-e5928afa98cf.png">
<img width="559" alt="Screen Shot 2019-06-20 at 5 19 57 PM" src="https://user-images.githubusercontent.com/6923653/59889118-b519b000-937f-11e9-96fc-9b43fcd26275.png">
