### ISSUE TITLE
"Next" button sitting too low on larger iPhone screens(iPhone XS, Iphone 8...)

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2366]
### Please describe the issue (What happens? What do you expect?)

"Next" button sitting too low on larger iPhone screens

### Steps to reproduce the problem (1, 2, 3...), including links

Page: https://localhost:3000/wevoteintro/network

<img width="368" alt="Screenshot 2019-06-21 at 10 23 05" src="https://user-images.githubusercontent.com/36188818/59940330-45530600-940f-11e9-9b60-6396e73365da.png">
<img width="356" alt="Screenshot 2019-06-21 at 10 25 57" src="https://user-images.githubusercontent.com/36188818/59940348-4f750480-940f-11e9-9b10-f79e4d5027dc.png">

**Comment by DaleMcGrew** [comment]
Fixed!
