### ISSUE TITLE
Popover "X" for the issues needs to be tapped twice in order to be closed. (iPhone)

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2367]
### Please describe the issue (What happens? What do you expect?)
Popover "X" for the issues needs to be tapped twice in order to be closed. (iPhone related) This was not created through the site itself, it was present in the App Live of Browserstack.
### Steps to reproduce the problem (1, 2, 3...), including links
Link: https://quality.wevote.us/office/wv02off28320/b/btdb/
<img width="380" alt="Screenshot 2019-06-21 at 11 11 06" src="https://user-images.githubusercontent.com/36188818/59942770-71718580-9415-11e9-94d2-77ef875f4eba.png">

**Comment by DaleMcGrew** [comment]
The actual app does not have this problem. This issue only appears within BrowsterStack.
