### ISSUE TITLE
API server does not update properly when selecting and unselecting oppose/support

### ISSUE THREAD

**Issue by LohitG** [wevote/WebApp#2368]
When you are logged in and choose oppose or support and then unselect it, a +1 still appears. Your endorsement doesn't seem to revert after you deselect your preference
<img width="1280" alt="Screen Shot 2019-06-21 at 12 07 57" src="https://user-images.githubusercontent.com/23069689/59945709-4ab74d00-941d-11e9-9f61-4acc2b29d7b1.png">
<img width="1280" alt="Screen Shot 2019-06-21 at 12 08 45" src="https://user-images.githubusercontent.com/23069689/59945736-5f93e080-941d-11e9-92e7-013238bff389.png">

**Comment by DaleMcGrew** [comment]
This has now been resolved in WebApp, and will be fixed in the mobile app when we update it.
