### ISSUE TITLE
Sign in/sign out: voter_found == false

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#237]
There are cases where a voter_device_id that has been deleted from the server, but the browser still has a cookie with the (newly) invalid voter_device_id. (In the case where you sign out from device A (killing all voter_device_id's for that voter), and device B expects it's voter_device_id to still work.)

I propose that if voterRetrieve gets "voter_found" == false, the voter_device_id be deleted, and a new cookie created. This is the voterRetrieve response:
{
voter_created: false,
voter_found: false,
voter_device_id: "BSBipSsp1ygFwPd0hzhFuzjlPDopW0H1w8CdRtnYVAXr7v9a7kqRNRY6abi2asQv4J4IWUROrpry9IJuQFCiyg2i",
status: "VOTER_NOT_FOUND_FROM_DEVICE_ID",
success: false
}

@lisamcho would you be willing to tackle this given your knowledge of /src/js/stores/VoterStore.js?
Note: Many other API endpoints fail if the voter_device_id doesn't return a valid voter. We will want to discuss how to react in all of these other locations in the code.

**Comment by lisamcho** [comment]
Hmmm, that's a little odd, is there a way to make it so that if you sign out of the account on one device it does not affect your signin state on other devices?

**Comment by DaleMcGrew** [comment]
Yes, just set "sign_out_all_devices" to false when calling voterSignOut. Changing this setting may allow us to avoid fixing this issue for a while, but eventually we will still need to deal with the case of the voter_device_id in the cookie not being valid.

**Comment by lisamcho** [comment]
OK, so we'll set sign_out_all devices to false and then put this on the backlog?

**Comment by DaleMcGrew** [comment]
Perfect.

**Comment by lisamcho** [comment]
Just set this to false with last pull request, changing to backlog.

**Comment by DaleMcGrew** [comment]
This is fixed!
