### ISSUE TITLE
Sign In Modal too narrow for the iPhone SE 

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2373]
### Please describe the issue (What happens? What do you expect?)
Sign In Modal too narrow for the iPhone SE which causes the button's text to be changed.
### Steps to reproduce the problem (1, 2, 3...), including links
<img width="371" alt="Screenshot 2019-06-21 at 14 44 01" src="https://user-images.githubusercontent.com/36188818/59953023-32522d00-9433-11e9-9de5-a09695f0a4a9.png">

**Comment by DaleMcGrew** [comment]
Resolved.
