### ISSUE TITLE
Facebook photo download and email save

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#238]
There is currently a button that downloads the user photo on the account/login page. Is this meant to eventually just be downloaded/saved to voter profile when you login to facebook (without clicking the button)?

**Comment by DaleMcGrew** [comment]
That is correct -- ideally we would just download/save the Facebook photo upon sign in. We will also need the ability to refresh the photo from the account settings page (separate from the sign in process), but we won't need this probably until 2017.

**Comment by pertrai1** [comment]
@DaleMcGrew @lisamcho Is there consideration in the future to use OAuth?

**Comment by DaleMcGrew** [comment]
We are using the standard Facebook/oauth.

**Comment by lisamcho** [comment]
Implemented in #251

**Comment by DaleMcGrew** [comment]
Verified.
