### ISSUE TITLE
Testimonial is not centered - iPhone SE

### ISSUE THREAD

**Issue by LohitG** [wevote/WebApp#2383]
The testimonial block is not centered and seems to float to the right. 
![IMG-7611](https://user-images.githubusercontent.com/23069689/60039192-00c3a680-966b-11e9-82aa-88e2b48a3d7a.PNG)

**Comment by jarodpeachey** [comment]
This seems to have been fixed from a change I made 2 days ago regarding an extra card around the testimonial item.

**Comment by LohitG** [comment]
Yeah it look great now. The border around the testimonial has disappeared but the next is entered so i think it looks great.
