### ISSUE TITLE
Too much space left at the bottom when scrolling through the ballot tab and values tab on mobile devices

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2387]
Too much space left at the bottom when scrolling through the ballot tab and values tab on mobile devices.

![Screenshot_20190624-142017](https://user-images.githubusercontent.com/36188818/60053032-b0a90c00-968b-11e9-8c19-629ec20fbe68.jpg)
![Screenshot_20190624-142023](https://user-images.githubusercontent.com/36188818/60053033-b272cf80-968b-11e9-8a8e-67cee317beb6.jpg)

**Comment by jarodpeachey** [comment]
I can't reproduce this using the Chrome dev tools mobile view, is this a testing-only issue?

**Comment by DaleMcGrew** [comment]
Thank you @jarodpeachey, this is in the Cordova mobile app. I don't believe it is visible in the browser.

**Comment by DaleMcGrew** [comment]
Verified.
