### ISSUE TITLE
Name of Election is not visible - iPhone SE

### ISSUE THREAD

**Issue by LohitG** [wevote/WebApp#2388]
The name of the election is not visible. This can be seen on the Ballot page when on an iPhone SE. After supporting a candidate, a bar pops up that lets you choose between Decided, Choices, and All. If you select Decided or Choices, you will not be able to see the name of the election. Sometimes a pop up appears and this allows you to see the name of the election. However closing the popup leads to the name of the election being covered up.
![IMG_BD2E87517269-1](https://user-images.githubusercontent.com/23069689/60054405-472afc80-968f-11e9-8b40-15c6d36be434.jpeg)
![IMG_7616](https://user-images.githubusercontent.com/23069689/60053291-5492b780-968c-11e9-9842-33905b54be4b.PNG)
![IMG_7615](https://user-images.githubusercontent.com/23069689/60053292-5492b780-968c-11e9-9aa3-ca8bda893e23.PNG)

**Comment by DaleMcGrew** [comment]
Verified!
