### ISSUE TITLE
Set up CDN service for wevote.me & wevote.guide

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#239]
Joe, can you set up the AWS CDN service for both wevote.me and wevote.guide so we can get these off our primary server? 
Move dependencies: bootstrap.css, bootstrap-social, and font-awesome to CDN

**Comment by pertrai1** [comment]
@DaleMcGrew @josephevans We should take advantage of using S3 for any static assets, which is most all of the web app. We had discussed this in previous talks and would be a big advantage for the speed and reliability of the application.

**Comment by DaleMcGrew** [comment]
I am moving some recent comments from Issue #226 so we can continue the conversation here:
From @nf071590: @DaleMcGrew, also try changing vendor libraries to CDN. The argument for letting Google host vendor libraries is that the user most likely already has them cached.
From @pertrai1: @DaleMcGrew @nf071590 we should not need to use a CDN as we will have our own using Amazon S3.
From @lisamcho: I agree with @nf071590 We should use CDN for stuff user probably already has cached, like jQuery, it will be faster.
From @pertrai1: But that is what Amazon S3 is and we are going to use that for all static assets of web app
From @dalemcgrew: By "CDN" I meant the Amazon S3 service. (I'm sorry for any confusion I created.) If Google hosts these libraries and we can use their hosting URL's, that sounds ideal to me since we benefit if those libraries are already cached in the browser from being loaded for another site.

**Comment by josephevans** [comment]
I created static.wevote.guide and static.wevote.me and put the following CSS files:

http://static.wevote.guide/css/bootstrap.css
http://static.wevote.guide/css/bootstrap-social.css
http://static.wevote.guide/css/font-awesome.css

What other files should be added here?

**Comment by DaleMcGrew** [comment]
Thank you @josephevans. I added a discussion tag and verify fix as a reminder for us to talk about the remaining questions.

**Comment by pertrai1** [comment]
@DaleMcGrew @nf071590 The files that @josephevans put on the static subdomain would be best served as minified files that are served as vendor file and one for application. As an example, having `vendor.xxx.css` and `app.xxx.css` would be efficient for the performance of the application. This would need to be added to the production build cycle.

**Comment by josephevans** [comment]
OK, after a lot of research on how we could utilize Amazon's S3 or other services to serve up static content, I've come to the conclusion that using S3 is probably not the right solution.

First off, S3 does not support SSL - so the site would have to request insecure content which makes browsers not show the lock in the URL bar and possibly a security warning in the JS console. Amazon does have a CloudFront service that will do SSL from an S3 bucket, but this costs $600/month. 

It seems like we're better off using the current setup (Elastic Load Balancer doing SSL termination) and passing the requests off to VM instances on our backend. We can serve up the static files using nginx and not have a requirement of running npm to serve up the files. This also gives us the ability to do request rewriting for our pages (such as redirecting /ballot to index.html.)

Any thoughts on this approach?

**Comment by nf071590** [comment]
The three files put on static.wevote.me <http://static.wevote.me/> should be on public CDNs. 

    ```<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" rel="stylesheet" />
      <link href="//cdn.bootcss.com/bootstrap-social/4.12.0/bootstrap-social.min.css" rel="stylesheet" />```

The only thing going on static should be our bundle.js and a new vendor.js file that we’ll be creating as part of the build.

I don’t really like that I don’t understand what’s going on but as long as you can figure it out then I’m fine. All the doors have been closed and it seems like there is a lot more work now to try and get this stuff going up and any external control or power that we did possess is gone. A lot of new back and forth for us trying to get things up and running. I preferred being able to pass a process to the server that can manage itself. 

> On May 11, 2016, at 12:40 PM, Joe Evans <notifications@github.com> wrote:
> 
> OK, after a lot of research on how we could utilize Amazon's S3 or other services to serve up static content, I've come to the conclusion that using S3 is probably not the right solution.
> 
> First off, S3 does not support SSL - so the site would have to request insecure content which makes browsers not show the lock in the URL bar and possibly a security warning in the JS console. Amazon does have a CloudFront service that will do SSL from an S3 bucket, but this costs $600/month.
> 
> It seems like we're better off using the current setup (Elastic Load Balancer doing SSL termination) and passing the requests off to VM instances on our backend. We can serve up the static files using nginx and not have a requirement of running npm to serve up the files. This also gives us the ability to do request rewriting for our pages (such as redirecting /ballot to index.html.)
> 
> Any thoughts on this approach?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/wevote/WebApp/issues/239#issuecomment-218517161>

**Comment by nf071590** [comment]
npm runs the gulp task which is basically the same thing so I’d have to say thats still say thats a requirement.

**Comment by DaleMcGrew** [comment]
Thank you @josephevans for doing the research into S3 and Cloudfront. I'm fine with sticking with serving up the bundle-vxx.js file and cached candidate/organization images from our app server. When we have enough traffic to warrant a $600/month Cloudfront service we can explore it again then. Feel free to close this Issue unless there is anything else to discuss here.

**Comment by josephevans** [comment]
Thanks Dale. I'll setup a build process that can run on our admin VM, then we can pull the generated files from it for the production VMs behind the load balancer.

**Comment by nf071590** [comment]
Re-opening the issue. There is no solution that has been communicated yet or working in production.

**Comment by DaleMcGrew** [comment]
I think we decided to not use a We Vote CDN at this point. (We will use public CDNs for the public libraries, but serve up the bundle-vxx.js and other assets from our app server cluster.)

**Comment by nf071590** [comment]
Oh, so we're doing the same thing that we were doing before and not changing the workflow?

We can give Joe an npm script that will build and serve files.

**Comment by josephevans** [comment]
I am already using the "NODE_ENV=production gulp build" command to build the static files. These then get sync'd to the backend servers, eliminating the need to serve the files up with npm. This is already working on production now.

**Comment by nf071590** [comment]
npm doesn't serve files express did and you only used `npm run prod` previously to run `NODE_ENV=production gulp`. `npm run prod` runs scripts for you. https://docs.npmjs.com/misc/scripts

**Comment by nf071590** [comment]
Check out that link so you know what's going on!

**Comment by josephevans** [comment]
I understand what's going on -- but there's no need to run express or anything to serve up files that are not changing per-request.

Previously, HTTP requests would come in to the ElasticLoadBalancer which would forward the request to nginx instances running on the back-end servers. Then nginx would proxy the request to express. I eliminated this step so that nginx can serve up the static files directly instead of proxying the request.

**Comment by nf071590** [comment]
I get that. Use npm to build the files instead of calling gulp directly.

**Comment by josephevans** [comment]
Ok, so what npm command should I use to do a build?

**Comment by nf071590** [comment]
You write one.
