### ISSUE TITLE
Push to empty empty object locks up iPhone 5s in cordova

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2390]
https://stackoverflow.com/questions/5129544/javascript-arrays-braces-vs-brackets

[Error] TypeError: positionListFromAdvisersFollowedByVoter[candidateId].push is not a function. (In 'positionListFromAdvisersFollowedByVoter[candidateId].push(one)', 'positionListFromAdvisersFollowedByVoter[candidateId].push' is undefined)
CandidateStore L 254

I would prefer not to make the change, since it would take for ever to know how to test it.

**Comment by SailingSteve** [comment]
<img width="1478" alt="Screen Shot 2019-06-25 at 11 46 51 AM" src="https://user-images.githubusercontent.com/6923653/60124669-05598f00-973f-11e9-80c1-8acd78091d6c.png">

That first error is a known issue, we can't put fixed paths to images in css and expect them to work in Cordova.  I haven't found where the image is not appearing, so maybe not a big problem.

**Comment by DaleMcGrew** [comment]
I believe I have fixed this.
