### ISSUE TITLE
Ballot List: Candidate name and support/oppose drop below photo

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#24]
1. Go to http://localhost:3000/ballot and make sure you see candidates
2. Shrink the browser width down to mobile size so the navigation is along the bottom of the screen
3. The Candidate name and "1 support  1 oppose" text is dropping below the photo, and should be to the right of the photo and candidate name (like it is in desktop mode)
![screen shot 2016-02-13 at 6 17 06 am](https://cloud.githubusercontent.com/assets/7756031/13028098/7080966e-d219-11e5-990d-8d308481bb95.png)

(Tested in Chrome)

**Comment by pertrai1** [comment]
Check pull request #25

**Comment by pertrai1** [comment]
merged #25
