### ISSUE TITLE
Choosing an old Voter Guide:  Performance and functionality issues

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2402]
When I choose my voter guide from from the settings menu, the app locks up until the "You have 318 positions..." dialog appears.  My current address is 94612.  When I click Ballot, I go to an election from Pennsylvania.  

On Cordova, the lock up goes on longer, and various events time out.  Occasionally resulting in an app hang.  Old voter guides is probably a rarely used feature, for other than developers, so probably not a show stopper.

<img width="1544" alt="Screen Shot 2019-06-28 at 5 54 16 PM" src="https://user-images.githubusercontent.com/6923653/60377790-6ba81100-99ce-11e9-82f5-4f3b55804980.png">
<img width="1544" alt="Screen Shot 2019-06-28 at 5 54 32 PM" src="https://user-images.githubusercontent.com/6923653/60377792-6ea30180-99ce-11e9-94ce-815f39fd3ef5.png">

**Comment by DaleMcGrew** [comment]
I will be rearchitecting the way we deal with this to optimize. Archiving for Later.
