### ISSUE TITLE
ValuesList Follow Toggle is Leaving "Follow" Artifact

### ISSUE THREAD

**Issue by ffrancetic** [wevote/WebApp#2430]
### Please describe the issue (What happens? What do you expect?)
On the initial load, the follow toggles don't work properly. When selecting Follow or Unfollow the Follow/Unfollow button stays fixed and does not disappear.
### Steps to reproduce the problem (1, 2, 3...), including links
When navigating to the /values/list page from the candidate page:

<img width="706" alt="Screenshot 2019-07-18 at 10 29 09" src="https://user-images.githubusercontent.com/36188818/61478738-07ca9580-a947-11e9-8995-795956749fa8.png">

The follow toggle is clicked and if the user wants to unfollow or follow the button stays fixed and does not disappear properly.

<img width="797" alt="Screenshot 2019-07-09 at 12 53 41" src="https://user-images.githubusercontent.com/36188818/60918627-a4ef4500-a248-11e9-97b6-f0045ee97b68.png">

Link: http://localhost:3000/values/list

Note: When refreshing the whole page the toggles work fine.

**Comment by jarodpeachey** [comment]
@ffrancetic What browser etc, are you using? I can't duplicate the issue on Chrome using Windows. Could you attach a GIF clip with the problem?

**Comment by ffrancetic** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/36188818/61482564-cab6d100-a94f-11e9-8f6c-adfd04187a80.gif)
This is on Chrome. Make sure you are not refreshing anything. And you can't start off on the values/list page, it must be from another page just like in the video.

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey I am still seeing this issue in the latest version.

**Comment by DaleMcGrew** [comment]
I fixed this and verified it.
