### ISSUE TITLE
Candidate page when reached via "your voter guides" needs a "back to" or menus

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2436]
Then needs a header sizing fix in Cordova and "Mobile"  There is also no consistent way to navigate away.

![IMG_1172](https://user-images.githubusercontent.com/6923653/61343437-984b8d80-a802-11e9-9c47-cea0aeaa2029.PNG)

**Comment by SailingSteve** [comment]
<img width="461" alt="Screen Shot 2019-07-16 at 7 48 53 PM" src="https://user-images.githubusercontent.com/6923653/61343514-d8127500-a802-11e9-8b93-ffaff3a71fed.png">

**Comment by DaleMcGrew** [comment]
Resolved!
