### ISSUE TITLE
Selenium AWS Instance

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#245]
@josephevans Can you set up Selenium grid on AWS so that we can start doing some automation testing? Let me know if you have done this before. The setup of selenium and the automation tests I can handle and add to the CI process, just need an instance of Selenium that can be started anytime there is an automation process that is started.

**Comment by josephevans** [comment]
I have not setup Selenium before, but it shouldn't be hard.

**Comment by josephevans** [comment]
@pertrai1 We just want a headless Selenium instance, correct? Do these installation instructions seem OK to use? 

https://christopher.su/2015/selenium-chromedriver-ubuntu/

**Comment by josephevans** [comment]
I installed Selenium on our admin VM - emailed instructions to Rob on how to get to it.
