### ISSUE TITLE
Expanding tags on candidate page has no function when tags are not overflowing

### ISSUE THREAD

**Issue by flurmbo** [wevote/WebApp#2456]
### Please describe the issue (What happens? What do you expect?)

On a candidate's page, there is a list of tags beneath the candidate's name. There is a three dotted button that expands these tags when they would otherwise overflow their container. However, the button is still present even when the tags do not overflow the container, making the button useless. See the gif below for a clear demonstration of this.

![expandingissuesbug](https://user-images.githubusercontent.com/35127144/61972228-accc1a80-afa6-11e9-8109-5d05613a6bbc.gif)

**Comment by DaleMcGrew** [comment]
Resolved! Thank you @flurmbo and @lazorfuzz.
