### ISSUE TITLE
When ballot does not appear, link to set address is not clearly hyperlinked

### ISSUE THREAD

**Issue by flurmbo** [wevote/WebApp#2471]
### Please describe the issue (What happens? What do you expect?)
A span with the id of "ballotIfBallotDoesNotAppear" is colored black, which means people won't necessarily realize it's a hyperlink.
### Steps to reproduce the problem (1, 2, 3...), including links
1) Not sure how to consistently reproduce it. Under some circumstances the ballot will not load and ask for the user to input an address, when that happens you should see something like this:

![Screenshot from 2019-08-07 12-52-36](https://user-images.githubusercontent.com/35127144/62646139-3a96f680-b913-11e9-9469-ccae519bd8ac.png)

**Comment by DaleMcGrew** [comment]
Verified. Thank you @flurmbo!
