### ISSUE TITLE
Payment Process: Confirmation Screen

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2476]
We already have this modal (Desktop) WebApp/src/js/components/Settings/PaidAccountUpgradeModal.jsx:
![Screen Shot 2019-07-24 at 2 08 31 PM](https://user-images.githubusercontent.com/7756031/61828897-98f4ad00-ae1c-11e9-972c-28fa38212c2c.png)

We want to format the final step, after Stripe payment processed (Desktop):
<img width="533" alt="Screen Shot 2019-07-24 at 2 05 54 PM" src="https://user-images.githubusercontent.com/7756031/61828722-356a7f80-ae1c-11e9-9621-a0554ad2c07d.png">

This is the mobile design:
![UpgradeToPro_Confirm_Mobile2](https://user-images.githubusercontent.com/7756031/61830663-9005da80-ae20-11e9-9a61-da7f5b8dc72b.png)

**Comment by jarodpeachey** [comment]
@SailingSteve @DaleMcGrew Is this ready for me to work on yet without causing merge conflicts in the paymentProcessModal.jsx file?

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, I'm really glad you asked. I'm in the middle of hooking that file up to the coupon API, so it might be better to wait until I'm done to work on this issue.

**Comment by jarodpeachey** [comment]
Ok, no problem! Are there any other issues you would like me to start on?

**Comment by DaleMcGrew** [comment]
Hi Jarod, in order to work on this Issue, go into this file:
WebApp/src/js/components/Settings/PaidAccountUpgradeModal.jsx
...and change line 71 to `paymentProcessed` instead of `choosePlan`:
```paidAccountProcessStep: 'paymentProcessed'```
You will then be able to work on the case block starting on line 936.

**Comment by DaleMcGrew** [comment]
It looks great. Thank you @jarodpeachey!
