### ISSUE TITLE
Settings-Sharing Screen: Upgrade modal keeps reappearing

### ISSUE THREAD

**Issue by lazorfuzz** [wevote/WebApp#2484]
### Please describe the issue (What happens? What do you expect?)
When I hit the "Upgrade to Premium" button and then X out of the modal, the modal keeps reappearing when I scroll or navigate to another page.
### Steps to reproduce the problem (1, 2, 3...), including links
* Go to /settings/sharing
* Hit the "Upgrade to Premium" button
* X out of the modal
* Scroll down

**Comment by DaleMcGrew** [comment]
Hi @lazorfuzz I have fixed this -- I thought I checked in the fix, but I might not have. I'll be checking in within the next couple of hours.
