### ISSUE TITLE
Organization subscriptions implementation

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2488]
See:    
* [We Vote Organization Subscriptions Implementation](https://docs.google.com/document/d/1cAIoODsTkOyaILV-8JmjIMCYyTrfwyDdImvQlgfZfN8/edit?usp=sharing)
* [Design Brief: Paid Subscription Plans, July 2019](https://docs.google.com/document/d/1oPA7ykoYFIoiI9sMwHT3UKrjrEIOq6M3HhZ4rxIZ5cw/mobilebasic)
 * [Payment Process: Add payment choice and Stripe processing #2451](#2451)

Basics:
- [x] Intermediate checkin ASAP python and js
- [x] Auto create a 25OFF row if it does not exist
- [x] Finish off the happy path organization subscription creation
- [x] Add filtering on the js side to exclude donation subscriptions display in history, opposite for the donation history page.

Stripe:
- [x] Need to verify that the charge goes through (it is not currently)
- [x] Make sure that we use the defaults if no coupon_code is passed in
- [x] When the charge payment comes back, associate it with the plan.  (Email in to Stripe support 8/20 and 8/22/19).  An ugly solution is possible by scraping the receipt url.

Postgres:
- [x] Monthly payment of $120 is $10 per month, so if we don't want to have to rely on using the  Plan Type Enum to determine monthly price, we would need a column to say $10.

Server Admin UI:
- [x] Display organization plans, initially without filtering.  Start with one Django template page.
- [x] Create new organization plans, start off with clone option, edit save
- [ ] Don't allow administrators to delete a plan instance that is in use by an organization.
- [ ] For any plan instance, show which organization is subscribed to it.
- [ ] Pop-up for editing the features bitmap
- [ ] Add a column to the /organization_plans/plan_list/ that shows how many active payment plans are associated with each coupon instance.
- [ ] Options to upgrade an organization on an existing plan to a newer instance of the coupon.
- [ ] Add code to prevent the  coupon from being used after the expire date/time

Others:
- [ ] Support (all through the stripe stack) for annual payments (assume that they auto renew)
- [ ] Support for payments outside of stripe
- [ ] We can be notified when credit cards are close to expiration, what should we do with this info?
- [ ] Steve's early work records both the voter id, for the guy with the credit card, and the organization ID for the beneficiary of the subscription.  At some point we want to support a consultant, setting up accounts for multiple organizations.

**Comment by DaleMcGrew** [comment]
More review and testing of this is needed, but for now I am marking this as Archive for Later.
