### ISSUE TITLE
Create beautiful "card" to display on Facebook when a We Vote page is shared to Facebook

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#249]
Facebook sharing now works. Add the open-graph meta tags to each page so that the snippet photo and title is customized depending on the url that the user wants to share.
- [ ] In WebApp/src/index.html fill in the "og:url" with the site url from /src/js/config.js WE_VOTE_HOSTNAME
- [ ] Make the URL that is shared "https://WE_VOTE_HOSTNAME/CANDIDATE_TWITTER_HANDLE"
- [ ] Make the the photo of the candidate be the photo that is shared.
- [ ] Change the sharing title to "We Vote - CANDIDATE_NAME"
- [ ] Add the twitter description text (from the candidate) underneath the title in the Facebook sharing box (the title that currently says "We Vote")
- [ ] Is it possible to prepopulate the "Say something about this..." box with this text? "Find out who supports or opposes CANDIDATE_NAME on We Vote."

**Comment by pertrai1** [comment]
@lisamcho @DaleMcGrew I have experience in working with the FB meta tags if you need me to tackle this.

**Comment by lisamcho** [comment]
@pertrai1 Sounds great, thanks for tackling this one.

**Comment by pertrai1** [comment]
@lisamcho - I am not confident that I will have time to get this done with some of the release stories I have at work going on right now. Going to have to pass this back to you.

**Comment by lisamcho** [comment]
OK, ditto, I'm not confident I'll have time either, lol. Put back in milestone B)? @DaleMcGrew

**Comment by DaleMcGrew** [comment]
That works for me.

**Comment by pertrai1** [comment]
@DaleMcGrew @lisamcho - Using https://github.com/nfl/react-helmet I think the level of effort would be slightly high taking into effect the learning of how to use react-helmet and how to use it efficiently in the application.

**Comment by lisamcho** [comment]
@pertrai1 That looks great

**Comment by lisamcho** [comment]
I looked at the react-helmet repo. It looks like a good way to manage the head so that we can dynamically set FB markup. Per the example in the react-helmet repo, we need to dynamically render the  html document (including head) on the server side. More specifically, I think we need to change our server.js to render the <head> with interpolated data from this component and also render the router component with routes there. Maybe @nf071590 wants to take a stab at this one?

**Comment by DaleMcGrew** [comment]
Thank you @lisamcho. @josephevans & @nf071590 are we dynamically serving up the index page, or is it pre-rendered and served from the NGNX load balancer? Would the three of you be open to scheduling some time (perhaps this or next Saturday morning) to discuss?

**Comment by josephevans** [comment]
We are serving up a static version of the file with nginx -- there is no running instance of node/npm/server.js to do this. Is there any alternative methods of getting the required data instead of having to dynamically generate the default index page?

**Comment by lisamcho** [comment]
I can't find any alternatives but open to suggestions. See the example on https://github.com/nfl/react-helmet

**Comment by DaleMcGrew** [comment]
We are now using Helmet, so we can implement this.

**Comment by nf071590** [comment]
Helmet is great!

**Comment by DaleMcGrew** [comment]
I agree @nf071590! It has been awesome to work with.

**Comment by DaleMcGrew** [comment]
Closing this issue since we will be developing Facebook cards as part of some new sharing features.
