### ISSUE TITLE
Facebook share measure??

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#250]
So we currently have the share button on both candidates and measures.
Sharing on a candidate can be sharing a link to that candidate detail page.
We don't have any measure detail page currently, so not sure what we should be "sharing" for measures....just wevote.me? @DaleMcGrew

**Comment by DaleMcGrew** [comment]
We will have a measure page soon, but for now you can share the ballot page with the we_vote_id as an anchor tag down to the measure.
