### ISSUE TITLE
Candidate Card: Choose/Oppose Buttons overlap each other

### ISSUE THREAD

**Issue by jarodpeachey** [wevote/WebApp#2502]
### Please describe the issue (What happens? What do you expect?)
When you hover on the candidate cards, the choose/oppose buttons are shown. However, the buttons are overlapping with each other. This might be from the Material UI v4 upgrade.
### Steps to reproduce the problem (1, 2, 3...), including links

![WeVoteIssue-82119](https://user-images.githubusercontent.com/46693952/63444422-9332bd00-c404-11e9-9d73-5540c4da9855.gif)

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, I broke this. I had to upgrade that component and accidentally updated it in a way that broke this. It might be faster if I fix it since I know exactly what happened.

**Comment by DaleMcGrew** [comment]
Fixed!
