### ISSUE TITLE
Settings Analytics (mobile): input box border covers placeholder text

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2520]
In mobile mode only (works fine in desktop), the placeholder text is blocked by the border line when you are typing text in the input box.

![Screen Shot 2019-08-30 at 1 26 58 PM](https://user-images.githubusercontent.com/7756031/64049673-72681700-cb2a-11e9-9e01-a63b00b266dc.png)

**Comment by jarodpeachey** [comment]
@DaleMcGrew I can't seem to replicate this issue. I'm using the Chrome dev tools and I've set it to simulate all phones, but everything seems to be working fine.

**Comment by DaleMcGrew** [comment]
Thank you @jarodpeachey, I did a hard refresh, and the problem has gone away. Thank you for taking a look at this!
