### ISSUE TITLE
Style google-autocomplete results in change address dialog

### ISSUE THREAD

**Issue by flurmbo** [wevote/WebApp#2550]
### Please describe the issue (What happens? What do you expect?)

Now that we can see the Google autocomplete results (see issue #2545), it looks like the results need to be styled better, mainly by fixing the length of the container to match the input.
 
### Steps to reproduce the problem (1, 2, 3...), including links

Click on "Address and Elections" and start typing an address. See screenshot.

![](https://user-images.githubusercontent.com/35127144/65362540-60c7db80-dbcd-11e9-9e68-06a8bb125832.png)

**Comment by DaleMcGrew** [comment]
This change looks great! Issue resolved.
