### ISSUE TITLE
Missing logo shows "c"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2558]
https://quality.wevote.us/candidate/wv02cand56771/b/btdo/

![Screen Shot 2019-09-28 at 12 30 41 PM](https://user-images.githubusercontent.com/7756031/65821543-cdedf900-e1eb-11e9-8eff-4915ecffbae7.png)

**Comment by flurmbo** [comment]
@DaleMcGrew, It looks like the PositionItem component is referencing `<glyph>` tags inside the file `src/sass/base/fonts/app-fonts.svg`. Looks like the `<glyph>` tag is deprecated and no longer supported by browsers, which may be why we're seeing this now.

I think we could use [this icon](https://github.com/wevote/WebApp/blob/develop/src/img/global/svg-icons/organization-icon.svg) for organizations and perhaps [this icon](https://github.com/wevote/WebApp/blob/develop/src/img/global/svg-icons/avatar-generic.svg) for individuals (there is a similar issue when the PositionItem is for an individual)

**Comment by DaleMcGrew** [comment]
Good detective work! Yes, your proposed solution, and the icons you identified, look good.

**Comment by DaleMcGrew** [comment]
Beautiful work @flurmbo. This fix is now on the live site!
