### ISSUE TITLE
Prefix [Bootstrap] classes

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#259]
Since we are currently using Bootstrap but will also be using custom utility classes (along with everything else), let's prefix all Bootstrap classes for clarity, and namespace other classes, as appropriate. (This may just be a stopgap if we eventually move to more encapsulated styles, but it still seems helpful.)

**Does anyone know of a good package or tool to prefix classes** by path? We only need something to rename premade classes like with Bootstrap.

Examples:
`tb-*` for all Bootstrap classes
`u-*` for custom utility classes
`track-*`, or `analytics-*` if class names get used as hooks for event tracking
`[component-name]` for all components or reusable elements (BEM naming) - not a prefix, but consistent naming convention

**Comment by DaleMcGrew** [comment]
@pertrai1 do you have any thoughts about this?

**Comment by pertrai1** [comment]
@ixley @DaleMcGrew - There is some good ideas behind what Jeff is proposing. I would like to take the approach that I have taken since Harry Roberts gave the presentation [CSS for Software Engineers](https://speakerdeck.com/csswizardry/css-for-software-engineers-for-css-developers). This will come to discussion once the new UX is brought into the fold.

**Comment by ixley** [comment]
@pertrai1 Yep - I am definitely on board with most of the conventions Harry Roberts is a proponent of certainly of keeping things DRY. I probably even read one of his posts suggesting namespacing classes a while back. There are a few new techniques I need to wrap my head around in terms of how styling can be done more efficiently with React (especially abstraction that's less dependent on naming), but in the meantime, I figure we should keep our styling clean, organized, and commented. That will at least make it easier to continue refactoring as we move forward.

**Comment by pertrai1** [comment]
@ixley That sounds great to me. It seems like you have a great handle on this which leads me to defer to you on the presentational layer decisions. Any help that you need I will be of assistance.

**Comment by ixley** [comment]
I just wasn't sure what an appropriate tool might be – especially still being relatively unfamiliar with React. Basically, I just want something that will auto prefix all class selectors within the bootstrap directory – I assume there has to be a simple package out there that does just this. Any suggestions @pertrai1 or @nf071590?

**Comment by ixley** [comment]
Looks like [gulp-class-prefix](https://www.npmjs.com/package/gulp-class-prefix) will work. I realized that even though there is a local copy of Bootstrap in the repo, the app is using a CDN hosted version, so I will address this as a chore when I'm able to get to it.
