### ISSUE TITLE
Cordova iPhone 5 does not proceed past the third welcome page -- Hangs

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2597]
Locks up on /WeVoteCordova.app/www/index.html#/wevoteintro/network
No problem on the iPhone 6

![Simulator Screen Shot - iPhone 5s - 2019-10-23 at 15 21 03](https://user-images.githubusercontent.com/6923653/67438678-fda0de80-f5a8-11e9-9397-347b4e28eaed.png)

**Comment by SailingSteve** [comment]
This is matched correctly after the UUID elimination from my previous checkin...

`2019-10-24 10:50:26.323 WeVoteCordova[63094:8852561] Cordova:  Matched ------------ iPhone 5, 5c, 5s, SE (4") by pbakondyScreenSize`

**Comment by DaleMcGrew** [comment]
Verified
