### ISSUE TITLE
Cordova 4" iPhone 5S, styling issues due to very small screen

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2600]
<img width="504" alt="Screen Shot 2019-10-23 at 8 20 31 PM" src="https://user-images.githubusercontent.com/6923653/67450601-c34c3700-f5d2-11e9-961b-90e897d852eb.png">

**Comment by SailingSteve** [comment]
Ivy Lee's name

<img width="504" alt="Screen Shot 2019-10-24 at 10 33 20 AM" src="https://user-images.githubusercontent.com/6923653/67510433-ca625c00-f649-11e9-84b5-f7566bd2b2d3.png">

**Comment by SailingSteve** [comment]
Long office name on a small screen
<img width="504" alt="Screen Shot 2019-10-24 at 10 34 41 AM" src="https://user-images.githubusercontent.com/6923653/67510485-e7972a80-f649-11e9-9a9f-045cd6c2b498.png">

**Comment by SailingSteve** [comment]
This was the result of a quick pass through, I suspect there are more.  This screen is very small.

**Comment by DaleMcGrew** [comment]
I did some work on this and verified it.
