### ISSUE TITLE
Update Candidate Card component JSX (markup + functionality)

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#266]
Update the Candidate Card markup and functionality in line with the updated design. 

*I'm proposing updating the JSX first because that is my biggest stumbling block. I've created an outline for the markup with styling in mind. If we update with styling in mind, but leave most of it until after the jsx is updated, I can potentially help with it as well. I'm open to other approaches too – this breakdown of tasks just seemed slightly more efficient to me.*

The designs can be referenced here: https://projects.invisionapp.com/boards/9V1ROYSQ6SKB3/
And here is the markup outline: (feel free to adjust as appropriate)
```haml
.candidate-card
  %img.candidate-card__photo{src: "https://placekitten.com/80"}
  %if(position selected)
    .support-icon // [support/oppose]
  .twitter-count
    129K
  .candidate-card__content
    %h2.candidate-card__name
      %a(Link to candidate page)
        Roque "Rocky" De La Fuente
    %button.bookmark-btn
    %p.candidate-card__candidacy
      %if(party association)
        %span.candidate-card__political-party
          // [Political Party Association for race]
          Democratic
        candidate for
      %else
        Candidate for
      %span.candidate-card__office
    %p.candidate-card__description
      // 'Twitter' bio - truncate to two lines ~60 characters with 'read more' link
      Wife, mom, grandma, women+kids advocate, FLOTUS, Senator,…
    // chunk  
    .network-positions
      .network-positions__support
        .network-positions__support-icon ↑
        .network-positions__count
          6 
          %span Support
      .network-positions__bar
        .network-positions__bar--majority.network-positions__bar--support 
          // support/oppose - pseudo content label: "Positions in your network"
          88% Oppose // Majority position as percentage (include 'mixed orgs'?)
      .network-positions__oppose
        .network-positions__oppose-icon ↓
        .network-positions__count
          45
          %span Oppose
  // chunk
  .candidate-card-actions
    // support/oppose buttons separate, then collapsed as combo button after selection
    %button.support-btn Support
    %button.oppose-btn Oppose
    %button.position-btn--[supported/opposed]
      %a Remove position // reset position to unselected
    %button.comment-btn Comment // hidden on mobile until user selects position
    %button.share-btn Share
    
// chunk
%if(position selected OR comment button clicked)
  .user-comment.user-comment--no-comment
    %img.user-comment__avatar
    .user-comment__text-field
      Why you [support] [Roque De La Fuente]...
  %if(comment)
    .user-comment.user-comment--comment-added
      %img.user-comment__avatar
      %a.user-content__name
      %p [comment]
      %a Edit
      %a Remove
      %span [Timestamp]

**Comment by ixley** [comment]
@DaleMcGrew mentioned that @pertrai1 offered to take this

**Comment by pertrai1** [comment]
@ixley - I can take this on or I can get on a Hangout with you and mentor you through the process of working with JSX/React. 

CC - @DaleMcGrew

**Comment by pertrai1** [comment]
@ixley One more thing ... if you don't want to go through the Hangout process, just go ahead and assign the issue to me.

**Comment by ixley** [comment]
@pertrai1 I appreciate the offer but it probably depends on how long you think it would take to pair through it as opposed to just going solo. I will be available tonight from about 6–8pm PT (working from Code for SF) if you're around tonight. In general, though, my availability is limited and sporadic, so I just figured it would probably be more efficient for you to tackle that part of it, and then I can at least learn a little by reviewing your edits.

*_I don't seem to have the ability to label or assign issues_ CC @DaleMcGrew

**Comment by pertrai1** [comment]
@DaleMcGrew I have started to make these changes and I am having issue getting candidates to load on localhost. When I go to `http://localhost:3003/ballot` I only get the spinner and never loads the candidates.

**Comment by DaleMcGrew** [comment]
Hi Rob, I have seen this problem,  but have not had a chance to reproduce it and store it as an issue.  If you delete your voter_device_id  cookie, you will be able to see your ballot again.

**Comment by pertrai1** [comment]
perfect. thanks Dale.

**Comment by pertrai1** [comment]
Lol. I thought it was perfect, but even after I delete the cookie, it is bringing it back every time I reload.

**Comment by DaleMcGrew** [comment]
Maybe try re-saving the address  to reload the ballot instead of refreshing the browser? This is a frustrating bug!

**Comment by pertrai1** [comment]
Final part of this conversation here. When I clear the cookie, stop gulp, start gulp, and then try to change my address, it will not let me change the address to try to get a new id

**Comment by pertrai1** [comment]
@DaleMcGrew   Actually this might be the final part of the conversation since we are here. When i look at the cookie, the expire date is `9999-12-31T23:59:59.000Z` where as the others are in the likes of `2018-05-19T06:41:29.000Z`. Is the date of the cookie expire date a possible cause of the issue?

**Comment by DaleMcGrew** [comment]
Yes, this is a problem. I'm investigating. While unrelated to the problem we are seeing now, also note that Chrome has an issue where it will create a path specific voter_device_id cookie if you are using "localhost". This problem goes away if you use an IP address instead (ex/ "127.0.0.1"), and the "localhost" + Chrome problem doesn't seem to have a solution according to the internet.

**Comment by DaleMcGrew** [comment]
Hi Rob, I updated the cookie expiration year to 2200 instead of 9999. This seems to solve the problem and is in Pull Request #267.

**Comment by ixley** [comment]
Hey Rob - Dale mentioned that you might be a little slammed with other work right now so I wanted to check in to see whether you want to hand this off. Lisa might be a bit more available so just let me know what you guys think.

@pertrai1 @DaleMcrew @lisamcho
