### ISSUE TITLE
Twitter handle links not routing on 2nd click

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#269]
This relates to code in Pull Request #268.
1. Search for "TODO TwitterHandle" 
2. Uncomment the line below this and comment out the 2nd line below this
3. Click on a candidate link like https://wevote.me/BernieSanders (this works) 
4. Now click on an organization on his page like https://wevote.me/NumbersUSA
The second click does not change the display, although the url in the address bar changes.
5. Refresh the page, and the organization link will work. But if you then try to click on a candidate page, the link will not work.
There seems to be a routing problem.

**Comment by DaleMcGrew** [comment]
Hi @nf071590 as our resident routing expert, can you think of any way around this problem? I wonder if what is displayed doesn't change because we are actually remaining on this route?: /src/js/routes/NotFound.jsx 
Do you know what code we could add to this page that would refresh the data displayed?

**Comment by pertrai1** [comment]
@DaleMcGrew If I can get figured out what the issue is with data not being retrieved on my local I can help get to the bottom of this bug.

**Comment by DaleMcGrew** [comment]
@pertrai1 thank you. I think we just need to re-render the page when the Twitter handle changes.

**Comment by DaleMcGrew** [comment]
Maybe try http://127.0.0.1:3000 instead of http://localhost:3000 ?

**Comment by pertrai1** [comment]
I will give that a shot tonight and give feedback on result

**Comment by DaleMcGrew** [comment]
Also, running on localhost in Chrome, there is a browser bug where the voter_device_id cookie will get created on the root AND a folder path, so you might have to delete two voter_device_id cookies.
