### ISSUE TITLE
Not Saving Full Address 

### ISSUE THREAD

**Issue by poonamsharma9** [wevote/WebApp#2694]
### Steps to reproduce the problem (1, 2, 3...), including links
1. Signed out on MAC desktop.
2. Go to the ballot page.
3. Click on address and elections in the header.
4. Type the start of address in the address and election input box."Ex/ Redmon"
5. You should see the auto address complete, select the remaining address using down arrow key. 
6. Hit enter on keyboard.Address should be saved.Modal will be closed.
7. Click on address and elections in the header.

Result:-
Expected:- The full address should be saved .Example- Redmond ,WA ,USA
Actual :- Not showing the full address.Example- Redmon

**Comment by DaleMcGrew** [comment]
Archived for later because we are adjusting the interface to prevent this problem.
