### ISSUE TITLE
On Candidate page, following org does not immediately add rating on same page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#270]
1. Go to https://wevote.me/nancypelosi
2. Follow the Sierra Club.
3. The "Follow/Ignore" option disappears from the page (which is correct)
4. The positive/negative counter should instantaneously update, and the rating should appear below the Candidate card.
5. If you refresh the page, the positive/negative counter and the rating show up correctly. This issue is about getting the rating to appear, and the positive/negative count to change immediately upon clicking a "Follow" button.

**Comment by lisamcho** [comment]
One way of doing this would be to re-fetch the counts when you click support/oppose.
Another way would be to keep it local, but the endpoint would need to be updated to show whether the org is support or opposing the candidate.
I am also thinking that the position should show whether the org supports or opposes the candidate right? In which case you'd need to update the endpoint anyway. @DaleMcGrew

**Comment by DaleMcGrew** [comment]
I would love it if you could refetch the counts for a particular Candidate when an org is followed from the list below the candidate.

You are right, on the Candidate page, the orgs/positions under "More Opinions About CANDIDATE" that you can Follow or Ignore, should show support/oppose/rating.

Am I correct that you are saying we should update http://localhost:8000/apis/v1/docs/voterGuidesToFollowRetrieve/ to return the support/oppose information, so that we could copy one organization's position data directly into the list of positions that are followed, which currently is retrieved from scratch with http://localhost:8000/apis/v1/docs/positionListForBallotItem/ ?

**Comment by lisamcho** [comment]
@dale, we currently don't have that information. Yes, we need to change voterGuidesToFollowRetrieve. I think that positionListForBallotItem already has the information.

If we have this information, then we don't need to refetch the counts, we just need to update the info locally I think.

**Comment by DaleMcGrew** [comment]
Awesome -- I'll update voterGuidesToFollowRetrieve. Thank you.

**Comment by DaleMcGrew** [comment]
The API server now provides support/oppose and rating info in the endpoint voterGuidesToFollowRetrieve, and that data is brought into /src/js/components/VoterGuide/Organization in Pull Request #274

**Comment by DaleMcGrew** [comment]
Hi @lisamcho 'Following' an organization on a candidate page is updating the rating count on the position bar (which is good), but the position description disappears from the page after 'Following'. When you Follow an organization it should not disappear. The organization should still disappear when you click the "Ignore" button.

**Comment by lisamcho** [comment]
So we are changing both the OpinionsToFollowPage as well as this?

**Comment by DaleMcGrew** [comment]
It would be good to change the OpinionsToFollowPage as well, but is less important for this milestone.

**Comment by lisamcho** [comment]
Should be fixed with #301

**Comment by DaleMcGrew** [comment]
Awesome!!! I really like how this is working now. Great work @lisamcho.
