### ISSUE TITLE
Abandoned WebApp javascript files

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2700]
Output from UnusedWebpackPlugin, manually confirmed.
 
   • js/components/Ballot/EmailBallotModal.jsx   (confirmed)
    • js/components/Ballot/EmailBallotToFriendsModal.jsx  (confirmed)
    • js/components/Ballot/FacebookBallotModal.jsx  (confirmed)
    • js/components/Ballot/FacebookBallotToFriendsModal.jsx  (confirmed)
    • js/components/Ballot/OrganizationFollowToggle.jsx  (confirmed)
    • js/components/Ballot/SelectAddressModal.jsx  (confirmed)
    • js/components/Facebook/FacebookDisconnect.jsx  (confirmed)
    • js/components/Facebook/FacebookLogout.jsx (confirmed)
    • js/components/Friends/AddFriendsByEmailBulk.jsx (confirmed)
    • js/components/Friends/FriendInvitationProcessedDisplayForList.jsx (confirmed)
    • js/components/Friends/FriendInvitationProcessedList.jsx  (confirmed)
    • js/components/Intro/IntroNetworkScore.jsx (confirmed)
    • js/components/Navigation/BallotLocationButton.jsx (confirmed)
    • js/components/Navigation/BallotLocationChoices.jsx (confirmed)
    • js/components/Navigation/HeaderBarAboutMenu.jsx (confirmed)
    • js/components/Navigation/SecondaryNavBarItem.jsx (confirmed)
    • js/components/Network/FriendDisplayForListCompressed.jsx  (confirmed)
    • js/components/Network/FriendListCompressed.jsx (confirmed)
    • js/components/Network/NetworkFriendRequests.jsx (confirmed)
    • js/components/Network/NetworkFriends.jsx (confirmed)
    • js/components/Network/NetworkIssuesToFollow.jsx (confirmed)
    • js/components/Network/NetworkOpinions.jsx   (possibly)
    • js/components/Search/SearchAllBox.jsx (confirmed)
    • js/components/Settings/VoterGuideSettingsGeneral.jsx (confirmed)
    • js/components/Settings/VoterGuideSettingsPositions.jsx (confirmed)
    • js/components/Settings/VoterGuideSettingsSuggestedBallotItems.jsx (confirmed)
    • js/components/Settings/security.html  (maybe save)
    • js/components/Values/IssueFollowToggleSquare.jsx (confirmed)
    • js/components/VoterGuide/ChooseElectionForVoterGuide.jsx (confirmed)
    • js/components/Widgets/OrganizationsToDisplay.jsx (confirmed)
    • js/components/Widgets/TestimonialCompany.jsx (confirmed)
    • js/dispatcher/FacebookDispatcher.js (confirmed)
    • js/dispatcher/RequestDispatcher.js  (probably)
    • js/routes/IssuesFollowed.jsx (confirmed)
    • js/routes/IssuesToFollow.jsx  (confirmed)
    • js/routes/Network.jsx (confirmed)
    • js/stores/AnalyticsStore.js (confirmed)
    • js/stores/VoterSessionStore.js (confirmed)
    • js/utils/createStore.js (probably)
    • js/utils/getElementPosition.js (confirmed)
    • js/utils/object-utils.js (confirmed)
    • js/utils/promise-utils.js  (confirmed)
    • js/utils/showToast.js (confirmed)
    • js/utils/stringOccurs.js  (confirmed)

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, out of curiosity, did you use an automated tool to figure out which components aren't being currently used? (I've been wondering if there is such a tool.)
PS. I will go through these files to double-check them and then delete them.

**Comment by SailingSteve** [comment]
@DaleMcGrew I'll check in UnusedWebpackPlugin after I do some more testing.

**Comment by DaleMcGrew** [comment]
Deleted:
   • js/components/Ballot/EmailBallotModal.jsx   (confirmed)
    • js/components/Ballot/EmailBallotToFriendsModal.jsx  (confirmed)
    • js/components/Ballot/FacebookBallotModal.jsx  (confirmed)
    • js/components/Ballot/FacebookBallotToFriendsModal.jsx  (confirmed)
    • js/components/Ballot/OrganizationFollowToggle.jsx  (confirmed)
    • js/components/Ballot/SelectAddressModal.jsx  (confirmed)
    • js/components/Friends/FriendInvitationProcessedDisplayForList.jsx (confirmed)
    • js/components/Friends/FriendInvitationProcessedList.jsx  (confirmed)
    • js/components/Intro/IntroNetworkScore.jsx (confirmed)
    • js/components/Navigation/BallotLocationButton.jsx (confirmed)
    • js/components/Navigation/BallotLocationChoices.jsx (confirmed)
    • js/components/Navigation/HeaderBarAboutMenu.jsx (confirmed)
    • js/components/Navigation/SecondaryNavBarItem.jsx (confirmed)
    • js/components/Network/FriendDisplayForListCompressed.jsx  (confirmed)
    • js/components/Network/FriendListCompressed.jsx (confirmed)
    • js/components/Network/NetworkFriendRequests.jsx (confirmed)
    • js/components/Network/NetworkFriends.jsx (confirmed)
    • js/components/Network/NetworkIssuesToFollow.jsx (confirmed)
    • js/components/Network/NetworkOpinions.jsx   (possibly)
    • js/components/Search/SearchAllBox.jsx (confirmed)
    • js/components/Settings/VoterGuideSettingsGeneral.jsx (confirmed)
    • js/components/Settings/VoterGuideSettingsPositions.jsx (confirmed)
    • js/components/Settings/VoterGuideSettingsSuggestedBallotItems.jsx (confirmed)
    • js/components/Values/IssueFollowToggleSquare.jsx (confirmed)
    • js/components/VoterGuide/ChooseElectionForVoterGuide.jsx (confirmed)
    • js/components/Widgets/OrganizationsToDisplay.jsx (confirmed)
    • js/dispatcher/FacebookDispatcher.js (confirmed)
    • js/routes/IssuesFollowed.jsx (confirmed)
    • js/routes/IssuesToFollow.jsx  (confirmed)
    • js/routes/Network.jsx (confirmed)
    • js/utils/createStore.js (probably)
    • js/utils/getElementPosition.js (confirmed)
    • js/utils/object-utils.js (confirmed)
    • js/utils/showToast.js (confirmed)

Not Deleted: 
    • js/components/Facebook/FacebookDisconnect.jsx  (confirmed)
    • js/components/Facebook/FacebookLogout.jsx (confirmed)
    • js/components/Friends/AddFriendsByEmailBulk.jsx (confirmed)
    • js/components/Settings/security.html  (maybe save)
    • js/components/Widgets/TestimonialCompany.jsx (confirmed)
    • js/dispatcher/RequestDispatcher.js  (probably)
    • js/stores/AnalyticsStore.js (confirmed)
    • js/stores/VoterSessionStore.js (confirmed)
    • js/utils/promise-utils.js  (confirmed)

Was Already Deleted:
    • js/utils/stringOccurs.js  (confirmed)
