### ISSUE TITLE
Your Endorsements: Edit and Preview Buttons in listing

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2719]
On this page (in desktop): http://localhost:3000/settings/voterguidelist
![Screen Shot 2020-01-01 at 9 47 45 PM](https://user-images.githubusercontent.com/7756031/71653276-74143800-2ce0-11ea-852e-da2feb9279c2.png)

You will need to be signed in to work on this page.

Update the listing of each election where the text currently says "US 2020 Presidential Primary":
<img width="516" alt="Screen Shot 2020-01-01 at 9 54 38 PM" src="https://user-images.githubusercontent.com/7756031/71653455-54314400-2ce1-11ea-854c-25b1975a302f.png">

**Comment by jarodpeachey** [comment]
@DaleMcGrew Does this need to show that card for each item? (One for the US 2020 Primary, one for the 2018 Midterms, etc;
)

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, yes a Card with the Edit and Preview buttons will be displayed for each election in the "Your Endorsements" list.

**Comment by DaleMcGrew** [comment]
Verified!
