### ISSUE TITLE
Abbreviate Twitter follower counts

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#272]
Let's abbreviate Twitter follower counts like Twitter does. Basically, aim for the count to not go beyond 4 characters (excluding commas/decimals). The exact count can be kept – perhaps for 'title' to show on hover if it seems useful.

< 10,000 - add commas (5,035)
10,000 – 99,999 - round to one decimal place (45.8K)
100,000 – 999,999 - round to nearest thousand (847K)
1,000,000 – ?? - round to ten-thousand (1.45M)

**Comment by lisamcho** [comment]
Hmmm, anyone know any good libraries that will take care of this for us? @DaleMcGrew @pertrai1 @nf071590

**Comment by pertrai1** [comment]
@lisamcho @ixley @DaleMcGrew 
```
function nFormatter(num) {
     if (num >= 1000000000) {
        return (num / 1000000000).toFixed(1).replace(/\.0$/, '') + 'G';
     }
     if (num >= 1000000) {
        return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
     }
     if (num >= 1000) {
        return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
     }
     return num;
}
```

`nFormatter(2500)` => 2.5k

**Comment by ixley** [comment]
Awesome - thanks @pertrai1. I'll make some adjustments and attempt to add this.
