### ISSUE TITLE
Show position in OrganizationPositionItem just like PositionItem

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#278]
Add position info to OrganizationPositionItem. Currently, it shows a rating without a timestamped year, but it doesn't show explicit positions. Show full position info with the same logic as in PositionItem.jsx. 

Bonus points if you can put the code for .explicit-position in a component (like PositionRatingSnippet) and modularize the whole thing.

**Comment by DaleMcGrew** [comment]
@ixley please verify fix once pull request #288 is approved.

**Comment by ixley** [comment]
I haven't been able to check this because nothing is showing up with explicit positions (only ratings). Were you seeing thumbed positions when you tested this?
