### ISSUE TITLE
Add org position to unfollowed orgs on Candidate page

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#279]
Currently, unfollowed orgs with positions on a candidate will show up below followed orgs on the candidate page, but without their positions. Show positions for unfollowed orgs too, beneath their twitter bio. (organization.jsx)

@DaleMcGrew can you confirm this is what you want?

**Comment by DaleMcGrew** [comment]
That is correct. It is helpful to see an organization's opinions about a
candidate before you follow it. The variables with the is_support /
is_positive _rating etc are already in the Organization Jsx card /
component, ready to style.

-Dale

On Monday, May 23, 2016, Jeff French <notifications@github.com> wrote:

> Currently, unfollowed orgs with positions on a candidate will show up
> below followed orgs on the candidate page, but without their positions.
> Show positions for unfollowed orgs too, beneath their twitter bio.
>
> @DaleMcGrew <https://github.com/DaleMcGrew> can you confirm this is what
> you want?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/wevote/WebApp/issues/279>
>


-- 

Dale John McGrew
Co-founder, We Vote USA
dale.mcgrew@wevoteusa.org
www.WeVoteUSA.org <http://wevoteusa.org/>
415-516-8777
Twitter: @WeVoteUSA <https://twitter.com/WeVoteUSA> & @DaleMcGrew
<https://twitter.com/dalemcgrew>
Protecting the interests of voters. Fueled by passion.

**Comment by DaleMcGrew** [comment]
@ixley you should be able to drop in this code now:
          { vote_smart_rating ?
          <PositionRatingSnippet {...position} /> :
              <PositionSupportOpposeSnippet {...position} /> }
I am about to lose internet connection or else I would do it!

**Comment by ixley** [comment]
I reordered the condition to be
```
{ position.is_support || position.is_oppose ?
    <PositionSupportOpposeSnippet {...position} /> :
    <PositionRatingSnippet {...position} />
}
```
but it doesn't seem like it's quite working because everything is currently showing up as ratings (I can't find any explicit positions). It's hard for me to check because I wasn't seeing many explicit positions before, but the ones I checked are all ratings now.

**Comment by DaleMcGrew** [comment]
I created an organization called "We Vote Test Organization": http://localhost:3000/wevoteusa In the election 4209 (California June 7th), I added various support/oppose entries, including Duf Sundheim for US Senate, and Willie Wilson for Democrat for President.

**Comment by lisamcho** [comment]
looks good!
