### ISSUE TITLE
PROCESS: Discuss procedure for approving pull requests

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#28]
Rob's proposal: If a pull request gets 2 thumbs up - it can be merged

**Comment by pertrai1** [comment]
@nf071590 @lisamcho If you agree or disagree with this process, share your thoughts on moving forward.

**Comment by pertrai1** [comment]
Approved

**Comment by DaleMcGrew** [comment]
I think requiring only one Admin to approve a pull request is enough. It would be ideal if we can have code reviews not hold up the acceptance of a pull request, but encourage code reviews. I think it would be to discuss this after version 1.0.

**Comment by lisamcho** [comment]
Hey,

I have some code for the candidate page, but I am confused about the git
process. Are the guidelines on Contributing.md now ok to use or should I
continue doing it the old way (push to a new branch, then pull request)?

Thanks!

**Comment by DaleMcGrew** [comment]
Hi Lisa, we have not completed the transition to the new process, so you
are welcome to push to a new branch and then do a pull request.

Thank you!

-Dale


Dale John McGrew
Co-founder, We Vote USA
dale.mcgrew@wevoteusa.org
www.WeVoteUSA.org <http://wevoteusa.org/>
415-516-8777
Twitter: @WeVoteUSA <https://twitter.com/WeVoteUSA>

**Comment by pertrai1** [comment]
@DaleMcGrew @lisamcho @nf071590 - The company I work for it closed today because of weather conditions here in VA. If you want to have a hangout to learn more about the branching techniques for Git, let me know and we can set one up.

**Comment by lisamcho** [comment]
Thanks Rob! I could really use help with git. Today is probably not going
to work for me, are you also free tomorrow by chance?
