### ISSUE TITLE
Turn off Appveyor github test for now?

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#281]
Hi @pertrai1 I notice that this 'Appveyor' test fails quite often, and we ignore it's failure. What do you think about removing this test from our build process until we are going to respond to it failing?

continuous-integration/appveyor/pr

**Comment by pertrai1** [comment]
@DaleMcGrew This has been done.

**Comment by pertrai1** [comment]
Here is the commit [7d1ef5aa](https://github.com/wevote/WebApp/commit/e7e2964f611fe3c8d94aca99795588f97d1ef5aa)

**Comment by DaleMcGrew** [comment]
Thank you Rob!
