### ISSUE TITLE
"Sierra Club Endorsement" for Chrome Extension (iFrame)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2837]
From our Chrome Extension, we need to be able to show a candidate within an iframe, so that a voter can choose or oppose the candidate. A "stub" file has been created. Please update this component to have a second tab "Organization Endorsement":
src/js/routes/Ballot/CandidateForExtension.jsx

This is related to "Your Opinion" Issue: https://github.com/wevote/WebApp/issues/2825

This is the path to this component: http://localhost:3000/candidate-for-extension

Note: the modal header and close modal in these images are generated by the Chrome Extension.
SIERRA CLUB ENDORSEMENT - Some styles will change:
![Screen Shot 2020-03-13 at 11 14 52 AM](https://user-images.githubusercontent.com/7756031/76648594-3a4f8100-651c-11ea-869a-d018afa2cd22.png)

We already have components to capture endorsements that will need to be modified, but can act as a starting point. Please create a rough draft that can then be discussed, and updated with new Action and Store methods. Signed in, please see this route and start an endorsement for one election:
https://localhost:3000/settings/voterguidelist

It will look something like this:
![Screen Shot 2020-03-13 at 11 30 04 AM](https://user-images.githubusercontent.com/7756031/76649520-11c88680-651e-11ea-9827-02cc20384a62.png)

These are the components to copy:
src/js/components/Settings/BallotItemForAddPositions.jsx
...and "<OfficeItemForAddPositions"
...and "<CandidateItemForAddPositions"

The first tab, shown as "Your Opinion" will be implemented in this other Issue: https://github.com/wevote/WebApp/issues/2825

**Comment by SailingSteve** [comment]
@DaleMcGrew 
At the very least the candidate name field has to be editable, because sometimes it's not possible to select the exact letters you need.

**Comment by SailingSteve** [comment]
<img width="438" alt="Screen Shot 2020-03-14 at 11 03 38 AM" src="https://user-images.githubusercontent.com/6923653/76687710-b95bbc80-65e3-11ea-99ba-8d0e88e3b6a8.png">
This is what the stub page looks like, with the data that it receives, when displayed in the extension.

**Comment by jarodpeachey** [comment]
@DaleMcGrew Where to I grab the data for the endorsement/organization? Is that passed as a URL parameter?

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, because we are storing these opinions into our "VoterGuidePossibility" system, which hasn't been done yet in the WebApp, you can just get the interface in place, and then I will wire up the data flow.

If you need an organizationWeVoteId to hard code for display purposes, you can use this one for Sierra Club: wv02org1061

I think you already have this, but this is a URL you can use to get the candidate data: https://localhost:3000/candidate-for-extension?candidate_name=Phil%20Ting&candidate_we_vote_id=wv02cand40131&endorsement_page_url=https%3A%2F%2Fwww.sierraclub.org%2Fcalifornia%2F2020-endorsements&candidate_home_page=https%3A%2F%2Fwww.philting.com%2F

PS. I'm available on Slack if you want to discuss via screen share.

**Comment by DaleMcGrew** [comment]
This is now in good shape, and ready for @SailingSteve. Thank you @jarodpeachey!
