### ISSUE TITLE
Add source attribution (name and link) for (explicit) positions

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#284]
Add a source attribution for explicit positions by orgs (similar to how ratings are attributed to Vote Smart) when available. List name and link to url.

**Comment by DaleMcGrew** [comment]
Added in pull request #288. @ixley please verify fix.

**Comment by ixley** [comment]
okay, I see the endorsement and source info on http://localhost:3000/progressivekick now, but still almost no others. Are there any other orgs to look for explicit positions with?

**Comment by DaleMcGrew** [comment]
@ixley we haven't entered very much data with explicit positions yet -- I'll keep adding more so we have more examples tonight. After the June 7th election I can write an importer to pull in explicit positions from Vote Smart.

**Comment by ixley** [comment]
Ok sounds good. Mostly just asking to verify things are working and showing
up as intended.
