### ISSUE TITLE
Open Overlay Panel when viewing candidate on organization page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2845]
I'm not sure whether to make this a modal or some other form of Material UI slide-out panel. We might make it a Modal for mobile, and a slide out panel for Desktop/Tablet.

From this page:
1. Please navigate to the US 2018 Midterm Election (Nov 6, 2018)
2. Go to the Sierra Club voter guide: https://localhost:3000/sierraclub/positions
![Screen Shot 2020-03-15 at 7 59 36 AM](https://user-images.githubusercontent.com/7756031/76704211-9e955080-6694-11ea-95ba-0a67d99fd3ad.png)

...when you click a candidate, please open an overlay like this (please ignore the page underneath the overlay in this image):
<img width="888" alt="Screen Shot 2020-03-15 at 8 13 45 AM" src="https://user-images.githubusercontent.com/7756031/76704264-fe8bf700-6694-11ea-9a1d-8b254b35dc17.png">

We will handle adding the candidate information in a subsequent Issue.

**Comment by jarodpeachey** [comment]
@DaleMcGrew I'll take this issue. I was thinking I could use the Drawer component for mobile, just like the ballot share button. I'll use a Drawer for desktop as well, but it will slide out from the right.
