### ISSUE TITLE
Error with voter_device_id

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#29]
When loading the root url, I get error logged to console:

Uncaught (in promise) Object {voter_device_id: "tAPbsZ8RlToFeproGtair2P6yW41scZDizoQbwpVt9vLXQjwGIRj3PtNcWZoymQEVSOOI5XEAgyZ9vbZiMngOSLu"}.

Tracing back it seems to be a problem with this code in service.js:
res.body.status is undefined, so it errors out.

return new Promise(function (resolve, reject) {
    return request.get(opts.WE_VOTE_SERVER_API_ROOT_URL).accept(opts.dataType).query(opts.query).withCredentials().end(function (err, res) {
      if (err || !res.body.status) {
        if (opts.error instanceof Function === true) {
          opts.error(err || res.body);

**Comment by pertrai1** [comment]
@nf071590 Do you have any suggestions about this issue?

@lisamcho If you have any code to change this to work, please do so and when the pull request is there we can code review

**Comment by nf071590** [comment]
Hey Lisa, I'll be working on this today. Dale is going to modify the
endpoints also to deal with some of this logic. We don't get a success =
true back which is why it throws and error.

**Comment by pertrai1** [comment]
@nf071590 will take this one and work with @DaleMcGrew

**Comment by DaleMcGrew** [comment]
As soon as Issue #46 is completed, we should be able to verify that this issue is fixed.

**Comment by DaleMcGrew** [comment]
Given the latest code in the develop branch, I was not able to reproduce this bug. I think it is fixed.
