### ISSUE TITLE
Loading Data Local Not Loading

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#291]
I am not able to get data to display locally. Pulled latest from dev branch. 

![we_vote](https://cloud.githubusercontent.com/assets/442374/15629093/f6dc785a-24de-11e6-9d0d-7694c7d1dffb.jpg)

**Comment by lisamcho** [comment]
@DaleMcGrew @pertrai1 This is weird. I pulled the latest down too. I can get my 'choices remaining' and 'ballot' pages to load, but bookmarks won't load no matter what. That was working fine before.

**Comment by DaleMcGrew** [comment]
I'm looking at the "What I Have Bookmarked" problem.

To get "All Ballot Items" page to work, try deleting your voter_device_id cookie and then save a new ballot address like "Charlotte, NC 28205". We need to occasionally delete cookies manually (there are a few cases where the voter_device_id becomes invalidated on the API server, but the browser still thinks the voter_device_id cookie is valid) until we fix issue #237.
