### ISSUE TITLE
candidate-for-extension margin problem causes "jiggle"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2926]
When you visit any "candidate-for-extension" page, there is a problem with the margins that causes the page to "jiggle" when it is loading. I believe that if you can get rid of the margins that are outside of the visible page, the scroll bars and the "jiggle" will go away.

https://quality.wevote.us/candidate-for-extension?candidate_we_vote_id=wv02cand55927

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve would you consider this resolved? (I know that https://quality.wevote.us has this code, but I'm not 100% sure https://wevote.us has this code on it)

**Comment by SailingSteve** [comment]
Looks great on quality.  So yes, it is resolved.
Thanks,
Steve
