### ISSUE TITLE
About Page, Mobile: Add "Show More" after first two people under board and staff

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#2935]
In mobile mode (not in desktop), on the About page:
http://localhost:3000/more/about

Only show the first two board members, and the first two staff. Follow each by a "Show More" link that shows the rest in that section.

![Screen Shot 2020-04-25 at 11 09 58 AM](https://user-images.githubusercontent.com/7756031/80287241-5b8fb980-86e5-11ea-8835-28066c37c294.png)

**Comment by DaleMcGrew** [comment]
Hi @jarodpeachey, if you haven't started this, may I free this issue up so one of the other engineers can tackle it?

**Comment by jarodpeachey** [comment]
@DaleMcGrew Yeah, that's fine.

**Comment by DaleMcGrew** [comment]
Verified!
