### ISSUE TITLE
Prefixed Bootstrap classes makes it more difficult to use Bootstrap related tools

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#294]
I recently added a task to prefix all Bootstrap classes (https://github.com/wevote/WebApp/pull/289) for better maintainability. My thinking was that because we are mixing a variety of custom component and utility classes along with vendor utility classes (like Bootstrap), that it's best to have them clearly scoped and identifiable. 

The downside, that I only realized more fully after the fact, is that third-party tools (like React-Bootstrap) assume default Bootstrap class names to work (since the assumption is that you wouldn't modify vendor specified naming). There is some customization that is possible, but more complex components might not work. Ultimately, I don't think we want to rely too heavily on layers of Bootstrap reliant tools, but acknowledging that they can be useful, I wanted to get weigh-in on whether this is a reasonable trade-off. If we decide it's not, I can roll back the prefixing and just try to prefix all custom components and utility classes for reasonable contrast. 

Thoughts?

**Comment by DaleMcGrew** [comment]
Adding a custom prefix, which requires us to host our own version of the Bootstrap classes in a We Vote specific CDN, also means that we don't get the benefit of the caching of the Bootstrap file from a visit to another website that uses the default, used-by-many-sites, Bootstrap CDN. There are many trade offs to weigh though. I don't have strong feelings either way.

**Comment by ixley** [comment]
I dismissed the front-end caching as a relevant concern for right now. The bootstrap file is still separate and not something we would edit often, so ultimately it's a small file that can still get cached. 

Does anyone else have strong feelings or thoughts on how much we might want to rely on the Bootstrap ecosystem in the near future? There is a relatively clear (even if limited) value to me with prefixing classes, but if Bootstrap plugins are important enough to justify avoiding prefixing, I want to be pragmatic. @pertrai1 @nf071590

**Comment by pertrai1** [comment]
If you feel that you have a good system being put in place for handling bootstrap then I would not worry about the cache.

**Comment by ixley** [comment]
@pertrai1 Yeah, I'm not worried about caching. My concern was about not being able to use other Bootstrap related tools that depend on its (unmodified) classes. React-Bootstrap is one where I realized I could accommodate simple adjustments (like for buttons), but that other components like drop-down menu/buttons wouldn't be feasible anymore. 

So my question is, how important do we think these Bootstrap-dependent tools are going forward?

**Comment by pertrai1** [comment]
@ixley It all depends. If there are not many of them that are going to be used, take the module, clone it, and make your version of it that accommodates this app. Now that npm has it where you can do private npm, you can use it just like any other. Might be the best route to go if you want to have full control over the React components you have.

**Comment by ixley** [comment]
Cloning a module and customizing it feels more overwhelming to me (mostly because I assume it means more manual maintenance). I am okay with customizing Bootstrap (via an automated task) but if we want to use many other BS dependent tools I would rather just roll back my prefixing than further customize everything. 

My question was mainly whether others here had strong opinions or thoughts about a reliance on or intention to use Bootstrap related tools, or a trade-off like this, in general.

**Comment by pertrai1** [comment]
I do not have a strong opinion on the subject

**Comment by pertrai1** [comment]
@ixley At this time I believe that Dale and We Vote will be looking for you to be the driving force for the UI decision making. If there is something up in the air you are not sure about or ideas you want to bounce around, that is something I am happy to assist with. You take it from here. Looks like you are doing an amazing job.

This can probably be closed now.

CC: @DaleMcGrew @nf071590

**Comment by ixley** [comment]
@pertrai1 Well thanks for the input and vote of confidence. I'll try to embrace that and just expect you and others to be vocal if you see something you think is questionable or disagree with. I will still probably continue to look for input with things like this but will try to not let it hold me up.

**Comment by DaleMcGrew** [comment]
You don't have to worry about this group not being vocal. ;)  I really appreciate all of the experience and passion you bring to We Vote Jeff!
