### ISSUE TITLE
get support/oppose dropdown working

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#297]
We should change the 'remove position' link on itemactionbar to a dropdown per Jeff's design.
@ixley Are you working on this one? Wasn't sure if you need help with jsx stuff or are just using an existing opensource dropdown component.

**Comment by ixley** [comment]
I have tried a couple different component plugins but without success. React Bootstrap would've worked except for the prefixing I added (for bootstrap classes) so if I roll those changes back OR customize the package to be compatible that could still work. It _seems_ like simple enough functionality that ideally I could write something custom with a basic state change but I just haven't had the time to attempt that and it's still a bit over my head. Soooo.. If you have time @lisamcho, go for it. I will try to take a crack tomorrow but can't guarantee any success...

**Comment by lisamcho** [comment]
Done! see #302
