### ISSUE TITLE
Disappearance of Organization Recommendations 

### ISSUE THREAD

**Issue by 4D617278** [wevote/WebApp#2970]
### Please describe the issue (What happens? What do you expect?)
Organization Recommendations disappear after clicking the follow button on the One Plus 6T. The behavior on the desktop is to maintain the position of the organization recommendation.
### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to url http://localhost:3000/
2. Scroll to the organizations section
3. Click follow button of an organization

https://automate.browserstack.com/dashboard/v2/builds/0548c46ecef6931e0ca11a0de2af3d52d4451f6a/sessions/9c6c081b6101602a17c6c00189f25da2e411baee

**Comment by DaleMcGrew** [comment]
@4D617278 could you please verify that this is fixed now?

**Comment by 4D617278** [comment]
I think the correct behavior is to have the organization recommendations disappear, so this is not an issue.
