### ISSUE TITLE
Sign In with SMS hangs if voter is already signed in, in another way

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#2993]
If you are already signed in via some other sign in method, sign in with SMS hangs -- the SMS comes in on my phone, but there is now way to enter it. Since the phone number entry dialog has not been removed.
<img width="1163" alt="Screen Shot 2020-06-03 at 8 48 46 AM" src="https://user-images.githubusercontent.com/6923653/83658580-3f4e2a80-a577-11ea-9dab-9383b9fafff7.png">

**Comment by DaleMcGrew** [comment]
Verified!
