### ISSUE TITLE
Ballot Candidate Page, Create & Style

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3]
This is the page you click through to when you click on a Candidate's name from the Ballot list.
src/js/routes/Ballot/Candidate.jsx
- [x] Add Organization placeholder icon, web_app/assets/fonts/icon-org-placeholder-6_2.svg
- [x] If the organization has a logo (as displayed on the "More Opinions" or "Opinions I Follow" pages), show that instead of the placeholder.
- [x] Comment out the link on the "Organization Name TEMP" line for now. We will turn that link back on after we complete Version 1.
- [x] Comment out the link on the candidate's name for now. We will turn that link back on after we complete Version 1.
- [x] Please create (or find) Javascript date formatting function that takes "2016-02-20 23:31:56.859465+00:00" and converts it to dates like: Yesterday at 3:15PM OR 2 days ago OR 6 months ago
- [x] Add the candidate name to the right of Supports or Opposes: "Supports Marco Rubio"
- [x] Please double-check the Support / Oppose logic is correct in the Javascript layer. Currently on my dev machine the number supporting Marco Rubio for example ("2 support") doesn't match the number of orgs listed that support him. NOTE: This may be an API issue.
![screen shot 2016-02-22 at 9 14 25 am](https://cloud.githubusercontent.com/assets/7756031/13226124/beacbe94-d944-11e5-8c46-5a156a2dc2f0.png)

**Comment by DaleMcGrew** [comment]
I am reopening since we are still working on building out this page. Lisa is checking in another version.

**Comment by lisamcho** [comment]
I think this is resolved, correct? Close out?

**Comment by DaleMcGrew** [comment]
Hi @lisamcho I'd like to leave this issue open until the page is totally ready for the deadline. It looks great -- you did awesome work. Do you want to keep working on a few items on this page before I start making tweaks? I will add specific check-marked items that need attention in the Issue description.

**Comment by lisamcho** [comment]
Sure. go ahead and add issues and I will take a look. I know the candidate
page is missing the long blurb of text describing each person. I don't
actually know where in the API that can be found.

**Comment by DaleMcGrew** [comment]
The description of each candidate will be coming from Ballotpedia and Wikipedia, but our scraper isn't ready yet for prime time.

**Comment by lisamcho** [comment]
What should I do about the timestamp? Right now it's dummy text "Yesterday at 2:18pm" Should that actually be the 'last_updated' field of positionRetrieve? It's hard to tell right now because that field always returns empty string with the data in the db right now.

**Comment by DaleMcGrew** [comment]
Yes, it should be the last updated field. I will look into why it's returning  an empty value.

**Comment by lisamcho** [comment]
Question for team - Given a list of positions which contain the organization we_vote_id, I need the logo photo url for each organization. This information is in the organizationRetrieve API. I am currently storing the positions in the PositionStore. The easiest to implement solution would be to call the organizationRetrieve from within the PositionStore, and save the url as an attribute of each position.
However, the drawback with that is that the same organizations may have positions on many candidates, and if I go with the above solution, we may unnecessarily fetch the same organizations multiple times when you visit different candidate pages (which have different positions).

So maybe it makes more sense to create an Organization Store that stores details of each organization, and simply retrieves the url from that store based on organization we_vote_id (or fetches it from API if not already fetched).

Alternately, it seems as if VoterGuideStore is also fetching a list of organizations, so I don't want to duplicate logic. VoterGuideStore is already large and complicated, so it may be bad design to try to make it also fetch the organizations for the Position List.

**Comment by pertrai1** [comment]
@lisamcho If all of the logic is stored in one place, I believe that it should be broken apart so that we keep the single responsibility and have the modules as small as possible.

**Comment by DaleMcGrew** [comment]
Hi Lisa, organizations are pretty tightly coupled with voter guides, so I would recommend using VoterGuideStore, specifically the getOrganizationByWeVoteId method. If the "More Opinions" page hasn't been visited by the time you are listing positions, you could call VoterGuideStore.initialize when you need organization logos. Happy Friday!

**Comment by pertrai1** [comment]
@DaleMcGrew why would the organizations be tightly coupled with guides? Should we not have organization, voter, guides, etc. that stand alone and don't have to know anything about each other?

**Comment by lisamcho** [comment]
getOrganizationByWeVoteId method only returns the org if it's already fetched. Do I really want to fetch all the organizations on the CandidateDetail page if they're not already loaded? VoterGuideStore also has no way of retrieving just one Organization.

**Comment by lisamcho** [comment]
How many organizations will there be total?

**Comment by DaleMcGrew** [comment]
If this method hasn't been called already, you can call VoterGuideStore.initializeGuidesFollowed and it will only retrieve the organizations that the voter is following.  There is definitely room for optimization in the coming weeks!

**Comment by pertrai1** [comment]
@DaleMcGrew Is there some type of UML that shows how all of the API's / data stores interact?

**Comment by lisamcho** [comment]
Hmmm, ok, maybe we need to discuss on Saturday. This could be a bug, but it
seems that positionListForBallot item is retrieving organizations that I
have never followed, whereas the API page says it retrieves "A list of all
positions (support/oppose/info) for this Ballot Item (Office, Candidate or
Measure) from organizations, friends, and public figures this voter
follows."  I definitely never clicked on follow Organization Name TEMP
under the Opinions page, and I definitely haven't followed 40 organizations
(the number that appears under Hilary Clinton). Is that a bug with the
backend?

**Comment by DaleMcGrew** [comment]
I noticed that glitch with Hillary Clinton too and I think that is a bug. I will look into it. For now while testing, if you first visit the "opinions I follow" page, and then look at the positions, the organizations should be populated in the voter guide store so you can display logos.

**Comment by lisamcho** [comment]
Saw the commit to add images and dates. Close this out?

**Comment by DaleMcGrew** [comment]
Would you prefer we add checkbox items that we need to iterate on, to this existing Issue, or close this issue and open new Issues? (I don't have the latest version -- its been a busy last 24 hours -- but an example of something that needs work on that page is adding template level date formatting for position.last_updated since it was in an unfriendly format.)

**Comment by lisamcho** [comment]
In terms of process, no strong preference either way. Was just checking in
to see what next highest priority item was for me to work on, now that
redirect is addressed (albeit without messages).

**Comment by pertrai1** [comment]
@DaleMcGrew @lisamcho I would accept what would have been the requirements for this issue/story and open a new one for 1.1.

**Comment by DaleMcGrew** [comment]
Thank you Lisa, you nailed it. We have a working version ready for Version 0.9.
