### ISSUE TITLE
Base shell with concept of views

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#30]
@DaleMcGrew @nf071590 - I believe that we should have a base shell for the app and only certain views will change. Get away from the concept of pages and rather think in views. For example, on the ballot you have a base shell and the only thing that happens when you go to a candidate is that the candidate list view goes to a candidate view. By doing this we are limiting the changes of the view for the user to only change what is requested from the event that the user took.

**Comment by pertrai1** [comment]
@DaleMcGrew @nf071590 - with no discussion going on with this, I am going to close and discussion can strike up again in the future.

**Comment by DaleMcGrew** [comment]
I agree with you Rob, I just suggest we hold off talking about this until we are past Version 1.0
