### ISSUE TITLE
positionListForOpinionMaker loads 20x when you go to a candidate page, and page redraws in an endless loop

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#3020]
For  /WeVoteCordova.app/www/index.html#/candidate/wv02cand59921/b/btdb"

[Log] AJAX Response to endpoint: positionListForOpinionMaker (cordova.js, line 1413)
[Log] render ==== PositionList ====  (cordova.js, line 1413)
[Log] render ==== FilterBase ====  (cordova.js, line 1413)
[Log] render ==== VoterGuideOrganizationFilter ====  (cordova.js, line 1413)
[Log] render ==== PositionItem ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413, x2)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== ReadMore ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== ReadMore ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== PositionItem ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413, x2)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== PositionItem ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413, x2)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== PositionItem ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413, x2)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)
[Log] render ==== OpenExternalWebSite ====  (cordova.js, line 1413)
[Log] render ==== PositionItem ====  (cordova.js, line 1413)
[Log] render ==== StickyPopover ====  (cordova.js, line 1413)
[Log] render ==== ImageHandler ====  (cordova.js, line 1413)

**Comment by SailingSteve** [comment]
**I also saw this for issuesFollowedRetrieve** on the ballot tab, after returning from the Security and SignIn page

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve I have totally seen this bug, but I can't seem to reproduce it (nor can @mlevoy). Could you please let us know if you see this again, and help us reproduce it?
