### ISSUE TITLE
iPhone8 does not return WEBVIEW context in ballotMainTest

### ISSUE THREAD

**Issue by 4D617278** [wevote/WebApp#3039]
### Please describe the issue (What happens? What do you expect?)
iPhone8 does not return WEBVIEW context in ballotMainTest, and iPad6 does not return WEBVIEW context when run alone using ballotMainTest
### Steps to reproduce the problem (1, 2, 3...), including links
1. Run ballotMainTest on iPhone8 with any number of devices or on iPad6 alone
2. Look for the output of getContexts() in the terminal 
Example:
[0-0] 2020-06-23T02:10:44.772Z INFO webdriver: COMMAND getContexts()
...
[0-0] 2020-06-23T02:10:45.439Z INFO webdriver: RESULT [ 'NATIVE_APP' ]
3. Observe that only NATIVE_APP is returned, and not WEBVIEW

**Comment by DaleMcGrew** [comment]
Archive for Later
