### ISSUE TITLE
Support/Oppose Incrementing/Decrementing bug

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#304]
Clicking Support, Oppose, or Remove Position rapidly excessively increments or decrements the counts. This bug was addressed previously, but it seems to have been reintroduced recently, possibly with https://github.com/wevote/WebApp/pull/302.

There is also a significant delay/lag with registering these clicks, which is not the source of the problem, but makes it more apparent.

[Screenshot with negative count!](https://www.evernote.com/shard/s15/sh/831a77c9-22fa-4218-8121-557471eec169/149530a2c891d6ac)

**Comment by lisamcho** [comment]
Should be fixed with #305

**Comment by DaleMcGrew** [comment]
Verified!
