### ISSUE TITLE
Friends tab flickers and does not display elements

### ISSUE THREAD

**Issue by 4D617278** [wevote/WebApp#3050]
### Please describe the issue (What happens? What do you expect?)
After inputting an email address and clicking the next button in the friends tab, the html elements disappear. It is expected that the html elements of the friend tab do not disappear. 
### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to https://wevote.us/friends
Under the Email of One Friend text box, enter filipfrancetic@gmail.com.
![screenshot](https://user-images.githubusercontent.com/52756433/85715112-b5ded380-b6b0-11ea-8cc3-02c338eac0af.png)

2. Click the Next Button
![screenshot](https://user-images.githubusercontent.com/52756433/85715144-becfa500-b6b0-11ea-833b-c5e41e6ecfaa.png)

3. Observe that the html elements disappear.
![screenshot](https://user-images.githubusercontent.com/52756433/85715189-ca22d080-b6b0-11ea-8523-6815e866c149.png)

**Comment by DaleMcGrew** [comment]
This has been fixed! Thank you @mlevoy.
