### ISSUE TITLE
webpackChunkName not working

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3057]
I have not been able to get dynamic imports (with webpackChunkName) to work within We Vote: https://webpack.js.org/guides/code-splitting/#dynamic-imports

My goal is to use Webpack  to create a variety for smaller bundles which only get downloaded when a voter navigates to a particular route. Currently with our setup, all bundles are being downloaded on initial load, which delays the onLoad event until all of the bundles finish downloading. I would like to build all bundles with webpack, but then only start the download of some bundles until a person tries to navigate to the page that uses that bundle (webpackPrefetch will be a bonus down the road).

It seems like there is some configuration problem in these files:
WebApp/webpack.config.js
WebApp/package.json

I created a simplified version based on the freecodecamp.org article:
https://www.freecodecamp.org/news/learn-webpack-for-react-a36d4cac5060/

Here is the branch with my attempt:
https://github.com/DaleMcGrew/WebApp/tree/dale_WebApp_FreeCodeCamp_202006

I set up webpackChunkName comments here that are not being used:
src/js/routes/App.js

The files I added to this branch:
WebApp/webpack.config.js
WebApp/package.json
src/js/simpleIndex.js
src/js/startReactApp.js
src/js/routes/App.js
src/js/routes/Home.js
src/js/routes/DynamicPage.js
src/js/routes/Loading.js
src/js/routes/NoMatch.js

**Comment by utsab** [comment]
@DaleMcGrew, is anyone working on this task? I could try to take a look.

**Comment by DaleMcGrew** [comment]
@utsab I'll warn you that this issue has stumped 4 engineers now (including myself spending over two weeks on it), so it is not for the faint of heart.

**Comment by user512** [comment]
@DaleMcGrew I can take a look, ok to assign to me?

**Comment by DaleMcGrew** [comment]
Hello @user512 I would love it if you would take a crack at this. This is also related to this issue: https://github.com/wevote/WebApp/issues/3255
I spent about two weeks looking at this, emulating a slow connection in my browser, and breaking up the bundle into 6-7 smaller chunks, and in the end every bundle had to finish downloading for the DOM to fully load. What we want is for the bundles that aren't being used on the landing page to load, but without holding anything up to do with rendering the landing page.

**Comment by DaleMcGrew** [comment]
Hi @user512, I wanted to warn you that we are poised to check in some code that will break the develop branch. This is the pull request: https://github.com/wevote/WebApp/pull/3257 and we are basically upgrading as much as we can to the newest versions. This will most likely affect the work you are doing since it is a full rework of the router. Is there anything we can do so it doesn't mess up the work you have already done?

**Comment by user512** [comment]
Don’t worry, I’m still reading webpack doc on code splitting. Feel free to merge #3257.

**Comment by DaleMcGrew** [comment]
Hello @user512, the latest code is up on the develop branch again, and most routes are working. Note that we have upgraded to react-router 5.2.0.

**Comment by DaleMcGrew** [comment]
Thank you @user512. We have found a solution. Steve was able to find a solution by creating this new test repository: https://github.com/SailingSteve/wevote-landing-page
We have taken what he learned from that, and used it to kick off our new Campaigns repo: https://github.com/wevote/Campaigns
