### ISSUE TITLE
Sign in with Apple: button too narrow (iPads from profileMainTest: ~27 seconds)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3066]
The "Sign in with Apple" button isn't the same width as the other buttons and it should be.
<img width="622" alt="Screen Shot 2020-07-07 at 8 55 38 AM" src="https://user-images.githubusercontent.com/7756031/86809355-a6587680-c030-11ea-8e50-5c9524d96b61.png">

https://app-automate.browserstack.com/dashboard/v2/builds/4eaa81b9bfceea8c914b1ee0cfd533399ca38536/sessions/ef2be04834736c6bd1780b176c6a2729189eba39

at ~27 seconds.

**Comment by SailingSteve** [comment]
<img width="856" alt="Screen Shot 2020-07-16 at 3 42 40 PM" src="https://user-images.githubusercontent.com/6923653/87729782-04950000-c77b-11ea-87ee-c0e8af84bf62.png">

**Comment by SailingSteve** [comment]
<img width="545" alt="Screen Shot 2020-08-12 at 3 50 37 PM" src="https://user-images.githubusercontent.com/6923653/90076016-96792580-dcb3-11ea-8b2b-977ecc2a76f6.png">

Sign in with Apple is gone, and Sign in with Twitter is grey again.

**Comment by SailingSteve** [comment]
Due to library limitations, WeVoteCordova for iOS will not support Sign in with Apple, or Sign in with Twitter on devices that have not (or can not) upgrade to iOS 13.  Approximately 5% of all iPhones are running an iOS version lower than v13.

On devices that are not running v!3, Sign in with Apple, or Sign in with Twitter will have their button greyed out.

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve, would it be possible to add the text "(Requires iOS13)" to the grayed out button?

**Comment by SailingSteve** [comment]
Done, but not yet checked in.

![Simulator Screen Shot - iPhone Xs (12 4) - 2020-08-13 at 10 13 09](https://user-images.githubusercontent.com/6923653/90165558-b0674680-dd4d-11ea-840c-1cccd341683e.png)

**Comment by SailingSteve** [comment]
Fixed in wevote/WebApp/pull/3136
