### ISSUE TITLE
Choose Election: showing below header (iPads from ballotMainTest, iPad: ~6 seconds)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3067]
On all of the iPads I looked at (iOS 11 and 12), this "Choose Election..." appears when the election data is loading. It should be shifted down so the header doesn't obscure it.

<img width="777" alt="Screen Shot 2020-07-07 at 9 09 35 AM" src="https://user-images.githubusercontent.com/7756031/86810298-9ee59d00-c031-11ea-8b7c-bb26ae61c62b.png">

This may also be the same offset that is causing the "How it Works" to be higher than it should.
<img width="775" alt="Screen Shot 2020-07-07 at 9 10 46 AM" src="https://user-images.githubusercontent.com/7756031/86810499-d48a8600-c031-11ea-9230-cf0c58e58aea.png">

**Comment by SailingSteve** [comment]
<img width="856" alt="Screen Shot 2020-07-16 at 3 36 45 PM" src="https://user-images.githubusercontent.com/6923653/87729539-7b7dc900-c77a-11ea-81d8-8968c2ec27c5.png">
<img width="856" alt="Screen Shot 2020-07-16 at 3 38 18 PM" src="https://user-images.githubusercontent.com/6923653/87729545-7de02300-c77a-11ea-9c64-bab29f162a98.png">
