### ISSUE TITLE
"Enter address where..." too high (iPhone XS from profileMainTest: ~14 seconds)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3068]
iPhone XS Max, iOS 12.1
<img width="473" alt="Screen Shot 2020-07-07 at 10 00 06 AM" src="https://user-images.githubusercontent.com/7756031/86816434-a8bece80-c038-11ea-8559-7b6b91c2c172.png">

At about 14 seconds:
https://app-automate.browserstack.com/dashboard/v2/builds/488d74bc977a993cf4c71e148212cff6c00fe1d1/sessions/a316b8aa0845a0944a6ccfac35aa9eae7243f7ea

**Comment by SailingSteve** [comment]
<img width="545" alt="Screen Shot 2020-07-16 at 3 18 30 PM" src="https://user-images.githubusercontent.com/6923653/87728303-a1559e80-c777-11ea-8484-d71711e2374b.png">
<img width="545" alt="Screen Shot 2020-07-16 at 3 18 22 PM" src="https://user-images.githubusercontent.com/6923653/87728304-a31f6200-c777-11ea-9045-f1a7cbb82472.png">

**Comment by SailingSteve** [comment]
Acutally the phone in the rrecording (which won't play anymore) is an iPhone Xs Max
