### ISSUE TITLE
Sign in link needs right margin (Galaxy S9 Plus from ballotMainTest: ~2:23 seconds)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3069]
Sign in link needs right margin (Galaxy S9 Plus from ballotMainTest: ~2:23 seconds)
<img width="372" alt="Screen Shot 2020-07-07 at 10 26 47 AM" src="https://user-images.githubusercontent.com/7756031/86819497-95adfd80-c03c-11ea-8e45-7c961a11291c.png">

https://app-automate.browserstack.com/dashboard/v2/builds/488d74bc977a993cf4c71e148212cff6c00fe1d1/sessions/f4b63bf560c41d76200e64eb4d8d11fcf654d00d

**Comment by SailingSteve** [comment]
Looks fine now!

<img width="877" alt="Screen Shot 2020-08-12 at 3 30 31 PM" src="https://user-images.githubusercontent.com/6923653/90074832-dd195080-dcb0-11ea-9b91-f9124e2d59f8.png">

**Comment by DaleMcGrew** [comment]
Resolved. Thank you @SailingSteve.
