### ISSUE TITLE
Footer Share button too low (Galaxy S9 Plus from ballotMainTest: ~2:23 seconds)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3070]
Footer Share button too low (Galaxy S9 Plus from ballotMainTest: ~2:23 seconds) Also seen on Google Pixel 2
On Candidate, Measure page (and I suspect the Office page)

<img width="372" alt="Screen Shot 2020-07-07 at 10 32 15 AM" src="https://user-images.githubusercontent.com/7756031/86819901-25ec4280-c03d-11ea-8adb-d0b32bd3e699.png">

https://app-automate.browserstack.com/dashboard/v2/builds/488d74bc977a993cf4c71e148212cff6c00fe1d1/sessions/f4b63bf560c41d76200e64eb4d8d11fcf654d00d

**Comment by SailingSteve** [comment]
Looks fine now!

<img width="1041" alt="Screen Shot 2020-08-12 at 3 28 06 PM" src="https://user-images.githubusercontent.com/6923653/90074614-76943280-dcb0-11ea-9d40-e2dfc9376344.png">

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, I still see this problem on any Measure page and Candidate page. The share button is perfect on the Office page.

**Comment by SailingSteve** [comment]
![Screen Shot 2020-08-18 at 4 48 26 PM](https://user-images.githubusercontent.com/6923653/90576305-ab9dfa80-e172-11ea-8a7a-8d6ab111f176.png)
Looks good to me?

**Comment by SailingSteve** [comment]
![Screen Shot 2020-08-18 at 4 49 59 PM](https://user-images.githubusercontent.com/6923653/90576373-e56f0100-e172-11ea-9ad4-9a2c959f39b2.png)

**Comment by SailingSteve** [comment]
Fixed with last night's checkin

**Comment by DaleMcGrew** [comment]
Verified. Thank you @SailingSteve!
