### ISSUE TITLE
Complete address not saved when you use Google Maps dropdown

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3082]
### Please describe the issue (What happens? What do you expect?)
If you start to type your address, the Google autocomplete widget will suggest addresses in a drop down.
![Screen Shot 2020-07-16 at 3 24 13 PM](https://user-images.githubusercontent.com/7756031/87729224-b0d5e700-c779-11ea-9a14-cd810d9e84d7.png)

If before you finish typing the full address you use the down arrow to select an address from the Google autocomplete, and then hit enter, the full address does not get saved. The partial one does.
![Screen Shot 2020-07-16 at 3 24 20 PM](https://user-images.githubusercontent.com/7756031/87729241-b8958b80-c779-11ea-8853-7d1838ff91a5.png)

### Steps to reproduce the problem (1, 2, 3...), including links
1. In desktop mode, go to Ballot page and click on the gear icon next to the election name. A modal will open.
2. Click on the gear icon next to the address that is currently saved to open the edit form.
3. Clear the address and Save.
4. Close the "Address & Elections" modal.
5. Go back to the "Ready" page and you will see an input box for "Full address and ZIP"
6. Start to type an address like "123 Main Street". When the Google Autocomplete starts to offer you an address, use the down arrow to select one, and then hit the "Enter" key on your keyboard.
It is the partial address you have typed that gets saved, instead of the full address suggested by Google auto comlete.

I found the core of this problem is in: src/js/components/Ready/EditAddressOneHorizontalRow.jsx
Related functions: _placeChanged, handleKeyPress, voterAddressSave, saveAddressToApiServer, onBallotStoreChange and these inputProps in "InputBase":
inputProps={{
  onBlur: this.saveAddressToApiServer,
  onChange: this.updateVoterAddress,
  onKeyDown: this.handleKeyPress,
}}

**Comment by utsab** [comment]
@DaleMcGrew Are you cool with me taking on this task?

**Comment by DaleMcGrew** [comment]
Yes that's fine @utsab !

**Comment by DaleMcGrew** [comment]
Verified!
