### ISSUE TITLE
Windows 10: Text in splitIconButton too low

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3093]
Windows 10: Text in splitIconButton too low
Please test on a variety of browsers and devices. (Using Browserstack account)

See src/js/components/Widgets/ViewOnBallotpedia.jsx
See src/js/components/Widgets/SearchOnGoogle.jsx

![Screen Shot 2020-07-22 at 11 10 47 AM](https://user-images.githubusercontent.com/7756031/88215241-32ad9080-cc10-11ea-80a1-9617e2e51e2d.png)

**Comment by jarodpeachey** [comment]
Hey Dale,

I can take this issue; what's the login info for the Browserstack account?

**Comment by DaleMcGrew** [comment]
Thank you @jarodpeachey. I will send you an invitation from BrowserStack. Note: We can only test with Browserstack once your changes are pushed to the quality site, but you should be able to see this bug on your local Windows machine.

**Comment by jarodpeachey** [comment]
@DaleMcGrew Sounds good. I started the site up in localhost, but I couldn't see this issue. What page is it one?

**Comment by DaleMcGrew** [comment]
Unable to reproduce.
