### ISSUE TITLE
Post Comment on Candidate Page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#310]
On a candidate’s page, offer a comment box where a voter can comment on the candidate. This comment can be saved with this API endpoint:
http://localhost:8000/apis/v1/docs/voterPositionCommentSave/
Save a voter's comment about an office, candidate or measure, to be shared with friends.
Once saved, the voter who made the comment should be able to edit and re-save the comment. Once saved, the comment should appear on the page as a position.

**Comment by pertrai1** [comment]
@DaleMcGrew Depending on how you want to set this up, I have seen rapid growth in sites using Disqus(sp?) because it allows you to post comments not only on site but also to other social media outlets. Possible implementation to consider.

**Comment by DaleMcGrew** [comment]
Done!
