### ISSUE TITLE
Icons in top navigation bar hug right side of browser

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#315]
1. Grab latest code
2. View ballot in desktop mode, with the browser window (Chrome) opened wide
3. The top 4 navigation items float over to the edge of the browser. They should only float over to the edge of the bounded We Vote content 
![screen shot 2016-06-23 at 12 11 07 pm](https://cloud.githubusercontent.com/assets/7756031/16316554/f84da35a-393b-11e6-876c-1a5bed66db5d.png)
area.

**Comment by ixley** [comment]
Hmm... I noticed this​ when I was working but thought it was gone by the
time I pushed my latest commit. I'll give it another look.

**Comment by ixley** [comment]
@DaleMcGrew Can you double check to make sure your cache is cleared? I'm not able to reproduce this.

**Comment by DaleMcGrew** [comment]
@ixley I apologize, you are correct that a full refresh of the browser gets rid of the problem. I'm sorry I didn't catch that!

**Comment by ixley** [comment]
No worries!
