### ISSUE TITLE
Update icons to Adam's new designs

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#316]
Adam has designed new icons that are ready for inclusion:
https://drive.google.com/drive/u/1/folders/0B_wLhwGZ781aQkQ0T2FpakZWdEU

Note: Design for bookmark icon is missing, but I think the one currently in use will match the new style?

**Comment by ixley** [comment]
Waiting for Adam to finalize icons - paths need to be cleaned up to minimize subpixel anti-aliasing.

**Comment by ixley** [comment]
Never received production-ready icons. Closing for now.
