### ISSUE TITLE
ActivityCommentAdd Input Box Modifications

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3175]
In order to see this code on the News page, you will need to have this set in your /src/js/config.js file:
`ENABLE_NEXT_RELEASE_FEATURES: true`

In this component `src/js/components/Activity/ActivityCommentAdd.jsx`:
![Screen Shot 2020-08-29 at 5 46 01 PM](https://user-images.githubusercontent.com/7756031/91648702-8ab19100-ea1f-11ea-83ac-c7674d5bd88a.png)

I would love these changes.
- [x] I tried to reduce the padding of `textFieldMultilineClasses` to `8.5px 8px 6.5px 8px` but couldn't figure out in the Material UI API how to pass in the changes
![Screen Shot 2020-08-29 at 5 49 37 PM](https://user-images.githubusercontent.com/7756031/91648735-0b708d00-ea20-11ea-8e75-ab3fe184135a.png)
This is from the "Elements" tab in Chrome:
![Screen Shot 2020-08-29 at 5 50 08 PM](https://user-images.githubusercontent.com/7756031/91648749-2216e400-ea20-11ea-8c87-0b2b5345f0b3.png)
- [ ] I'd love to figure out how to get the "Add your comment..." to show as placeholder text in the comment box before there is any text, and have it move up to be along the top border after you have started typing text.

**Comment by jarodpeachey** [comment]
I updated the padding using the margin="dense" to the input. However, it doesn't look like it's possible to have the placeholder text if you have an input adornment. I'll keep looking at the MUI docs

**Comment by DaleMcGrew** [comment]
Thank you @jarodpeachey. I'm available if you would like to discuss.

**Comment by jarodpeachey** [comment]
@DaleMcGrew I'm free to do a call now or at 1:15 your time in an hour and a half

**Comment by DaleMcGrew** [comment]
Verified, thank you @jarodpeachey!
