### ISSUE TITLE
Crashing Bug: Windows 10, IE 11 & Safari 

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3184]
We Vote won't load on Windows 10, IE 11:
![Screen Shot 2020-09-05 at 1 13 02 PM](https://user-images.githubusercontent.com/7756031/92312847-b7166180-ef79-11ea-9a56-eb37d15b1adb.png)

We Vote also doesn’t load on Safari on Windows 10. This is the error I’m seeing:
![Screen Shot 2020-09-05 at 1 09 12 PM](https://user-images.githubusercontent.com/7756031/92312841-a6fe8200-ef79-11ea-9ddf-8da72c904249.png)

**Comment by SailingSteve** [comment]
@DaleMcGrew I found the problem.  We have approximately 100 arrow functions in the WebApp, which will not run on IE. 

IE is not standards compliant, and is dying with maybe as much as a 5% market share.  Edge uses Chromium, so it keeps up.  Anyone still using IE, must be running into daily problems with sites that can't be rendered.

Have we had a real customer complain about IE support?

Even if we solved the arrow function problem, who knows what the next layer of the onion will be.

We should abandon IE support.  If they are running IE, I could change "Your election is loading..." to "We're sorry, we no longer support Internet Explorer."

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, thank you for working on a fix. I think you are correct that we should abandon IE, and display a different message. Could you please display this error message: "We're sorry, we no longer support Internet Explorer. We recommend Firefox, Chrome or Chromium."
