### ISSUE TITLE
Support/Oppose/Share Icons with Text instead of Buttons with Text

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#319]
Convert the visual look of the "Support", "Oppose" and "Share" buttons under a candidate to be the icon plus text similar to this image.
<img width="537" alt="screen shot 2016-06-27 at 8 53 58 am" src="https://cloud.githubusercontent.com/assets/7756031/16386218/c3a5ac4a-3c44-11e6-8269-9c19999e3469.png">
![pasted_image_6_27_16__11_38_am](https://cloud.githubusercontent.com/assets/160662/16391390/c12573a8-3c5b-11e6-92ca-74b71e9fa1d8.png)

**Comment by DaleMcGrew** [comment]
Hello @ixley what does the "ready" tag mean?

**Comment by ixley** [comment]
@DaleMcGrew I was just playing around with [Waffle.io](https://waffle.io/) and [ZenHub](https://www.zenhub.com/) to see if either would be helpful for managing issues and tasks. They both use kanban style progress tracking, and Waffle.io adds its categories as labels. 'Ready' is sort of like the queued backlog, as opposed to Icebox or new/unsorted.
