### ISSUE TITLE
Drawer that comes from Discuss/News propostion has two render bugs for phone sized screens

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#3199]
1.  position public toggle does not wrap on larger phone screen sizes and extends beyond desired column (Not a problem on iPhone SE sized screen).
2. Other elements on the screen violate the edges of the desired column, which enables bad horizontal scrolling
<img width="533" alt="Screen Shot 2020-09-13 at 10 45 21 AM" src="https://user-images.githubusercontent.com/6923653/93024871-61137080-f5ae-11ea-8a98-be1c044b24b7.png">

**Comment by Sean1783** [comment]
Looks like the UI has changed since this issue was raised. Is this issue still valid?

**Comment by SailingSteve** [comment]
No longer relevant
