### ISSUE TITLE
Warning: flattenChildren(...): Encountered two children with the same key

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#32]
1. In WebApp, visit "More Opinions" page
2. Navigate back to Ballot
3. Visit "More Opinions" page again
4. You will see these "flattenChildren" errors in the browser console log

Warning: flattenChildren(...): Encountered two children with the same key, `.$wv02vg6`. Child keys must be unique; when two children share a key, only the first child will be used.

![screen shot 2016-02-13 at 10 17 52 am](https://cloud.githubusercontent.com/assets/7756031/13029257/b731b83c-d23b-11e5-9aa8-107afa5a9020.png)

**Comment by DaleMcGrew** [comment]
Hello Raph, I was able to reproduce this bug again in the latest version in the "develop" branch.

**Comment by nf071590** [comment]
@DaleMcGrew can you check the database and verify that there aren't two entries with the same we_vote_id?

**Comment by DaleMcGrew** [comment]
@nf071590 The database enforces unique=True on the we_vote_id field in class Voter. My guess is that the way we are adding values to this variable "let _voter_guide_store = {};" (somewhere in /js/stores/VoterGuideStore.js) doesn't overwrite the prior value, like it would in a classic array, but instead tries to add another entry with the same key, leading to this error.

**Comment by DaleMcGrew** [comment]
It looks like this was resolved when this was fixed: https://github.com/wevote/WeVoteServer/issues/85
