### ISSUE TITLE
Searching for "proposition", loads the same proposition twice

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#3201]
I forgot the number, so I just typed in proposition
<img width="1626" alt="Screen Shot 2020-09-13 at 3 27 32 PM" src="https://user-images.githubusercontent.com/6923653/93030182-f6762b00-f5d5-11ea-87e8-93d21171bb88.png">

**Comment by DaleMcGrew** [comment]
This is now fixed. Thank you @SailingSteve!
