### ISSUE TITLE
"Submit Feedback" Widget

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#322]
We are showing https://wevote.me to many people. In case any people see the site and would like to submit feedback, I would like to offer a link anyone can click to "Submit Feedback". This should like to a third-party service and include these features:
- [ ] Require your email to submit feedback. We Vote should have access to the emails submitted.
- [ ] Include a website where we can view comments
- [ ] Should send notification(s) when a comment is made
- [ ] Small cost is ok

**Comment by pertrai1** [comment]
@DaleMcGrew take a look at this one: https://usersnap.com/features/feedback-widget-bug-tracking

**Comment by DaleMcGrew** [comment]
Live!
