### ISSUE TITLE
WeVote.me deployment has 3-5 minute delay

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#323]
Hi Joe, I was able to duplicate this. 
1)
Sign into AWS:
ssh dmcgrew@admin.wevote.me

2)
sudo /root/update_www_code

For about 3-5 minutes, the site https://wevote.me showed only a blue screen. The source for the page showed a bundle file with timestamp:
<script src="/js/bundle-1467380377.js"></script>

...but when I clicked on the bundle link:
https://wevote.me/js/bundle-1467380377.js
I got:
404 Not Found
nginx/1.4.6 (Ubuntu)

**Comment by josephevans** [comment]
When you run "update_www_code", this is updating the admin server with the latest code from github and then building it. This admin server is not an actual webserver -- it is just building the latest code and staging it. The backend webservers then have a cron job that runs every 5 minutes that grabs the latest code from the admin server (without having to restart any services.) 

It was setup this way to minimize work when updating the codebase. Let's say we have 20 backend web servers - we don't want to have to individually update the code on each of the 20 servers. Instead, they pull the latest code from this admin server instance automatically.

**Comment by DaleMcGrew** [comment]
Hi Joe, did you make any changes to fix the 3-5 minute downtime?

**Comment by josephevans** [comment]
There shouldn't be any downtime when updating the codebase. I am not sure why it seemed like it was down. Maybe you had a stale index.html loaded referring to the old javascript bundle that was deleted?

**Comment by DaleMcGrew** [comment]
Prior to updating the site, WeVote.me loads fine. As soon as I start the "sudo /root/update_www_code" process, I get only a blue screen when I hard-refresh WeVote.me for about 3-5 minutes.

**Comment by josephevans** [comment]
I can't duplicate this. There could potentially be a race condition when running update_www_code -- if the webserver attempts to copy the built files before they are finished, it could end up getting only the completed files. Let me think about how to avoid this.

**Comment by pertrai1** [comment]
@DaleMcGrew @josephevans Hey guys, just wanted to pipe in and see if I could be of help. It could be helpful to go the route of doing a nightly build that could be done during non-peak hours. Also, if there needs to be updates that are pushed to the production server during the day, have a static page that in put in place saying updates/upgrades are in progress(ex).

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 great to hear from you! Joe and I discussed this, and @josephevans thinks he can solve it by changing the order of how he builds and copies files into the production staging folder. The complication comes because we have a build server that prepares files that then get distributed to the Web servers that deliver these files to voters. What seems to be happening are partial builds were getting copies to the Web servers before the new builds were complete.

**Comment by josephevans** [comment]
OK, I made some changes so that we atomically sync a new build output. This will prevent the webserver from grabbing an incomplete build and displaying an error to the user.

**Comment by DaleMcGrew** [comment]
Awesome @josephevans thank you! I will verify this later today when I do another release.

**Comment by DaleMcGrew** [comment]
Verified.
