### ISSUE TITLE
5 Files - Part B: Prop spreading is forbidden

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3231]
We just upgraded to the latest version of AirBNB ESLint rules. We have quite a few files which are violating the "Prop spreading is forbidden" rule. These are the ones to work on for this Issue.

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Friends/SuggestedFriendList.jsx
  40:17  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Organization/OpinionsFollowedListCompressed.jsx
  50:95  error  Prop spreading is forbidden  react/jsx-props-no-spreading
  57:95  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Organization/OpinionsIgnoredList.jsx
  41:83  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Organization/OrganizationDisplayForList.jsx
  78:34  error  Prop spreading is forbidden  react/jsx-props-no-spreading
  80:61  error  Prop spreading is forbidden  react/jsx-props-no-spreading
  83:43  error  Prop spreading is forbidden  react/jsx-props-no-spreading

/Users/dalemcgrew/PycharmProjects/WebApp/src/js/components/Settings/SettingsAddress.jsx
  38:29  error  Prop spreading is forbidden  react/jsx-props-no-spreading

An example of what needs to be changed is in the file `/src/js/components/Connect/CurrentFriends.jsx` (Please don't work on this example -- only the files above.):
```
<FriendDisplayForList {...oneFriend} />
```
In this case, we are passing a dict `oneFriend` with several values into `FriendDisplayForList`, and relying on the `...` to break up these variables and pass them individually into `FriendDisplayForList`. Within FriendDisplayForList, we take in these props, all of which come from the `oneFriend` dict:
```
FriendDisplayForList.propTypes = {
  linked_organization_we_vote_id: PropTypes.string,
  mutual_friends: PropTypes.number,
  positions_taken: PropTypes.number,
  voter_we_vote_id: PropTypes.string,
  voter_photo_url_large: PropTypes.string,
  voter_email_address: PropTypes.string,
  voter_display_name: PropTypes.string,
  voter_twitter_handle: PropTypes.string,
};
```

What we need to do are the following steps:
1) Start with file with the root error, ex/ `CurrentFriends.jsx` (see the list at the start of this issue for the ones for you to work on)
2) Find the line with the ESLint error and identify the component we are passing the object into (ex/ `<FriendDisplayForList`).
3) Search the code base for other instances of that object.
4) Go into that component and find `.propTypes` which shows with variables are being brought into the component. Some of them will be from the incoming object (ex/ `oneFriend`), but some of them may be unrelated.
5) Convert the variables in the `propTypes` code to camel case (ex/ instead of `linked_organization_we_vote_id` change it to `linkedOrganizationWeVoteId`)
6) Add incoming variables on the component we are passing the object into. Ex:
```
<FriendDisplayForList 
  linkedOrganizationWeVoteId={oneFriend.linked_organization_we_vote_id}
  mutualFriends={oneFriend.mutual_friends}
  etc...
/>
```
7) Delete the object being "spread"/passed into the component (i.e., `oneFriend` from `<FriendDisplayForList {...oneFriend} />`)

**Comment by DaleMcGrew** [comment]
Hi @gautam-ergo I wanted to warn you that we are poised to check in some code that will break the develop branch. I will manually bring over the changes you added in your last pull request, but I wanted to warn you if you have additional work that is not in your last pull request. Could you please let me know if this will cause any problems for you?

**Comment by gautam-ergo** [comment]
Hi @DaleMcGrew please go ahead with the changes, shouldn't cause any problems for me. Please let me know if you need additional info.
