### ISSUE TITLE
Display explanation of what a Vote Smart rating means

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#324]
Throughout We Vote we have ratings that have come from Vote Smart. When someone clicks on a rating, pop up a div that explains how the rating was created. (Use one of the bootstrap popups.)

<img width="381" alt="screen shot 2016-07-01 at 10 40 46 am" src="https://cloud.githubusercontent.com/assets/7756031/16529528/4e2d920c-3f78-11e6-9149-ac027e73fc57.png">

**Comment by ixley** [comment]
@dalemcgrew Can you provide a sample of the text you'd like here?

**Comment by DaleMcGrew** [comment]
Thank you @ixley, lets start with this:
Source: VoteSmart.org
Ratings are given by the organization, and collected by the nonprofit Vote Smart. 
(down arrow icon) 0% is a low score, and (up arrow icon) 100% is a high score. 
Ratings can be invaluable in showing where an incumbent has stood on a series of votes in the past one or two years, especially when ratings by groups on all sides of an issue are compared. Some groups select votes that tend to favor members of one political party over another, rather than choosing votes based solely on issues concerns. Please visit the group's website or call 1-888-VOTESMART for more specific information.

**Comment by ixley** [comment]
@DaleMcGrew I'm not quite ready to take this - was just trying to help add some definition so it's ready to go.
This is also probably more text than is appropriate for a popover, so it's worth considering whether this would work in a modal or whether we can trim down the text a bit.

**Comment by DaleMcGrew** [comment]
Fair enough @ixley! Ideally the popover could show some of the text, but then have a way to reveal the rest. Perhaps a way to scroll down?

**Comment by ixley** [comment]
Yeah, that's reasonable to try. A technical blocker is that React-Bootstrap doesn't currently support custom prefixing for all classes, which makes it largely incompatible with the namespaced classes I prefixed. I wasn't clear how important it would be to leverage third-party Bootstrap 'plug-ins', but it's seeming like it might make sense to roll back the Bootstrap class namespacing for the time being so it's not an impediment.

**Comment by pertrai1** [comment]
Possibly a good scenario would be to have the side bar open up with the menu hidden and have the information shown about the source that would allow for the complete content to be revealed.

**Comment by ixley** [comment]
I think a popover (large ‘tooltip’) could be reasonable but the amount of
text makes it feel a bit heavy. Additionally, in the current context (each
item citing vote smart as the source), the content become redundant
quickly. It should. Be accessible, but in this case (with no varied
content) it doesn’t need to be so ‘frictionless’ that something like a
modal window wouldn’t also be reasonable.

**Comment by ixley** [comment]
Additionally, this is making me feel a bit conflicted since this story could be easily solved with a (React-)Bootstrap component, but to do that I would have to remove the namespace prefixing I added. I would also prefer not to be as reliant on the Bootstrap ecosystem, but it still has the lure of simpler implementation, absent our own set of robust custom components.

Nice to see you back around here @pertrai1 - penny for your thoughts? Attempting to adhere to certain principles vs. compromising for tools that offer simpler implementation (at least for the time being)?

**Comment by pertrai1** [comment]
I believe that the source would not be needed next to every calculation. If the source is notes in one place, that would be enough for someone to know what was the source of the calculations. I also believe that if a user was to click on the url, the intent would be that the user is expecting to go to that website.  Anything else could be not what the user expected. I believe adding a footer for less important information would help. In the footer there could be a link that would show a view that could offer the information about the data that is gathered.

**Comment by ixley** [comment]
I've been thinking about this more, and while I don't think it necessarily means we shouldn't have a brief inline explanation (tooltip, popup, or otherwise) as well, it seems more relevant to have an entire section/page to explain ratings, endorsements, how network 'scores' are constructed, and anything else related.

**Comment by DaleMcGrew** [comment]
Hi @ixley, we tried to implement a simple OverlayTrigger in WebApp/src/js/components/Widgets/PositionRatingSnippet.jsx
It didn't work, and I suspect because of our "bs-" style prefix. Can you please take a look?

**Comment by ixley** [comment]
@DaleMcGrew I'm confused - the modal and trigger appear to be working. Can you be more specific?

**Comment by DaleMcGrew** [comment]
You can see the "(source Votesmart.org)" button we tried to implement here:
https://wevote.me/candidate/wv02cand98
We couldn't get the Popover to work.

**Comment by DaleMcGrew** [comment]
@zachmonteith, Jeff is going to rollback the "bs-" bootstrap class prefix we are using. Once that is done (this weekend) hopefully we will be able to get this Popover to work.

**Comment by ixley** [comment]
I also made a PR last night to get this working. Be mindful that in one
view/route you have both that modal and the popover being triggered by the
same click.

**Comment by DaleMcGrew** [comment]
Issue resolved. Great work @zachmonteith!
