### ISSUE TITLE
Candidates appearing twice

### ISSUE THREAD

**Issue by omegabytes** [wevote/WebApp#3241]
### Please describe the issue (What happens? What do you expect?)
Some candidates are appearing twice. I noticed this when browsing "local" candidates for https://wevote.us/ballot/election/100011 (Colorado Springs).
![image](https://user-images.githubusercontent.com/5423475/95496825-3f5f9c00-0956-11eb-9311-cf684cf85911.png)

This also appears when clicking into the section (ie: https://wevote.us/office/wv02off45219/b/btdb)
![image](https://user-images.githubusercontent.com/5423475/95497179-c57be280-0956-11eb-9caf-21cc753fd0c5.png)

Other context:
- The problem persists on page refresh.
- Observed on Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
- Observed on Safari Version 13.1.1 (15609.2.9.1.2)
- I didn't check if candidate info is also being dropped (this is not my local election)
- I browsed open issues but didn't see any obviously related issues.
- I feel like I noticed this issue when using WeVote for a San Francisco election back in 2018. I can't provide any proof.

### Expected Behavior
I expect to see one or more unique candidates.

### Actual Behavior
Local candidates are duplicated. 

### Steps to reproduce the problem (1, 2, 3...), including links
- navigate to wevote, do not log in
- enter an address
- browse to the local election section (click OR scroll)
- click on the election section link, duplication persists

**Comment by DaleMcGrew** [comment]
Thank you @omegabytes for reporting this! We have deduplication tools that we will use to fix this and see if we have other candidates to dedup.

**Comment by DaleMcGrew** [comment]
We have merged these two duplicates together. Thank you again @omegabytes for pointing this out. Please let us know if you are ever interested in volunteering to help add features or fix bugs on We Vote! We are an all-volunteer team.
