### ISSUE TITLE
Clicking on Rating bar should take you through to Candidate page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#325]
When you are on the ballot page, a click anywhere on the positions bar should take you to the candidate's page.
<img width="546" alt="screen shot 2016-07-01 at 10 47 03 am" src="https://cloud.githubusercontent.com/assets/7756031/16529691/323c3f84-3f79-11e6-9aac-9e9afd6621f5.png">

**Comment by pertrai1** [comment]
@DaleMcGrew Is this not needed for the shootout? I do see Next but wanted to make sure that it is not needed for the shootout and is there just because there was no resources for this to make it into the shootout.

**Comment by DaleMcGrew** [comment]
@pertrai1 It would be ideal to have for Saturday, but is not critical.

**Comment by DaleMcGrew** [comment]
Thank you @zachmonteith, this is working very well.
