### ISSUE TITLE
Improve Performance Spring 2021

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#3273]
<img width="957" alt="Screen Shot 2021-04-12 at 4 46 59 PM" src="https://user-images.githubusercontent.com/6923653/114476323-daa82700-9bae-11eb-944b-9703ec5e3320.png">

<img width="957" alt="Screen Shot 2021-04-12 at 4 49 53 PM" src="https://user-images.githubusercontent.com/6923653/114476483-265ad080-9baf-11eb-82fa-4b32855f7f31.png">

Before

**Comment by DaleMcGrew** [comment]
Great work with these speed improvements!
