### ISSUE TITLE
Instant search results display fixes

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#328]
Instant search box code is here: /src/js/components/SearchAllBox.js

- [x] Whenever we have results for instant search, put them (search_results) in a drop-down
- [x] The search box is floating down from the top of the page. Please bring it up to be in line with the "My Voter Guide" text and header icons.
- [x] When the view area is less than 330px wide, hide the "My Voter Guide demo" text, and show the "Search We Vote" box (with the navigation hamburger)
- [x] When the view area is between 330px wide and 695px wide, the search box should not drop down to a new line (which it currently does).
- [x] Between 696px and 770px the Search box drops down about 12-15px. Please remove this spacing.
- [x] When the view area is 771px and greater, the search box can be wider and continue expanding its width as the browser gets wider
- [x] Make the width of the search results dropdown match the width of the search input box, including the magnifying glass icon.

**Comment by pertrai1** [comment]
@DaleMcGrew For the first point, if the name is longer than the width, do  you want ellipsis used to mask the rest of the name or have it break to new line?

**Comment by DaleMcGrew** [comment]
Ellipses please. We can also make the Instant Search box automatically scale to fill the available space in the header.

**Comment by pertrai1** [comment]
@DaleMcGrew I wanted to make sure you are aware that the search results are not accurate when doing searches? Testing has continued to bring back results that had no relevance to what the characters were that I had in the input field. Here is an example:

Type in 'af' and the first result is Christy Afflerbach Hudson
Type in 'Christy' and there is no return of Christy Afflerbach Hudson

I believe it would be best to have this search functionality working before introducing the search capabilities as a release candidate.

**Comment by DaleMcGrew** [comment]
Hi @pertrai1, thank you for the bug report. @josephevans and I are still working on tuning the indexing of data (this will be an ongoing process), so specific reports like this one are very helpful. We can have temporary imperfections in the develop branch for the next couple of months as we work out kinks like this.

As you find more search problems, can you enter them as issues in https://github.com/wevote/WeVoteServer assigned to @josephevans with the label "ElasticSearch"?

**Comment by pertrai1** [comment]
@DaleMcGrew @josephevans I will certainly do so. Anytime there is an inconsistent result I will add issue with the steps to reproduce.

**Comment by pertrai1** [comment]
@DaleMcGrew I have pushed a PR for you to pull from and see what has been done and the small changes that are still needed to get this complete. #330 is the PR. If we need to discuss, let me know and I can jump on gmail or slack to talk.

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 I am checking out your pull request. We are off to a great start. It looks best in desktop mode (full width). Some comments from Chrome on a Mac:
- [ ] In narrow browser mode, limit the width of the search box so it stays on the same line with "My Voter Guide"
- [ ] Make sure the drop down is limited to the width of the search box + the search button.

**Comment by DaleMcGrew** [comment]
@pertrai1 I moved some of the elements of this issue to new issues #331 and #332. This issue is now completely focused on the styling of the instant search box.

**Comment by pertrai1** [comment]
* [x] When the view area is less than 330px wide, hide the "My Voter Guide demo" text, and show the "Search We Vote" box (with the navigation hamburger)
* [x] Between 696px and 770px the Search box drops down about 12-15px. Please remove this spacing.
* [x] Make the width of the search results dropdown match the width of the search input box, including the magnifying glass icon.

@DaleMcGrew Before going full out with this, there should be consideration taken for moving to using flexbox so that there will not have to be as many media queries used as I am doing now. The fluid movement is having issues because of the structure of the layout that I did when we first started. At that time the top right icons were needed and they are absolute positioned, making it hard to have precise control over the search box right now.

**Comment by DaleMcGrew** [comment]
The latest version is almost there @pertrai1! It is exciting to see. 

This is the only remaining item for this Issue: When the view area is between 330px wide and 695px wide, the search box should not drop down to a new line (which it currently does).

That said, I am totally open to your refactoring to use flexbox if that is a more maintainable solution.

**Comment by pertrai1** [comment]
@DaleMcGrew I think flexbox would be the way to go but would want @ixley to chime in and say whether he wants to go this route or not. 

@DaleMcGrew What is the deadline for this milestone? Is it today? If so, getting this last issue with the view area is not a problem. I can also fix the clicking on the body to get the container of results to be removed if it is needed to show the basics of what the search will do. For this issue, I will handle gettig that last viewport size display taken care of.

**Comment by DaleMcGrew** [comment]
Thanks @pertrai1,  I love the idea of wrapping up this issue with one more fix today, and then entering a new issue for discussing re-factoring the whole header to flexbox after discussion.

**Comment by pertrai1** [comment]
@DaleMcGrew Hey, on 360x640, can we remove the name and have the hamburger and search?

**Comment by pertrai1** [comment]
@DaleMcGrew forget that last question :-)

**Comment by pertrai1** [comment]
@DaleMcGrew after playing around in Firefox responsive mode, I am not sure that having the search on the same line as the hamburger and name would be enough real estate for the search to be useful? 500 looks about the closest that I see there being enough room for it to work. Take a look in responsive mode and see what you think.

**Comment by pertrai1** [comment]
@DaleMcGrew after playing around in Firefox responsive mode, I am not sure that having the search on the same line as the hamburger and name would be enough real estate for the search to be useful? 500 looks about the closest that I see there being enough room for it to work. Take a look in responsive mode and see what you think.

**Comment by DaleMcGrew** [comment]
@pertrai1 Maybe if between 330px and 500px, when you give focus to the search box, we remove "My Voter Guide demo"?

I didn't see any changes just now -- I may have overwritten your changes with a commit to that branch just now (sorry!)

**Comment by pertrai1** [comment]
@DaleMcGrew I did not push yet. I am still playing around with the sizes because and various viewport sizes the search can look sometimes weird. I will give the focus a shot and see what that does

**Comment by pertrai1** [comment]
@DaleMcGrew I just pushed the latest change where the text logo goes away on search focus and then comes back on blur. The only thing is that right now the widths are not consistent because of the layout and that the focus and blur happens on any viewport size. This can be fixed to only happen at different sizes, but there will have to be multiple factors taken into consideration because it has to be done from the JS side and not just CSS. Go ahead and grab the latest. I will be out for a couple hours and then will check back in.

**Comment by pertrai1** [comment]
* [x] When the view area is between 330px wide and 695px wide, the search box should not drop down to a new line (which it currently does).

**Comment by DaleMcGrew** [comment]
I think we are in a good spot with this one! I will thumbs up and merge your pull request in a couple of hours. Great work @pertrai1!

**Comment by ixley** [comment]
@pertrai1 @DaleMcGrew I'm not familiar with all the factors, but I definitely think it makes sense to use flexbox if it simplifies layout and resizing or minimizes media queries.
