### ISSUE TITLE
Update README for WebApp Only

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#34]
@DaleMcGrew @nf071590 Should we update the README so it only shows the steps to get the webapp started locally since it is now hitting external end points? At the bottom of the README we can have a link to the backend that someone can head over to that repo and fork if they want to have the backend locally.

**Comment by DaleMcGrew** [comment]
Hi Rob, yes we will want to update the README, but I want to do this after our upcoming version 1 Milestone.

**Comment by pertrai1** [comment]
Ok, I will delete my pull request #37
