### ISSUE TITLE
Create a candidate suggestion dialog within WebApp for use by the extension

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#3462]
The WeVote extension has a button to save a new candidate from a popup that is on the right-click menu.  At one time we were evolving the extension to be for anyone to use, but for now we are orienting it back to be a tool for our political team to gather endorsements.

There is also a more complicated mode the "Edit panel" where there are more options for entering data, including the actual endorsement text.  Maybe we will want to add all those options to the right click popup, but for now all we send is `candidate_name`, `candidate_specific_endorsement_url`, `endorsement_page_url`, and `candidate_specific_endorsement_url`.    We won't know the candidates candidate_we_vote_id since they are a new candidate.

* This is the URL to load the page
```
https://localhost:3000/add-candidate-for-extension?candidate_name=Kristen%20McDonald[…]kristen-mcdonald-rivet%2F&candidate_specific_endorsement_url=](https://localhost:3000/add-candidate-for-extension?candidate_name=Kristen%20McDonald%20Rivet&candidate_we_vote_id=&endorsement_page_url=https%3A%2F%2Feverydistrict.us%2Fcandidates%2F2022-candidates%2Fkristen-mcdonald-rivet%2F&candidate_specific_endorsement_url=
```
* It has to fit in the iFrame shown in this image

<img width="1283" alt="Screen Shot 2022-07-05 at 11 15 41 AM" src="https://user-images.githubusercontent.com/6923653/177617838-ff21932b-2f30-4e8a-a54b-10d2b8b4d34d.png">

* It should have a send button
* The send button will make an API call to save the information.  (See https://api.wevoteusa.org/apis/v1/docs/)
* It might be this API, but to be confirmed by Dale:  https://api.wevoteusa.org/apis/v1/docs/voterGuidePossibilitySave/

**Comment by SailingSteve** [comment]
[Steve Podell](https://app.slack.com/team/U527YE5J4)
  [9:41 AM](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212061724749)
Dale:  When you are on a page with highlights, and you select a name that is not highlighted and the data entry dialog pops up, what api call do you make to create a suggestion for a new candidate?


[Dale McGrew (Oakland, CA)](https://app.slack.com/team/U02GWLNJK)
  [9:45 AM](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212324868139)
Checking…
[9:46](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212413542779)
I think it was this one: https://api.wevoteusa.org/apis/v1/docs/voterGuidePossibilityPositionSave/
[9:47](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212478477119)
These are listed about 3/5s of the way down this page:
https://api.wevoteusa.org/apis/v1/docs/
voterGuidePossibilityHighlightsRetrieve		Return a highlight dict which includes the candidates and measures to highlight on a web page.
voterGuidePossibilityRetrieve		Has a volunteer marked this URL as a voter guide?
voterGuidePossibilityPositionsRetrieve		Return one or all of the possible positions for one VoterGuidePossibility.
voterGuidePossibilitySave		Update an existing VoterGuidePossibility entry.
voterGuidePossibilityPositionSave		Update an existing VoterGuidePossibilityPosition entry.
[9:49](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212559541249)
It looks like its being called from this component: WebApp/src/js/components/Ballot/CandidateItemEndorsement.jsx


[Steve Podell](https://app.slack.com/team/U527YE5J4)
  [9:50 AM](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212644587059)
It doesn’t have a parameter for the candidate name.  Needed for a candidate who is not in the list of all possible highlights.
[9:53](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212801725359)
I guess it is voterGuidePossibilitySave
[9:54](https://wevote.slack.com/archives/C03NK1AQFA6/p1657212893841299)
So if you are on a newly discovered endorsement page, that is not in the db, you can’t save a possibility of a new candidate.  (there is an option to save the new page in the editor, but I don’t have that working again)
New


[Dale McGrew (Oakland, CA)](https://app.slack.com/team/U02GWLNJK)
  [10:00 AM](https://wevote.slack.com/archives/C03NK1AQFA6/p1657213259907169)
My initial analysis is that you would call https://api.wevoteusa.org/apis/v1/docs/voterGuidePossibilityRetrieve/ on the URL.
I doesn’t look like https://api.wevoteusa.org/apis/v1/docs/voterGuidePossibilitySave/ supports creating a new voterGuidePossibility entry, but that is fine for now.
We then should be able to use (or upgrade so we can use it) https://api.wevoteusa.org/apis/v1/docs/voterGuidePossibilityPositionSave/ to save a new candidate position.


[Steve Podell](https://app.slack.com/team/U527YE5J4)
  [10:01 AM](https://wevote.slack.com/archives/C03NK1AQFA6/p1657213319050039)
Ok!

**Comment by MvPodell** [comment]
<img width="458" alt="Screen Shot 2022-07-07 at 10 37 12 AM" src="https://user-images.githubusercontent.com/98058692/177835579-9c1a377a-4a09-4ab9-88f0-66cc6e6de289.png">

**Comment by SailingSteve** [comment]
This webapp code was meant for voter facing extension, not a political team facing extension.  Use it as an example for how to convert your page into a react component that uses flux stores and action, for this politial team facing extension.

https://localhost:3000/candidate-for-extension?candidate_name=Kristen%20McDonald%20Rivet&candidate_we_vote_id=&endorsement_page_url=https%3A%2F%2Feverydistrict.us%2Fcandidates%2F2022-candidates%2Fkristen-mcdonald-rivet%2F&candidate_specific_endorsement_url=

**Comment by SailingSteve** [comment]
Done!
