### ISSUE TITLE
Error when running WebApp on Windows

### ISSUE THREAD

**Issue by fdiazq** [wevote/WebApp#3511]
### Please describe the issue (What happens? What do you expect?)
An error occurs when running the command npm start after the setting up environment by following steps for manual installation of WebApp from this link.
https://github.com/fdiazq/WebApp/blob/develop/docs/installing/ENVIRONMENT.md
### Steps to reproduce the problem (1, 2, 3...), including links
Once NodeEnvironment has been setup and code brought into environment.
When running npm start there is an error message " 'PROTOCOL' is not recognized as an internal or external command,
operable program or batch file."

![webapperror](https://user-images.githubusercontent.com/46939004/190037374-5472e07a-4054-429b-874a-ca551005d478.PNG)

**Comment by SailingSteve** [comment]
If you got that far into the setup, you might just be able to use the new `npm run start-win` command in my latest checkin, which is not merged in yet.
For a quick hack, you could just try removing PROTOCOL=HTTP from the "start" line in package.json -- line 22

**Comment by DaleMcGrew** [comment]
Hi @fdiazq could you please test to see if the latest release fixes this problem on your Windows machine?

**Comment by DaleMcGrew** [comment]
Thank you for verifying @fdiazq!
