### ISSUE TITLE
Maintaining Responsive Header and Footer for Browser version

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#3518]
In the most recent version in the develop branch, it is possible in the browser version to resize the window and end up without a header or footer, or have both a header and footer at the same time. In the browser version (non Cordova), I would like to maintain the ability to for a voter to resize the window dynamically and still have the correct header or footer appear.

I'd like to discuss using the new header/footer visibility system implemented for Cordova that does not require responsive CSS, while maintaining the responsive CSS styles that hide and show the navigation items (Ballot, Friends, Discuss etc) when the site is viewed in the browser.

To see site without header or footer navigation:
1. In Chrome, with the window set to 720 pixels width, refresh the window. The footer navigation bar appears.
2. Resize the window to greater than 990 pixels without refreshing. The footer navigation disappears (as expected) but the header navigation items (Ballot, Friends, Discuss etc) do not appear.

To see site with both header and footer navigation:
1. Start on the Ballot page.
2. In Chrome, with the window set to 720 pixels, refresh the window. The footer navigation bar appears.
3. Resize the window to greater than 990 pixels without refreshing. The footer navigation bar disappears (as expected) but the header navigation items do not appear.
4. Click on the We Vote icon in the upper left of page, taking you to the Ready page. The header navigation items (Ballot, Friends, Discuss etc) appear, and the footer navigation bar is not visible.
5. Resize the window down to 720 pixels, and the footer navigation bar appears, while the header navigation items remain visible.

**Comment by SailingSteve** [comment]
Sure, I can make it responsive.  It just requires a listener.

**Comment by DaleMcGrew** [comment]
Verified and closed. Thank you @SailingSteve!
