### ISSUE TITLE
Display Position Statements

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#361]
Allow users to post and edit statements for candidates and ballot items.

**Comment by ixley** [comment]
@DaleMcGrew I did some style cleanup but was unclear about a couple things. Take a look and let's touch base to discuss.
Two quick notes - I added a placeholder for speaker_display_name (you can fix), and think that ideally the text input would expand (as textarea) to accommodate a few vertical lines (a la Facebook, etc.)

https://github.com/ixley/WebApp/tree/position-statement

**Comment by DaleMcGrew** [comment]
Thank you @ixley! Would you like to try to have a quick Google hangout or phone call today to discuss? Since this is very much a work-in-progress, please feel free to submit a pull request, even though there is more to iterate on. -Dale

**Comment by ixley** [comment]
@DaleMcGrew I've been super busy, but could talk through this possibly sometime Friday afternoon or evening, or else maybe Saturday morning. I'll submit a PR if you don't mind the messiness of fragmented commits and such.

**Comment by DaleMcGrew** [comment]
Hi @ixley what I saw looked far enough along for a pull request. Thank you for tackling this issue.
