### ISSUE TITLE
Add small text under icons in top bar

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#362]
Please add small text under the top bar navigation icons (which show in desktop mode):
Ballot, Requests, Connect, Activity
![screen shot 2016-08-11 at 4 50 17 pm](https://cloud.githubusercontent.com/assets/7756031/17608781/babd3c2a-5fe3-11e6-9e9e-a200bbd699c9.png)

Code (I believe): WebApp/src/js/components/Navigator.jsx file

**Comment by zachmonteith** [comment]
this is done in my latest pull request, although I still haven't been successful in standardizing the size of the icons

**Comment by DaleMcGrew** [comment]
Working now!
