### ISSUE TITLE
Organization's image not appearing on certain page(s)

### ISSUE THREAD

**Issue by ColettePhair** [wevote/WebApp#394]
https://WeVote.US/measure/wv02meas122

The link to an organization's photo is cached in the PositionEntered and VoterGuide tables. Currently our admin tools are not updating the link in the PositionEntered table when it gets updated in the master Organization table. This causes this problem: On this page Sierra Club's Twitter image doesn't appear in the "Voter Guide" list, but if you click the image/name, it appears on their own profile page.

![screenshot 21](https://cloud.githubusercontent.com/assets/20586344/17984109/ca1b9874-6ac4-11e6-947c-6a7bf55adb8d.png)

The fix will be to refresh this cached information whenever the master Organization table is updated.

**Comment by DaleMcGrew** [comment]
We are revamping the image system which will fix this.
