### ISSUE TITLE
Make position source link active: open new tab in desktop mode, open modal with content in mobile mode

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#397]
<img width="490" alt="screen shot 2016-08-26 at 6 15 37 am" src="https://cloud.githubusercontent.com/assets/7756031/18006525/c0b22d30-6b54-11e6-9d4a-96cfe19de6b8.png">

When a person clicks on the source link for a position:
- [x] In desktop mode, open the link in a new tab
- [ ] In mobile mode, open the link in a modal that can be closed

**Comment by zachmonteith** [comment]
Unable to get modal to load and display full external webpage, so commented it out.  mobile users will not see a "view source" link, desktop users will open link in new tab as desired.

**Comment by DaleMcGrew** [comment]
Agreed. We won't offer a "view source" link in mobile mode for the foreseeable future. Verified.
