### ISSUE TITLE
Candidate - One Position Page, Create & Style

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#4]
http://localhost:9090/ballot/candidate/2/org/27 (web_app/app/containers/ballot/BallotCandidateOnePositionPage.jsx)
- [ ] Like/Share icon positioning: Make the horizontal spacing of each action even relative to each other.
- [ ] Adjust the size of the text. Adjust the color of the text to be gray, even on roll-over.

**Comment by pertrai1** [comment]
@DaleMcGrew I am going to close this issue because I am not able to find this file anymore

**Comment by DaleMcGrew** [comment]
We can implement this page in version 1.1 (we can skip it for version 1.0), but it is still an outstanding task. I need to bring this page into the WebApp repository.

**Comment by pertrai1** [comment]
@DaleMcGrew Ah, must be one of those that did not get pulled in during the transition? Thanks for reopening so we have a history of what needs to be done.

**Comment by lisamcho** [comment]
closing out. No additional info to put on this page right now
