### ISSUE TITLE
Position Toggle Switch should appear on Your Page for each ballot item with a position

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#403]
currently the position toggle switch (to change a post from one only your "Friends" can see to one available to the "Public" and vice-versa) appears on the Ballot page and on the individual ballot item's page, but not on the list of ballot items a user has taken positions on (available by clicking "Your Page" in the hamburger menu/left column menu, or navigating to /{the user's twitter handle}).

First step will be to extract the toggle from its current home in ItemActionBar into a standalone file, in order to increase its flexibility and compartmentalization.  

Second step, integrate into PositionItem and OrganizationPositionItem, to appear if signed_in_with_this_twitter_account === true.

**Comment by DaleMcGrew** [comment]
I am working on changing the value of signed_in_with_this_twitter_account based on live data.

**Comment by DaleMcGrew** [comment]
Fixed.

**Comment by DaleMcGrew** [comment]
Hi @zachmonteith I think this was working, but isn't working any longer. When I go to my page now (signed into my Twitter account http://localhost:3000/WeVote ), I don't see the "Friends/Public" toggles any more. Can you please take a look?

**Comment by DaleMcGrew** [comment]
@zachmonteith can you please verify this? I believe I fixed it.

**Comment by zachmonteith** [comment]
Yes, it's working both on ballot page (where it is pulled in by ItemActionBar) and on "Your Page" (where it is pulled in by OrganizationPositionItem).  I tried it locally and in the version running on wevote.me and toggled a few positions, everything seems great.

**Comment by zachmonteith** [comment]
👍
