### ISSUE TITLE
San Francisco showing as "nearby address" for Virginia

### ISSUE THREAD

**Issue by ColettePhair** [wevote/WebApp#405]
I entered "101 W Franklin St, Richmond, VA 23220" and this message appeared that it was showing the ballot for a nearby address, in SF.   Yet the ballot data is actually for Virginia on this page.
![screenshot 24](https://cloud.githubusercontent.com/assets/20586344/18013300/4752d1e2-6b72-11e6-94f4-ea84474b652c.png)

**Comment by DaleMcGrew** [comment]
Removed.
