### ISSUE TITLE
Ratings Info Popovers should not appear within modal

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#407]
first, Ratings Popovers should be extracted from current home within PositionRatingSnippet to their own standalone file.

second, these popovers should not appear when ratings are appearing in a modal link (example: when on page /ACLU, looking at list of ACLU ballot item ratings, clicking on an individual ballot item brings up a modal for that particular candidate and rating.  clicking the VoteSmart text here should not ALSO produce a popover, as interested users can trigger the popover from within the modal, and the popover + modal looks messy).

third, position of popover (top, bottom, etc) should be extracted into a variable that can be passed as a prop, and popovers appearing from modals should appear below, not above, the words (Source: VoteSmart.org) so as to not go off the top of the window.

**Comment by DaleMcGrew** [comment]
Nailed it! 👍
