### ISSUE TITLE
Dropdown options do not go away

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#419]
After selecting from a dropdown, the options do not go away as I scroll up and down the page. Using Mac Chrome. See screenshot. @DaleMcGrew I assign these to you so you can decide who is best to fix these if they are indeed an issue.

![dropdown-still-visible](https://cloud.githubusercontent.com/assets/442374/18034829/c24d3538-6d14-11e6-88a2-48994f8469f1.png)

**Comment by DaleMcGrew** [comment]
@pertrai1 thank you for creating this issue. You are correct, they should go away when a voter clicks away from the drop-down.

**Comment by DaleMcGrew** [comment]
@kyleludlow we are migrating away from these drop-downs, so there is no need to fix this bug.
