### ISSUE TITLE
editing position comments about a measure from within a modal creates a new item

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#420]
Walkthru for encountering this bug:
1) make a comment about any ballot measure (i put my location as New York, NY, and commented on proposition one, we vote id measure/wv02meas8)
2) go to "Your Page" (url should be /your twitter handle, also available from hamburger/left side menu)
3) click on the card for the measure you commented on to bring up the modal for that measure
4) click to edit your comment
5) type a new comment
6) upon return to Your Page, a new item will appear without the ballot_item_display_name with only a placeholder image and your new comment.  It will link to the same WeVote ID but under the path of candidate/{wevoteid} instead of measure/{wevoteid}... and of course it will never load as this item does not exist.

seems like each new edit of comments about any ballot item makes a new position-item on the users "Your Page" rather than deleting the old comment and replacing with the new one.

**Comment by DaleMcGrew** [comment]
Closing this issue since we won't be re-introducing the "Edit Position Modal" for a while.
