### ISSUE TITLE
some ballot items' display names are appearing in all caps

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#422]
if ballot item name in database is in all caps, name appears in all caps on front end.  We would prefer to have names appear in typical Capitalized Case, where only the first letter of each word is capitalized.

We do not, however, want to apply this capitalization at ALL times, as it will eliminate some good formatting such as US President becoming Us President, etc.  Only when name is stored in ALL CAPS should this be implemented.

I wrote a function called capitalizeString a few weeks ago when implementing support for measure ballot items, but it needs to be tweaked to only apply to strings in all caps, and needs to be imported and included in all appropriate places.

**Comment by DaleMcGrew** [comment]
👍
