### ISSUE TITLE
Create "copy link" Modal for ShareButtonDropdown

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#435]
In Widgets/ShareButtonDropdown we have a "copy link" option. Turn this "copy link" on, and when the option is selected, open a modal with the link in a select box that allows the person to copy the link to their clipboard.

To get started, I suggest searching for "EditPositionAboutCandidateModal" for example code you can start with.

Next step after this is to show a preview of the link in the modal.

**Comment by abbynormative** [comment]
I'm interested in working on this. Can you post a link to a page in the WeVote app where the copy link option should appear?

**Comment by DaleMcGrew** [comment]
Hello, you can use a dummy link  for now in the modal.  The copy link option is currently commented out in the ShareButtonDropdown component.

**Comment by abbynormative** [comment]
Ok. Can you post a link to one of the pages that has this button? I just want to clarify what exactly I'm working on, and to have a page to view when testing my code.

**Comment by DaleMcGrew** [comment]
Any page with the support/oppose/share buttons. https://wevote.me/measure/wv02meas100

**Comment by DaleMcGrew** [comment]
Verified! Great work @zachmonteith.
