### ISSUE TITLE
#7 Organization is offered to be followed on measure page, even though there is no comment or support/oppose

### ISSUE THREAD

**Issue by tiffanysun** [wevote/WebApp#441]
Data bug: Dale McGrew doesn’t show a ‘supports’ or any stance on the Prop 51. 

<img width="634" alt="screen shot 2016-09-06 at 12 54 54 pm" src="https://cloud.githubusercontent.com/assets/12804592/18296703/6cc4f0bc-7460-11e6-92a2-b21f7ba1b9b3.png">

**Comment by DaleMcGrew** [comment]
This needs to be fixed on the API server in the voterGuidesToFollowRetrieve API endpoint. We have a filter in place for positions about candidates that don't have support/oppose or comment, and that same filter needs to be added for Measures.

**Comment by DaleMcGrew** [comment]
I am closing this as an active issue.
