### ISSUE TITLE
#4 Rework dropdown into tab format

### ISSUE THREAD

**Issue by tiffanysun** [wevote/WebApp#442]
4) Instead of dropdown, rework these as tabs (ie: Remaining Choices, Support, Bookmark)
<img width="355" alt="screen shot 2016-09-06 at 12 44 16 pm" src="https://cloud.githubusercontent.com/assets/12804592/18296653/f7d3a4ec-745f-11e6-95e5-245e5d34197a.png">

**Comment by DaleMcGrew** [comment]
Merged with issue #440
