### ISSUE TITLE
#8 In mobile view, make search box fill top bar to right of hamburger menu

### ISSUE THREAD

**Issue by tiffanysun** [wevote/WebApp#443]
Alignment issue in mobile view.
<img width="396" alt="screen shot 2016-09-06 at 12 59 04 pm" src="https://cloud.githubusercontent.com/assets/12804592/18296804/0d35ae7e-7461-11e6-8894-b4a03c3c1ea8.png">

If you shrink the window even further, the search box fills the entire top bar, so this is an issue of the responsive design transition widths.

Note that the search box is lower than it should be, when it does fill the top header bar.

**Comment by ixley** [comment]
I'm working on cleaning up the header nav bar.
