### ISSUE TITLE
Remove 2nd Header Bar

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#444]
In mobile mode, the 2nd header bar should take less vertical space, and the text should not wrap.
![screen shot 2016-09-07 at 7 51 43 am](https://cloud.githubusercontent.com/assets/7756031/18316636/46cd72c4-74d0-11e6-93cf-9dfa221aa2e7.png)

Dale would like to be trained in the layout styles for the header so he can make tweaks.

**Comment by ixley** [comment]
Can we just remove this? We've discussed before how these nav items are relevant in certain contexts but probably don't warrant taking up that much prime space all the time.

**Comment by DaleMcGrew** [comment]
I'd like to leave this bar in place for user testing. I know that now it doesn't feel right the way it is displayed currently. This 2nd header bar will feel less "heavy" when we make it *much* shorter. I think we will also want to change the buttons we put there after some experimentation. Facebook has a 2nd header bar like this, and I suspect it is based on what they've learned through user A/B testing.

**Comment by ixley** [comment]
@DaleMcGrew I can appreciate getting feedback from users on this, but I still think there are better ways to surface these options _in relevant contexts_ without having them take up prime space all the time.

**Comment by zachmonteith** [comment]
I just made the header bar shorter itself without changing the icon/text font size.  could change icon size too if you want it shorter still, just let me know.

**Comment by ixley** [comment]
I'm removing this with Dale's acquiescence.
