### ISSUE TITLE
react-burger-menu breaks react-headroom

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#450]
[react-burger-menu](https://github.com/negomi/react-burger-menu) currently breaks [react-headroom](https://github.com/KyleAMathews/react-headroom) functionality after the menu has been triggered.

react-burger-menu injects `overflow-x: hidden` into the `<html>` and `<body>` tags when the menu is triggered, but does not remove them on close.

Investigate whether the problem can be solved on our end (implementation fix) or whether the fault is with the react-burger-menu code, in which case, please [file an issue](https://github.com/negomi/react-burger-menu/issues) with them and report it here.

**Comment by DaleMcGrew** [comment]
Hi @ixley I think I broke this. I was trying to get rid of the console errors "No pageWrapId supplied" and "outerContainerId".

In /src/js/components/Navigation/HeaderBar.jsx we call:
<ReactBurgerMenu pageWrapId={ "" } outerContainerId={ "app-base-id" } styles={ menuStyles }>
In the last couple of weeks I added:   pageWrapId={ "" } outerContainerId={ "app-base-id" }

...if we don't pass in pageWrapId or outerContainerId I am guessing this will fix this. Can you confirm?

**Comment by ixley** [comment]
@DaleMcGrew It's possible you adjusted something that broke it in a different way, but it doesn't look like this is a full fix. Without `outerContainerId`, the page will still scroll (along with the slide-out nav), in an undesirable way. (This is the current behavior on wevote.me). 

The menu transition we're using doesn't require `pageWrapId`, but it doesn't seem to matter whether you pass an empty string or omit it.

**Comment by DaleMcGrew** [comment]
@ixley following your most recent changes, is this still a bug?

**Comment by ixley** [comment]
@DaleMcGrew Unfortunately, yes. I dug into it while I was doing clean up, but am not sure how to fix. The info I posted about the `overflow-x: hidden` values not being removed is the most I can probably offer.

**Comment by ixley** [comment]
submitted an issue with [react-burger-menu](https://github.com/negomi/react-burger-menu) to see if it's on their side.
https://github.com/negomi/react-burger-menu/issues/103

**Comment by ixley** [comment]
acknowledged bug: https://github.com/negomi/react-burger-menu/issues/103#issuecomment-249113137 - waiting for fix to see if it resolves our issue
