### ISSUE TITLE
Mobile (Safari): Can we add "momentum" to scroll?

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#454]
### Please describe the issue (What happens? What do you expect?)
When I am trying to scroll down the ballot while using iPhone Safari, or a list of candidates, there isn't any scrolling momentum. (It doesn't seem to be a problem with iPhone Chrome.) It would feel better if you could flick up, and have the page keep scrolling and then slow to a stop.
### Steps to reproduce the problem (1, 2, 3...), including links
1. Set your address to somewhere in the San Francisco Bay Area.
2. Go to your ballot
3. Try to scroll down the ballot quickly with your finger
4. The scrolling feels sluggish, and the scrolling stops as soon as you let go

**Comment by ixley** [comment]
@DaleMcGrew I think this might just be a browser thing. Scrolling has the momentum you describe in Chrome, but not in Safari – seems specific to the (mobile) browser, as opposed to the website.

**Comment by ixley** [comment]
*I haven't dug into it but `-webkit-overflow-scrolling: touch` might do the trick.

**Comment by ixley** [comment]
I found another factor. Seems like triggering the react burger menu is a/the cause of this.

**Comment by DaleMcGrew** [comment]
Hi Jeff, good catch, I can confirm that the scrolling slows down on iPhone Safari only AFTER you open the menu. I haven't tested since the new update. I'll do that shortly.

**Comment by DaleMcGrew** [comment]
Verified! Woohoo!
