### ISSUE TITLE
Ballot -> Ballot Item page -> Ballot: Can we return to same spot?

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#455]
### Please describe the issue (What happens? What do you expect?)

When you click away from a long ballot page to a particular office or measure, and then go back, you don't return to the same spot in the page. This is disorienting.
### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to a ballot that is longer than a single screen, like "Charlotte, NC 28205" for example.
2. Scroll down to the bottom of the page.
3. Click on a Measure or office.
4. Click the "back" arrow
5. You are taken to the top of the Ballot page, and should return to the same place (in the page scroll) that you started at in step 2.

**Comment by DaleMcGrew** [comment]
This seems to work now on my Mobile browser, but not still does not work on Mac desktop.

**Comment by Anoninnyc** [comment]
So, would something like [this](https://www.npmjs.com/package/react-router-restore-scroll)?

**Comment by DaleMcGrew** [comment]
Hello Krishan @anoninnyc, yes this looks perfect. Thank you.

**Comment by DaleMcGrew** [comment]
Fixed! Thank you @Anoninnyc.
