### ISSUE TITLE
Can't load ballot page

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#46]
Hmmmm, after pulling down the latest changes, the ballot page doesn't seem to load the list of candidates anymore. In previous versions when you just go to the root url or localhost:3000/ballot, the candidates appear after a brief delay, but now the spinner displays perpetually. The VoterGuideStore is not being initialized??

**Comment by nf071590** [comment]
Hey Lisa, this may be my fault. I’m going to see if I can revert changes to the VoterStore because I didn’t mean to check them in. I’m not sure what is going on with the VoterGuideStore.

**Comment by nf071590** [comment]
I'm going to push through the issues I create a fix. Beginning work now... Apologize for any inconveniences... Possibly try and checkout a version before the change that broke this if you need access to the ballot page.

**Comment by DaleMcGrew** [comment]
You are a rock star Nick! Thank you.

**Comment by DaleMcGrew** [comment]
We added a line to utils/service.js to automatically included voter_device_id with every call to any endpoint. If a full address in Virginia is saved (which can't be done from WebApp yet, see Issue #2) you will now see a full ballot.

**Comment by nf071590** [comment]
@DaleMcGrew now that the VoterStore is updated, we should be able to save address easily. I will commit code for this.
