### ISSUE TITLE
Copy link problems

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#487]
### Please describe the issue (What happens? What do you expect?)
On iPhone 5, when I use the ShareDropdown Copy Link option, it offers a second modal, and doesn't bring the link into the clipboard.
- [x] The copy or Select All button is 1px too low on iPhone and Desktop Firefox
- [x] The Select All link doesn't work on Mac Firefox.

**Comment by zachmonteith** [comment]
current behavior: on iOS, clicking "Select All" button selects all text in the input field and brings up options to copy.  clicking input field itself does NOT select all.

Android: select all selects the text, but then user has to click and hold to bring up clipboard options.

desktop: clicking input field or Select All button (if window is narrow enough to show the button) selects all text in input field, clicking "copy" button (when visible) copies to clipboard and displays copied text in red.

**Comment by DaleMcGrew** [comment]
@zachmonteith I found some more issues with this while testing.

**Comment by DaleMcGrew** [comment]
@zachmonteith implemented a good enough solution for this upcoming release.
