### ISSUE TITLE
"Build Your Network" iPhone 5: Two options wrapping to two lines

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#488]
### Please describe the issue (What happens? What do you expect?)
The "Who You Can Follow" and "Currently Following" options should stay on one line.
![screen shot 2016-09-22 at 8 43 21 pm](https://cloud.githubusercontent.com/assets/7756031/18773605/6d7f05cc-8105-11e6-9041-701fa5498ab9.png)

### Steps to reproduce the problem (1, 2, 3...), including links
1. iPhone 5. Go to Connect. "Who You Can Follow".
2. The The "Who You Can Follow" and "Currently Following" options should stay on one line.

**Comment by ixley** [comment]
Because this is a spacing issue rather than a css bug, I'd recommend just coming up with slightly shorter text. Alternatively, we could either override the horizontal button padding here (or even rewrite the default button padding), but changing the text seems slightly preferable, if reasonable.

**Comment by DaleMcGrew** [comment]
@ixley I like your suggestion. I will change "Currently Following" -> "Following". Thank you! I will mark this as "Verify Fix" as soon as the change is on the live site.

**Comment by DaleMcGrew** [comment]
Verified locally.
