### ISSUE TITLE
Organization Search Result not working/disappearing

### ISSUE THREAD

**Issue by ColettePhair** [wevote/WebApp#493]
### Please describe the issue (What happens? What do you expect?)

When searching for the org "SF Berniecrats" on a PC in Chrome, on the Location page, the result came up, but nothing happened when it was clicked.  Then when we were clicking on another part of the page, the search result still hung there instead of disappearing.  It still appeared there even when we navigated to another page of the web application.

### Steps to reproduce the problem (1, 2, 3...), including links

1. Type in "SF Berniecrats" in the search bar (this is the only org I've seen this happen with so far)
2. Try selecting it
3. Try navigating to another page
*Note:  The second time I tried this, on
 another day, the search result did disappear and did not stay stuck there, though clicking the result link still didn't go to the org's page.

![screenshot 66](https://cloud.githubusercontent.com/assets/20586344/18798186/28fa9354-8186-11e6-92b8-a0f0af67c18e.png)

**Comment by zachmonteith** [comment]
formerly bad URI for SF Berniecrats, Dale fixed.

**Comment by DaleMcGrew** [comment]
I am closing this issue since we have another issue for the drop down not closing on mobile.
