### ISSUE TITLE
Ballot Major Navigation style tweaks

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#5]
components/Navigator.jsx Styling
- [x] For the "Ballot", "Requests", "Connect" and "Activity" icons that are NOT selected (in both mobile and desktop mode), please make the navigation icons (and text links) gray instead of blue, with text underline on roll-over and darker gray for both text and icon
- [x] Do not use roll-over on the "selected" icon (as it currently works)
- [x] Create an "at" state for Ballot/Requests/Connect/Activity with the icon and text blue.
- [x] Please use the blue currently used for "not selected" for the "selected" state
- [x] Make these changes in both mobile and desktop modes

**Comment by pertrai1** [comment]
@nf071590 Do you know how to do this with the routes? I am not able to get the regular CSS to match the selected or active href

**Comment by pertrai1** [comment]
@DaleMcGrew what is the status of this? If it has to do with the routes handling state for changing the UI, might want to have @nf071590 or @lisamcho take a look at this in the next couple of days before the milestone deadline.

**Comment by nf071590** [comment]
sure I can take a look at this now. Do you have different icons?

**Comment by pertrai1** [comment]
@nf071590 No just need to add a class for the active state and we can give the icon a color of blue and the other 3 can be grey

**Comment by DaleMcGrew** [comment]
@pertrai1 yes this is still needed. Thank you @nf071590 

The state of each icon is based on which route you are in.
Ballot icon: In <Route path="ballot
Requests icon: In <Route path="requests"
Connect icon: In <Route path="connect"
Activity feed icon: In <Route path="activity"

**Comment by pertrai1** [comment]
Great. I change assignee to @nf071590
