### ISSUE TITLE
Search text disappears if you click away from the search box, then click back

### ISSUE THREAD

**Issue by nickbarry** [wevote/WebApp#505]
### Please describe the issue (What happens? What do you expect?)

Search text disappears if you click away from the search box, then click back. I would expect that the text persists until the user navigates to another page (or manually deletes the text).
### Steps to reproduce the problem (1, 2, 3...), including links

Reproduce this problem by:
1. Typing some text into the search box
2. Clicking out of the search box
3. Clicking back into the search box.

The text disappears. This also occurs if you type text into the search box, navigate to another tab, then navigate back.

**Comment by nickbarry** [comment]
Per discussion with Dale, this is actually by design. We talked about ways to improve what potentially could be a confusing experience for the user. Here are the user stories:
- If the user starts typing some text, blurs the search box, then clicks back, the text should remain unchanged; it should be highlighted, though, for ease of deletion
- Whenever the user navigates to a page, the title of the page should be filled in the search box (like in Facebook). As before, clicking into the search box should select all the text

**Comment by DaleMcGrew** [comment]
Closing this case.
