### ISSUE TITLE
Use react patterns instead of searching the DOM

### ISSUE THREAD

**Issue by nickbarry** [wevote/WebApp#507]
There are many cases when we're searching the DOM for elements, instead of using proper React patterns to modify the DOM. This is slow. It would also be confusing for other React developers (including our future selves, looking at the code and trying to figure out how it works!).

For example, see the `src/js/utils/search-functions.js` file.

**Comment by nickbarry** [comment]
I've assigned this to myself, but it's probably not super high priority. If someone else comes across this issue, and I'm not clearly in the middle of it (i.e., I haven't left recent comments on the issue), feel free to work on it yourself.

**Comment by DaleMcGrew** [comment]
Thank you @nickelser!
