### ISSUE TITLE
Reconcile service.js functions

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#51]
There are functions in service.js such as "candidatesRetrieve" that seem to be duplicated by BallotAPIWorker in BallotStore.js
Needs to delete the ones we are not using.

**Comment by nf071590** [comment]
Hey Lisa, we should be migrating towards jQuery $ajax function. I will work on cleaning up these requests.

**Comment by DaleMcGrew** [comment]
It looks like @nf071590 resolved this.
