### ISSUE TITLE
Galaxy S3 different line breaks with icons

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#516]
### Please describe the issue (What happens? What do you expect?)

Using the Galaxy default browser "Internet" there are formatting differences.
![screenshot952016-09-30-14-18-241](https://cloud.githubusercontent.com/assets/7756031/19015167/fd91bbf0-87b3-11e6-8fea-3eacb151e310.png)

and:
<img width="479" alt="screen shot 2016-10-01 at 8 49 52 am" src="https://cloud.githubusercontent.com/assets/7756031/19015172/14a81c8a-87b4-11e6-9007-07647ca9aee8.png">

We should probably run some tests with one of these cross-browser tools:
http://mashable.com/2014/02/26/browser-testing-tools

**Comment by ixley** [comment]
This is likely due to lack of browser support for flexbox. We can create fallbacks if necessary, but first we should create a list of browsers and versions that we need to support.

**Comment by DaleMcGrew** [comment]
Per Issue #522 (updated now with Minimum Supported browsers) we are going to support Internet Explorer on Android. We are going to close this issue for now since we will need to track browser specific issues in a new way.
