### ISSUE TITLE
Discuss javascript method name prefix standards

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#52]
I'd like to propose that we take some time (no rush) when we are on a call together to discuss function name standards. I propose:

- retrieve for pulling data from permanent store (i.e., reaching out to an endpoint) (ex/ retrieveVoterObject)
- get for getting a value from local store (ex/ getVoterObject)
- save for saving to permanent store (i.e., saving to an endpoint) (ex/ saveVoterGuide)

**Comment by pertrai1** [comment]
@DaleMcGrew @nf071590 @lisamcho I believe it should be as simple as `getVoterObject` and `setVoterGuide` as examples. We are using getters and setters so starting functions with `get` and `set` are a normalized standard

**Comment by pertrai1** [comment]
No milestone needed for this issue
