### ISSUE TITLE
Do an SEO audit of We Vote

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#521]
### Please describe the issue (What happens? What do you expect?)
Now that we are on WeVote.US, we can start paying closer attention to Google finding all of the great information we have on We Vote. Below are notes I took at a great talk on SEO. There is a lot here, so instead of doing ALL of these items as part of this Issue, please do an audit of how we are doing things that affect SEO (including test Google searches) and break up the major steps into new Issues we can tackle one-by-one.

### Notes
Action items
1. Make sure every page has `<title>` tag
2. Description tag
3. Rewrite all headings and insert keywords
4. Rewrite all link text
5. Create XML sitemap
6. Set up CDN

SEO is straight up magical. It’s free, easy, and can drive millions of visitors to your website. I’ll show you how I used SEO to secure top Google placement for almost any search related to voting, driving millions of visitors to LongDistanceVoter.org. We’ll share our case study on how LDV registered 100,000 voters in 2012 on just $5000.

Use H1, H2 tags: Only one H1 per main content section - (likely this will only be once per page).
Provide alt and title tags for images.

Try to use a keyword in the urls, H1, body, start of the Title tag

The title page should match what is being talked about on the page. 50-60 characters
Use a unique title tag for each page. Use consistent pattern, like: '[Title] - [Site Name]' (Don’t lead with the name of your site)

Title tag is the bold text that shows up on Google. Description is what shows up below that in the search results.

Description tag is NOT what Google indexes — it is only viewed by humans. Write copy that makes people want to click on your link.

Do not use “click here” as a link. Link text should be descriptive. If no other options, “click here to adopt a kitten”. But better: “Adopt a kitten"

For different words, use “-“ as opposed to “_"
They suggest using all lower case letters.
Every part of your url should be human readable.

If you change a URL, remember to do a 301 redirect using .htaccess which tells Google to move indexes. All the SEO juice will transfer to the new domain.

Create an XML sitemap and submit it to Google’s webmaster tool: http://webmaster.google.com

**Comment by zachmonteith** [comment]
I created distinct issues for several of these action items, but not for headings or link text/urls.  I think our headings are already pretty descriptive, many of the urls are dependent on twitter handles or otherwise already include keywords/are descriptive.  WeVoteID url strings aren't ideal for SEO, but seem like a pretty integral part of the structure.

Also didn't create an issue for setting up a CDN; while this seems pretty critical for scalability, I'm not clear on how it helps with SEO, and also appears to generally have a cost associated.  Also not sure what I would write as a description of the issue, other than just "set up CDN" :)

**Comment by ixley** [comment]
@zachmonteith My guess for why CDN is on there is that load times have an impact on SEO. But I agree, I think performance oriented goals should be prioritized in their own right, since they have just as much or more relevance to UX than SEO at this stage.

**Comment by pertrai1** [comment]
If you want a long list to look at, this was interesting: http://backlinko.com/google-ranking-factors

In regards to CDN, site speed is starting to creep up the list of factors for the search engine algorithms. Might be better to consider going the service worker path for offline usage of the app. CDN's work great for the static assets no matter what, and could be part of SEO or separate.

**Comment by DaleMcGrew** [comment]
It appears we have other issues created for everything we are going to tackle now, so I am closing this Audit issue.
