### ISSUE TITLE
Create list of supported browsers

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#522]
Establish a list of which browsers (including versions and device, when relevant) that the web app should support. This will aid in determining a list of browsers for a test suite as well as where we will need to rely on fallbacks or different implementation (particularly with CSS).

If we are supporting older browsers, it would also be helpful to have standards around what features can be partially degraded as long as they are still functional/usable.

**Comment by DaleMcGrew** [comment]
Niyati has created this Minimum Supported Browser list here:
https://docs.google.com/spreadsheets/d/1FlUMCvg1pNIO0IzJm0jQyvUW1YC_KHh-LO4l-OVIcog/edit#gid=1774503729

...with this supporting research:
https://docs.google.com/spreadsheets/d/14LQmWNqc74aR1a5eZftX2JFaEdDXD-S0kLRi0tPwqe8/edit#gid=1232767229

Comments welcome!

**Comment by DaleMcGrew** [comment]
Completed. Thank you @niyatikothari!
