### ISSUE TITLE
Placeholder Icons: shape, lower margin

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#524]
2 notes on Placeholder Icons:
1) we have changed avatar images to always be round for candidates and square for orgs; however, the placeholder icon for orgs is round.  perhaps we want to redesign?

2) placeholder icons seem to have a lower margin, or padding, that is altering the shape of their containers.  less of an issue with position cards, etc, but becomes more obvious in search results images (PR #523), as it changes the alignment of the display name with the image.  see screenshot below.

![screen shot 2016-10-04 at 10 44 37 am](https://cloud.githubusercontent.com/assets/17035647/19085589/b07805cc-8a1f-11e6-83c7-9faad621b68e.png)

**Comment by ixley** [comment]
There are some elements—like the search results dropdown—that disappear on *any* mouse or keyboard action, including clicks using the inspector. This makes it really tricky to debug styling issues. Can we use more friendly defaults for click handlers?

**Comment by Anoninnyc** [comment]
@ixley  This worked for me, but yeah... annoying :(
https://www.dropbox.com/s/lrdw7vv5f2hgf77/trythis.webm?dl=0

**Comment by ixley** [comment]
Thanks @Anoninnyc. Maybe I'll revisit using that tactic. On the topic, are you familiar with a better way to setup event listeners so they're confined to the viewport (and don't pick up clicks in the inspector)?

**Comment by Anoninnyc** [comment]
@ixley I'm trying it on this page. The only side effect it's giving is that, when you try to resume the script via clicking play in yellow banner atop page, it will register *that* as a click. ie you'll have to double click :)

However, it's not registering any cIicks make in devtools.

**Comment by Anoninnyc** [comment]
well, sometimes it does...

**Comment by Anoninnyc** [comment]
@ixley @DaleMcGrew 
Hey, so... 
I'm finding the alignment seems to be fixable by targeting specific classes associated with placeholder profiles, and adding top: 2px/2em/2%, etc.

Any problems/pitfalls/caveats with this approach before I go in and try it out, make my first PR, etc?
![centering](https://cloud.githubusercontent.com/assets/16432389/22845877/fa525840-efa1-11e6-9020-08eaa2af499c.png)

**Comment by ixley** [comment]
@Anoninnyc To be honest, that approach feels a bit hackish. If you're interested in taking a stab at this specific issue, it can be solved more cleanly by using `position: flex;`. I'll let you explore how to implement that if you're interested in learning more about flexbox properties. If not, I can handle it (and I can share what I do for reference). Either way, I appreciate the tip on intercepting events with DevTools.

And again, if you have any familiarity with a better way to implement click handlers so this doesn't happen for any interactions on our site, that would be great. (That's something that's specifically over my head.)

**Comment by ixley** [comment]
@Anoninnyc I'm gonna give you the answer and you can implement to better understand why it works and get practice making your PR.

```scss
.search-image {
    - display: inline;
    + display: inline-block;
    + height: 30px;
    font-size: 30px;
    margin: 0 12px 0 0;
    width: 30px;
}
.search-container__results {
    background: #fff;
    margin-bottom: .5em;
    padding: .75em;
    + display: flex;
    + align-items: center;
    + font-size: 1rem;
}
```

**Comment by Anoninnyc** [comment]
@ixley Thanks! I'm familiar with all the above properties, so I'm happy to try it out. 
Re: your question, I'll slack you.

**Comment by Anoninnyc** [comment]
So... as I relayed to @DaleMcGrew , it looks like the placeholders might be riding a bit higher than real candis. @ixley, take a look at the att.

Dunno it this is splitting hairs or if having at least partially rectified this issue has bumped this down a priority level (& we should place on back-burner(?)), but the placeholder icons are riding a *bit* higher in their spans than are the rounded images (important distinction is placeholders use i tags, whereas candidates use img tags). 

![placeholders](https://cloud.githubusercontent.com/assets/16432389/22868423/03ac0ece-f153-11e6-8a08-f9810aa4833d.png)

![realcandis](https://cloud.githubusercontent.com/assets/16432389/22868424/064fd1b0-f153-11e6-9fb4-ed42b865504a.png)

**Comment by ixley** [comment]
Thanks @Anoninnyc - I think it's good enough, especially since this stuff is likely to change. If you want to take a stab at another issue that is also low priority, but gets more at the root of this, check out https://github.com/wevote/WebApp/issues/649

**Comment by DaleMcGrew** [comment]
I consider this fixed. Thank you @Anoninnyc!
