### ISSUE TITLE
Create XML Sitemap, submit to Google webmaster

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#525]
We need to create an XML sitemap to help google give searchers optimized results, and take them to the appropriate parts of We Vote.

https://en.wikipedia.org/wiki/Sitemaps

here are a few sitemap generators: 
https://www.xml-sitemaps.com/
https://xmlsitemapgenerator.org/
http://www.web-site-map.com/

When complete, submit to Google’s webmaster tool: http://webmaster.google.com

**Comment by ixley** [comment]
We will probably want something that generates and updates our sitemap with our own config, rather than having to rely on external site crawlers. I'm not able to assess personally, but see if there's anything built specifically to work with react(-router).

**Comment by alexthornton** [comment]
> We will probably want something that generates and updates our sitemap with our own config

Are you suggesting something that is generated with the build / deploy? If so, that seems like a good idea to ensure that the sitemap always reflects the latest deploy.

Poking around a bit in the code, I can't find where the build and deploy are defined. I see a `.travis.yml` file that appears to be just running `npm run lint`. What builds the code and deploys it so folks can access it at https://wevote.us?

**Comment by ixley** [comment]
> Are you suggesting something that is generated with the build / deploy? If so, that seems like a good idea to ensure that the sitemap always reflects the latest deploy.

@alexthornton Yes - the sitemap should always reflect current, live content. The most relevant aspect (that I'm familiar with) is to aid search engines and help with SEO. I'm not familiar with the deploy process or with even with how the router is structured, so I can assist with info organization and mapping, but not much with the technical side.

It occurs to me that we will probably also want more readable URLs at some point too. (`https://wevote.us/measure/wv02meas119` and `https://wevote.us/office/wv02off1016` leave something to be desired...)

**Comment by alexthornton** [comment]
Ok. I'll see what I can find out about the deploy process.

Regarding readable URLs, those measure identifiers are more the responsibility of the application (probably backend). It will likely be more challenging to automatically generate a sitemap for those so I suggest leaving that as an incremental improvement after we have a basic sitemap.

**Comment by ixley** [comment]
@alexthornton Right – readable URLs would be a separate task. The potential drawback to not getting our URLs in order first is that it means 'needing' 301 redirects when we change them (if we want to keep page rankings), but realistically, I'm guessing our search engine rankings won't be significant enough to matter at this stage of the game anyway.

**Comment by clapinton** [comment]
@ixley @zachmonteith On the subject of sitemap, adding a robots.txt is also a good idea, specially if we don't want search engines to waste crawlers in specific pages, like user accounts.

I worked in Marketing for a startup recently and had to fix some SEO issues, so I ended up diving into the subject and can be of help on that front. I'd say we expand more on that once we leave alpha, but sitemap and robots are a good place to start.

**Comment by ixley** [comment]
@clapinton awesome. If you have some experience there, it'd be welcome. Feel free to add an issue with the relevant info (and to take it on if you're volunteering).

**Comment by clapinton** [comment]
@ixley Will do. I'll check for tech changes that we can work on at this point.

**Comment by DaleMcGrew** [comment]
For now we will rely on getting picked up by search engines dynamically.
