### ISSUE TITLE
Keywords needed for SEO

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#527]
We need to integrate keywords into webapp, to help boost our Search Engine Optimization.  Might be worth having specific keywords for specific parts of the site, like including "ballot" on ballot page, etc

quick brainstorm of some good keywords:
"election", "ballot", "voting", "opinion", "proposition", "initiative", "measure", "candidate", "senate", "governor" etc etc

**Comment by ixley** [comment]
Let's deprioritize this one for now. My understanding is that keyword value is dubious in SEO these days. We will get more value from relevant page titles, descriptions, and headings.

**Comment by DaleMcGrew** [comment]
I believe we are covered on keywords given our recent adoption of Helmet.
