### ISSUE TITLE
Address doesn't fit on top

### ISSUE THREAD

**Issue by nf071590** [wevote/WebApp#53]
When address is populated in the header region, it goes beneath the icons to the left

**Comment by nf071590** [comment]
I would prefer to put the location/address on the left of all the icons and let the icons float up against the right border and stay flush

**Comment by pertrai1** [comment]
:+1:  On alignment of location

**Comment by pertrai1** [comment]
@DaleMcGrew Do you want me to do anything with the ellipsis on this before end of this milestone?

**Comment by DaleMcGrew** [comment]
Might as well -- we need to solve the problem of long addresses very soon. Thanks.

**Comment by pertrai1** [comment]
Ok, position it in the center as well?

**Comment by DaleMcGrew** [comment]
Either of these (whichever is easier, or in this order of preference if equally easy/difficult):
1) centered between "My Ballot" and the 4 icons
2) ~100px to the right of "My Ballot"
