### ISSUE TITLE
Office Pages stuck in infinite Loading

### ISSUE THREAD

**Issue by luojxxx** [wevote/WebApp#532]
### Please describe the issue (What happens? What do you expect?)
The page makes the http request to the api and gets back a response with the office object. However, the page does not load.

The issue may be the way the information is passed through the actions/stores. Researching the issue further.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to the wevote main page
2. Type in president in the search bar
3. Click on the first/only drop down from the search bar, it's the president as a quick link (http://wevote.us/office/wv02off1)
4. As you can see the page doesn't load but the page does get http response from the api containing the necessary information.

**Comment by luojxxx** [comment]
Further digging shows that the object is being retrieved successfully in OfficeStore, so it seems to be an issue with it not being passed properly to the Office view. Will try to implement a fix.

**Comment by luojxxx** [comment]
The getOffice function within OfficeStore is trying to
`return office_list[office_we_vote_id]`
However, office_list is only a single object without an ID/key. So currently it errors here and _onOfficeStoreChange receives and undefined variable. So by using
`return office_list`
_onOfficeStoreChange is now able to correctly retrieve the office object and set it's state.

However, for some reason setState does not re-render the page. You must refresh in order to display the information.... Hmmm.....

**Comment by DaleMcGrew** [comment]
Fixed
