### ISSUE TITLE
Followed people/orgs don't appear in list on candidate/measure pages

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#534]
### Please describe the issue (What happens? What do you expect?)
When I visit a candidate/measure page, I expect to see the people/orgs I follow that have posted positions or statements on that candidate/measure.

Instead, I see a position rating bar and counts, but not the actual position items. I can only see orgs/people that I do not follow.
![image](https://cloud.githubusercontent.com/assets/160662/19141070/19fadd08-8b47-11e6-9df8-401f433883e0.png)

Not sure if these are related errors or not...
![image](https://cloud.githubusercontent.com/assets/160662/19141066/142f2992-8b47-11e6-9f86-5ec609d80702.png)

### Steps to reproduce the problem (1, 2, 3...), including links
1. Sign in
2. Go to a candidate or measure page (https://wevote.us/measure/wv02meas108)
3. Follow someone on that page with a position
4. Anticipated bug: they will no longer be listed on that page

**Comment by DaleMcGrew** [comment]
Fixed.
