### ISSUE TITLE
Organize Github Issue labels

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#535]
Low priority, but thought it might be helpful to clean up our issue labels a bit.

I found this approach useful - color coding by type. It wouldn't be appropriate to copy their labels directly, but I appreciate the structure and breakdown.
https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

**Comment by ixley** [comment]
Outline/Proposal for labels here: https://docs.google.com/document/d/13Vq_xeOGTF1ftc3wCoBLoNP5c7Ox8y-RxpllCrstZZ4/edit?usp=sharing

**Comment by ixley** [comment]
@DaleMcGrew @zachmonteith 
Tagged [issue labels](https://github.com/wevote/WebApp/labels) for deletion by prepending with `x-`. Could you guys just let me know if you object to removing any of these?

- **Waiting Feedback** - this hasn’t been used. If we want something like this, it could go in the ‘Pending’ category.
- **Ready** - not sure what this is for
- **Duplicate** - We haven’t encountered this yet. Could be added as a label in the ‘Inactive’ category down the road.
- **Code Review** - should be signaled by pull request or manual request in rare cases
- **QA Testing** - this should probably be part of an established process rather than something attached to individual issues.
- **Browser Compatibility** - overly specific. Can fall under HTML/CSS, Visual Design, etc.
- **Backlog** - What does this imply? Low priority? Pending prioritization? We can probably come up with a better way of triaging issues.

I also wanted to see if there was a better way to address priority than the Priority 1, 2, 3 labels. If you guys are attached to them, that's fine, I just wanted to bring it up since it seems like we could probably upgrade backlog ordering with a different method. (Perhaps [ZenHub](https://www.zenhub.com))

**Comment by DaleMcGrew** [comment]
I am archiving this for future consideration.

**Comment by ixley** [comment]
I already implemented some of my proposed changes and recently removed the unused ones that I flagged for deletion a few months back.
