### ISSUE TITLE
Can't remove 2nd unverified email address from account

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#544]
### The issue

I accidentally added an additional (unverified) email address when attempting to invite someone as a friend. (This is probably an edge case since the second email was entered in the 'from' email field in the invitation flow.) Whenever I log in with the linked account now, it shows the additional email address as unverified, but I cannot remove the email.
### Steps to reproduce the problem

_This is approximately how I encountered the bug. If recent changes do not allow for recreating this flow, just check behavior to make sure a user can't end up stuck in this state (with an unverified second email that can't be removed.)_
1. Sign in via email.
2. Go to the invitation screen and enter an email to invite, but enter a different email as the sender email.
3. On the sign in screen, if the second email shows as an unverified email, attempt to remove it.

![image](https://cloud.githubusercontent.com/assets/160662/19369386/e294cb3a-9159-11e6-83a2-3b8bb35aa14c.png)

**Comment by DaleMcGrew** [comment]
@ixley what happens when you click "Remove Email" for waltfrench?

**Comment by ixley** [comment]
@DaleMcGrew Nothing happens when I click "Remove Email".

**Comment by ixley** [comment]
Attempting to invite friends with another sender email has again added it as an additional unverified email address (that I can't remove).

![image](https://cloud.githubusercontent.com/assets/160662/19449326/fad73c5c-9459-11e6-97fd-7d3c8606788b.png)

**Comment by DaleMcGrew** [comment]
Hi Jeff, can you please verify this is fixed?

**Comment by ixley** [comment]
Yes, this was fixed previously. I haven't noticed any related/additional issues with this behavior so far.
