### ISSUE TITLE
Clicking 'Send Verification Email' returns confusing alert message

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#545]
### The issue

Entering my email address and clicking 'Send Verification Email' returns a confusing message stating 'That email is already being used by another account'. The dialogue includes a way to continue sending a verification email but the whole experience is confusing. 

If the email is known and there is an account associated with it, the default action should be to send a sign in link email. Clarification around the intended flows might help clear this up.

![image](https://cloud.githubusercontent.com/assets/160662/19369603/45204bfc-915b-11e6-8a5a-4bf275803409.png)
### Steps to reproduce the problem

I'm not clear how common this case is, but my email seems to trigger this, as displayed.

**Comment by DaleMcGrew** [comment]
Thank you @ixley -- great bug report. I can fix this.

**Comment by ixley** [comment]
Not sure if this is related, but just now I got this message after signing in via email link, which again, is misleading.
![image](https://cloud.githubusercontent.com/assets/160662/19407363/062157b6-9255-11e6-9fab-71d714b17b89.png)

**Comment by DaleMcGrew** [comment]
Thank you Jeff, I will fix this too.

**Comment by DaleMcGrew** [comment]
Closing this since we are reworking the email sign in system.
