### ISSUE TITLE
Multiple requests for the same org data

### ISSUE THREAD

**Issue by nf071590** [wevote/WebApp#55]
My network tab shows 3-5 requests for each unique organization on the more opinions page.

![network duplicate requests](https://cloud.githubusercontent.com/assets/7058732/13145941/657c9c52-d621-11e5-87d8-3bde2a290e8e.jpg)

**Comment by DaleMcGrew** [comment]
We can fix this after we complete version 1.

**Comment by DaleMcGrew** [comment]
@nf071590 is this now resolved with the fix to https://github.com/wevote/WeVoteServer/issues/85 ?

**Comment by DaleMcGrew** [comment]
Verified.
