### ISSUE TITLE
Can't edit address (consistently)

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#550]
### The issue
When entering a new ballot address, the new address usually doesn't stick.

### Steps to reproduce the problem
1. Click edit link on /ballot page and enter: `4209 Park Blvd, Oakland, CA 94602`
2. Click Save. -- Address does not update. No error or other indication is given. Old address simply persists.
3. Click edit again and enter (slightly modified): `420 Park Blvd, Oakland, CA 94602` -- address should update correctly.

I couldn't figure out what was happening, but some addresses seem fine, while others get 'rejected' but fail with no error message – the address simply does not update. Seems at least partially related to the street number...

**Comment by DaleMcGrew** [comment]
Thanks Jeff, I'm seeing this too. I will take a look.

**Comment by DaleMcGrew** [comment]
Fixed
