### ISSUE TITLE
Can't send email invitations

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#554]
### The issue

When attempting to invite friends in We Vote, after entering an email to invite and then a sender email, the loading icon appears and then hangs.
### Details
- I'm signed in to my account, which has Facebook, Twitter, and email accounts linked.
- I have been entering my primary email tied to these accounts (jfre...@ixley.com)

Console error:
![image](https://cloud.githubusercontent.com/assets/160662/19448881/6f4247b4-9458-11e6-95b6-03cd73aa479c.png)

**Comment by DaleMcGrew** [comment]
Hi Jeff, can you verify that this is fixed?

**Comment by ixley** [comment]
Yes, appears to work. I did not confirm the email verification for a new email account since this bug was specifically around initiating an invite from a non logged in state.
