### ISSUE TITLE
My Account page showing same email twice

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#555]
### The issue

When I log in, my account page shows multiple entries for my email handle.
I'm not sure what's causing this, but for reference, both my Twitter and Facebook accounts use this email as the primary email, and I have manually entered this email in the sender field for We Vote invitations. In the image below, the unverified emails are ones that I have accidentally or experimentally entered (and now cannot remove). Possibly related?

<img width="268" alt="redundant_emails" src="https://cloud.githubusercontent.com/assets/160662/19449235/923ba836-9459-11e6-84ba-13390a52de6b.png">

**Comment by DaleMcGrew** [comment]
Hi Jeff, can you please verify this is fixed for you?

**Comment by ixley** [comment]
Confirmed.
