### ISSUE TITLE
measures should display on which ballot (city, state, election) they appear: phase 1

### ISSUE THREAD

**Issue by zachmonteith** [wevote/WebApp#558]
Measure pages should indicate their state, city if relevant, and in which election they'll appear.  This is especially critical if a user searches for and finds a measure that isn't on their personal ballot, as it won't be clear where and when this measure will be voted on. 

Phase 1 will be to include the info already being passed in from the API call: State and Election ID.

**Comment by DaleMcGrew** [comment]
Verified. Great work @zachmonteith!
