### ISSUE TITLE
Remove cookies for storing temp data

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#57]
Remove these cookies, and any dependencies on them: location, voter_id
Instead of using the cookies, reference the data in the VoterStore.
Leave these cookies in place: voter_device_id, voter_api_device_id

**Comment by pertrai1** [comment]
@DaleMcGrew when was the last discussion on this topic? Maybe can be an ongoing sprint discussion that is not part of a milestone, or I guess it can be. Just can be moved to the next milestone at the end of the current one.

**Comment by DaleMcGrew** [comment]
Moved from main description to a comment: 
From @DaleMcGrew:
Hi Nick, I don't think its a good idea to store the voter's address (or the voter_id) in a cookie, but should instead use the VoterStore (in memory) as the single source for the location to display. I have seen scenarios over the years where data stored "temporarily" in cookies can quickly get out of sync with the live data, and this creates debugging nightmares.
=========
From @nf071590:
Dale, also on your point about storing data in cookies… The idea was basically just to have records there so that we don’t have to reach out to the api server again if we don’t need to. They aren’t the master records and the front-end will reach out to the server if it needs to. for location, users can save a new address into the cookies by using address save. It is kind of a one way path into cookie storage and if they exist then don’t make all the server calls and render the app, otherwise, create the voter because it’s their first time visiting and then render the app. I do think that’s a good point but I don’t plan on using the cookies except for a logical short circuit. then everything will be stored in memory like you suggested.
Because I think you are right essentially about the point you made and I don’t want to run into those nightmares.
Cookies are only being used so the browser can remember information about the user and try to use what the browser knows about the user before having to speak with API server.
-------
From @DaleMcGrew:
Thank you Nick. Can’t we get location (for example) from the VoterStore (stored in RAM) once they’ve been retrieved from the API, instead of looking in a cookie?
---------------
From @nf071590:
Well we have to speak to the api server to get the address and I’m trying to prevent network calls if possible. We should be able to write the address for next time they load the application.
yeah, we don’t look in the cookie again I don’t think once we get the data.
we jsut write it to a cookie so next time they load the app we can default to what they have saved last
instead of reaching out to the API
That’s what I mean by not using the cookies as a master record.
It just saves for help later down the road if we need it
We can start with a cookie instead of making network calls
I dont know… does that make sense?
I think that once we get some endpoints modified and have better flow between endpoints and user recognition then this will be modified anyway and we can make one call to get user info or something… For now this should maintain enough stability for the purpose
If they see their address is all F’d up when they load the app then they click on it andd save a new address and their cookie will update
next time they load the app, the cookie will be read and it will be the new address they havae updated it to
It’s just a measure for preventing network calls that would essentially slow down the experience
-------
From @DaleMcGrew:
Definitely a rich topic for discussion. I see your points. I think we can use cookies for now and talk about the data-caching strategy we want to adopt after we get an MVP working.

**Comment by nf071590** [comment]
We should think about storing cookies on the browser from the server using the set-cookie headers. Then we can read the cookies on the front-end when the application response is returned and not have to manage reading and writing on the front-end, only reading.

The server can put the location into the cookies and possibly device_id and other key/values we want to use on the front end.

**Comment by DaleMcGrew** [comment]
That shouldn't be a problem. Can you create a new issue for "Server should also return the voter device ID set header" in the WeVoteServer repo? @nf071590
Since the same voterRetrieve API endpoint (which currently returns a new voter device ID if one doesn't already exist) will be used for iOS and android apps, I'm curious to find out if those apps would be able to use a "set cookie" header from the server as well.  My guess is that they would be able to ignore that header if they can't use it as-is.

**Comment by lisamcho** [comment]
Sounds like a good idea. I am going to refactor voterStore over to be a FluxMapStore like the others while I'm doing this.

**Comment by DaleMcGrew** [comment]
Verified. Great work Lisa!
