### ISSUE TITLE
Item visibility (public/friends) is not reflected by setting

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#575]
### The issue

Many items I set to public visibility are shown as public, however (possibly due to a previous data migration?), many of those positions, including the visibility settings are NOT reflected in my account. Going in and reselecting or editing the position, as well as toggling the audience visibility setting don't seem to have any effect on what was already publicly displayed.

I'm not sure whether this is unique to my account, introduced by a single data migration 'hiccup,' or indicative of a larger issue.

![image](https://cloud.githubusercontent.com/assets/160662/19577485/702d2e70-96cc-11e6-96e5-453e9d864ee9.png)

**Comment by DaleMcGrew** [comment]
Hi Jeff, can you check to see if my most recent update fixed this issue?

**Comment by ixley** [comment]
Appears to be fixed.
