### ISSUE TITLE
Your position statement displays temporarily on the wrong position

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#579]
### Steps to reproduce the problem (1, 2, 3...), including links
1. Enter a position 1 on one measure and post it.
2. Search for position 2 and go to it.
3. Your position 1 shows up as if you entered it for position 2.
   Your position 1 disappears from position 2 when you refresh the position 2 page.

**Comment by zachmonteith** [comment]
after some preliminary testing, this appears to happen only with measures, not candidates

**Comment by jpellizzari** [comment]
@DaleMcGrew I'm going to take a look at this one. I can't assign it to myself unfortunately

**Comment by DaleMcGrew** [comment]
I am merging this with Issue #533
