### ISSUE TITLE
Duplicate (partially linked) ballot items

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#580]
### The issue

My ballot page includes duplicates of most California propositions and some candidates (like Hillary/Kaine) with slightly different name formatting. 
- I'm assuming this is a data issue, but I am unable to remove or remedy the redundancies myself. 
- In most cases, editing one affects/updates its duplicate, but removing a position entirely does not necessarily remove (or update) the duplicate. 
- The items all show up under the same ballot as well, as opposed to being associated with a different ballot, primary, etc.
- I'm not sure whether it's related, but my account still shows two identical email handles as being associated with my account. (#555)
- This is likely related to https://github.com/wevote/WebApp/issues/575

![image](https://cloud.githubusercontent.com/assets/160662/19663287/28fa2ee6-99f0-11e6-94be-6366fae65586.png)

**Comment by ixley** [comment]
Measures are now mostly synced in order, but still duplicated. The occasional duplicate is out of sync though. @DaleMcGrew 
![image](https://cloud.githubusercontent.com/assets/160662/19880242/c61893e8-9fb8-11e6-8b77-23c655daffde.png)

**Comment by ixley** [comment]
Got an extra one! Seemed to appear after editing as the entry with a Support position (which I can't remove) no longer had the comment. Additionally, the visibility toggle doesn't necessarily seem to have an effect as even when the friends-only setting is selected, I can still see these as public on my page (when not logged in).

**Logged in**
![image](https://cloud.githubusercontent.com/assets/160662/19904316/545c0a06-a02f-11e6-9a16-142973f42a5d.png)

**Publicly visible (not logged in)**
![image](https://cloud.githubusercontent.com/assets/160662/19904345/75689ffc-a02f-11e6-82ae-11640b99515f.png)

**Comment by DaleMcGrew** [comment]
Thank you Jeff! I am almost done with a "de-duplication" routine to combine duplicates, but knowing what is creating duplicates is very valuable!

**Comment by ixley** [comment]
YES! Hoped the quasi real-time updates would be at least marginally helpful.

**Comment by DaleMcGrew** [comment]
Hi Jeff, can you see if my latest update fixed this?

**Comment by ixley** [comment]
Woohoo! There were a few remaining inconsistencies that I was able to squash by toggling settings/positions, and then one tiny remaining inconsistency detailed below.

The one remaining inconsistency I see is that for me, the 'Hillary Clinton/Tim Kaine' candidate item has an inconsistency that is likely a holdover from duplicate candidate/measure items. This appears to be an incredibly minor issue, but I'm noting it since it's likely related.

The difference is a subtle one – a `/` instead of a `'` divider between the ticket names. The two used to appear as redundant items for me, now the `/` version shows up in my ballot, but the `'` version persists on my guide page (`/ixley`). Removing my position, statement, and visibility, and then re-adding them did not appear to have an effect (the `'` version persisted). Adding a public position to another Presidential candidate (Trump/Pence) shows the correct version.

<img alt="candidate_item" src="https://cloud.githubusercontent.com/assets/160662/19909900/0707d966-a047-11e6-93ad-17da0ff98932.png">

**Comment by DaleMcGrew** [comment]
The worst of this has been fixed. Closing issue.
