### ISSUE TITLE
Edit text on "address/ballot" page (entering "los angeles" w/o address shows San Francisco items)

### ISSUE THREAD

**Issue by ColettePhair** [wevote/WebApp#581]
### Please describe the issue (What happens? What do you expect?)

When I enter the city of LA without a full address, the wrong ballot items appear.  But when I enter a full LA address, it seems to work.

A quick fix would be to edit the text on the page to say below in smaller print something like "Make sure to enter your full address for accurate results."
### Steps to reproduce the problem (1, 2, 3...), including links

1) Enter "los angeles" in "Your address/ballot" (https://wevote.us/settings/location), hit enter
2) View items that appear on your ballot page

**Comment by DaleMcGrew** [comment]
We are adding incremental address completion to address this issue. Thank you for this suggestion!
