### ISSUE TITLE
Inappropriate message on triggering email sign in verification

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#583]
### The issue
When using email verification to sign in, after entering my email, I get the message "That email is already being used by another account." Along with "Please click "Send Login Link in an Email" below to sign into that account."

The first part of this message is confusing and inappropriate. When triggering attempting to sign in via email verification, the default behavior should be to generate a login email with no other conflicting message.

*I thought this was addressed previously, but it appears to have returned (or wasn't actually fully addressed).

### Steps to reproduce the problem
1. Go to /more/sign_in
2. Enter an email address and click 'Send Verification Email'

![image](https://cloud.githubusercontent.com/assets/160662/19845874/4d9a20c8-9ef8-11e6-8044-ac61fb11fe62.png)

**Comment by alexthornton** [comment]
After digging into this a bit, this appears to be more like a backend than frontend bug. Let's look at the API interaction here.

The request from the React app is: `https://api.wevoteusa.org/apis/v1/voterEmailAddressSave/?voter_device_id=UNIQUE_ID&text_for_email_address=alex.thornton%2Bwevote%40gmail.com&make_primary_email=true`

The response is:

```json
{
    "email_address_deleted": false,
    "verification_email_sent": false,
    "email_address_list_found": false,
    "email_address_already_owned_by_other_voter": true,
    "voter_device_id": "DEVICE_ID",
    "link_to_sign_in_email_sent": false,
    "email_address_found": true,
    "email_address_we_vote_id": "wv02email171",
    "status": "EMAIL_ALREADY_OWNED_BY_ANOTHER_VOTER",
    "delete_email": false,
    "success": true,
    "make_primary_email": true,
    "email_address_saved_we_vote_id": "",
    "text_for_email_address": "alex.thornton+wevote@gmail.com",
    "email_address_list": [],
    "email_address_created": false
}
```

Note how `email_address_already_owned_by_other_voter` is already set to `true`. The React app doesn't know any better so it shows the error message.

**Comment by alexthornton** [comment]
Adding a clarification to the analysis above, I'm not at all implying that this isn't a bug. Rather, I think this bug is should files in https://github.com/wevote/WeVoteServer.

**Comment by DaleMcGrew** [comment]
Closing for now since we'll be updating this with a new design.
