### ISSUE TITLE
Successive 'new' invitations send the same (unusable) single-use link

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#584]
### The issue
Inviting someone (that has already been invited) but is not currently a friend appears to use the same authentication link that has been sent for previous invitation attempts. If the link has been clicked (even if the person is not currently a friend), the link is invalid and triggers the message "Invitation not found. You may have already accepted this invitation. Invitation links may only be used once."

_I came across this because I was actually trying to explore another apparent bug where accepting an invitation request if the receiver is not signed in appears to mess up the intended relationship. This still needs more exploration as this bug blocks reproduction._

![image](https://cloud.githubusercontent.com/assets/160662/19846477/df7f1238-9efc-11e6-8b9b-53c791e2a693.png)

### Steps to reproduce
Not sure how best to reproduce, but try:
1. Generating an invitation w/ account A
2. Accepting invitation for account B (when not signed in OR when signed in as account A - not sure if one of these cases specifically triggered the issue). 
3. The invitation should be effectively voided. If the friend link was adequately confirmed, remove the the friend relationship. Confirm account A and account B are not linked as friends.
4. Send another friend invitation from account A to account B. (The expected bug behavior is that the link generated will be the same as before and future attempts and will not work because it has already been 'used'.)

**Comment by DaleMcGrew** [comment]
I am going to close this issue and weave a fix into a refactoring of this feature I will be doing soon.
