### ISSUE TITLE
Local ballot items are still on We Vote but do not appear in my ballot list

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#587]
### The issue
There are a number of local ballot items that are in the system, but no longer show up for me in my ballot. The two I previously took positions on are still visible on my page (`/ixley`) but still not in my ballot. Additionally, there are others that I know exist (in We Vote) that also don't appear on my ballot. I have been able to find a few of them via other users who have made public positions on them. Similarly, once I take a position on one, it will show up on my page, but still not on my ballot.

### To reproduce
1. Enter any Oakland address (even just `Oakland, CA` should work)
2. Look for Measure RR in your ballot list (https://wevote.us/measure/wv02meas143)

I am assuming this is a data issue, but it's curious because the entries obviously still exist, but are not appropriately associated with their current ballots.

**Comment by DaleMcGrew** [comment]
Hi Jeff, this has to do with how we assign measures and offices to a person's ballot. Solving this for the next election we run will require some work on the data side, but I am going to close this issue for now. Thank you for capturing it!
