### ISSUE TITLE
Slack Sign Up: Allow new volunteers to self-register for We Vote Slack

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#594]
I am very impressed with how easy CodeCorps makes it to sign up for their Slack Channel:
http://slack.codecorps.org/

To complete this issue, set up the same feature. They said they used this:
https://github.com/rauchg/slackin

**Comment by DaleMcGrew** [comment]
Dale can get an API token here:
https://api.slack.com/docs/oauth-test-tokens

**Comment by pertrai1** [comment]
This might be of assistance: https://bryanhadaway.com/how-to-create-a-slack-chat-community-with-auto-invites/

**Comment by DaleMcGrew** [comment]
We won't be tackling this issue at the current time.
