### ISSUE TITLE
Organization Page, Create & Style

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#6]
Correct Invision link here: https://projects.invisionapp.com/share/2R41VR3XW#/screens/94226088
File location: /src/js/routes/Guide/PositionList.jsx
In interface: http://localhost:3000/guidepositions/wv02org111

**Comment by pertrai1** [comment]
@DaleMcGrew From the mockup, I believe that this is the correct view that has been styled from #36

**Comment by DaleMcGrew** [comment]
Hi Rob, somehow I pasted the wrong Invision link above, and need to run right at the moment. I still need to migrate the Organization page (with the basic page layout so you can style it) into WebApp.

**Comment by pertrai1** [comment]
@DaleMcGrew - Ok, I am available most all day today so we can catch up and look at the 50% left to do for this version 1 release. :

**Comment by DaleMcGrew** [comment]
Basic framework in place. Need styling and population with live data.

**Comment by DaleMcGrew** [comment]
Hi @lisamcho I finished a first version of positionListForOpinionMaker:
https://api.wevoteusa.org/apis/v1/positionListForOpinionMaker

Test with:
https://api.wevoteusa.org/apis/v1/positionListForOpinionMaker/?csrfmiddlewaretoken=thMROZneWOjA2nBBxQRjaMd5a1gy2o5j&voter_device_id=1JHUUGG2kUrbeiaoxTVO3j8mtlbORspEMSjYlv72OGQCk0i2tdgUQ8Y3cAHM3CsJR2rNjAicGhHkoTbxCxQMLFq2&kind_of_opinion_maker=ORGANIZATION&opinion_maker_id=&opinion_maker_we_vote_id=wv02org1310&stance=ANY_STANCE

It currently returns some candidate duplicates. I need to create a script that removes Candidate duplicates from the database.

**Comment by DaleMcGrew** [comment]
Looks great! This is a huge step forward, having a summary organization page. I'll create new issues for any other needed modifications. Thank you @lisamcho.
