### ISSUE TITLE
Create basic interaction for an 'intro tour' to We Vote

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#615]
Add functionality for a basic 'intro tour' for first-time We Vote users to orient them to the benefits and basic features of We Vote. In the absence of design or content, focus on basic interactions and features agnostic to content.

The goal of this feature will be to give first-time visitors/users a basic overview of what high-level benefits/abilities to expect. It should _not_ attempt to orient them to specific functionality.

## Overview
- Tour will be a multi(3-4)-screen 'app tour'
- Should be responsive (work on all screen sizes and accommodate both touch devices and desktop browsers)

### UI/Interaction
- Swipe left to advance on touch/mobile devices
- Dots to indicate position/progress
- Include more prominent clickable arrow(s) for non-touch devices
- Make full-screen on smaller screens, and constrain to a reasonable TBD size on larger screens (single breakpoint for responsive design)

### Additional considerations
- Don't worry about content but assume a single call to action (registration) on (only) the last screen. That is to say, focus primarily on the content containers for the time being. If the plugin supports things like nice transitions within a screen, that's fine, but I wouldn't prioritize it.
- If selecting a plugin, ideally focus on something well-supported (popular), content agnostic, and easy to customize (something with bare bones and editable out-of-the-box styling and potentially customizable behavior)

## Reference
- [Basic design brief](https://docs.google.com/document/d/1QEzIu8GIuxcXkcJQQlUYl7BNQc9AeedwZu3Ktjl8f7g/edit#)
- [In-progress prototype](https://app.moqups.com/DaleMcGrew/Xa9gsWkvx0/view/page/a0dc9d6cd)

**Comment by sarah-clements** [comment]
Per another of Jeff's suggestions, there should be a clear sense of what happens above a certain screen size (ideally determined and conveyed by the designers).

**Comment by ericogawa** [comment]
Something along these lines, perhaps? (from the Patreon responsive website) (Attempting to upload screen shot)
![screen shot 2017-01-18 at 12 00 32 pm](https://cloud.githubusercontent.com/assets/13991758/22080807/ce828ad4-dd75-11e6-9ea7-d787ffa15012.png)

**Comment by ericogawa** [comment]
I suspect with the proper image file(s), we could resize all the way to full screen on mobile. We'd have to find some images that are aesthetically functional across a wide range of "croppings"

**Comment by sarah-clements** [comment]
The desktop snapshot looks great with the arrows. For mobile, I've gotten
the image to go to 100% viewport by tinkering with the CSS (thanks to Jeff)
- its very much improved now.

**Comment by ericogawa** [comment]
For sure. Something else you see is an automated slideshow in the main box--removes need for the user to comprehend the clicking/swiping interaction; higher likelihood all the value props get seen.

**Comment by ericogawa** [comment]
And of course there's always the option to throw out the slideshow all together and just have everything in one long scrollable "slab" with call to action buttons along the way....here's Squarespace's version of this. [https://www.squarespace.com](url) Possible Search Engine Optimization perks to doing it this way.

**Comment by ericogawa** [comment]
Sorry, no idea why that link is not working. Just google Squaresoft and check out their main page to see what I mean.

**Comment by ixley** [comment]
@ericogawa Thanks for your comments and input. There are some good points you bring up that underscore the value of figuring out the intended usage and proposed implementation details before building too much. Please make sure to coordinate w/ @DaleMcGrew and @KIVA7777 (if he is working on design for this) to confirm the design satisfies intended use cases for both mobile (touch) and desktop.

**Comment by DaleMcGrew** [comment]
Great work @sarah-clements and @KIVA7777!
