### ISSUE TITLE
Ballot page is missing margins/padding on the left & right

### ISSUE THREAD

**Issue by flobotbear** [wevote/WebApp#624]
### Please describe the issue (What happens? What do you expect?)
When you make the viewport more narrow (less than 692px -- or whenever the left sidebar is hidden), the right column with "US 2016 General Election" tex and the candidate cards lose padding/space on the left and right sides.

![ballot_-_we_vote-nomargins](https://cloud.githubusercontent.com/assets/823927/22319691/ec217bda-e339-11e6-8f19-acfb37d0b332.png)

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to https://wevote.us/ballot
2. Make your viewport narrow enough to lose the left sidebar

This has been observed on the following browsers:
- Chrome
- Firefox
- Safari
- Mobile Chrome

Interestingly the screen before you put in the zipcode for where you are registered to vote, the padding/spacing is still there.

**Comment by flobotbear** [comment]
Dale helped me pinpoint the issue -- it seems to be coming from ``` './components/intro-story';``` bc when we comment that out, the spacing is back. Will make sure the fixes don't end up messing up the work for the intro

**Comment by DaleMcGrew** [comment]
Resolved!
