### ISSUE TITLE
Include First and Last Name in the Add Friends "Connect" flow

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#635]
Currently in /src/js/components/Friends/AddFriendsByEmail we accept a comma separated list of email addresses. We want to copy this current code to AddFriendsByEmailBulk, and then modify the existing file to also accept First and Last name.

Slack has a nice interface for this (we will not offer "Connect your Google Contacts"):
![screen shot 2017-01-30 at 9 56 00 am](https://cloud.githubusercontent.com/assets/7756031/22434785/5bf068d6-e6d2-11e6-974e-ad05bfced51d.png)

Here is once you have added a second line:
![screen shot 2017-01-30 at 9 57 33 am](https://cloud.githubusercontent.com/assets/7756031/22434837/8fdf15b6-e6d2-11e6-85db-c81d37e15315.png)

We can offer to invite up to 5 friends at once.

Please also upgrade the WeVoteServer API End point friendInvitationByEmailSend to take in "email_addresses_array"
Implementation notes here: https://docs.google.com/document/d/1b4WQ3zAr6Jh9-rmqJXoQ553lL7e6spomCw0P6XPU-QY/edit

**Comment by DaleMcGrew** [comment]
Hello @clapinton this is all checked in and ready for you.

**Comment by clapinton** [comment]
Thanks! I'll pull it and start working on it.

**Comment by DaleMcGrew** [comment]
Thank you Eric and Neelam, this is in good shape!
