### ISSUE TITLE
"Bookmark for later" action has an awkward outline

### ISSUE THREAD

**Issue by flobotbear** [wevote/WebApp#641]
### Please describe the issue (What happens? What do you expect?)
When you click on the "Bookmark for later" icons in the app, you see a blue fuzzy highlight (on Chrome) around an area once you click in.

**Chrome**
![bookmark-chrome](https://cloud.githubusercontent.com/assets/823927/22536889/964a8bc6-e8ba-11e6-98e5-61ef9860e6e6.png)

**Firefox**
![bookmark-firefox](https://cloud.githubusercontent.com/assets/823927/22536895/9a8f0c0c-e8ba-11e6-8c53-eb2a873bfaba.png)

**Safari**
![bookmark-safari](https://cloud.githubusercontent.com/assets/823927/22536902/a5ecb9f0-e8ba-11e6-88cf-c4a07dc97777.png)

### Steps to reproduce the problem (1, 2, 3...), including links
Go to https://wevote.us/ballot and click on the "Bookmark for later" icon.

**Comment by ixley** [comment]
FYI: [Don't remove CSS outlines!!](http://a11yproject.com/posts/never-remove-css-outlines/) (without replacing them with something comparable for accessibility)
