### ISSUE TITLE
Replace 'app-font' icon images with image files

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#649]
The icon font introduced to add placeholder (and other) iconography across the app were helpful in the beginning, but have gotten more cumbersome to work with, especially when mixed with normal images.

![image](https://cloud.githubusercontent.com/assets/160662/22842528/57cd06cc-ef8a-11e6-8921-b104a9cd7c88.png)

1) Convert existing icon font images to SVGs and size and reference them to match the context they're used in.
2) Replace all instances where they are used with paths to SVGs - there is a plugin (`react-svg-icons`) you can use to pull in SVGs, particularly if the color needs to be customizable, like for various UI states like in the navbar.
    - If an image from the custom icon font is not being used, it doesn't need to be converted and added.
3) Remove the [`app-font`](https://github.com/wevote/WebApp/tree/b1961e95e34819ac6c8ad14609cb3ec9aea986c1/src/sass/base/fonts) files and all references (mostly CSS)

**Comment by Anoninnyc** [comment]
@ixley So, we would convert to something like [this](https://jsfiddle.net/5zxdzftf/1/), save one per file, then use react-svg-icons to point to each file?

**Comment by ixley** [comment]
@Anoninnyc Yes, that's my thinking. A few things to consider...
- Again, this is low-priority and a 'chore,' meaning it could be good if you're interested or otherwise want to get more familiar with this type of thing in the app, but doesn't provide a huge amount value on its own.
- In general, I will want SVG files to be 'clean' and well-formed, but since many of these icons will be targeted for replacement with redesign efforts, AND it's easier to clean up individual SVGs than those generated into a font file, this is not a requirement for this story. If you are interested, [SVGOMG](https://jakearchibald.github.io/svgomg/) is a great tool for SVG code cleanup/optimization.
- You should be able to just extract the SVG code from the [svg font file](https://github.com/wevote/WebApp/blob/develop/src/sass/base/fonts/app-fonts.svg?short_path=fe94110) though the code will likely need some conversion (easy to look up).

**Comment by Anoninnyc** [comment]
@ixley: I'm interested in whatever will move the app forward, though the more meaningful the contribution the better. If you want me to do it- consider it done. If you think there are better uses of my time, let me know. 
Re: my skills...
I'm a full-stack guy (70% front end/ 30% backend), 70% of front-end UX(React), 30% UI (html/SASS/css).

**Comment by DaleMcGrew** [comment]
Thank you @bharathdn for fixing this!
