### ISSUE TITLE
Cleanup new 'summary' view styling on /ballot

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#654]
Clean up styling of summary position view on /ballot (on develop branch). The reference design is here: https://app.moqups.com/DaleMcGrew/2vW41QMVXE/view/page/a211a4810

1) For candidates, keep all of these elements on one line:
Name + "follow options" or "positions in your network" + support/oppose

2) For measures, I think the measure description should display above the line that has these two elements:
"follow options" or "positions in your network" + support/oppose

- [x] Use flexbox instead of tables for layout
- [x] break apart styles assigned by context
- [ ] alternate layout for measures: display description above network indicator and buttons
- [ ] ~~alternate style when position is selected?? (still displaying both options)~~

### Pending questions:
- When should text be truncated, and by how much?
    - ![image](https://cloud.githubusercontent.com/assets/160662/22897709/9b997a4c-f1d9-11e6-8e2a-51508de398f5.png)
    - At this time I don't think we need to truncate the measure text

- Should we introduce a new pattern for persistently displaying both (support/oppose) options even after a selection has been made?
    - ![image](https://cloud.githubusercontent.com/assets/160662/22897667/69ee8e60-f1d9-11e6-9d99-2945f081c645.png)
    - At this time I don't think we need to alter the support/oppose display standard (we can discuss and create another Issue if needed)

**Comment by ixley** [comment]
@DaleMcGrew Can you add any additional definition/clarification to this?

**Comment by DaleMcGrew** [comment]
Hi @ixley I just updated the description for this Issue with clarification and answers to your questions.
