### ISSUE TITLE
Reset search box results when...

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#658]
When you type into the global search box, the search results update per character (addition or deletion) — with the exception of all characters being deleted. Search results should not persist in cases when there are no characters in the search box, a result has been clicked on, or the user exits the search.

Update the search box so that the search results reset when:
- the input field is empty (no relevant characters)
- a search result has been selected (user has clicked one of the results)
- the search box has been exited (user has clicked out of the search box to escape without selecting any results)
    - One potential exception to this is if we decide we want _different_ behavior. The search box currently clears when the user clicks outside of it. If search results should persist (instead of being cleared) when a user clicks outside the search box, the search string should persist as well.

**Comment by DaleMcGrew** [comment]
Thank you @clapinton, you nailed it!

**Comment by ixley** [comment]
@clapinton The search string now also persists when a user selects a search results. Can we clear the search string when a user selects a result (or alternatively, update the string to match the selected result)?

**Comment by clapinton** [comment]
Good catch. I just noticed Facebook updates the search bar to the selected result. I'll fix it.

**Comment by DaleMcGrew** [comment]
Hi @ixley these fixes are up on https://WeVote.US and ready for your verification.
