### ISSUE TITLE
Don't exit search box when clicking outside the DOM

### ISSUE THREAD

**Issue by ixley** [wevote/WebApp#659]
When the global search box is open, clicking anywhere else (even to another browser window or within the DevTools inspector) exits/closes it. This is not how it should behave. 

The search results should remain active until:
- a user clicks within the window, but outside the search box or the search results window
- a user clicks on a result (after that click is captured)
Clicking outside the window into the devtools inspector or to another browser window or application should NOT cause the search window to exit.

Ref: See how Facebook's search bar—and other similar overlays—behave.

BONUS points if you feel up to the task of abstracting out a HOC ([Higher Order Component](https://facebook.github.io/react/docs/higher-order-components.html)) to handle various UI overlays. Though this probably warrants further discussion first.

**Comment by ixley** [comment]
BTW - there are existing HOC wrappers that folks have created for this purpose (clicking outside an element) if you want to go that route.

**Comment by Anoninnyc** [comment]
@ ixley My understanding, as per our initial convo was that this was an issue as it slowed development.
For me, fixing solely for the purposes of dev.  (i.e. while developing only, include a module with stoppropgation, or while developing) would be easier than for the purposes of UX, though I can certainly see how this is not user-friendly.

**Comment by ixley** [comment]
@Anoninnyc certainly – don't feel obligated to take this. I should maybe create a separate label for 'UX-bug' (or some such). 

With most projects—but especially with a volunteer project like this—there will always be a tension between trying to do things in a forward-thinking way and just getting things finished/functional. While I _do_ appreciate the value of getting things out the door, as someone focused on UX and project standards, I will also tend to push for things that fall into categories of cleanup or refactoring efforts. 

Again, take what interests you and/or look to @DaleMcGrew for issue prioritization.

**Comment by Anoninnyc** [comment]
@ixley gotcha and thx for response.
If we'd like to create (or look for something) expiliticly to expedite development, I can do that with relative ease. 
Though, addressing the fundamental improper behavior will take longer (for me, at least).

**Comment by clapinton** [comment]
I'm working on #658 which involves this behavior, so I'll take care of this. I haven't worked with HOCs before, but I'll take a look at that too.

**Comment by ixley** [comment]
@clapinton Awesome. I'll be interested to see what you come up with. As a designer, I'm particularly interested in structuring our UI patterns intelligently and my impression is that HOCs could lend themselves well to this effort. Let me know if you want to discuss pattern behavior at all.

I love this example of how to think about HOCs...
<img width="500" alt="img-1" src="https://cloud.githubusercontent.com/assets/160662/23077566/f5c6b782-f4f9-11e6-8243-77002cb4bea9.png">

If you want to try using or referencing existing approaches...
- [react-onclickoutside](https://github.com/Pomax/react-onclickoutside) - just an example - can't vouch for this but superficially looks to fit the bill
- Also, look at how React-Bootstrap constructs some of their [components](https://react-bootstrap.github.io/components.html).

**Comment by DaleMcGrew** [comment]
@ixley does the fix posted by @clapinton accomplish your goals? Thank you!

**Comment by ixley** [comment]
The described issue does NOT appear to have been addressed by #674. The search results window still closes when triggering the inspector, clicking in the inspector, or clicking outside the browser window. 

The only behaviors that should close the search results window are:
- selecting a search result
- clicking inside the DOM/window but not in the search box or results pane (think of the click behavior for escaping a modal)

* I thought this would be simple to address, but it doesn't need to be prioritized for now since it's a relatively small UX bug. I would like to keep the issue in place until it's fixed though.

**Comment by clapinton** [comment]
I wasn't seeing that. I was switching between windows and tabs, but whenever I went back to it, the results pane was still open, so I though it was ok. I just saw it actually instantly opens the tab as soon as I land on the page again. Sorry for missing it.

I did some digging and just found out that it happens because the `onblur` function that we're using on the form (hides the results when we leave the search bar) is also triggered when we switch windows. Any idea on how to fix that? One way would be to remove the `onblur` function and add a listener to all clicks and see if it happened outside the search area, in which case we would close the results pane, but I feel it might be a bit overkill to listen to every click for this situation.

**Comment by ixley** [comment]
Thanks @clapinton - no worries on 'missing' a subtlety of my request. I initially noticed this behavior because using the browser inspector collapses the pane, so that makes sense that it is tied to `onblur`. If you are interested in tweaking this more, feel free to go at it, but also acknowledge that my interest in this subtle UX element is somewhat disproportionate to so many other things that could use attention. 

_I might also eventually try using [react-click-outside](https://github.com/kentor/react-click-outside) to address this since it seems like it might work here._

**Comment by DaleMcGrew** [comment]
Hi @ixley there is a new version up on https://WeVote.US. Are you ok with us closing this issue given the experience on voters is minor compared to the other issues we need to work on?

**Comment by ixley** [comment]
Sure - I can revisit later if inspired.
