### ISSUE TITLE
Typo when signing in with Twitter

### ISSUE THREAD

**Issue by clapinton** [wevote/WebApp#663]
Go to https://wevote.us/more/sign_in -> Hit the Twitter **Sign In** -> Complete the process until success message is displayed:
`Your have successfully signed into Twitter.`

(HTML element: `<div role="alert" class="alert alert-success">`)

Should be `You have successfully signed into Twitter.`

Maybe also change language to `You have successfully signed in with Twitter.`

**Comment by DaleMcGrew** [comment]
Thank you @clapinton, I have fixed this (I will check in later today) and found a few other spots in the code where we mistakenly had sentences start with the text "Your have". Good catch!
