### ISSUE TITLE
"Ready to Vote" view on Ballot page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#664]
On the main ballot page, create a filter (to the right of "All", "Remaining", and "Bookmarked") called "Ready to Vote". 

Please make sure to grab the latest code since others have been working in these files.
- [x] In src/js/routes/Ballot/Ballot.jsx replace "show_expanded_ballot_items" variable with "in_ready_to_vote_mode" and set it based on the filter mode chosen in "BallotFilter"
- [x] Currently this line (~line 261) uses the "BallotItem" component: ballot.map( (item) => \<BallotItem key={item.we_vote_id} {...item} />)  -- Create a copy of the "BallotItemCompressed" and name it "BallotItemReadyToVote"
- [x] Make copies of "MeasureItemCompressed" and "OfficeItemCompressed" called "MeasureItemReadyToVote" and "OfficeItemReadyToVote"

We want to show all measures and offices (from BallotStore.ballot), but when we are rendering the ballot we want to:
- [x] MeasureItemReadyToVote
  - [x] HIDE: support/oppose buttons, position bar, bookmark, description of the measure
  - [x] SHOW IF TRUE: "Supported by you" or "Opposed by you", 
  - [x] OTHERWISE, IF THERE IS A CLEAR WINNER SHOW: "Your network supports" or "Your network opposes"
  - [x] OTHERWISE, SHOW: "Your network is undecided" or "Your network has no opinion"
- [ ] OfficeItemReadyToVote
  - [x] HIDE: support/oppose buttons, position bar, bookmark, description of the measure
  - [x] SHOW CANDIDATE IF TRUE: "Supported by you", and hide all other candidates
  - [x] OTHERWISE, IF THERE IS A CLEAR WINNER IN YOUR NETWORK SHOW: "Your network supports", and hide all other candidates
  - [x] OTHERWISE, SHOW NO CANDIDATES: "Your network is undecided"

**Comment by DaleMcGrew** [comment]
Great work @emilyliza! This is complete.

**Comment by emilyliza** [comment]
Great - thanks!

On Fri, Feb 24, 2017 at 10:33 AM, Dale John McGrew <notifications@github.com
