### ISSUE TITLE
Clicking on ItemTinyOpinionsToFollow should open popup (empty for now)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#665]
In MeasureItemCompressed, ~line 110 we have this onClick handler:
                      onClick={ this.props.link_to_ballot_item_page ?
                        goToMeasureLink :
                        null }

Please remove this onClick handler, and add a similar onClick for ItemTinyOpinionsToFollow that opens a (currently empty) Modal popup.

Sample code showing a working Modal popup is commented out on this component:
WebApp/src/js/components/ballot/PositionItem.jsx

You should be able to execute this sample code on this page:
http://localhost:3000/KamalaHarris
You might need to Follow an organization to be able to get the Modal popup link.

**Comment by Anoninnyc** [comment]
@DaleMcGrew 
Quick Question:
How long does it usually take for your page to "hot reload"? 
I only ask because I think it may be my machine that's slow. 

In other news, 
I have a rough-draft/sample for you. Pls pull down my develop branch. Couple of things:
1. I haven't associated a route with the popup (do we want to do this, if it's simply quick info we want to show?).
2. Do we want to change this to an "onHover" listener? Just a thought, 
3. In theory, there could be multiple modals per ballot (if a user could click on a measure while another modal was open).
4. Lastly, the modal isn't extracted onto it's own page. 

I can easily fix all these things, I just want to make sure my is in line with your vision for this task. (feedback loop, and whatnot).

**Comment by DaleMcGrew** [comment]
Thank you @Anoninnyc, I got a chance to run it locally and it looks great!
Browserify usually takes about 30 seconds to build on my machine.

You are correct that we could have 20+ possible modals to display on the ballot page. To avoid rendering 20+ modals, I am hoping you can find a way to only render the modal that is being clicked on? Perhaps we can use one modal, and replace the contents with different this.props passed in based on the onClick event?

We will want to show popover divs (different than this modal) onHover in some areas. This particular display will require a click since it "takes over" the whole display area.

**Comment by Anoninnyc** [comment]
@DaleMcGrew 
30 seconds? So it's not my computer.  Wow. Is it not problematic for you when developing?

- I can center and enable 'x' easily. 
- I should be able to extract the modal to the main ballot page, include a 'toggleModal' method on the ballot page, then pass down to each ballot initiative. 
- For the hide modal onClickAnythingButTheModal, we could:
a. Use jQuery to remove any modals from screen on click. Obvi not 1st preference
b. Add a react click listener to the entire body, though disable for the modal itself.  
c. Any other ideas that come to mind?

Thx, 
KMA

**Comment by Anoninnyc** [comment]
@DaleMcGrew
update: So I:
1.Vertically re-positioned (let me know where I should put the css you see added, do you want me to add a new component file)? 
2. Enabled the x;
3.  It looks like the modal is disabled when we click back on the screen(?)

**Comment by DaleMcGrew** [comment]
Hi Chris, I think "src/sass/components/_ballotList.scss" is the right place for the CSS related to this modal.
Moving the Module code to its own component can wait. 
I think the bigger question is if we can dynamically change the contents of the Modal depending on which ItemTinyOpinionsToFollow is clicked on? (Avoiding the creation of 20+ Modals when we render the Ballot.)

When you are ready to share your code, could you please create a pull request? I won't necessarily merge it into develop, but it will make it easier to review and add comments to the code.

Thank you! -Dale

**Comment by Anoninnyc** [comment]
OK- pull my branch down for a more 'verbose' modal.

**Comment by Anoninnyc** [comment]
I'll move the s(css).
Notice how the contents are already dynamic. Click on a measure and notice the name of the measure in the modal header. 
Moreover, I don't know if we need vertical centering if we're going to have long modals(?)

**Comment by Anoninnyc** [comment]
pr made- some minor code cleanup @ least is needed. Let me know if/how you'd like to modulate. 
Though no more than 1 will popup @ any time.

**Comment by DaleMcGrew** [comment]
Working! Thank you Krishan.
