### ISSUE TITLE
Ballot does not load when navigating from candidate page

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#67]
If you load the Ballot, then navigate to Candidate page, and then back to Ballot you are fine.
If you load the web app starting with the Candidate Page or refresh the page while you're on the Candidate Page (which fetches a single candidate), then navigate to the Ballot, the Ballot does not initialize. This is because the Ballot initialize method checks for a length of zero before fetching all the Ballot items.

**Comment by DaleMcGrew** [comment]
I confirmed that this is working now.
