### ISSUE TITLE
Make the positions popup a bit friendlier

### ISSUE THREAD

**Issue by nickelser** [wevote/WebApp#676]
### Please describe the issue (What happens? What do you expect?)
- [x] In mobile (iPhone Safari) the single click on a TinyOpinionToFollow is still opening the organizational popover, instead of opening the modal.
- [x] On https://wevote.us/ballot when looking at Kamala Harris, hover over "California National Organization for Women". In the popover you are not able to click the Follow button (the left-most 1/2 of it at least).
- [x] In desktop mode I noticed that multiple popovers can open:
<img width="463" alt="screen shot 2017-03-01 at 7 37 22 pm" src="https://cloud.githubusercontent.com/assets/7756031/23492033/eef33d2e-feb6-11e6-81a9-196e0404665b.png">

![screen shot 2017-02-22 at 7 17 31 pm](https://cloud.githubusercontent.com/assets/367553/23243417/bd8b8eea-f933-11e6-8f7b-6ce3cd28986d.png)

The positions popup is a little wonky in formatting (some overflow), has some minor usability issues (cannot hover over and click anything).

### Steps to reproduce the problem (1, 2, 3...), including links

Hover over the organization.

**Comment by nickelser** [comment]
Looks like the multiple popovers bug is still present -- reopening.

**Comment by DaleMcGrew** [comment]
Great work!
