### ISSUE TITLE
Ballot not loading: If Ballot is empty tell voter to enter address

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#68]
I am working on another laptop and started up the app. When I went to the app I continued to get the loading spinner without any notice of why it continued to load. The response looks like so:

```
https://api.wevoteusa.org/apis/v1/voterBallotItemsRetrieve?voter_device_id=a7AeW6jxVfq0716ebMsxmbogmFkgBzIlnbpcrHIgPmZHiqcX5ZvDwbKQfOSg6omMZTcjyGyR0YlMiuGLzttdKxTk
```

```
{
  "success": false,
  "voter_device_id": "a7AeW6jxVfq0716ebMsxmbogmFkgBzIlnbpcrHIgPmZHiqcX5ZvDwbKQfOSg6omMZTcjyGyR0YlMiuGLzttdKxTk",
  "google_civic_election_id": "4167",
  "ballot_item_list": [],
  "status": "NO_BALLOT_ITEMS_FOUND_0"
}
```

```
Request URL:https://api.wevoteusa.org/apis/v1/voterBallotItemsRetrieve?voter_device_id=a7AeW6jxVfq0716ebMsxmbogmFkgBzIlnbpcrHIgPmZHiqcX5ZvDwbKQfOSg6omMZTcjyGyR0YlMiuGLzttdKxTk
Request Method:GET
Status Code:301 MOVED PERMANENTLY (from cache)
Remote Address:52.33.188.152:443
```

For any UI that there is no feedback or there is no data retrieved for one reason or the other, we should think about a timeout letting someone know possible reasons as to why we could not retrieve the data they are wanting.

**Comment by pertrai1** [comment]
Changing to @nf071590 for capacity reasons to get done before EOD tomorrow - 23rd. @lisamcho already has the other 2 issues left in this milestone.

**Comment by lisamcho** [comment]
This is the redirect issue correct? Believe that it is already addressed.

**Comment by DaleMcGrew** [comment]
Thank you @lisamcho and @nf071590. When we get our messages framework set up we will want to give an explanation for the redirect, but this Issue can be considered closed.
