### ISSUE TITLE
Unable to access options on left side of page when size is less than 694 px

### ISSUE THREAD

**Issue by niyatikothari** [wevote/WebApp#680]
Unable to access options that are available on left side of the page when size is 694 px and less. 
I am able to access when size is 695 px * 638 px but when it is changed to 694 px * 638 px, I am unable to access them.

Steps to reproduce:

1. Open https://wevote.us/ballot.
2. Change window size such that it is less than or equal to 694 px.
3. Unable to access options available on left side of scree (Your Voter Guide, Your Account, About We Vote).

[Unable to access left side of page when size is less than 694 px.pdf](https://github.com/wevote/WebApp/files/800379/Unable.to.access.left.side.of.page.when.size.is.less.than.694.px.pdf)

**Comment by DaleMcGrew** [comment]
Hi @niyatikothari, this is not a bug -- those options move to the hamburger menu when the viewport is less than 694 px.

**Comment by niyatikothari** [comment]
Hi Dale,

I just verified. Yes, it is coming like the one we have in phone screen. I
assumed we will get scroll bar to access left side of the page.

Thanks for update. Will update Defect Tracking Log and Route Display
Testing sheets on Monday.

Regards,
Niyati Kothari

**Comment by niyatikothari** [comment]
Hi Dale,

I just verified. Yes, it is coming like the one we have in phone screen. I
assumed we will get scroll bar to access left side of the page.


Regards,
Niyati Kothari
