### ISSUE TITLE
Ballot page layout problem when too narrow

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#681]
### Please describe the issue (What happens? What do you expect?)
When in desktop mode, the layout of the a) candidate name and b) measure text looks good, uses space well, and does not need to change:
![screen shot 2017-02-24 at 3 57 07 pm](https://cloud.githubusercontent.com/assets/7756031/23325461/4e975e7e-faaa-11e6-9de6-66091132ce24.png)

In iPhone 5 mobile mode though, the text to the left gets squished:
![screen shot 2017-02-24 at 4 00 59 pm](https://cloud.githubusercontent.com/assets/7756031/23325482/77d6ca7c-faaa-11e6-88ca-81fd16877395.png)

For smaller screen sizes, please move the candidate names and measure text above the position bar and support/oppose buttons. 

Regarding photos, please make the placeholder and actual image size be 48x48 in desktop mode. Currently the sizes don't match and are wrong:
![screen shot 2017-02-24 at 4 07 48 pm](https://cloud.githubusercontent.com/assets/7756031/23325605/703cf16e-faab-11e6-9b40-7a2d7f0535d3.png)

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to the ballot page: https://wevote.us/ballot
2. Make sure you see the "Oakland, CA" ballot
3. Look for "Proposition 51" and "San Francisco County Superior Court Judge"
4. Follow an organization or two, and/or support or oppose each item.
5. View in both desktop and in iPhone 5 emulation.

**Comment by Anoninnyc** [comment]
@DaleMcGrew I'm gonna get rid of the *bar* for iphone5, but keep the count.

**Comment by Anoninnyc** [comment]
Just saw this: "For smaller screen sizes, please move the candidate names and measure text above the position bar and support/oppose buttons."... :O

**Comment by Anoninnyc** [comment]
@DaleMcGrew Beginning to fix this. Misread issue specs...

**Comment by Anoninnyc** [comment]
@DaleMcGrew Pls take a look at my PR (aware I should have submitted separate PR's- my apologies)

**Comment by DaleMcGrew** [comment]
This is shaping up nicely. Measures are looking particularly good. A few comments:

- [ ] If there is room for the support/oppose buttons to fit on the same line as the candidate name, it would be nice if if they could all fit on one line. Then, as soon as there is a position, the position bar and support/oppose buttons would slide down to the next line (like it does now). Vertical ballot space is very precious. We want to get as many candidates on the screen as possible:
![screen shot 2017-02-26 at 4 35 23 am](https://cloud.githubusercontent.com/assets/7756031/23339731/2114ab12-fbdd-11e6-935e-8242a4fcb99a.png)
- [ ] The link to the candidate's page is missing from the candidate name in mobile mode
- [ ] I think it would be good to add a small version of the candidate photo or placeholder photo (24x24) in the mobile mode
- [ ] In Desktop: the candidate names should be on the same horizontal line as the candidate photo.
- [ ] In Desktop: the candidate photos should be limited to 48x48

**Comment by DaleMcGrew** [comment]
Thank you @Anoninnyc for knocking out 90% of the items. I am going to close this issue for now.
