### ISSUE TITLE
Ready to Vote: Convert to flex (from tables)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#686]
The js/components/Ballot/MeasureItemReadyToVote and OfficeItemReadyToVote pages are still using tables. Please convert to the new flex system. There is example code in js/components/Ballot/MeasureItemCompressed and OfficeItemCompressed.

**Comment by emilyliza** [comment]
The js/components/Ballot/MeasureItemReadyToVote uses cards instead of tables.

**Comment by DaleMcGrew** [comment]
Hi @emilyliza I see now that you are correct. :) So it is the OfficeItemReadyToVote that just needs the update. Thank you!

**Comment by DaleMcGrew** [comment]
Resolved!
