### ISSUE TITLE
Convert YouTube or Vimeo links to display in a video player

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#689]
Some voter guides contain links to videos, hosted on YouTube or Vimeo. Whenever we recognize a YouTube or Vimeo URL, we want to offer a video player. We should be able to use the module ReactPlayer to play most videos. (See js/routes/More/About.jsx for sample code using ReactPlayer.)

**Comment by emilyliza** [comment]
I can't seem to find any voter guides with video links. Would the video link be in the organization/person's card with the description, website link and twitter followers count?

**Comment by DaleMcGrew** [comment]
Hi Emily, you can add a link in your own comment on any candidate or measure. This is an example video link you can use: 
https://www.youtube.com/watch?v=hMdjN-4V95c

This is an organization that has several videos in their voter guide: https://wevote.us/lwv_oakland

**Comment by emilyliza** [comment]
Ahh, thanks!

**Comment by emilyliza** [comment]
@DaleMcGrew I have things set up so that if a person pastes a youtube or a vimeo link in the comment box, the link will be converted to a video via ReactPlayer. However, this only works if a link is the only text. So for example: "Here is a video: "https://www.youtube.com/watch?v=hMdjN-4V95c" would not work. This is because I use regex to identify the link and then feed it to the player. Thoughts?

**Comment by emilyliza** [comment]
I wonder if it makes sense to add a stand alone text area for urls?

**Comment by DaleMcGrew** [comment]
Hi Emily, we can write a text parser (or regex) that looks through the text and pulls out the video link(s) that can be fed to the player. Checking in a first version that just looks at {statement_text_to_be_saved} to see if it is a video link is a good first step!

**Comment by emilyliza** [comment]
Ok, sounds good!

**Comment by emilyliza** [comment]
@DaleMcGrew I opened a request. It now pulls just the url and leaves any remaining text. I think the code could be more concise.

**Comment by DaleMcGrew** [comment]
Hi Emily, I made a couple of changes to the code to fix some errors I got (please make sure to grab the latest code before working on this further), but this is a great new feature! Thank you!

I wanted to point out two more areas to make the video player appear:
WebApp/src/js/components/Widgets/PositionSupportOpposeSnippet.jsx
WebApp/src/js/components/Widgets/PositionInformationOnlySnippet.jsx

You can test this by signing in with Twitter, then viewing your own voter guide. Let me know if you need help finding these pages.

**Comment by emilyliza** [comment]
Ok, great and thank you for the fixes. I'll pull down the latest code and work on this today.

**Comment by emilyliza** [comment]
Pull request is open for this, along with a note. The code may need to be modified further if there is a case for a user to add a URL in the both the `statement text` and the `more info url` in `PositionOnlyInformationShippet.jsx`.

**Comment by DaleMcGrew** [comment]
Great work @emilyliza! Check it out: https://wevote.us/lwv_oakland
