### ISSUE TITLE
Android Browser: Spacing issue between Requests and Connect

### ISSUE THREAD

**Issue by niyatikothari** [wevote/WebApp#695]
Spacing between Requests and Connect is not as expected.
(1) Open https://wevote.us/ballot in Samsung Galaxy S4 Emulator and Android browser 4.4
(2) Spacing between Requests and Connect is not proper.

Please use below link for the issue:
https://saucelabs.com/beta/tests/af2b9b44dea74f2db44eee8d1f5c1497/watch

Please find below screenshot:

![image](https://cloud.githubusercontent.com/assets/25673349/23480408/c7ba12c6-fe95-11e6-842d-44cc9679c4cf.png)

Facing similar issue in 
![image](https://cloud.githubusercontent.com/assets/25673349/23480583/730c67a0-fe96-11e6-9e89-11fabd88b87f.png)

Note from @dalemcgrew: I suspect that the issue has to do with the search box not being resized properly in this view size.

For instructions re: confirming that a fix worked, see here: https://docs.google.com/document/d/1-KxvYRLs4cQdZ6_GPy5JhtX5kswtaNq7LID5k11X2aQ/edit

**Comment by DaleMcGrew** [comment]
We have been reworking the navigation, so I am closing this issue until we do more cross-platform testing.
