### ISSUE TITLE
Desktop profile photo should open right navigation

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#696]
Desktop profile photo (far right) should open right navigation, in the same way it opens the right navigation in mobile mode.

**Comment by bigethan** [comment]
My proposal (I'm new so please feel free to tell me where I'm wrong):

`react-burger-menu` is a slightly strange fit for desktop, as it's attached to the right (or left) side, and the icon isn't always over on that side. It's also a lot of animation code that isn't being (currently) used. My thought is to remove `react-burger-menu` and use a more generic menu component that will work the same on mobile and desktop.  It'll also simplify the responsive setup in the css and the component.

Let me know if it sounds good and I'll put up a PR for review.

**Comment by DaleMcGrew** [comment]
Hi @bigethan I am totally open to using a different menu component. I look forward to your pull request! Thank you.

**Comment by DaleMcGrew** [comment]
I love this solution! Thank you @bigethan.
