### ISSUE TITLE
Organization Page - One Position, Create & Style

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#7]
Jeff (@ixley) is finishing up a new design for this, item 5.2. This is the current design brief: https://docs.google.com/document/d/1xlaUN6FyjKSp8lgctH5fC3bgOEYmpNqbyU8nBsm9vEY/edit#

**Comment by lisamcho** [comment]
This design looks so much better! Close this out?

**Comment by DaleMcGrew** [comment]
Yes! Great work @ixley!
