### ISSUE TITLE
Ballot items list photos: visual clean up

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#704]
### Please describe the issue (What happens? What do you expect?)
On the main ballot page, the small (24 x 24 in mobile mode) and larger (48x48 in desktop mode) images need better spacing.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to http://localhost:3000/ballot (not on live server yet)
2. Enter address "Oakland, CA"
3. Notice desktop spacing around candidate photos AND mobile spacing

**Comment by ixley** [comment]
@DaleMcGrew I'm getting a little confused about what the intended display is supposed to look like. I've added spacers between the candidate avatars and their names to the right, but a lot of the code in here feels like it's adding unnecessary complexity without a clear reason (that I can tell at least). There are also more custom classes that have been added that again, seem like they are adding complexity without a clear justification.

For example, why are there redundant elements for the candidate name and photo that get hidden and shown at different breakpoints? Am I missing something?

**Comment by DaleMcGrew** [comment]
Hi Jeff, feel free to clean up the code and CSS. The goal is to have  different sized photos in mobile versus desktop, and keep the photo, Position bar, and Support or Oppose buttons on the same line if possible, but wrap if not. Thank you!

**Comment by ixley** [comment]
I did some light cleanup but didn't want to get into the weeds since a lot of this feels somewhat fragile. What we really want to target layout changes like this is element queries (instead of media queries). They are not here for CSS yet, but there is some promise with React plugins. Anyway, that's a whole other endeavor but worth looking into eventually.

**Comment by DaleMcGrew** [comment]
Awesome work! Thank you!
