### ISSUE TITLE
Move "Edit Address" feature into a modal popup

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#711]
### Please describe the issue (What happens? What do you expect?)
Currently when you edit your address, it navigates to a new page. Instead we want to open a modal popover, similar to "SelectBallotModal" in WebApp/src/js/routes/Ballot/Ballot.jsx
![screen shot 2017-03-04 at 10 23 28 am](https://cloud.githubusercontent.com/assets/7756031/23581217/e63ef686-00c4-11e7-94ce-d496be0668a0.png)

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to https://WeVote.US/ballot
2. Click on the edit address link

**Comment by Anoninnyc** [comment]
@DaleMcGrew So, I submitted a PR, and there are 2 lines worth of conflicts. If you think I'm on the right track here, let me know. Then, I'll do a brief code clean-up/optimization & make my branch mergeable.

**Comment by Anoninnyc** [comment]
@DaleMcGrew  Currently, my PR has no conficts.

**Comment by DaleMcGrew** [comment]
Thank you @Anoninnyc, this new feature is great!
