### ISSUE TITLE
Support video display from first video link in paragraph of text

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#712]
### Please describe the issue (What happens? What do you expect?)
If a voter enters a Vimeo or YouTube URL as a position statement, we display the video directly in the position feed. What we would like to do is update these RegEx's to use the first video URL in the position to display a video, but also allow the voter to add text before and after the video URL.
See WebApp/src/js/components/Widgets/ItemPositionStatementActionBar.jsx
      youtube_url = statement_text_to_be_saved.match(youtube_reg);
      vimeo_url = statement_text_to_be_saved.match(vimeo_reg);

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to the ballot page: http://localhost:3000/ballot
2. Choose any candidate or measure
3. Paste in a video URL into the position statement and save. (Ex/ "https://www.youtube.com/watch?v=hMdjN-4V95c")

**Comment by emilyliza** [comment]
@DaleMcGrew I believe this is working now locally - I needed to change the youtube regex.

However, there is a new concern. The code finds and removes the url from the text block, saves the new text (sans url) and puts the url into the video player. This is fine as long as you don't need to edit. If you choose to edit the text, you will no longer have access to the url. Thoughts?

**Comment by emilyliza** [comment]
Perhaps I will create a new variable for the visible text.

**Comment by DaleMcGrew** [comment]
That is what I was going to suggest. :)

**Comment by emilyliza** [comment]
Ok, working on it now. Thanks!

**Comment by emilyliza** [comment]
Pull request open. Hopefully, it works now! :-)

**Comment by DaleMcGrew** [comment]
Works like a charm! Thank you @emilyliza.
