### ISSUE TITLE
Connect, Current Friends: Show photo icons for existing friends

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#731]
Connect, Current Friends: Show photo icons for existing friends. See visual design at the bottom of this page:
https://app.moqups.com/DaleMcGrew/EdffBLTLBI/view/page/aed27cc24
- [ ] Show the photo icons for any current friends that have photos. Data would come from same source as friends shown on https://wevote.us/more/connect
- [ ] After showing 10 photo icons, summarize the remaining number of voter guides with “+x”. See example in WebApp/src/js/components/Position/ItemTinyPositionBreakdownList.jsx
- [ ] Clicking on any of the friend images should link to the page https://wevote.us/friends

**Comment by Anoninnyc** [comment]
@DaleMcGrew  safe to assume desktop view will be a wider version of what's shown in moqup?

**Comment by Anoninnyc** [comment]
@DaleMcGrew  Also, I'm  not receiving the friend invitation I'm sending to my alt. email address

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc, we are working on fixing the bug with friend invitations not working. And you are correct that the desktop view of this component will be wider.

**Comment by Anoninnyc** [comment]
@DaleMcGrew got it... thanks!

**Comment by DaleMcGrew** [comment]
Thank you @jainanisha90 for the first version of this feature!
