### ISSUE TITLE
Optimize browserify process

### ISSUE THREAD

**Issue by Anoninnyc** [wevote/WebApp#738]
### Please describe the issue (What happens? What do you expect?)
It currently takes ~30 seconds for hot reloading to complete.
### Steps to reproduce the problem (1, 2, 3...), including links
Edit one of the .jsx files, and you'll have to wait quote a while to see your changes rendered. 

http://gulpjs.org/recipes/fast-browserify-builds-with-watchify.html

**Comment by DaleMcGrew** [comment]
Thank you @Anoninnyc!
