### ISSUE TITLE
Make Twitter link active

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#745]
### Please describe the issue (What happens? What do you expect?)
Links in the descriptions of organizations or candidates are not active HTML links, and they should be. Files that need to be updated (search for "twitter_description" in these files):
- /src/js/components/Ballot/CandidateItem.jsx
- /src/js/components/VoterGuide/OrganizationCard.jsx
- /src/js/components/Twitter/TwitterAccountCard.jsx

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to an "organization" that has a link in the "twitter_description" (ex/ http://localhost:3000/lscott )
2. Currently the link ("https://t.co/G6GRhMY3f7") is not active.
3. We want to make this link open in a new tab.

**Comment by Anoninnyc** [comment]
@DaleMcGrew - "https://t.co/G6GRhMY3f7  valid link, it seems. 
But, you want twitter to open, when click on icons, click on handle ( ex @sdfsdkjfh), or other?

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc, we just want to create an external link around the text of the Twitter link "https://t.co/G6GRhMY3f7" so when you click on it, a new tab is opened with that destination. No other links are needed at this time.

**Comment by Anoninnyc** [comment]
Got it.

**Comment by Anoninnyc** [comment]
@DaleMcGrew Hi Sale- so... let's use Scott M's acct as an example. 
We need to parse the description (which is currently a string) such that we turn anything that's a link (starts with "http") into "<a hfef='http.....".

Please pull down my addHyperLink branch and let me know if my solution is satisfactory. Fundamentally, I don't think there's any other way to do this, if all we're provided is a string.

(I'm aware I still need to to this for CandidateItem.jsx and  TwitterAccountCard.jsx; let me know if the [http://localhost:3000/lscott](http://localhost:3000/lscott) is formatted how you want it.

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc, I'd like to avoid attempts to support general markup, but instead focus on converting http and https links into active links. I think the approach @emilyliza took for activating video links is a good one. See https://github.com/wevote/WebApp/pull/735/files

**Comment by Anoninnyc** [comment]
@DaleMcGrew  So, to my knowledge, what's being done in the example you showed me can't be done when parsing thru text.  @emilyliza is injecting <a href's... into the code because she knows where the urls are going to pop up within surrounding text.

For what I'm doing, if I have a string like: "Hello, my name is bob, see my website at https://www.dsfsdf.com and here, too: https://www.dsfsdf.com ", in order to make active links, I need to put <a hef's around the links (to my knowledge). And to turn a string into html, I need to, well, markup. 

Here's the difference between what she and I are doing:
I need to display active links somewhere between the full text description. 
So, the end jsx needs to be something like this:
<div>Hello, my name is bob, see my website at <a href= https://www.dsfsdf.com>https://www.dsfsdf.com></a> and here, too: <a href= https://www.dsfsdf.com>https://www.dsfsdf.com</a> </div>

We don't know where, within the text, the hyperlink will go, nor how many of them there are...

Let me now if  we're on the same page...

**Comment by DaleMcGrew** [comment]
You are correct in your description that this is what we want to end up with:
-------
Hello, my name is bob, see my website at http://www.abcdef.com and here, too: https://www.dsfsdf.com as well as www.xyzxyz.com
-------

You should be able to search for "http:" or "https:" or "www" with a regex (like how Emily did the video link matching), and then convert the text of the entire link to an active link. I would imagine that there is existing code on the web that does this.

**Comment by Anoninnyc** [comment]
Hi Dale,
I've looked far and wide and have found nothing that would allow us to to what we're attempting. 
Let me know if this will suffice: http://stackoverflow.com/a/29048207
Best, 
Chris

**Comment by Anoninnyc** [comment]
<script>console.log(3)</script>

**Comment by Anoninnyc** [comment]
@DaleMcGrew Pls see abv comment.

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc, I unfortunately cannot do a deeper dive on this issue now, so maybe we should punt on this for now.

**Comment by Anoninnyc** [comment]
@DaleMcGrew I have an idea for this.....

**Comment by Anoninnyc** [comment]
@DaleMcGrew  , can you pull down my Anoninnyc:twitterDetector branch and let me know if this is a satisfactory approach, and I'll continue to flesh it out, then send a PR? This is re: issue #745..

**Comment by amatranga** [comment]
Twitter provides [cards](https://dev.twitter.com/cards/overview) which do pretty much exactly this (among other things).
It seems like the card type we want is a [Summary card with large immage](https://dev.twitter.com/cards/types/summary-large-image). We can then populate this card with [user objects](https://dev.twitter.com/overview/api/users) which contain [entities](https://dev.twitter.com/overview/api/entities) which contain urls and the indices of said urls

**Comment by selva-oscura** [comment]
NOTE: linter gave error
	src/js/components/Twitter/ParsedTwitterDescription.jsx
	47:55  warning  Gratuitous parentheses around expression  no-extra-parens

The parentheses are NOT gratuitous.  Under ES6, parentheses are used to return the results of a ternary operation within an Array.map.  Omission of these parentheses or use of curly braces would not return the result.

The options for that rule should be
	"enforceForArrowConditionals": false

To get that one line through linting, line 51 of ParsedTwitterDescription.jsx has 
  //eslint-disable-next-line no-extra-parens

**Comment by DaleMcGrew** [comment]
Issue solved!
