### ISSUE TITLE
Connect, Add Friends by Email: Only show "Include a Message" after first email has been entered

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#747]
### Please describe the issue (What happens? What do you expect?)
When I go to the "Connect" page, the "Include a Message" optional field appears before an email address has been entered. We want to hide that field (and label) until after a valid email address has been entered in at least one of the 5 inputs.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Go to http://localhost:3000/more/connect

**Comment by Anoninnyc** [comment]
@DaleMcGrew Can we kill the issue?

**Comment by DaleMcGrew** [comment]
This is fixed. Thank you @Anoninnyc!
