### ISSUE TITLE
If “Opinions I’m Following” is empty, redirect to “More Opinions”

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#75]
If the voter hasn't followed any organizations yet when they visit the "Opinions I'm Following" page, redirect to the "More Opinions" page. Ideally we would also show a message after the redirect to the "More Opinions" page ("You are not following any organizations or people yet. Please follow those that match your points of view."), but this can wait until we get our messages framework in place.

**Comment by pertrai1** [comment]
Completed with #80 merge
