### ISSUE TITLE
Travis tests: Find way to run tests with different config.js file

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#750]
### Please describe the issue (What happens? What do you expect?)
When we try to run Travis for build & test verification, it fails ( https://travis-ci.org/wevote/WebApp/builds/213232696 ). I believe this is because it cannot find a WebApp/src/js/config.js file, and the solution might be to add a configuration setting in WebApp/.travis.yml to tell it to use a different config.js file, or at least put one in place for the travis run only.
Note: We need to keep the WebApp/src/js/config.js file in the WebApp/.gitignore file since different developers need to make changes to that file without checking in their changes.

**Comment by Anoninnyc** [comment]
@DaleMcGrew Unsure as to what, in any conclusion we came to re: this issue. 

We could have different environmental variables for local devs, than we have for YAML, than we have for production. We would have to change the values in the current config to process.env.VARIABLE_NAME.

Or we could put a script in the "before_script:" section of Yaml that will rewrite the config file for the purposes of YAML only.... 

Do you think this will be a viable solution?

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc it turns out you can set Global variables in the Yaml file, so when I added the access key, the selenium tests worked! https://travis-ci.org/wevote/WebApp/builds/213659549

**Comment by Anoninnyc** [comment]
Great!
