### ISSUE TITLE
Make "Follow" and "Ignore" buttons work on More Opinions page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#76]
On the "More Opinions" page page: 
*) When you click "Follow" it should toggle to "Following"
*) When you click "Following" it should toggle to "Follow"

**Comment by nf071590** [comment]
Starting this now.

**Comment by DaleMcGrew** [comment]
@nf071590 requested https://github.com/wevote/WeVoteServer/issues/86 so Ignore can be implemented.
