### ISSUE TITLE
Improve look of team photos on "About We Vote" page

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#768]
This issue is for a developer who is an expert at CSS. On the "About We Vote" page:
http://localhost:3000/more/about
- [ ] Reduce the horizontal space between each person's photo and bio (for both desktop and mobile)
![screen shot 2017-03-30 at 11 45 03 am](https://cloud.githubusercontent.com/assets/7756031/24520770/7fdd74e2-153e-11e7-8e3b-d318ca325bce.png)
- [ ] Reduce font size of team titles and bios.
- [ ] Please make sure to check your work by resizing the view space.

**Comment by clapinton** [comment]
Also fix this on /more/team

**Comment by clapinton** [comment]
How do these look:

**Desktop**
![image](https://cloud.githubusercontent.com/assets/8397150/24823682/21d830c0-1bb6-11e7-8c24-1eed4a452f4d.png)

**Mobile**
![image](https://cloud.githubusercontent.com/assets/8397150/24823690/4a78e722-1bb6-11e7-841d-7bcaf9c37cad.png)

**Comment by DaleMcGrew** [comment]
Thank you @clapinton, you nailed it.
