### ISSUE TITLE
About We Vote, Desktop: Split into three pages

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#769]
When using We Vote from a mobile device, clicking on "About We Vote" will click to this page:
http://localhost:3000/more/about
No changes are required to this.

When using We Vote from a DESKTOP device, please make the following changes:
- [ ] Convert the "About We Vote" top navigation item to open a drop down when clicked (please mimic the drop down opened from the profile photo)
- [ ] Create the following 4 dropdown options: 1) How to use We Vote, 2) Vision, 3) Organization, 4) Team
- [ ] Create a new route for "How to use We Vote": /routes/More/HowToUse.jsx (/more/howtouse)
- [ ] Create a new route for "Vision": /routes/More/Vision.jsx (/more/vision)
- [ ] Create a new route for "Organization": /routes/More/Organization.jsx
- [ ] Create a new route for "Team": /routes/More/Team.jsx

**Comment by Anoninnyc** [comment]
@DaleMcGrew Hey dale, nearly done with this.  
Quick question- when user clicks on About we vote, you want a route change *and* the dropdown?

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc -- when the voter clicks the "About We Vote", there should not be a route change. Only the dropdown should appear.

**Comment by Anoninnyc** [comment]
@DaleMcGrew  can we kill this issue. or is there more needed here?

**Comment by DaleMcGrew** [comment]
I will create another issue for the menu positioning bug. Thank you @Anoninnyc for doing this!
