### ISSUE TITLE
Move video regex's into one location

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#771]
Please take the video regex code (shown in the closed pull request: https://github.com/wevote/WebApp/pull/735/files ) and move it into one location (used by the components referenced in the closed pull request). Lets put this regex code in a function (or constant?) in WebApp/src/js/utils/textFormat.js

**Comment by Anoninnyc** [comment]
@DaleMcGrew  was unable to find vimeo video's with which to test this...

**Comment by DaleMcGrew** [comment]
Fixed!
