### ISSUE TITLE
Update ballot to use inline styling to avoid position bar overflow

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#784]
### Please describe the issue (What happens? What do you expect?)
In this screenshot we show that position bars wrap to the next line in cases where they could fit on the same line as the candidate name.
![screen shot 2017-04-11 at 1 40 03 pm](https://cloud.githubusercontent.com/assets/7756031/24929922/82b2ee04-1ebc-11e7-8ac7-c2693002e31a.png)

**Comment by ixley** [comment]
Hey @abasalilov - are you still actively working on this? I saw your note that you hit a wall with the element-queries approach. It's possible that's just not the best way to integrate with the current way our grid framework is setup (mixed with using Bootstrap and classnames for styling). I have another idea for addressing this with flexbox (just an idea - not validated yet) but wanted to check to see if you were in progress with anything else for this.
