### ISSUE TITLE
Replace react-headroom React package because it makes the bundle too big

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#787]
react-headroom (14.8M and 7 children) is the biggest package. It's only required on Application.jsx to hide the header when the user scrolls. I think we can switch to a lighter package, such as the original headroom.js (not specific to React, but easy to readapt), or some other similar;

More notes here:
https://docs.google.com/spreadsheets/d/1mINBClQJ8CBd8e4rceE8ZvXPJXZE4d6dxa9Tp5OcCo0/edit#gid=0

**Comment by DaleMcGrew** [comment]
(I just assigned it to you Eric because I saw your note on the other case where you said you could look at other options for react-headroom. Thank you!)

**Comment by clapinton** [comment]
I'm testing the original headroom.js package. The folder is 70KB. It needs a bit more work on it, as it only assigns specific class names to a target element, so it's up to us to specify the CSS rules that hides/shows the header bar. I'm working on implementing the same behavior as we have now.

**Comment by DaleMcGrew** [comment]
Great work Eric! Fixed.
