### ISSUE TITLE
Change Support/Oppose "at" state in ItemActionBar

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#797]
In /js/components/Widgets/ItemActionBar.jsx, after a voter has selected "Support" or "Oppose", we show just the selected position:
<img width="123" alt="screen shot 2017-04-22 at 9 58 26 am" src="https://cloud.githubusercontent.com/assets/7756031/25306461/5b22ff30-2742-11e7-9c3b-d515900cd01f.png">

- [ ] Instead, leave both Support/Oppose options visible, but with the selected state highlighted.
- [ ] New functionality: If Support is already chosen, and you click it again, remove Support. (Same for Oppose.)

**Comment by Anoninnyc** [comment]
Hi @DaleMcGrew, so I think I have a working solution to this which  I'm going to refine before I submit PR, let me know if [this video](https://youtu.be/utvEZsh_qPE) demonstrates desired behavior,  (obviously not desired highlighting, I'm sure).

I also wanted to clarify some things:
1. You want the PositionDropdown component removed, correct?
2. If you have a preference, how would you like me to properly highlight the thumbs?

**Comment by Anoninnyc** [comment]
also... you'll notice that my computer is very slow.

**Comment by DaleMcGrew** [comment]
Thank you Chris, for now you can just make the support thumb icon take the green, and the oppose take the red.

**Comment by DaleMcGrew** [comment]
And please leave the PositionDropdown component in the repo for now.

**Comment by Anoninnyc** [comment]
@DaleMcGrew, - got it, thanks

**Comment by ixley** [comment]
I appreciate the simplicity of the updated component but I'm unclear on the intent here. My original understanding was that once a user selects a position, we aren't trying to encourage them frequently change their position. This updated approach seems to remove friction for changing your position, but I'm unclear on the value it provides in doing so. @DaleMcGrew could you clarify this for me?

If the goal, however, is just to make the selected state more compact, we can do that by removing the label text but without keeping both options exposed, no?

**Comment by DaleMcGrew** [comment]
Hi Jeff, thank you for your question. Cara, Samantha and Randy all argued for the benefits of simplifying the support/oppose selection process on the ballot page. This implementation needs more visual design, but until we finish that design, this pull request gives us a chance to see how it feels.

**Comment by DaleMcGrew** [comment]
Hi @Anoninnyc, this component is used on the ballot page as well as on the Candidate and Measure pages. On the ballot page the "at" states are visible. When you are a candidate's page (or a measure page), the click functionality works, but there isn't a visual "at" state on the "Support" and "Oppose" buttons (the wider format).

**Comment by DaleMcGrew** [comment]
I fixed this by adding the highlight_thumb_green and highlight_thumb_green to the item-actionbar.
