### ISSUE TITLE
In Modal popup for organization on Ballot, "Follow" button cannot be clicked

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#812]
### Please describe the issue (What happens? What do you expect?)
On the ballot page (Address: Oakland, CA 94602), prior to signing in, there are a number of organizational icons. When you hover over them, some of them have a problem with the Follow button. The Follow button on some of them cannot be clicked along the left side of the button. The clickable area is obscured for some organizations.

### Steps to reproduce the problem (1, 2, 3...), including links
1. Sign out
2. Go to ballot page: https://wevote.us/ballot
3. Set your address to "Oakland, CA 94602"
4. Find one of these two organizations. There is something about their names that causes the clickable area of the Follow button on the left side to be "obscured":
<img width="307" alt="screen shot 2017-04-29 at 8 01 10 pm" src="https://cloud.githubusercontent.com/assets/7756031/25560998/1f0db99c-2d17-11e7-8f5a-c3a95b53d64c.png">
<img width="313" alt="screen shot 2017-04-29 at 8 01 59 pm" src="https://cloud.githubusercontent.com/assets/7756031/25561002/23e455a2-2d17-11e7-90c5-5f40ac2f3093.png">
5. I think this code is in "organizationPopover" within WebApp/src/js/components/VoterGuide/ItemTinyOpinionsToFollow.jsx

**Comment by Anoninnyc** [comment]
@DaleMcGrew I'm having trouble replicating this problem... is this in mobile view only? In addition, I signed out, and can't find "Alameda County Green party" on my ballot even after setting address as"Oakland, CA 94602". Is this problem occurring on [this ](https://wevote.us/AlamedaGreens)page?

**Comment by Anoninnyc** [comment]
I'd like to work on this, should I be able to replicate the problem...

**Comment by ixley** [comment]
This is basically what's happening. 
![pasted_image_5_2_17__12_39_pm](https://cloud.githubusercontent.com/assets/160662/25635894/7ff736ba-2f34-11e7-835a-c4e59bab9930.png)

At a high level, things that were constructed as components are being used in contexts that weren't originally anticipated without being updated. 

In this specific case, the text container is essentially overlapping with part of the button.
I have an adjustment that is not a specific fix but will address most cases like this.

**Comment by ixley** [comment]
A longer term fix would be to adjust sizing for this specific component – a smaller image and maybe a wider popover would be relatively small adjustments. I don't want to advocate for duplicating components with minimal differences though. An ideal solution might be better abstracted components to allow for slight variations like this.
