### ISSUE TITLE
Network page: Error when you click on "Invite Friends" link

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#828]
1. Click on Network top nav
2. Click on "Invite Friends" button
3. This error appears in console log:
Uncaught TypeError: _FacebookStore2.default.facebookInvitableFriendsList is not a function
    at new InviteByEmail

**Comment by smokymcbear** [comment]
In short, **SyntaxError**.

In js/routes/Friends/InviteByEmail.jsx, `this.state.facebook_invitable_friends_list` was pointing to `FacebookStore.facebookInvitableFriendsList()`.

After digging around FacebookStore.js, there was no class method of `facebookInvitableFriendsList` but there was a `facebookInviteableFriends` on line 80. So before I had to dive deeper, I just adjusted the syntax properly.
