### ISSUE TITLE
Mixed Content over HTTPS

### ISSUE THREAD

**Issue by pertrai1** [wevote/WebApp#835]
I was playing around with the search and noticed the messages coming in the console about mixed content being served over https. To avoid this issue you can remove `http` or `https` from the url of the source for the image. So for example, instead of 

```
<img class="icon-office-child card-main__avatar"
src="http://pbs.twimg.com/profile_images/495021634437525504/IhnxbiWT.jpeg"
alt="candidate-photo">
```

You can just do:

```
<img class="icon-office-child card-main__avatar"
src="//pbs.twimg.com/profile_images/495021634437525504/IhnxbiWT.jpeg" 
alt="candidate-photo">
```

Notice that for the `src` the `http` is left out. This way you let the browser determine how to serve the asset over the wire.

Hope this can be of help.

**Comment by DaleMcGrew** [comment]
Thank you @pertrai1! We just implemented an image caching system so all images will be hosted https from our AWS CDN account. These errors will go away when we've finished migrating all of the photos.
