### ISSUE TITLE
Simulate an iframe on "facebook_invitable_friends"

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#836]
### Please describe the issue (What happens? What do you expect?)
We just got a first version of "Choose Facebook Friends" working. Currently all of your friends appear in a long vertical list. 
![screen shot 2017-05-15 at 1 25 58 pm](https://cloud.githubusercontent.com/assets/7756031/26077778/1ecf08c0-3972-11e7-99b8-354f87c2cdac.png)

We need an HTML/CSS expert to make these changes:
- [ ] Make the list appear in an "iFrame-like" box so that a voter can scroll through their friends. See the design here: https://app.moqups.com/DaleMcGrew/EdffBLTLBI/view/page/aa31ff480
- [ ] Change the listing of friends to be in 2-4 "columns" (left to right, and then onto the next row) depending on the available width. We would like as many friends to appear above the fold as possible.
- [ ] This could be in another issue, but ultimately we will want to add a search box that filters down the list based on a search for friend's name
- [ ] This can be another issue, but we would like the ability to include a message box

### Steps to reproduce the problem (1, 2, 3...), including links
1. Make sure you have the Facebook APP key in your local dev environment (Reach out to @DaleMcGrew)
2. Sign in with Facebook
3. Go to "Network" page and click "Choose Friends" button
4. This should take you to this page: http://localhost:3000/facebook_invitable_friends

**Comment by DaleMcGrew** [comment]
Some ideas for how to do this from searching for "bootstrap scroll box":
http://stackoverflow.com/questions/19639842/bootstrap-3-scrollable-div-for-table
http://getbootstrap.com/css/#code-block
http://www.quackit.com/html/codes/html_scroll_box.cfm
https://www.bootply.com/qdLCAlG9fm

**Comment by Jayadev6191** [comment]
@DaleMcGrew You don't need an iframe to get this working. Adding an IFrame will introduce a lot of complexity, for example sharing props from parent component to the iframe component can be a little tricky.

The better solution would be to have div container with a fixed height and making it scroll with overflow-y property.  This DIV container will have the entire friends list.

**Comment by DaleMcGrew** [comment]
This is now working! Thank you to everyone who contributed ideas, and to @jainanisha90 for implementing.
