### ISSUE TITLE
How to handle saving of address with no Google Civic Election

### ISSUE THREAD

**Issue by lisamcho** [wevote/WebApp#84]
I have redirected the 'Ballot' page to the address page when the ballot is empty, but there is still an issue...

If I delete all my browser cookies on localhost, it redirects and prompts to enter an address as expected. If I enter 2208 Ebb Tide Rd, Virginia Beach, VA, the page loads the ballot as expected.

If I enter the default San Francisco CA (or my full, valid home address in San Francisco), the backend saves the address, but can't get a Google Civic ID (API status response is ADDRESSED SAVED ... GOOGLE_CIVIC_API_ERROR: Election unknown). Hence the ballot is still empty, and the front end stays on the enter address page (though there is no explanation why).

Is this a backend issue? Where if we get GOOGLE_CIVIC_API_ERROR: Election unknown", we assign a default election #? Or else we handle the error on the frontend by redirecting to an empty ballot page and displaying a message to the users that their address was saved but there are no elections in their area currently, check back later.?

**Comment by DaleMcGrew** [comment]
Great point Lisa, it would be helpful to redirect to a component or route where we could create a custom page for this situation. The message on this page can be for now:
"Our data providers don't have ballot data for your address yet. Please check back 1-2 weeks before your election day."

**Comment by lisamcho** [comment]
To review and close?

**Comment by DaleMcGrew** [comment]
Thank you Lisa, what you have implemented is ready for Version 0.9.
