### ISSUE TITLE
"Your Mission" modal pop up opens at wrong time

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WebApp#854]
In a new session, login with Twitter, end up at http://localhost:3000/ballot, and you get the new "Your Mission" modal pop up.
The x button will not dismiss the modal.
Stepping through all the "Next" buttons, gets you to a "See your ballot" button that does nothing.
You have to manually change the URL in the browser to get unstuck.

**Comment by DaleMcGrew** [comment]
Thank you Steve -- Bharath is working on a fix right now.

**Comment by DaleMcGrew** [comment]
Fixed.

**Comment by SailingSteve** [comment]
I updated with the latest from upstream/develop a few hours ago.
In a new session if you click the Sign in icon, the the Sign in with twitter, click the authorize app button, you get the twitter redirecting, then the wheel, then end up on http://localhost:3000/ballot
where you get the non-dismissable "Your Mission" dialog.  

It may actually be dismissing, and immediately coming back, there is a flicker.  On each dismiss attempt it sends a 

[24/May/2017 00:03:49] "GET /apis/v1/voterUpdate/?voter_device_id=OORHR22t601D3mOM2QGnjXwAKOmHtdoJSzXXOuu1BUuEx9XfGYLlDOPRgCHC8lr1exL8dzrbe9oIXlfEiMQcqWDt&flag_integer_to_set=2 HTTP/1.1" 200 582

**Comment by SailingSteve** [comment]
Found some more changes, checking.

**Comment by SailingSteve** [comment]
My mistake
