### ISSUE TITLE
Enter address where you are registered to vote: contains worldwide countries

### ISSUE THREAD

**Issue by RohanVB** [wevote/WebApp#858]
Under normal conditions, we would only have addresses within the United States.

When we run the webapp locally, by `npm start` the initial prompt on `http://localhost:3000/settings/location` allows users to view/enter world-wide locations. 

![screen shot 2017-05-24 at 6 31 24 pm](https://cloud.githubusercontent.com/assets/15197846/26404393/5e559718-40af-11e7-83ee-c3fa7818e368.png)

**Comment by SailingSteve** [comment]
Done.
