### ISSUE TITLE
Create a second layer of navigation to js/Navigation/HeaderBar.jsx

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#862]
While a new voter is getting acquainted with We Vote, we would like to include a horizontal bar directly below that current header. This bar will include links to initial tutorials, but can default to "/ballot" for now. These links should be: Issues, Organizations, Stance, Friends, Share, Vote
The bar should slide up at the same time the current header bar slides up.

This is the mobile mockup:
![bardesignmobile_v1-short](https://user-images.githubusercontent.com/7756031/27396074-d4bdf4c8-5666-11e7-8745-62efd2605d9a.png)

This is the desktop mockup. The collection of icons can be centered on desktop:
![bardesign_v1_2-short](https://user-images.githubusercontent.com/7756031/27396214-3dfb4602-5667-11e7-993b-4c1cb289b913.png)

The assets (svg, png and source files) are here:
https://drive.google.com/drive/u/0/folders/0B1LwjBgBxA2NaGVMYThrYUFiaDg

**Comment by pertrai1** [comment]
@DaleMcGrew Having the names appear in phone form does not work. Can a mock up be created and added here that would show how this would look on phone?

**Comment by DaleMcGrew** [comment]
Hi @pertrai1, thank you. We are working on designs for what the buttons look like this next week. It would be incredibly helpful to have this second bar, in place this week, even with only one simple text link "Issues". This second horizontal "slide-down" navigation bar would be like the second horizontal area we had about a year ago. It is meant to appear on both desktop and mobile. I appreciate your help!

**Comment by pertrai1** [comment]
@DaleMcGrew Ok will start with the one button for "Issues" along with the modal that would appear when you click on it. Is the checkmark a visual when you have the modal open? If so, does it appear when you open and then disappear when you close?

**Comment by DaleMcGrew** [comment]
Hi @pertrai1 we have a modal in the works, so you don't need to set that up or deal with the checkmark. If you create a 50px tall area with a single link (for now), we can add to it as the designs come online. It would be good to have a state that we can set to "close" this second navigation bar. For now the second navigation bar can remain on all the time.

**Comment by DaleMcGrew** [comment]
Hello @pertrai1, I have some good news -- I updated the description of this Issue with new designs and art assets.

**Comment by DaleMcGrew** [comment]
Hello @pertrai1, I was able to get a first (rough) version of this working (and checked in) with the Issues icon using this component: js/Components/Navigation/HeaderGettingStartedBar.jsx
I will keep working on getting the icons in place so I can hand this case back to you for style refinement.

**Comment by DaleMcGrew** [comment]
Hi @pertrai, I have a first version with all of the icons in place. Do you have time this weekend to clean up the styles per the designs, and get the "completed" state with the icon faded slightly, and the check mark in place? The white bar has left-over dark blue lines that needs to be removed.

Also, I added img/global/svg-icons/check-mark-v2-21x21.svg to overlay the icons per the design. Note: Each icon will eventually have its own modal, but they all use the same one for now.

**Comment by pertrai1** [comment]
@DaleMcGrew I sure can 👍

**Comment by DaleMcGrew** [comment]
@kuwood thank you for your great work on this. I totally forgot that we also need completion check marks and a way to "gray out" each of these steps when each one is complete.

**Comment by DaleMcGrew** [comment]
This is now complete. Thank you @kuwood!
