### ISSUE TITLE
Add list of ballot items to js/Components/Navigation/BallotLeft.jsx

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#863]
To the left of the Ballot (in desktop mode) we want to show a list of all of the offices and measures (no candidates) that are on the ballot so that voters can jump quickly down to an office or measure. Please include an "anchor tag" when you click the office name or measure name.

The code powering this left component is js/Components/Navigation/BallotLeft.jsx

**Comment by DaleMcGrew** [comment]
Thank you Steve for your first version. It looks like you are making the quick links go to another page (the Office or Measure pages). Our goal is to jump the voter down the Ballot page to the particular item (the same page the voter is already on), with an anchor tag.

**Comment by SailingSteve** [comment]
TODO:

1. Figure out why we have to sometimes click twice to get the page to scroll to the anchor
2. Leave in the subtitle, but shorten it to fit on the same line as the title, and use css to make it fit
3. Make the fonts and white boxes match the mock Dale sent me
4. In the mobile layout (responsive html5 iphone5 as reference size) make the "Summary of Ballot Items" a modal pop-up, like SelectAddressModal in ballot.

**Comment by DaleMcGrew** [comment]
The first version of this looks great @SailingSteve. Thank you! I look forward to seeing the mobile modal version and the styling updates.

**Comment by DaleMcGrew** [comment]
Thank you Steve for your most recent upgrades to the BallotSideBar (I renamed the "BallotLeft" component). I made some style changes (make sure to grab before continuing work), and we can ask Jeff or another CSS expert for advice on getting the ellipsis working. So the only thing remaining is the mobile modal.

**Comment by SailingSteve** [comment]
Hi Dale,
   My new Mac is transferring 1TB of data so I am computerless until Sunday.  I'm glad you renamed those files!  
   The ellipses were working, it was the responsive sizing that wasn't working due to that width value.  Did you try it first?  No worries in any case, I'll take a look Monday.

Thanks,
Steve

**Comment by DaleMcGrew** [comment]
Great work @SailingSteve! I am marking this as finished. 👍
