### ISSUE TITLE
Add share buttons to Welcome page (Facebook, Twitter, Email)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#872]
- [x] On the new welcome page, create a share default popup for Facebook & Twitter (provided by Facebook and Twitter) for sharing We Vote.
- [x] On the new welcome page, create a "mailto" for the Email share button.
Suggested text: "Check out https://WeVote.US! View your ballot. Learn from friends. Share your vision. @WeVote #Voting #WeVote"

**Comment by ixley** [comment]
* I've commented out the buttons until someone makes them functional

**Comment by DaleMcGrew** [comment]
Hi @jainanisha90, on this page when I click the "share by email" link, it opens the mailto in another browser tab using an "a" tag:
https://www.aclu.org/bio/faiz-shakir

<a href="mailto:?body=https%3A%2F%2Fwww.aclu.org%2Fbio%2Ffaiz-shakir%0D%0A%0D%0AFaiz Shakir joined the American Civil Liberties Union (ACLU) in January 2017. As National Political Director, he oversees the ACLU’s National Political Advocacy Department, which houses the organization’s Washington Legislative Office and State Advocacy and Policy departments. In his role, Shakir develops and implements strategies to advance the organization’s priorities at the federal and state levels.&amp;subject=Faiz%20Shakir%20%7C%20American%20Civil%20Liberties%20Union" target="_blank" title="Submit this to Email">Email</a>

That is what I suggest we try.

**Comment by DaleMcGrew** [comment]
Verified.
