### ISSUE TITLE
Reorganise imports in components

### ISSUE THREAD

**Issue by RohanVB** [wevote/WebApp#887]
### Please describe the issue (What happens? What do you expect?)
```
import GuideActions from "../../actions/GuideActions";
import GuideList from "../../components/VoterGuide/GuideList";
import GuideStore from "../../stores/GuideStore";
import Helmet from "react-helmet";
import ItemSupportOpposeCounts from "../../components/Widgets/ItemSupportOpposeCounts";
```
is  what it currently looks like.
Ideally, we should have all the external library imports at the top, with a new line and the local ones below it like this:

```
import Helmet from "react-helmet";

import GuideActions from "../../actions/GuideActions";
import GuideList from "../../components/VoterGuide/GuideList";
import GuideStore from "../../stores/GuideStore";
import ItemSupportOpposeCounts from "../../components/Widgets/ItemSupportOpposeCounts";
```

I came across this when working on react-native I'll make a PR for the same for `Ballot.jsx`, please leave the issue open until it is not done for the rest.

Also, reorganising the related imports (components together, stores together, etc,. would be a big plus with this issue and related PRs)

**Comment by DaleMcGrew** [comment]
Hi @RohanVB, thank you for starting this conversation. I totally agree regarding grouping external imports at the top, in alphabetical order. What is the benefit of organizing Actions in their own alphabetical block, Stores in another alphabetical block, and Component in yet another? My concern is has been hard enough to keep Actions, Stores and Components in alphabetical order in a single list, and having 4 alphabetical blocks (instead of just two: 1) external and 2) We Vote components) starts to get confusing to maintain.

**Comment by RohanVB** [comment]
Hi @DaleMcGrew, 
External and wevote components is something we all agree upon.
Instead of alphabetic order an alternative solution would be keeping common directories grouped together. (stores/*, actions/*, etc,.). While I was replicating the stores for example, a broken import down the line after I was working on actions would have meant I would have to go back to the stores directory, then switch back to the actions directory.

**Comment by DaleMcGrew** [comment]
I propose that next week we do a screen share and talk about how the order affects ReactNative. We might want to have different ordering standards for ReactNative and WebApp, given the display component names are different in many cases.

**Comment by DaleMcGrew** [comment]
@RohanVB and I got a chance to speak. I am going to close this issue for now, but we can reopen it when we reopen the discussion.
