### ISSUE TITLE
Install Bootstrap Social CSS for Social Sign In Buttons

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#9]
Hi Rob, I would like to use these buttons for our social sign in pages:
https://lipis.github.io/bootstrap-social/

Could you please set up our style sheet(s) show these styles?
You can see test buttons here:
WebApp/src/components/Facebook/FacebookSignIn.jsx
WebApp/src/components/Facebook/FacebookDisconnect.jsx

Which can be seen on this page:
http://localhost:3000/more/sign_in

**Comment by pertrai1** [comment]
@DaleMcGrew What sign in options are going to be available? Facebook and Twitter?

**Comment by DaleMcGrew** [comment]
Facebook, Twitter and Gmail for now. -Dale


Dale John McGrew
Co-founder, We Vote USA
dale.mcgrew@wevoteusa.org
www.WeVoteUSA.org <http://wevoteusa.org/>
415-516-8777
Twitter: @WeVoteUSA <https://twitter.com/WeVoteUSA>

**Comment by pertrai1** [comment]
@DaleMcGrew Please code review and let me know also if there are any views that I have missed.

**Comment by pertrai1** [comment]
@DaleMcGrew I am going to close this now that the icons have been implemented.
