### ISSUE TITLE
Sign in page doesn't have access to VoterStore (sometimes)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#93]
I am no longer able to see the Facebook information needed to operate the Facebook sign in. Lisa, I think your changes with this pull request might have caused this. Can you please take a look?:
https://github.com/wevote/WebApp/pull/91/files

1. Visit the ballot
2. Click the Hamburger in the upper left, or use the navigation on the left side
3. Choose "Sign In" or "Account Settings"
4. You should see the "Uncaught TypeError: listener must be a function" error

**Comment by lisamcho** [comment]
Yes, I am sorry. I made the same change a bunch of places and clicked around to make sure nothing broke but I failed to re-test logging in/and out. All the more reason why we should start writing tests like Rob suggests :) Bug is in main.js:

But now how do we change this given that it's already merged? Should I make the change in a new branch and create a pull request or is there a way to edit my previous commits and the merged branch?

**Comment by DaleMcGrew** [comment]
No worries. New pull request is fine!

**Comment by lisamcho** [comment]
I am able to resolve the setState warnings on Facebook login/logout and get rid of the  "Uncaught TypeError: listener must be a function" error.

Was there already an  error: FB.login() called when user is already connected.? I don't see an issue/bug filed in Github but it looks vaguely familiar.

**Comment by DaleMcGrew** [comment]
Hi Lisa, yes that FB.login() error was already there. I will create an issue for that.

**Comment by lisamcho** [comment]
OK, I think this can be closed as my fixes have been merged in.

**Comment by DaleMcGrew** [comment]
Hi Lisa, I renamed this because the cause is different, but the symptoms are the same. I have bumped this to Version 1.0 since it only surfaces if you refresh on the sign in page. Thank you!
1. Visit http://localhost:3000/ballot
2. Visit "Sign In" and Sign in with Facebook: http://localhost:3000/more/sign_in
3. Refresh this page: http://localhost:3000/more/sign_in
4. The VoterStore is not initialized so we don't have access to the signed in state. Clicking "Sign In with Facebook" throws an error.

**Comment by lisamcho** [comment]
Hmmm, that's odd. I don't see any error about VoterStore not being initialized while following those steps.   I get the FB.login() error. Can you doublecheck your steps to reproduce?

**Comment by DaleMcGrew** [comment]
You need to do a browser refresh when you are on this page http://localhost:3000/more/sign_in
To clarify, this doesn't need to be finished today (today is Version 0.9) -- we are targeting Monday for all Version 1.0 features.

**Comment by DaleMcGrew** [comment]
To clarify, there isn't an error printed to the console log. I can just tell by looking at the screen that the VoterStore data hasn't been brought into the browser.
![screen shot 2016-02-23 at 12 47 16 pm](https://cloud.githubusercontent.com/assets/7756031/13266169/9c475840-da2b-11e5-8e04-24e734efb383.png)

**Comment by lisamcho** [comment]
Hmmm, still can't replicate. I navigate to the page, click 'sign in with Facebook' and it immediately populates the signed_in_personal, signed_in_facebook, and we_vote_id. I refresh the page multiple times and those values are still populated. I click 'Disconnect from Facebook', and it immediately clears the fields, and then they stay clear as I refresh the page. Are you clicking the gray buttons? I am always clicking the blue branded buttons.

**Comment by DaleMcGrew** [comment]
Verified fixed.
