### ISSUE TITLE
pre-commit check blocking check-ins

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#94]
I am no longer able to check in with PyCharm, and when I check in with the command line, files get picked up that I don't intend to check in. Would it be possible to resolve these errors early today (by removing the pre-commit test) so we can check in more easily today? In general I would prefer that we implement procedure once we hit Version 1.0.

Error:Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /Users/dalemcgrew/PythonProjects/webapp/node_modules/pre-commit/node_modules/spawn-sync/error.log for more details
... WARNINGS REMOVED HERE ...
pre-commit: We've failed to pass the specified git pre-commit hooks as the `test`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit:

**Comment by DaleMcGrew** [comment]
I can work with this for now. It would be good to get this resolved as we fix bugs leading up to version 1.0, but it can wait if it must until Version 1.1.

**Comment by nf071590** [comment]
Dale, comment out line (or remove) with “pre-commit” in package.json. That should fix the issue.

**Comment by DaleMcGrew** [comment]
Thank you Nick, I'll give that a try.

**Comment by DaleMcGrew** [comment]
This issue was resolved.
