### ISSUE TITLE
Page Headers shadow the content underneath while scrolling up

### ISSUE THREAD

**Issue by bharathdn** [wevote/WebApp#962]
### Please describe the issue (What happens? What do you expect?)
On the ballot page, click a candidate section which has more candidates to show.
After all the candidates are shown, click to see fewer candidates. This should scroll the page up until the section header is seen. 
But, the page headers shadow the section heading and the first item in the list is hidden

### Steps to reproduce the problem (1, 2, 3...), including links
* Login to wevote.us, navigate to ballot page
* enter "fairlawn, OH" as your address, (because this has enough number of candidates to show)
* For Presidents click on "Click to show 11 more candidates"
* Scroll down and click on "Click to show fewer candidates"
* The President heading gets hidden under the headers

**Comment by DaleMcGrew** [comment]
Resolved for now.
