### ISSUE TITLE
Unable to close SelectAddressModal with "x" in upper right corner

### ISSUE THREAD

**Issue by edward-ly** [wevote/WebApp#969]
### Please describe the issue (What happens? What do you expect?)

On the ballot page, I am unable to close the SelectAddressModal by clicking on the "x" in the upper-right corner of the modal. The modal can still close if the user saves a new address or refreshes the page, however.

### Steps to reproduce the problem (1, 2, 3...), including links

1. Go to http://localhost:3000/ballot
2. Show the SelectAddressModal by clicking "Edit" (located next to the address if you already entered one) or "Add Your Address"
3. Attempt to close the modal by clicking  on the "x" in the upper-right corner

**Comment by DaleMcGrew** [comment]
Fixed
