### ISSUE TITLE
Facebook Login State Error: FB.login()

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#97]
This is related to Issue #93 (which happens if you refresh the page while on the Sign On screen), but is not a currently breaking warning.

1. Start not signed in on the ballot page
2. Go to the "Sign In" page
3. Click Sign In with Facebook
You will see a FB.login() error in the console

**Comment by lisamcho** [comment]
#243

**Comment by DaleMcGrew** [comment]
Verified.
