### ISSUE TITLE
Hillary Clinton: 18 support, 11 oppose

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#98]
When I visit Hillary Clinton's candidate page:
http://localhost:3000/candidate/wv02cand1
I see 18 support and 11 oppose, even though I've only followed about 10 orgs. This is an issue with the API server and we have a bug for that:
https://github.com/wevote/WeVoteServer/issues/82

**Comment by DaleMcGrew** [comment]
Even though https://github.com/wevote/WeVoteServer/issues/82 is not fully resolved, this Issue #98 is fixed.

**Comment by lisamcho** [comment]
Looks good!
