### ISSUE TITLE
Some organization icons (placeholders) different sizes

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#991]
### Please describe the issue (What happens? What do you expect?)
When I go through the ballot intro modal, on the third screen when choosing organizations, some of the placeholder icons are sized differently, and they should all be the same (smaller) size.
![screen shot 2017-08-01 at 9 21 37 am](https://user-images.githubusercontent.com/7756031/28835680-10c5ccb2-769b-11e7-8691-7ebb8a38ca53.png)

### Steps to reproduce the problem (1, 2, 3...), including links
1. Sign out
2. Click on the "Sample Ballot" button in the header, and then click through to get to the modal
3. The "Ballot intro modal" pops up. Click through to the Organizations screen (the third one)
4. You will see some organizations without icons that have placeholder icons that are of different sizes.

I think this has to do with the WebApp/src/js/components/ImageHandler.jsx

The container that is calling ImageHandler in this case is WebApp/src/js/components/Ballot/BallotIntroOrganizations.jsx

**Comment by n0f3** [comment]
I can take care of this

**Comment by DaleMcGrew** [comment]
I made this issue go away by fixing how we were passing images into the modal.
