### ISSUE TITLE
Tools For Your Website: Update code to work within ReactJS

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#995]
### Please describe the issue (What happens? What do you expect?)
We are adding a page where organizations can find widgets to add WeVote.US and Vote.org features to their websites. We have a first version which still needs work. These are the active TODO items on this page: WebApp/src/js/routes/More/ToolsToShareOnOtherWebsites.jsx
Visit page here: http://localhost:3000/more/tools
See the original source code we are emulating here: https://www.vote.org/technology/
- [x] Get textarea working, and enclosing the "iframe" code so React doesn't try to process it
- [x] Get ReactJS to ignore the iframeResizer
- [x] Get "Click to copy code" buttons working.

More details: https://docs.google.com/document/d/1QU4TFco-Jtb-kI-WgNfhfBJ3kQnD4OnxZ-JIxfohXDE/edit#heading=h.omhhu4jepx3f

**Comment by josh-southern** [comment]
Hi! I just read the development setup docs and then found myself working on the first in the checklist. Is there anyone else working on this? Can I be assigned to this?

**Comment by DaleMcGrew** [comment]
Hi Josh, yes please feel free to run with it! If you would like to be added to our Slack channel for questions/discussion, feel free to email me at dale.mcgrew@WeVote.US

**Comment by DaleMcGrew** [comment]
I will test and verify.

**Comment by DaleMcGrew** [comment]
Hi @josh-southern, I tested this and will be updating the live site soon. Thank you again for knocking this issue out of the park!
